### ISSUE TITLE
Pktgen page latency not populating

### ISSUE THREAD

**Issue by scorban** [pktgen/Pktgen-DPDK#10]
Hi

Am running a DPDK throughput and latency test with two DPDK Redhat 8.1 servers back to back, but pktgen latency page never updates.
My test script is below:

Server A:
stop 0
set 0 rate 30
set 0 proto tcp
set 0 dst mac 00:ae:cd:01:0c:50
set 0 src mac 00:ae:cd:01:0b:60 
set 0 size 96
enable 0 latency
start 0

Server B:
stop 0
set 0 rate 30
set 0 proto tcp
set 0 dst mac 00:ae:cd:01:0b:60
set 0 src mac 00:ae:cd:01:0c:50
set 0 size 96
enable 0 latency
start 0

/ Ports 0-0 of 1   <Latency Page>  Copyright (c) <2010-2019>, Intel Corporation
  Flags:Port        : -------Lat         :0
Link State          :         <UP-10000-FD>     ----TotalRate----
Pkts/s Max/Rx       :                   9/1                   9/1
       Max/Tx       :       7575966/5453347       7575966/5453347
MBits/s Rx/Tx       :                0/5060                0/5060
                    :
Latency usec        :                     0
Jitter Threshold    :                    50
Jitter count        :                     0
Total Rx pkts       :                  2323
Jitter percent      :                     0
                    :
Pattern Type        :               abcd...
Tx Count/% Rate     :          Forever /30%
PktSize/Tx Burst    :             96 /   64
Src/Dest Port       :         4/ 1234/ 5678
Pkt Type:VLAN ID    :       IPv4 / UDP:0001
Dst  IP Address     :           192.168.1.1
Src  IP Address     :        192.168.0.1/24
Dst MAC Address     :     00:ae:cd:01:0c:50
Src MAC Address     :     00:ae:cd:01:0b:60
Pktgen:/> 

grep hpet /proc/timer_list
Clock Event Device: hpet
 set_next_event: hpet_legacy_next_event
 shutdown: hpet_legacy_shutdown
 periodic: hpet_legacy_set_periodic
 oneshot:  hpet_legacy_set_oneshot
 resume:   hpet_legacy_resume
[root@rhel81-k8-wnode2 ~]#

**Comment by pktgen** [comment]
What is the version of Pktgen and dpdk plus the command line you are using to start Pktgen?

**Comment by scorban** [comment]
20.02 for both.

dpdk-20.02  dpdk-20.02.tar.xz  pktgen-20.02.0  pktgen-20.02.0.tar.gz

 pktgen -l 0-18 -- -m 1.0

**Comment by pktgen** [comment]
Why do u need to use 0-18 cores you only need two. Try changing -l 0-18 to -l 0-1

**Comment by pktgen** [comment]
No response, closing.
