### ISSUE TITLE
Race condition in pktgen

### ISSUE THREAD

**Issue by yuyang0** [pktgen/Pktgen-DPDK#101]
Since i need add some features to pktgen, so I read the code entirely and find some code i don't understand. for example

    /* Count the type of packets found. */
    switch ((int)pType) {
    case ETHER_TYPE_ARP:        info->stats.arp_pkts++;     break;
    case ETHER_TYPE_IPv4:       info->stats.ip_pkts++;      break;
    case ETHER_TYPE_IPv6:       info->stats.ipv6_pkts++;    break;
    case ETHER_TYPE_VLAN:       info->stats.vlan_pkts++;    break;
    default:                    break;
    }

these code stays in function `pktgen_packet_classify`(pktgen.c), I know it is used to update statistics, but multiple threads can execute these code, so it is a race condition, but I'm not sure. Can you explain a little about  why you don't use atomic variable or lock? thanks.

**Comment by pktgen** [comment]
Normally only one core is receiving traffic and the code is per port. 

I think you found a bug for multiple rx cores per port. 

Can not use locks as they are too slow so will need to use atomic operators. They are slow too but better the locks. 

Thanks

**Comment by yuyang0** [comment]
I think even in one rx core per port situation, it is still a race condition, because the master thread reads these variables to display the statistics on the screen.
