### ISSUE TITLE
pktgen-build.sh bugs

### ISSUE THREAD

**Issue by OneToughMonkey** [pktgen/Pktgen-DPDK#102]
Hello everybody,

I believe I have discovered some bugs in the `tools/pktgen-build.sh` script that can have serious consequences.

1. It is not possible to trigger a global installation, as `DESTDIR` is always set to the SDK dir.
2. The `PKTGEN_TARGET` is configurable but is used *only* in the `clean` procedure, it has no effect on the target for the actual installation.
3. The `clean` procedure does not remove `target_path` as advertised but rather `target_dir`.

I have personally been naive enough to attempt a global installation by setting the `PKTGEN_TARGET` environment variable to `/usr` without reading the whole script first and imagine what happened...

**Comment by KeithWiles** [comment]
Sorry, that is not good. I normally only use pktgen from the build directory and do not install it globally.

BTW you did not state which version of Pktgen you are using and the dev branch is normally the most up to date code until I merge it to main branch.

I will fix the issues, but I will be out of town for a few weeks and will look into the issues when I return.

If you would like to submit a patch for these issues it would be great, but if not I will fix this when I return.

**Comment by OneToughMonkey** [comment]
Thanks for the fast response. I have been using the dev branch, but at a glance the same problems seemed to exist in the master branch as well. I will try to come up with a patch on monday :)

**Comment by KeithWiles** [comment]
I have a few minutes to look at the issues and may have something that works this weekend if I get time. I will push it to the dev branch and let you know so you can verify it works correctly.

If I get something pushed to the dev, please suggest any changes you feel are better or fixes I missed.

**Comment by KeithWiles** [comment]
I push a draft of the ptkgen-build.sh script, it is not done yet, but I am not able to work in it till I return on the 14th.

**Comment by pktgen** [comment]
Please look at the 'dev' branch and see if this fixes the issue.

**Comment by OneToughMonkey** [comment]
Hi Keith, sorry for my idleness. The version of the script in the current dev branch looks good to me, thanks for your work :)
