### ISSUE TITLE
Packets bigger than 1024 Bytes are truncated at reception

### ISSUE THREAD

**Issue by davidfernandes1212** [pktgen/Pktgen-DPDK#103]
Hi !

I send packets from an interface and I directly receive them in an other interface. 

When I send packets with a size lower (or equal) than 1024 bytes its OK ! But when I send packets with a size higher than 1024 Bytes, they are truncated at the reception to 1024 Byte packets. 

For example, if I send 1500 bytes packets, at the reception, the packets that I get from the buffers have a size of 1024.

I use the following command to run Pktgen : 
./pktgen -c 0x0E -n 1 -n 1 -- -m "2.0,3.1"

How could I solve that issue ? Thanks in advance !!

**Comment by pktgen** [comment]
> On Jun 22, 2017, at 9:44 AM, davidfernandes1212 <notifications@github.com> wrote:
> 
> Hi !
> 
> I send packets from an interface and I directly receive them in an other interface.
> 
> When I send packets with a size lower (or equal) than 1024 bytes its OK ! But when I send packets with a size higher than 1024 Bytes, they are truncated at the reception to 1024 Byte packets.
> 
> For example, if I send 1500 bytes packets, at the reception, the packets that I get from the buffers have a size of 1024.
> 
> I use the following command to run Pktgen :
> ./pktgen -c 0x0E -n 1 -n 1 -- -m "2.0,3.1"
> 
> How could I solve that issue ? Thanks in advance !!

I just tested Pktgen sending 1500 byte frames and capturing the packets on another port and I got the 1500 byte packets in the PCAP file.

Something on you receive side is limiting the packets to 1024.

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by davidfernandes1212** [comment]
I don't understand. I have the last version of Pktgen and DPDK and I didn't modify the source code. 
As you can see in the picture, Wireshark processes the packet and deduces the size of the packet, but only 1024 bytes have been captured.

![issue_pktgen](https://user-images.githubusercontent.com/15196732/27443805-8ef7d698-5774-11e7-8c09-b176c7dd168e.png)

**Comment by pktgen** [comment]
> On Jun 22, 2017, at 11:06 AM, davidfernandes1212 <notifications@github.com> wrote:
> 
> I don't understand. I have the last version of Pktgen and DPDK and I didn't modify the source code.
> As you can see in the picture, Wireshark processes the packet and deduces the size of the packet, but only 1024 bytes have been captured.

This looks like a wire shark configuration issue as the Length is correct in the picture of 1496 + FCS = 1500



0x5d8 = 1496 bytes

> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by davidfernandes1212** [comment]
I made some researches and I found the next patch :
[http://dpdk.org/dev/patchwork/patch/4479/](http://dpdk.org/dev/patchwork/patch/4479/)

So, according to the comment found on the **dpdk/drivers/net/ixgbe/ixgbe_rxtx.c** file of DPDK directory (line 4765) it seems that the registers of the queues have a value resolution of 1 KB

So I modified DEFAULT_BUFF_SIZE from 2048 to 2048*2 to test, because MBUF_SIZE depends on its value. 

The modification seems to solve the problem. Now I really receive packets with the original length and the field _m->data_len_ at packet reception has a value of 1496 (it had a max value of 1024 before) 

Does this modification have any influence on the performances of Pktgen ?

**Comment by pktgen** [comment]
> On Jun 23, 2017, at 3:43 AM, davidfernandes1212 <notifications@github.com> wrote:
> 
> I made some researches and I found the next patch :
> http://dpdk.org/dev/patchwork/patch/4479/
> 
> So, according to the comment found on the dpdk/drivers/net/ixgbe/ixgbe_rxtx.c file of DPDK directory (line 4765) it seems that the registers of the queues have a value resolution of 1 KB
> 
> So I modified DEFAULT_BUFF_SIZE from 2048 to 2048*2 to test, because MBUF_SIZE depends on its value.
> 
> The modification seems to solve the problem. Now I really receive packets with the original length and the field m->data_len at packet reception has a value of 1496 (it had a max value of 1024 before)
> 
> Does this modification have any influence on the performances of Pktgen ?

I should not have any performance hit, but it does require Pktgen have a bigger packet size and use more memory :-(

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by pktgen** [comment]
Updated pktgen to account for this new patch, pktgen-3.3.3


> On Jun 23, 2017, at 8:57 AM, Roger Keith Wiles <keith.wiles@icloud.com> wrote:
> 
> 
>> On Jun 23, 2017, at 3:43 AM, davidfernandes1212 <notifications@github.com> wrote:
>> 
>> I made some researches and I found the next patch :
>> http://dpdk.org/dev/patchwork/patch/4479/
>> 
>> So, according to the comment found on the dpdk/drivers/net/ixgbe/ixgbe_rxtx.c file of DPDK directory (line 4765) it seems that the registers of the queues have a value resolution of 1 KB
>> 
>> So I modified DEFAULT_BUFF_SIZE from 2048 to 2048*2 to test, because MBUF_SIZE depends on its value.
>> 
>> The modification seems to solve the problem. Now I really receive packets with the original length and the field m->data_len at packet reception has a value of 1496 (it had a max value of 1024 before)
>> 
>> Does this modification have any influence on the performances of Pktgen ?
> 
> I should not have any performance hit, but it does require Pktgen have a bigger packet size and use more memory :-(
> 
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> Keith Wiles
> keith.wiles@icloud.com
> 
> 
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by davidfernandes1212** [comment]
I tested your update and it works fine !

Thank you !
