### ISSUE TITLE
Size counters are wrong when receiving in multiple queues

### ISSUE THREAD

**Issue by julpen** [pktgen/Pktgen-DPDK#104]
When simultaneously receiving frames in multiple queues, the counters don't add up, which seems to be caused by multiple threads incrementing the same counters in pktgen_packet_classify. 

I suspect that this also happens for other counters like arp, ip, ipv6 and vlan, but i didn't actually check any of those so i can't confirm. 

For my personal usecase I was able to resolve this by adding the size counters to the individual queue stats and then adding them up in  pktgen_process_stats but I'm not sure if this would be a reasonable approach for a general fix.

**Comment by pktgen** [comment]
Please try the 'dev' branch to see if it fixes the issue.

**Comment by KeithWiles** [comment]
Fixed this issue in the latest release.
