### ISSUE TITLE
pktgen-DPDK v3.3.2: How to use the "ping4 <portlist>"

### ISSUE THREAD

**Issue by ckleu** [pktgen/Pktgen-DPDK#104]
I would like to use the ping4 function to train the Open vSwitch (learn the MAC addresses) but not sure how to use the command:
```
ping4 <portlist>                   - Send a IPv4 ICMP echo request on the given portlist

Pktgen:/> ping4 0
Misc invalid command:
  Invalid line: <ping4 0 >
```
Scenario:
- two VMs, each with a single SR-IOV port
- `enable 0 icmp` enable icmp replies on both VMs
- statically define src/dst ip
- statically define src/dst mac
- try to run the `ping4` command

Built with: DPDK v16.11.2 (LTS)

Later I would like to use the `mac_from_arp` function so that I don't need to define the MAC addresses (and integrate easier in OpenStack environments) and then use `ping4`

**Comment by pktgen** [comment]
> On Jun 26, 2017, at 6:48 AM, Christo Kleu <notifications@github.com> wrote:
> 
> I would like to use the ping4 function to train the Open vSwitch (learn the MAC addresses) but not sure how to use the command:
> 
> ping4 <portlist>                   - Send a IPv4 ICMP echo request on the given portlist
> 
> Pktgen:/> ping4 0
> Misc invalid command:
>   Invalid line: <ping4 0 >

That is the correct command and the single packet mode is the IP and mac addresses to use. The ping4 command should work, but I am out of town. Look in the app/cli-functions.c file to the ping command and see if you can spot the problem. 

> 
> Scenario:
> 
> 	• two VMs, each with a single SR-IOV port
> 	• enable 0 icmp enable icmp replies on both VMs
> 	• statically define src/dst ip
> 	• statically define src/dst mac
> 	• try to run the ping4 command
> Built with: DPDK v16.11.2 (LTS)
> 
> Later I would like to use the mac_from_arp function so that I don't need to define the MAC addresses (and integrate easier in OpenStack environments) and then use ping4
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by ckleu** [comment]
Thank you Keith, I got it working (I also got my Use Case working with arp_from_mac - it updates the GUI when it modifies the L2 information)

**Lessons learnt**
- need to use `enable 0 process` on both VMs (saw the option when running through the help file, did not see it documented online)
- need to set protocol to ICMP on TX side `set 0 proto icmp` otherwise it does not work

**Changes to fix CLI configuration**

Original configuration: /root/pktgen-3.3.2/app/cli-functions.c
`  1131          { 140, "ping4 %P %4" },`

Modified configuration: /root/pktgen-3.3.2/app/cli-functions.c
`  1131          { 140, "ping4 %P" },`

```
VM01
====
stop 0
set 0 src ip 10.10.10.250/24
set 0 dst ip 10.10.10.1
set 0 src mac ca:32:c2:9a:57:91
set 0 dst mac 9e:9a:9a:07:b2:6f
set 0 proto icmp
enable 0 process
enable mac_from_arp

<>

start 0 arp request
ping4 0
```

```
VM02
====
stop 0
set 0 src ip 10.10.10.1/24
set 0 dst ip 10.10.10.250
set 0 src mac 9e:9a:9a:07:b2:6f
set 0 dst mac ca:32:c2:9a:57:91
enable 0 process
enable 0 icmp

```

**Comment by pktgen** [comment]
Thanks I will fix that problem

**Comment by ckleu** [comment]
Is it possible in pktgen-dpdk (via LUA) to get the `dst mac` after it has been learnt via `mac_from_arp`? All the example only show retrieving `portRates` and `portStats`

Goal:
- use setup described above
- get MAC address of remote VM via ARP
- ping4 to prime the Open vSwitch bridge
- use the MAC addresses learnt in single packet mode and setup multi-packet mode (range) to send multiple flows (idea is to iterate on TCP port number)

**Comment by pktgen** [comment]
Sorry I do not remember returning the MAC address via lua. It would not be hard but I am out of town this week.
