### ISSUE TITLE
Pktgen Latency values incorrect - v 3.3.3

### ISSUE THREAD

**Issue by harriganshane** [pktgen/Pktgen-DPDK#105]
Hello,

Running Pktgen V3.3.3 (DPDK V17.05.0) with no special setup, just using the console provided with latency enabled on all ports.

When going to latency page via 'page latency' I see this:
![image](https://user-images.githubusercontent.com/24823300/27730252-81fe4a32-5d80-11e7-9e5e-6ad40624b15f.png)

Given the standard 'system-level' latency inheritance, I don't believe that these numbers are correct ^_^.

I am running **./pktgen -c 0x07 -n 3 -- -P -m "1.0, 2.1"** if that helps at all.

**Comment by pktgen** [comment]
> On Jun 30, 2017, at 4:53 AM, SPPH <notifications@github.com> wrote:
> 
> Hello,
> 
> Running Pktgen V3.3.3 (DPDK V17.05.0) with no special setup, just using the console provided with latency enabled on all ports.
> 
> When going to latency page via 'page latency' I see this:
> 
> 
> Given the standard 'system-level' latency inheritance, I don't believe that these numbers are correct ^_^.

The latency only valid on a single port meaning the packet must be sent from and received by the same port/core to get a valid value. The next thing is the resolution of the timer in the system, which may not be able to measure the real latency.

> 
> I am running ./pktgen -c 0x07 -n 3 -- -P -m "1.0, 2.1" if that helps at all.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by harriganshane** [comment]
Ah, silly me!

Thanks Keith! Pktgen is so useful for me!
