### ISSUE TITLE
Retrieve DST MAC in single-packet mode after ARP response successfully received

### ISSUE THREAD

**Issue by ckleu** [pktgen/Pktgen-DPDK#106]
I have gone through the documentation and examples but could not find a way how to get access the Destination MAC value in single-packet mode after a successful ARP reply has been received with `mac_from_arp` enabled and then use it to craft the multi-packet configuration.

The Use Case is learning the destination MAC address in an OpenStack environment (integrated with Open vSwitch) where security groups are implement filters and restrictions on layer2 and layer3 - the layer 3 addresses are known.

Is there a LUA example somewhere or part of code to inspect to access the dst.mac?

Pseudo-code
```
enable 0 process
enable mac_from_arp
start 0 arp request
mac_variable = pktgen.get_dst_mac(0)
pktgen.dst_mac("all", "start", mac_variable);
pktgen.dst_mac("all", "inc", "0000:0000:0000");
pktgen.dst_mac("all", "min", "0000:0000:0000");
pktgen.dst_mac("all", "max", "0000:0000:0000";
```

**Comment by pktgen** [comment]
> On Jun 30, 2017, at 10:34 AM, Christo Kleu <notifications@github.com> wrote:
> 
> I have gone through the documentation and examples but could not find a way how to get access the Destination MAC value in single-packet mode after a successful ARP reply has been received with mac_from_arp enabled and then use it to craft the multi-packet configuration.
> 
> The Use Case is learning the destination MAC address in an OpenStack environment (integrated with Open vSwitch) where security groups are implement filters and restrictions on layer2 and layer3 - the layer 3 addresses are known.
> 
> Is there a LUA example somewhere or part of code to inspect to access the dst.mac?
> 
> Pseudo-code
> 
> enable 0 process
> enable mac_from_arp
> start 0 arp request
> mac_variable = pktgen.get_dst_mac(0)
> pktgen.dst_mac("all", "start", mac_variable);
> pktgen.dst_mac("all", "inc", "0000:0000:0000");
> pktgen.dst_mac("all", "min", "0000:0000:0000");
> pktgen.dst_mac("all", "max", "0000:0000:0000”;

At this point the code does not retrieve the MAC address information via Lua. Sorry, but you can submit a patch for it :-)

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by ckleu** [comment]
Workaround:
```

  pktgen.save("/root/temp.txt");
  pktgen.stop("all");
  for c=0, pktgen.portCount()-1, 1
  do
    file = io.open("/root/temp.txt", "r");
    str = file:read"*a";
    mac = string.match(str, "set " .. tonumber(c) .. " dst mac (%w+:%w+:%w+:%w+:%w+:%w+)");
    printf("iteration[" .. tonumber(c) .. "] - " .. mac .. "\n");
    pktgen.dst_mac(tonumber(c), "start", mac);
    pktgen.dst_mac(tonumber(c), "inc", "00:00:00:00:00:00");
    pktgen.dst_mac(tonumber(c), "min", "00:00:00:00:00:00");
    pktgen.dst_mac(tonumber(c), "max", "00:00:00:00:00:00");
  end
  pktgen.set_range("all", "on");
  pktgen.start("all");
```

**Comment by Letty5411** [comment]
Do you know how to get the dst mac through ARP request in cmd line?
I tried:
enable mac_from_arp
start 0 arp request
ping4 0
page stats

It seems not work.

Thanks~

**Comment by pktgen** [comment]
> On Jul 17, 2017, at 10:45 AM, Letty5411 <notifications@github.com> wrote:
> 
> Do you know how to get the dst mac through ARP request in cmd line?
> I tried:
> enable mac_from_arp
> start 0 arp request
> ping4 0
> page stats

did you enable input processing of packets for ARP, which it is off by default.

'enable <portlist> process’

If all you are doing is setting up the ARP one time, then you can 'disable <portlist> process' after you get the MAC address.

Input processing will slow down the RX packet processing.

> 
> It seems not work.
> 
> Thanks~
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com
