### ISSUE TITLE
Error found in Pktgen-DPDK with maximum number of packets in a PCAP file uploaded

### ISSUE THREAD

**Issue by rubenricartsanchez** [pktgen/Pktgen-DPDK#106]
Hi,

I am experiencing the following error while I try to load a pcap file with Pktgen-DPDK: **!PANIC!: Cannot init port 0 for 524288 PCAP packets.**

When I load a PCAP with 262144 packets pktgen-dpdk works perfectly, however with 524288 packets it fails.

Command use to execute Pktgen-DPDK:
**sudo -E usr/local/bin/pktgen -l 0,1-3 -n 3 --socket-mem=4096,4096 --proc-type auto --log-level 7 --file-prefix pg -a 03:00.0,safe-mode-support=1 -- -v -T -P -m [1].0 -s 0:pcap/524288ips/524288ports_1500bytes.pcap** 

Why can not I use a PCAP with 524288 packets in Pktgen-DPDK? There is a limit on the number of packets per PCAP I can use with Pktgen-DPDK?

Thank you in advance.

Kind regards,
Ruben.

**Comment by pktgen** [comment]
Yes I have a limit to the number of pcap packets. I am out today and can not look up the define. In one of headers is a max mbufs or packets per port. 

When I get back I can look it up. 

Which version it pktgen and dpdk are you using? The version may not make any difference.

**Comment by rubenricartsanchez** [comment]
Thank you for your comment.

I am using DPDK 21.02 and Pktgen 21.03.1.

I would be very grateful if you could tell me the maximum number of packets per port and also if there is a way to change this number.

**Comment by KeithWiles** [comment]
The define is called MAX_MBUFS_PER_PORT located in pktgen-dpdk/app/pktgen-constant.h and is calculated to 262144 buffers per port. You will need to adjust the MAX_MBUFS_PER_PORT to maybe something like (DEFAULT_TX_DESC * 16) to double it.

It would better to allocate the number of buffers in a pcap file and then create the mbuf pool :-(

**Comment by rubenricartsanchez** [comment]
Thank you for your help.

**Comment by sobiaarshad** [comment]
We also encountered the same issue with the file size of 623 MB. We still looking for its solution. We also reduced the file size up to 283MB but it didn't work. Only for 138MB, it loaded successfully.

Hugepages are configured as 1GB and we used total 16 pages. 

![WhatsApp Image 2022-11-24 at 12 55 11](https://user-images.githubusercontent.com/32703907/203726484-a94b500d-56c6-4d17-9f00-7b00d13e31b2.jpeg)

**Comment by KeithWiles** [comment]
In the above comments you can adjust the number of mbufs or packet for all of the ports. The size of the pcap file is not the number you need to understand, but the number of packets in the pcap file. Pktgen works on packets per port and if the number of packets in a pcap file is larger then the max number of mbufs per port you will get the error above.

> The define is called MAX_MBUFS_PER_PORT located in pktgen-dpdk/app/pktgen-constant.h and is calculated to 262144 buffers per port. You will need to adjust the MAX_MBUFS_PER_PORT to maybe something like (DEFAULT_TX_DESC * 16) to double it.

**Comment by rashidali-net-sys** [comment]
What if the Pcap has 289 MB size having 446334 packets, then how will we calculate the max number of mbufs for all ports? Kindly provide us with the generic formula if exist. In addition to this, please guide me in which file ( location of file) and which variable we need to modify to encounter this issue. I have already implemented the solution like I changed MAX_MBUFS_PER_PORT=(DEFAULT_TX_DESC * 8) to (DEFAULT_TX_DESC * 16) but it didn't work.
