### ISSUE TITLE
How to escape/quit a running LUA script

### ISSUE THREAD

**Issue by ckleu** [pktgen/Pktgen-DPDK#111]
I have tried all the normal combinations of `Ctrl+c`, `Ctrl+x`, `Ctrl+z`.. but can't seem to stop an actively running script which is running in the foreground.

**Comment by pktgen** [comment]
Not at this time, stopping a lua script is not supported. The Ctrl+c, … require the keyboard to be scanned which is not done in Pktgen while a Lua script is running. I guess I would have to add some type of signal to stop the Lua when Ctrl+c pressed. In the current version of Pktgen I use Ctrl+x to terminate Pktgen at the prompt.

> On Jul 12, 2017, at 6:23 AM, Christo Kleu <notifications@github.com> wrote:
> 
> I have tried all the normal combinations of Ctrl+c, Ctrl+x, Ctrl+z.. but can't seem to stop an actively running script which is running in the foreground.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com
