### ISSUE TITLE
the usage of sequence mode 

### ISSUE THREAD

**Issue by Letty5411** [pktgen/Pktgen-DPDK#112]
What's the purpose of sequence mode?
In my understanding, single mode will send packets with the same contents.
range mode will send packets with different src ip/port etc.
What's the purpose of sequence mode? How to use sequence mode?

Thanks a lot!

**Comment by gkenaley** [comment]
The purpose of sequence mode is to give the user full control of the source/destination MAC address, source IP address/port number, destination IP address/port number, and the protocol in use - for an arbitrary number of flows.

Applications such as multi-core vSwitches perform best when they have a **large number** of these flows passing **bi-directionally** through them - e.g. at least a dozen flows in each direction. You can use the attached scripts to generate and run such flows with pktgen.

[mac.pkt.sequences.txt](https://github.com/pktgen/Pktgen-DPDK/files/1464405/mac.pkt.sequences.txt)
[generate-sequences.sh.txt](https://github.com/pktgen/Pktgen-DPDK/files/1464406/generate-sequences.sh.txt)

The more recent versions of pktgen (e.g. 3.4+) have an easier way of generating a large number of flows, at least if all you want to change between flows is the source and destination IP addresses. The attached file shows you how to generate a range of flows with varying IP src/dest with simple commands.
[mac.pkt.3.4.ip-range-gen.txt](https://github.com/pktgen/Pktgen-DPDK/files/1464412/mac.pkt.3.4.ip-range-gen.txt)

**Comment by pktgen** [comment]
Thanks gkenaley, can I add these to the pktgen/test directory as examples?

> On Nov 12, 2017, at 1:08 AM, gkenaley <notifications@github.com> wrote:
> 
> The purpose of sequence mode is to give the user full control of the source/destination MAC address, source IP address/port number, destination IP address/port number, and the protocol in use - for an arbitrary number of flows.
> 
> Applications such as multi-core vSwitches perform best when they have a large number of these flows passing bi-directionally through them - e.g. at least a dozen flows in each direction. You can use the attached scripts to generate and run such flows with pktgen.
> 
> mac.pkt.sequences.txt
> generate-sequences.sh.txt
> 
> The more recent versions of pktgen (e.g. 3.4+) have an easier way of generating a large number of flows, at least if all you want to change between flows is the source and destination IP addresses. The attached file shows you how to generate a range of flows with varying IP src/dest with simple commands.
> mac.pkt.3.4.ip-range-gen.txt
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by gkenaley** [comment]
Keith,
Yes, feel free to use the files I uploaded however you wish. Pktgen examples are very helpful.
Best Regards,
Gary
