### ISSUE TITLE
Cant replay big pcap files(7.4GB)

### ISSUE THREAD

**Issue by AlienX2001** [pktgen/Pktgen-DPDK#113]
Hey,
I wanted to replay a pcap of size 1GB, but it seems i was facing a similar issue from this issue https://github.com/pktgen/Pktgen-DPDK/issues/106#issuecomment-1113715971.
I tried applying this patch but instead of doing a x16 i did a x256 since my 1 GB pcap had that many packets.

I changed the pktgen-port-cfg.h changing the datatype of nb_mbufs from uint_16t to uint_64t here https://github.com/pktgen/Pktgen-DPDK/blob/3aafe7e606fa08a183eda89f05475fc7667e76b3/app/pktgen-port-cfg.h#L216 so that that big of a MAX_MBUFS_PER_PORT doesnt get overflowed.

After changing these, and compiling the app.(The app compiled successfully). Pktgen is just not getting started. It always says this

![image](https://user-images.githubusercontent.com/64488123/175274436-938ac6bb-e6b9-4fa7-8ba4-f7ebcb1f96ce.png)

My build is 
OS:- Ubuntu 20.04 Server
DPDK:- 19.11
Pktgen:- 19.12

and 32 pages of hugepages each of size 1GB.

**Comment by KeithWiles** [comment]
I assume you have enough hugepages allocated in the system to support 2G + amount of allocation?

**Comment by AlienX2001** [comment]
I think so, because I have 32G worth hugepages and the Pcap is of 1G.

**Comment by KeithWiles** [comment]
I missed the comment on the first post about 32 1G pages.

It is difficult for me to debug old versions of Pktgen and DPDK, can you try the latest DPDK and Pktgen versions?

You do not need to use the same DPDK version your application uses as they can be independent versions.

**Comment by AlienX2001** [comment]
Ok, I tried it

**Comment by AlienX2001** [comment]
Ok, I tried it
![image](https://user-images.githubusercontent.com/64488123/175382050-7ef075aa-4b8a-4a9d-97d8-6e8d6c6c7af6.png)

This is for 100MB packet as mentioned in this issue https://github.com/pktgen/Pktgen-DPDK/issues/114#issue-1282160678, and now it works.

But for 1G pcap it still shows the error
![image](https://user-images.githubusercontent.com/64488123/175382455-79c1a76b-44b5-42bb-b3cf-e0fa3f822502.png)

**Comment by AlienX2001** [comment]
Ohk, 1 GB worth pcap loaded after I increased the hugepage to worth 100GB

**Comment by AlienX2001** [comment]
Our goal was to replay around 35 GB worth pcap, we were incrementing gradually, but its seems even with 100GB worth of hugepages, it error'ed out
![image](https://user-images.githubusercontent.com/64488123/175383742-e3b3430c-f1ea-4f45-85bd-dd93788b2955.png)

and the pcap is 
![image](https://user-images.githubusercontent.com/64488123/175383900-3f92be6f-91b5-4a47-87e5-5d56ad54564e.png)

**Comment by AlienX2001** [comment]
Even a 7.4 GB worth pcap didnt run, but the error is a bit different
![image](https://user-images.githubusercontent.com/64488123/175384614-09491203-4fa6-4694-8bd6-7ae3516ed33d.png)

**Comment by KeithWiles** [comment]
Take the number of packets you have in the pcap file and multiple by 2048 this will give you the amount of memory required for the pcap file. PCAP files are compress or packets are set in the file one after the other. In DPDK we have to create an mbuf for each packet and mbufs are ~2048 bytes in size.

**Comment by AlienX2001** [comment]
Ohk, so that requires me to have near about 1TB worth RAM

**Comment by AlienX2001** [comment]
We tried running a 2.7GB pcap which has 16,344,602 packets, and have assigned 100 GB worth hugepages.
Estimating 2048 bytes per packet, we should have accomodated 52,428,800 packets, which is far less than 16.3 mil, but still we cant run it
![image](https://user-images.githubusercontent.com/64488123/175500823-2c1af450-96d2-4e2e-adc8-32c9a431916f.png)

**Comment by KeithWiles** [comment]
Well it looks like the setup should work, but without debugging the problem I do not know why it does not work.

I will try to look at it this weekend.

**Comment by NicNull** [comment]
Just a thought, 
Are you running a dual socket setup, then the Hugepages are default split between numa nodes equally.
So assigning 100G gives you 50G per numa instance.
It can be set vis sysfs runtime manually to skew more memory to one socket/numa node.

Your meminfo seem to only show 69 HP free after it crashed, sometimes I'd had to reboot to get full HP back after core dumps.

**Comment by KeithWiles** [comment]
You can also do 'sudo rm /dev/hugepages/*' to get all of the hugepages freed as long as the hugepages have a file backing the region of memory. If the page is being held via a anonymous allocation the rm will not work and a reboot or find the process holding on to the pages and kill it.

**Comment by sobiaarshad** [comment]
We also encountered the same issue with the file size of 623 MB. We still looking for its solution. We also reduced the file size up to 283MB but it didn't work. Only for 138MB, it loaded successfully.

Hugepages are configured as 1GB and we used total 16 pages. 

![WhatsApp Image 2022-11-24 at 12 55 11](https://user-images.githubusercontent.com/32703907/203726484-a94b500d-56c6-4d17-9f00-7b00d13e31b2.jpeg)

**Comment by AlienX2001** [comment]
hey @sobiaarshad  we managed to replay around 1.5G worth of pcap, but it required a lot of RAM.
We have Pktgen 22.04.1 (DPDK 22.07.0-rc1) and we assigned 100G worth of hugepages to DPDK

**Comment by sobiaarshad** [comment]
@AlienX2001 So is there any other solution worked for you for bigger pcaps?and high speed packet generation?

**Comment by AlienX2001** [comment]
Nope, not yet for large pcaps. But for high speed packet generation, you can replay a pcap, by default pktgen will replay it indefinitely, you can try capturing the packets and storing it in a pcap

**Comment by handsome-meme** [comment]
Is there any solution available now? I am facing the same question. If there is a solution to this problem, please assist me.

**Comment by YanivShoham** [comment]
2048 mbuf size can be configurable/automatic change?
I have a big PCAP(10GB) with small frames(100-200). so if pktGen will scan my PCAP and see the max frame size it will be best, but configurable be ok as well.
