### ISSUE TITLE
Question: What is the granularity between time samples using portStats "rate"?

### ISSUE THREAD

**Issue by ckleu** [pktgen/Pktgen-DPDK#113]
When I changed my delay between samples from `1000ms` to `250ms`, it looked like every four values were the same..
```
portRates = pktgen.portStats("all", "rate");
```

I assume this is calculated per EAL thread but couldn't find which portion of the source code implements the rate calculation.

What is the granularity between time samples using portStats "rate"?

**Comment by pktgen** [comment]
> On Jul 16, 2017, at 1:10 PM, Christo Kleu <notifications@github.com> wrote:
> 
> When I changed my delay between samples from 1000ms to 250ms, it looked like every four values were the same..
> 
> portRates = pktgen.portStats("all", "rate");
> 
> I assume this is calculated per EAL thread but couldn't find which portion of the source code implements the rate calculation.
> 
> What is the granularity between time samples using portStats "rate”?

To make the math simple the code gathers the stats every second or 1000ms.

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com
