### ISSUE TITLE
Getting wrong RX stats 

### ISSUE THREAD

**Issue by syeedhaiderali** [pktgen/Pktgen-DPDK#115]
I am trying to send and receive 100Gbps traffic. I have enabled range and configured different parameters:
```
enable 0 range
range 0 proto udp
range 0 dst port 331 331 331 0
range 0 src port 1 1 50000 1
range 0 dst ip 192.168.1.1 192.168.1.1 192.168.1.1 0.0.0.0
range 0 size 1518 1518 1518 0
```
I am successfully able to TX 100Gbps, but I am not able to receive 100Gbps on receiving server. I am only getting around 10Gbps on the receiver side.

Kindly see the below image in which the left-hand side is of receiving end, and the right-hand side is of the transmitting end.
![88942675-c097-4a37-985c-46e5d1e607a0](https://user-images.githubusercontent.com/20606725/176667060-2a659d8b-ed0b-4c56-b0ff-da05bbfcb6b7.jpg)

**Comment by syeedhaiderali** [comment]
@KeithWiles @pktgen kindly look into this.

**Comment by KeithWiles** [comment]
I am not able to view the pictures for some reason very clearly.

What version of Pktgen and DPDK are you using?

Also what are the command lines used to start pktgen?

Sometimes the RSS hashing does not work as expected and all of the packets are hitting a single queue, which limits the rate for receive as only one lcore is doing receive work.

**Comment by syeedhaiderali** [comment]
Pktgen-21.11.0, DPDK 21.11.0 versions are used. Also tried with Pktegen-22.2.0 on the receiver side.

Below commands are used to start pktgen
**On Receiver:**
`./Builddir/app/pktgen -l 0-15 --main-lcore 1 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 41:00.0 --socket-mem 1024,0 -- -T -P -m [0/2/3/4/5/6/7/8/9/10/11/12:15].0 -f themes/black-yellow.theme`
**On Sender**
`./Builddir/app/pktgen -l 0-15 --main-lcore 1 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 41:00.0 --socket-mem 1024,0 -- -T -P -m [15:0/2/3/4/5/6/7/8/9/10/11/12].0 -f themes/black-yellow.theme`

Kindly note these servers have a single numa node. 
RSS is working fine, as I can see packet steering on multiple queues using "Page stats".

**Comment by KeithWiles** [comment]
hmmm, this should work. As long as DPDK can allocate memory for the correct NUMA node having one NUMA node is fine.

Are the machine connected via a cable between the two machines, I assume so and wanted to make sure nothing is between the two machines limiting the rate.

**Comment by syeedhaiderali** [comment]
Yes, the two servers are connected back to back, and there is no other machine between them.

**Comment by NicNull** [comment]
Please try setting the single pkt size as well. 
I've seen this with the dashboard, that the presented values uses the single ip pkt size for the live calculations.
Right now you have 64B set if I can read the blurry screenshot correctly.. 
The Tx side shows 148MPPS, that is linespeed for 64B packets, not 1518B.
Your Rx side shows it being in "Single IP" mode. Set it up using ranges at both sides. I think it is needed to get the RSS/multiq setup to scale traffic even over the Rx cores.
I'll leave it to KW to answer that.

#
set 0,1 size 1518
range 0,1 size 1518 1518 1518 0

I always set all IP/port base values both to for single IP and range setup to get the dashboard to show the test setup even if only using ranges, for readability.

**Comment by KeithWiles** [comment]
The RX side does not need to be in Range mode unless you are sending from that machine. Almost all of the counters are taken from the NIC hardware and the main screen is reporting those values. The different modes Single, Range, ... are all for sending traffic and are suppose to be independent configurations.

To see the RSS queue stats you can look at the 'page stats' screen and it attempts to show the RSS distribution.

**Comment by KeithWiles** [comment]
Is this still a problem, if not I will be closing this issue.
