### ISSUE TITLE
Question: What is the granularity between time samples using portStats "port"?

### ISSUE THREAD

**Issue by ckleu** [pktgen/Pktgen-DPDK#115]
Similar to one of my previous questions regarding the granularity of the portStats "rate", it looks like portStats are also only updated once a second?

I increased my sampling from 1s down to 250ms per sample.. this is mainly to detect and estimate received framesize with more samples (wanted to move from 3 samples [1 per second], to 7 samples [4 per second])

Format
`timestamp, ports, framerate, throughput, ipackets, ibytes`

As you can see the various samples have ipackets and ibytes stay constant between sampling periods

```
8.0,4,64,28323133,19030  (stored)
8.0,4,64,28323133,19030,28323133,1699387860
8.0,4,64,28323133,19030,28323133,1699387860
8.0,4,64,28323133,19030,28323133,1699387860
9.0,4,64,28319574,19029  (stored)
9.0,4,64,28319574,19029,28319574,1699174560
9.0,4,64,28319574,19029,28319574,1699174560
9.0,4,64,28319574,19029,28319574,1699174560
10.0,4,64,28321835,19030  (stored)
10.0,4,64,28321835,19030,28321835,1699310100
10.0,4,64,28321835,19030,28321835,1699310100
10.0,4,64,28321835,19030,28321835,1699310100
11.0,4,64,28321444,19030  (stored)
```

**Comment by pktgen** [comment]
> On Jul 31, 2017, at 2:03 AM, Christo Kleu <notifications@github.com> wrote:
> 
> Similar to one of my previous questions regarding the granularity of the portStats "rate", it looks like portStats are also only updated once a second?
> 
> I increased my sampling from 1s down to 250ms per sample.. this is mainly to detect and estimate received framesize with more samples (wanted to move from 3 samples [1 per second], to 7 samples [4 per second])
> 
> Format
> timestamp, ports, framerate, throughput, ipackets, ibytes
> 
> As you can see the various samples have ipackets and ibytes stay constant between sampling periods
> 
> 8.0,4,64,28323133,19030  (stored)
> 8.0,4,64,28323133,19030,28323133,1699387860
> 8.0,4,64,28323133,19030,28323133,1699387860
> 8.0,4,64,28323133,19030,28323133,1699387860
> 9.0,4,64,28319574,19029  (stored)
> 9.0,4,64,28319574,19029,28319574,1699174560
> 9.0,4,64,28319574,19029,28319574,1699174560
> 9.0,4,64,28319574,19029,28319574,1699174560
> 10.0,4,64,28321835,19030  (stored)
> 10.0,4,64,28321835,19030,28321835,1699310100
> 10.0,4,64,28321835,19030,28321835,1699310100
> 10.0,4,64,28321835,19030,28321835,1699310100
> 11.0,4,64,28321444,19030  (stored)
> 

The code in Pktgen only grabs the stats every second and requesting stats more often will not help. If you want pktgen poll faster then 1s then you have change the timer and fix the code to understand that the polling rate.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com
