### ISSUE TITLE
How to use pktgen-dpdk when DPDK PMD link.link_speed returns 0

### ISSUE THREAD

**Issue by ckleu** [pktgen/Pktgen-DPDK#116]
In certain scenarios, SR-IOV VFs return a link_speed of 0 (ETH_SPEED_NUM_NONE)

**Use Case**: transfer >50GbE (PCI-E Gen3 x8) between two VFs on the same machine (two guest Vms each with one SR-IOV interface added), while only having 2x10GbE interfaces. The PMD returns 0 as the link_speed

Is it currently possible to overwrite the detected link speed (pktgen: `UP-0-FD`) and/or ignore any of the "rate" conditions? (basically blasting at full-speed, "no matter what")

Thank you!

**Comment by pktgen** [comment]
Currently no there is no way. It would be better if the device reported something useful.
