### ISSUE TITLE
Issues with ARP after pktgen-dpdk version 3.3.2

### ISSUE THREAD

**Issue by ckleu** [pktgen/Pktgen-DPDK#117]
Today I tried to migrate from 3.3.2 to a later version..

> 3.3.2: works
> 3.3.3: compiled, ran results, didn't spent much time because the diff is not big
> 3.3.4 segfault
> 3.3.5 does not compile
> 3.3.6 does not compile
> 3.3.7 does not compile
> 3.3.8 ARP broken
> 3.4.0 ARP broken

I compiled pktgen-dpdk against dpdk-stable-17.05.2 (DPDK 17.05.2-stable)

The Use Case I am using is two machines back-to-back, ptkgen-dpdk compiled inside a CentOS VM, connected using one or more SR-IOV VFs, Open vSwitch using NORMAL rules, unidirectional blasting..
I use the ARP request/responses to get the NORMAL rules to forward traffic correctly and makes it easier to migrate tests around [making assumptions on static L3 addresses, but not MACs]

Has anyone else seen anything regarding ARP issues as well?

**Comment by pktgen** [comment]
> On Sep 15, 2017, at 9:55 AM, Christo Kleu <notifications@github.com> wrote:
> 
> Today I tried to migrate from 3.3.2 to a later version..
> 
> 3.3.2: works
> 3.3.3: compiled, ran results, didn't spent much time because the diff is not big
> 3.3.4 segfault
> 3.3.5 does not compile
> 3.3.6 does not compile
> 3.3.7 does not compile
> 3.3.8 ARP broken
> 3.4.0 ARP broken
> 
> I compiled pktgen-dpdk against dpdk-stable-17.05.2 (DPDK 17.05.2-stable)
> 
> The Use Case I am using is two machines back-to-back, ptkgen-dpdk compiled inside a CentOS VM, connected using one or more SR-IOV VFs, Open vSwitch using NORMAL rules, unidirectional blasting..
> I use the ARP request/responses to get the NORMAL rules to forward traffic correctly and makes it easier to migrate tests around [making assumptions on static L3 addresses, but not MACs]
> 
> Has anyone else seen anything regarding ARP issues as well?

I found the bug and pushed 3.4.1, thanks for the report.

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by ckleu** [comment]
Can confirm that this is working in 3.4.1 and 3.4.2 - thank you!
