### ISSUE TITLE
Set command is invalid

### ISSUE THREAD

**Issue by MaxencePPierre** [pktgen/Pktgen-DPDK#118]
Hi Good morning,

I am running pktgen, and I want to change some configuration.
I found help on this issue : https://github.com/pktgen/Pktgen-DPDK/issues/5

But the fact is that I obtained errors but I don't understand why. Rather I want to change src or dst IP and MAC addresses, I am having : Set command is invalid

![screenshot from 2017-10-12 16-23-52](https://user-images.githubusercontent.com/25708842/31535163-4c4ba34a-affa-11e7-88d0-fc0167b7fdb2.png)

Could you help ?

Thank you by advanced

Maxence

**Comment by pktgen** [comment]
> On Oct 13, 2017, at 2:39 AM, Maxence <notifications@github.com> wrote:
> 
> Hi Good morning,
> 
> I am running pktgen, and I want to change some configuration.
> I found help on this issue : #5
> 
> But the fact is that I obtained errors but I don't understand why. Rather I want to change src or dst IP and MAC addresses, I am having : Set command is invalid


Command is ‘set <portlist> dst ip <ipaddr>'

**Comment by MaxencePPierre** [comment]
Hi,

Thank you for the answer.

Max.
