### ISSUE TITLE
enable|disable <portlist> capture  can only capture queue0's received packets.

### ISSUE THREAD

**Issue by oldcityustc** [pktgen/Pktgen-DPDK#12]
when enable multiqueues, only Q0's packets can be captured. Q1 and Q2  can not be captured.

Port 0                        Pkts Rx/Tx      Rx Errors/Missed            Rate Rx/Tx           MAC Address
 0-0b:00.0                         760/0                   0/0                   0/0     00:11:22:33:00:00

                 ipackets       opackets         ibytes         obytes         errors
     Q  0:            636              0          38160              0              0
     Q  1:             36              0           2160              0              0
     Q  2:             88              0           5394              0              0

**Comment by pktgen** [comment]
Thanks I will try and look into it when I get the chance. The capture is handled by the lcore polling that queue and I don’t remember any code that would restrict it from working. Can you also tell me the DPDK and Pktgen version.

**Comment by oldcityustc** [comment]
Hi Keith Wiles,
    Thank you for your reply.
version:
dpdk-20.02
pktgen-20.03.0
cmd:
./app/x86_64-native-linuxapp-gcc/pktgen -l 0-15 -n 2 -w $vPcie -w $vPcie_1 -- -P -j -m "[1-3:4-6].0,[8-10:11-13].1"












At 2020-06-28 23:30:13, "Keith Wiles" <notifications@github.com> wrote:

Thanks I will try and look into it when I get the chance. The capture is handled by the lcore polling that queue and I don’t remember any code that would restrict it from working. Can you also tell me the DPDK and Pktgen version.
