### ISSUE TITLE
PANIC! Did not find any ports to use.

### ISSUE THREAD

**Issue by asvcer** [pktgen/Pktgen-DPDK#120]
Dear Keith,

I have encountered a problem when running pktgen-dpdk. I use the following command：
```
$ sudo -E ./app/app/x86_64-native-linuxapp-gcc/pktgen -l 0 -n 4 -- -P -m "0.0"
```

However, pktgen-dpdk show the following error message:

```
   Copyright (c) <2010-2016>, Intel Corporation. All rights reserved.
   Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<

Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
>>> Packet Burst 32, RX Desc 512, TX Desc 512, mbufs/port 4096, mbuf cache 512
!PANIC!: *** Did not find any ports to use ***
PANIC in pktgen_config_ports():
*** Did not find any ports to use ***6: [./app/app/x86_64-native-linuxapp-gcc/pktgen(_start+0x29) [0x4381d9]]
5: [/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7ffff6eb9830]]
4: [./app/app/x86_64-native-linuxapp-gcc/pktgen(main+0x4dd) [0x43781d]]
3: [./app/app/x86_64-native-linuxapp-gcc/pktgen(pktgen_config_ports+0x1658) [0x462748]]
2: [./app/app/x86_64-native-linuxapp-gcc/pktgen(__rte_panic+0xc9) [0x43341b]]
1: [./app/app/x86_64-native-linuxapp-gcc/pktgen(rte_dump_stack+0x2b) [0x4b215b]]
Aborted (core dumped)
```

Here is my NIC card information:
```
sudo lshw -class network
```
```
  *-network:0             
       description: Ethernet interface
       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
       vendor: Broadcom Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: enp1s0f0
       version: 01
       serial: a4:dc:be:f3:26:84
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=tg3 driverversion=3.137 duplex=full firmware=5719-v1.31 NCSI v1.2.12.0 ip=219.223.189.149 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:24 memory:948b0000-948bffff memory:948a0000-948affff memory:94890000-9489ffff
  *-network:1 DISABLED
       description: Ethernet interface
       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
       vendor: Broadcom Corporation
       physical id: 0.1
       bus info: pci@0000:01:00.1
       logical name: enp1s0f1
       version: 01
       serial: a4:dc:be:f3:26:85
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=tg3 driverversion=3.137 firmware=5719-v1.31 NCSI v1.2.12.0 latency=0 link=no multicast=yes port=twisted pair
       resources: irq:51 memory:94880000-9488ffff memory:94870000-9487ffff memory:94860000-9486ffff
  *-network:2
       description: Ethernet interface
       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
       vendor: Broadcom Corporation
       physical id: 0.2
       bus info: pci@0000:01:00.2
       logical name: enp1s0f2
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical
       configuration: broadcast=yes driver=igb_uio latency=0 multicast=yes
       resources: irq:24 memory:94850000-9485ffff memory:94840000-9484ffff memory:94830000-9483ffff
  *-network:3
       description: Ethernet interface
       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
       vendor: Broadcom Corporation
       physical id: 0.3
       bus info: pci@0000:01:00.3
       logical name: enp1s0f3
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical
       configuration: broadcast=yes driver=igb_uio latency=0 multicast=yes
       resources: irq:51 memory:94820000-9482ffff memory:94810000-9481ffff memory:94800000-9480ffff
```

Here is the NIC dirver info:
```
./dpdk-devbind.py --status
```
```
Network devices using DPDK-compatible driver
============================================
0000:01:00.2 'NetXtreme BCM5719 Gigabit Ethernet PCIe' drv=igb_uio unused=tg3
0000:01:00.3 'NetXtreme BCM5719 Gigabit Ethernet PCIe' drv=igb_uio unused=tg3

Network devices using kernel driver
===================================
0000:01:00.0 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=enp1s0f0 drv=tg3 unused=igb_uio 
0000:01:00.1 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=enp1s0f1 drv=tg3 unused=igb_uio 

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>
```

Since this is a remote server, I use enp1s0f0 for internet connect. I bind the last two NICs with igb_uio.
I think it goes wrong when trying to initialize the NIC port. But I don't know why.

Would you like to help me?  Any suggestion is appreciated. 

Thank you.

Yours,
Shuo

**Comment by pktgen** [comment]
> On Oct 22, 2017, at 4:16 AM, asvcer <notifications@github.com> wrote:
> 
> Dear Keith,
> 
> I have encountered a problem when running pktgen-dpdk. I use the following command：
> 
> $ sudo -E ./app/app/x86_64-native-linuxapp-gcc/pktgen -l 0 -n 4 -- -P -m “0.0"

You need to give pktgen two cores, pktgen -l 0-1 -n 4 — -p -m “1.0"

> 
> However, It pktgen-dpdk show the following error message:
> 
>   Copyright (c) <2010-2016>, Intel Corporation. All rights reserved.
>   Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<
> 
> Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
>>>> Packet Burst 32, RX Desc 512, TX Desc 512, mbufs/port 4096, mbuf cache 512
> !PANIC!: *** Did not find any ports to use ***
> PANIC in pktgen_config_ports():
> *** Did not find any ports to use ***6: [./app/app/x86_64-native-linuxapp-gcc/pktgen(_start+0x29) [0x4381d9]]
> 5: [/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7ffff6eb9830]]
> 4: [./app/app/x86_64-native-linuxapp-gcc/pktgen(main+0x4dd) [0x43781d]]
> 3: [./app/app/x86_64-native-linuxapp-gcc/pktgen(pktgen_config_ports+0x1658) [0x462748]]
> 2: [./app/app/x86_64-native-linuxapp-gcc/pktgen(__rte_panic+0xc9) [0x43341b]]
> 1: [./app/app/x86_64-native-linuxapp-gcc/pktgen(rte_dump_stack+0x2b) [0x4b215b]]
> Aborted (core dumped)
> 
> Here is my NIC card information:
> 
> sudo lshw -class network
> 
>  *-network:0             
>       description: Ethernet interface
>       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
>       vendor: Broadcom Corporation
>       physical id: 0
>       bus info: pci@0000:01:00.0
>       logical name: enp1s0f0
>       version: 01
>       serial: a4:dc:be:f3:26:84
>       size: 1Gbit/s
>       capacity: 1Gbit/s
>       width: 64 bits
>       clock: 33MHz
>       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
>       configuration: autonegotiation=on broadcast=yes driver=tg3 driverversion=3.137 duplex=full firmware=5719-v1.31 NCSI v1.2.12.0 ip=219.223.189.149 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
>       resources: irq:24 memory:948b0000-948bffff memory:948a0000-948affff memory:94890000-9489ffff
>  *-network:1 DISABLED
>       description: Ethernet interface
>       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
>       vendor: Broadcom Corporation
>       physical id: 0.1
>       bus info: pci@0000:01:00.1
>       logical name: enp1s0f1
>       version: 01
>       serial: a4:dc:be:f3:26:85
>       capacity: 1Gbit/s
>       width: 64 bits
>       clock: 33MHz
>       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
>       configuration: autonegotiation=on broadcast=yes driver=tg3 driverversion=3.137 firmware=5719-v1.31 NCSI v1.2.12.0 latency=0 link=no multicast=yes port=twisted pair
>       resources: irq:51 memory:94880000-9488ffff memory:94870000-9487ffff memory:94860000-9486ffff
>  *-network:2
>       description: Ethernet interface
>       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
>       vendor: Broadcom Corporation
>       physical id: 0.2
>       bus info: pci@0000:01:00.2
>       logical name: enp1s0f2
>       version: 01
>       width: 64 bits
>       clock: 33MHz
>       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical
>       configuration: broadcast=yes driver=igb_uio latency=0 multicast=yes
>       resources: irq:24 memory:94850000-9485ffff memory:94840000-9484ffff memory:94830000-9483ffff
>  *-network:3
>       description: Ethernet interface
>       product: NetXtreme BCM5719 Gigabit Ethernet PCIe
>       vendor: Broadcom Corporation
>       physical id: 0.3
>       bus info: pci@0000:01:00.3
>       logical name: enp1s0f3
>       version: 01
>       width: 64 bits
>       clock: 33MHz
>       capabilities: pm vpd msi msix pciexpress bus_master cap_list ethernet physical
>       configuration: broadcast=yes driver=igb_uio latency=0 multicast=yes
>       resources: irq:51 memory:94820000-9482ffff memory:94810000-9481ffff memory:94800000-9480ffff
> 
> Here is the NIC dirver info:
> 
> ./dpdk-devbind.py --status
> 
> Network devices using DPDK-compatible driver
> ============================================
> 0000:01:00.2 'NetXtreme BCM5719 Gigabit Ethernet PCIe' drv=igb_uio unused=tg3
> 0000:01:00.3 'NetXtreme BCM5719 Gigabit Ethernet PCIe' drv=igb_uio unused=tg3
> 
> Network devices using kernel driver
> ===================================
> 0000:01:00.0 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=enp1s0f0 drv=tg3 unused=igb_uio 
> 0000:01:00.1 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=enp1s0f1 drv=tg3 unused=igb_uio 
> 
> Other network devices
> =====================
> <none>
> 
> Crypto devices using DPDK-compatible driver
> ===========================================
> <none>
> 
> Crypto devices using kernel driver
> ==================================
> <none>
> 
> Other crypto devices
> ====================
> <none>
> 
> Since this is a remote server, I use enp1s0f0 for internet connect. I bind the last two NICs with igb_uio.

Well the rest of the info seems right are you sure the NIC is supported by DPDK. This is not a strictly speaking a pktgen problem, but DPDK does not understand how to use the NICs you have assigned.

**Comment by asvcer** [comment]
Dear Keith,

Thank you for your reply.
I know the cause now. My NIC card doesn't support DPDK.
Here is a useful reference. Maybe someone will encounter the same problem.

https://stackoverflow.com/questions/42106676/while-using-dpdk-application-rte-eth-dev-count-is-returning-0-always

Yours,
Shuo
