### ISSUE TITLE
Understanding RX/RSS Pktgen ConnectX-5 100G

### ISSUE THREAD

**Issue by shelbyt** [pktgen/Pktgen-DPDK#121]
Hi,

I have pktgen running on two identical computers with a 100G NIC between them. Enabling the range command on the tx side, I am able to transmit packets at 80MPPS with 12 physical cores (UDP,64B packets) but on the rx side pktgen shows I am only receiving 30MPPS regardless of how many physical cores I allocate (performance seems to degrade slightly with more cores in fact).

Without the range command, I transmit at 148MPPS but the RX is stuck at 30MPPS. It seems like I'm hitting this limit even with largest packet sizes. 

I assumed I would be getting much higher on the rx side, is there something else I need to enable? Or is there something related with RSS+pktgen I am unaware of?

Thank You.

**Comment by pktgen** [comment]
> On Oct 22, 2017, at 3:15 PM, shelbyt <notifications@github.com> wrote:
> 
> Hi,
> 
> I have pktgen running on two identical computers with a 100G NIC between them. Enabling the range command on the tx side, I am able to transmit packets at 80MPPS with 12 physical cores (UDP,64B packets) but on the rx side pktgen shows I am only receiving 30MPPS regardless of how many physical cores I allocate (performance seems to degrade slightly with more cores in fact).
> 
> Without the range command, I transmit at 148MPPS but the RX is stuck at 30MPPS. It seems like I'm hitting this limit even with largest packet sizes.

The transmitted packets are split up between the queue/core via RSS which means the RSS hardware needs to be able to split them based on the 5 tuple.

I think the command is ‘page stats’ which may help to identify if the packets are being distributed across RSS. It seems like the 30Mpps is the limit for a single core.

**Comment by shelbyt** [comment]
I am generating random L2/L3/L4 headers. Page stats only shows me an ethernet address.
![image](https://user-images.githubusercontent.com/1332316/31901832-8af95666-b7d7-11e7-89f7-741d28c7d047.png)

Is there any other way to get that information? The packet distribution stats would be incredible useful in debugging this. Thanks

**Comment by pktgen** [comment]
> On Oct 23, 2017, at 11:50 AM, shelbyt <notifications@github.com> wrote:
> 
> I am generating random L2/L3/L4 headers. Page stats only shows me an ethernet address.
> 
> 
> Is there any other way to get that information? The packet distribution stats would be incredible useful in debugging this. Thanks

Need to see the page range or what is the mode you are sending packets again?

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by cliffburdick** [comment]
Did this issue every get solved? I'm noticing that when I have more than one core/queue receiving on a ConnectX-5, the RX rate doesn't go up. I'm assuming all packets are landing in a single queue.

**Comment by pktgen** [comment]
> On Dec 20, 2017, at 11:15 PM, Cliff Burdick <notifications@github.com> wrote:
> 
> Did this issue every get solved? I'm noticing that when I have more than one core/queue receiving on a ConnectX-5, the RX rate doesn't go up. I'm assuming all packets are landing in a single queue.

You need to make sure the packets being received are different enough to cause RSS to distribute the packets to different queues. Make sure the 5 tuples are changing enough to see the packet being distributed.

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by shelbyt** [comment]
@cliffburdick There are two things you can try, first ensure that the receiving dpdk code is setup for RSS i.e.
`
static struct rte_eth_conf port_conf_default = {

    .rxmode = {
        .mq_mode = ETH_MQ_RX_RSS,
        .max_rx_pkt_len = ETHER_MAX_LEN,
        .split_hdr_size = 0,
        .header_split   = 0, 
        .hw_ip_checksum = 0, 
        .hw_vlan_filter = 0, 
        .jumbo_frame    = 0,
        .hw_strip_crc   = 0, 
    },
    .rx_adv_conf = {
        .rss_conf = {
            .rss_key = NULL,
            .rss_hf = ETH_RSS_IP,
        },
    },
    .txmode = {
        .mq_mode = ETH_MQ_TX_NONE,
    `},

Second, run the command `enable 0 range` where 0 is the port you're using. This forces variation of addresses and allows the tuple hash to distribute the packets on the receiver.

**Comment by cliffburdick** [comment]
@shelbyt @pktgen Thanks! I'm not too familiar with pktgen yet, but that config looks like it would be config for DPDK's API. I'm assuming that using pure pktgen this won't be possible from the receiver side? Right now I'm just running some quick throughput tests, and pktgen was nice for transmitting, and it seemed like it could at least count the packets for receive as well.

**Comment by shelbyt** [comment]
Did the range command make any difference?

**Comment by cliffburdick** [comment]
The range command alone didn't seem to make any difference. It was still getting about the same performance as single core on the RX side. I'll look into it more.
