### ISSUE TITLE
DPDK Pktgen generating less tx rate and getting pktdrop

### ISSUE THREAD

**Issue by ramya-netizen** [pktgen/Pktgen-DPDK#123]
Hi,

We are using pktgen with the following command to generate IPSec packets by establishing the tunnel
./usr/local/bin/pktgen -c 0xff00f -n 4 -- -T -P -m [1:3].0 -s 0:/home/dell1/output2_src_24.pcap
Used the imix.pcap and modified the dst mac/srcip/dst/ip. We are now getting tx rate of 3.6gbps only while receive rate is 2.35gpbs. 

root@dell1-PowerEdge-R620:~# grep Huge /proc/meminfo
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:    8192
HugePages_Free:     7768
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
root@dell1-PowerEdge-R620:~#
root@dell1-PowerEdge-R620:~#

Version: DPDK 22.11.0-rc0, Command Line Interface without timers

-- Pktgen 22.2.0 (DPDK 22.11.0-rc0)  Powered by DPDK  (pid:5930) --------------

![dpdk-pkt-gen](https://user-images.githubusercontent.com/112680859/188064468-015d6989-b463-47f5-be54-8013f0a74522.png)

we are estblishing ipsec tunnel between dell1- enp5s0f1 and dell2 -enp5s0f1.
Tried increasing size of RX buffers too 
root@dell1-PowerEdge-R620:~# ethtool -g enp66s0f1
Ring parameters for enp66s0f1:
Pre-set maximums:
RX:             4096
RX Mini:        0
RX Jumbo:       0
TX:             4096
Current hardware settings:
RX:             4096
RX Mini:        0
RX Jumbo:       0
TX:             4096

Expected to receive 10G traffic. Our cards are 10G, we need pointers to improve the tx rate to line rate and to avoid pktdrop in receiver.

**Comment by KeithWiles** [comment]
Not sure I understand the picture above. I believe Dell-1 is sending to Dell-2 via the enp5s0f1 network interface. I do not understand ens6s0f0/ens6s0f1, plus later in the text I see enp66s0f0 and ens66s0f1 which I do not see in the picture. Plus they are not handled by pktgen I believe.

Anyway the pktgen command line you are using has -c 0xff00f, but the -m [1:3].0 is only using 3 lcores.
I would use -l 0,1,3 and you have 12 lcores assigned. The -l option uses lcore numbers and much easier to use IMO.

Pktgen uses the first lcore 0 in this case for display and timer, then we have port 0 using lcore 1 and 3. lcore one is for RX and 3 is for TX. To get a higher RX/TX speeds you need to add more lcores to the Rx/Tx for port 0.

I would do something like this:
./usr/local/bin/pktgen -l 0,1-3,4-7 -n 4 -- -T -P -m [1-3:4-7].0 -s 0:/home/dell1/output2_src_24.pcap

This adds 3 lcores to Rx and to Tx. You need to make sure you are using one hyper-thread per lcore for best performance. Using DPDK user tool cpu_layout.py will show you the lcores and which socket each one using. If you only have on CPU then you do not need to worry about this step. Also if you do have multiple sockets then you need to make sure you use lcores on the socket the NIC is attached.

I do not know your hardware configuration and can not easily help setup the system.
