### ISSUE TITLE
Set arbitrary ethertype value

### ISSUE THREAD

**Issue by jwbensley** [pktgen/Pktgen-DPDK#123]
Is it possible to set an arbitrary ethertype value?

Using a Lua script to test a range of values e.g. `pktgen.set_type("all", "ipv4");` only the options `ipv4|ipv6|vlan` work. To clarify I can actually use a statement like `pktgen.set_type("all", 1);`  or `pktgen.set_type("all", 0x1);` but running a packet capture reveals the packets are always using the Pktgen default Ethernet type value of IPv4.

**Comment by pktgen** [comment]
Sorry, I only allow IPv4/IPv6 values. The code defaults to IPv4 if the value is not known.

> On Nov 11, 2017, at 4:08 AM, James Bensley <notifications@github.com> wrote:
> 
> Is it possible to set an arbitrary ethertype value?
> 
> Using a Lua script to test a range of values e.g. pktgen.set_type("all", "ipv4"); only the options ipv4|ipv6|vlan work. To clarify I can actually use a statement like pktgen.set_type("all", 1); or pktgen.set_type("all", 0x1); but running a packet capture reveals the packets are always using the Pktgen default Ethernet type value of IPv4.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by jwbensley** [comment]
Hi Keith,

Thanks for the confirmation.
