### ISSUE TITLE
EAL parameter -w has been removed in dpdk v21.11.1 LTS - Update README.md accordingly

### ISSUE THREAD

**Issue by subendu4u** [pktgen/Pktgen-DPDK#124]
Historically, we used pktgen with the `-w` option of dpdk to specify the pci whitelist.
This option however was deprecated in dpdk v20.11 LTS and is finally removed from dpdk v21.11 LTS.
Hence, we need to move to the correct `-a` option of dpdk.

```
Option -w, --pci-whitelist is deprecated, use -a, --allow option instead
```

With the new dpdk, we get this error when we run pktgen with `-w`:
```
-bash-4.2# sudo -E pktgen -l 4-7 -n 4 --proc-type auto --log-level 7 --socket-mem 1024 --file-prefix pg -w 00:07.0 -w 00:08.0 -- -T -P -N --crc-strip -m [5].0 -m [6].1 -f /tmp/tmp.lua

Copyright(c) <2010-2021>, Intel Corporation. All rights reserved. Powered by DPDK
EAL: SSE4 support detected
pktgen: invalid option -- 'w'
```

We need to modify the `REAME.md` file of pktgen to reflect this.

**Comment by KeithWiles** [comment]
Updated in the next release.
