### ISSUE TITLE
Pktgen maximum throughput

### ISSUE THREAD

**Issue by ognjen011** [pktgen/Pktgen-DPDK#125]
Hi 

i am testing a 100G link through SRIOV and i am consistently  finding that pktgen hangs at around 1.2 mpps which is around 4.5 to 6 gbps.  On the website the https://pktgen-dpdk.readthedocs.io/en/latest/ it says that pktgen can handle 10G network with 64bytes frame size. Can it scale to a 100G how do i make it generate more packets?

**Comment by KeithWiles** [comment]
I run pktgen on my 40G NICs on a Xeon platform with two sockets and about 112 logical core. I get about 40Mpps at 64 byte frames. The rate of 1.2 Mpps is very low, but it does depend on the process and core speeds. Normally on a single core I can get close to 10G or 14Mpps TX performance. To get the 40Mpps are need to add more TX cores per port and Rx cores if you need to receive at this rate.

Here is the configuration file I am using, which will have to be changed for your system/platform. The NIC and the cores need to be on the same NUMA zone as well.

```c
description = 'A Pktgen default simple configuration'

# Setup configuration
setup = {
    'exec': (
	'sudo', '-E'
        ),

    'devices': (
	    '03:00.0', '03:00.1',
	    '82:00.0', '82:00.1'
	    ),
    # UIO module type, igb_uio, vfio-pci or uio_pci_generic
    'uio': 'vfio-pci'
    }

# Run command and options
run = {
    'exec': (
	'sudo', '-E'
        ),

    # Application name and use app_path to help locate the app
    'app_name': 'pktgen',

    # using (sdk) or (target) for specific variables
    # add (app_name) of the application
    # Each path is tested for the application
    'app_path': (
		'./usr/local/bin/%(app_name)s',
		'/usr/local/bin/%(app_name)s'
        ),

	'cores': '2,4-7,8-11,14-17,18-21',
	'nrank': '4',
	'proc': 'auto',
	'log': '7',
	'prefix': 'pg',

	'allowlist': (
		'03:00.0', '03:00.1',
		'82:00.0', '82:00.1'
		),

	'opts': (
		'-v',
		'-T',
		'-P',
		'-G',
		),
	'map': (
		'[4-5:6-7].0',
		'[8-9:10-11].1',
		'[14-15:16-17].2',
		'[18-19:20-21].3',
		),

	'theme': 'themes/black-yellow.theme',
	'loadfile': 'cnet-fwd'
	}
```

I hope this helps.

**Comment by ognjen011** [comment]
Just one more comment do you see any limitation running through kuberntes while testing? I am running it  on AMD epyic 128 cores and intel xeon gold 128 cores,  i seem to be getting seeing the same limitation on both. These tests are  running  on the best NUMA node. Normally 4 cores are assigned to the pods that are executing the tests i tried with 8 it seems it was the same. Networks and servers are not utilised at all during the tests so i would think i am hitting the system limits. I will try with your config file to make sure there is nothing there that might be misconfigured.

**Comment by KeithWiles** [comment]
I would not expect Kuberntes to be a problem.

Can you send me your command line, DPDK version and Pktgen version. The output from the cpu_layout.py script (int DPDK usertools directory) and the NUMA node the NIC is located.

**Comment by ognjen011** [comment]
The pods are configured with dpdk 19.11 LTS and for pktgen version i am not sure exactly how to check but when i run it with -v i am seeing 

Copyright (c) <2010-2019>, Intel Corporation. All rights reserved. Powered by DPDK
EAL: Detected 64 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: RTE Version: 'DPDK 19.11.0'

For the best numa there is an algorithm within a tool to check and choose best or worst NUMA as needed for testing so i never try and set best NUMA before the test run. The physical card is on NUMA 1. The card is Intel E810 100G. 

available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62
node 0 size: 128372 MB
node 0 free: 100092 MB
node 1 cpus: 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63
node 1 size: 129012 MB
node 1 free: 97925 MB
node distances:
node   0   1 
  0:  10  20 
  1:  20  10 

NUMA node(s):                    2
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63

Output from the script on one of client pods during the execution of the test:

======================================================================
Core and Socket Information (as reported by '/sys/devices/system/cpu')
======================================================================

cores =  [0, 16, 1, 17, 2, 18, 3, 19, 4, 20, 5, 21, 6, 22, 7, 23, 8, 24, 9, 25, 10, 26, 11, 27, 12, 28, 13, 29, 14, 30, 15, 31]
sockets =  [0, 1]

        Socket 0     Socket 1    
        --------     --------    
Core 0  [0]          [1]         
Core 16 [2]          [3]         
Core 1  [4]          [5]         
Core 17 [6]          [7]         
Core 2  [8]          [9]         
Core 18 [10]         [11]        
Core 3  [12]         [13]        
Core 19 [14]         [15]        
Core 4  [16]         [17]        
Core 20 [18]         [19]        
Core 5  [20]         [21]        
Core 21 [22]         [23]        
Core 6  [24]         [25]        
Core 22 [26]         [27]        
Core 7  [28]         [29]        
Core 23 [30]         [31]        
Core 8  [32]         [33]        
Core 24 [34]         [35]        
Core 9  [36]         [37]        
Core 25 [38]         [39]        
Core 10 [40]         [41]        
Core 26 [42]         [43]        
Core 11 [44]         [45]        
Core 27 [46]         [47]        
Core 12 [48]         [49]        
Core 28 [50]         [51]        
Core 13 [52]         [53]        
Core 29 [54]         [55]        
Core 14 [56]         [57]        
Core 30 [58]         [59]        
Core 15 [60]         [61]        
Core 31 [62]         [63]

**Comment by KeithWiles** [comment]
When pktgen is started it will display a lot of information and this is not it. If you have the pktgen source directory you can look in the VERSION file for the version. If this is DPDK 19.11 I can not support older versions of DPDK with Pktgen, I do this work in my spare time and providing backward compatibility is very hard to maintain as DPDK keeps changing function name and defines :-(

If you can please update to latest DPDK version from dpdp.org and the latest Pktgen from github.com/pktgen/Pktgen-DPDK. Because Pktgen is a tools you can use the latest DPDK. If you need to test your application with older DPDK versions you can still do that, but Pktgen tool needs to be build with the latest DPDK version.

**Comment by ognjen011** [comment]
Ok thanks for letting me know i just wanted to see if there was something i am missing the version file says 19.12.0. I will ask around DPDK upgrading to newer versions as these images are not built by me.

**Comment by KeithWiles** [comment]
This version is very old. The performance of a traffic generator in a container can be limited by a number of things, but I can tell you that Pktgen can achieve around 40Mpps TX with the configuration I provided above, so I am thinking it is something in the environment slowing down the performance. It could be some OVS or it is using a TUN/TAP interface or a number of little things. Good luck
