### ISSUE TITLE
protocol for range

### ISSUE THREAD

**Issue by x1nas** [pktgen/Pktgen-DPDK#126]
Help:
`range <portlist> proto tcp|udp                - Set the IP protocol type`

Command:
`Pktgen:/> range 0 proto udp`

Error:
```
Range command error:
  Invalid line: <range 0 proto udp >
```

Version:
`Pktgen Ver: 3.4.2 (DPDK 17.05.2)`

**Comment by pktgen** [comment]
That should work but I am out of town for the week and will take some time to look into the problem
