### ISSUE TITLE
[Feature Request] A deployed version of doc

### ISSUE THREAD

**Issue by duskmoon314** [pktgen/Pktgen-DPDK#126]
I just found this fantastic project and want to use it to replay several pcap files. But I found that a massive part of `README` talks about the previous version with some non-exist files. Also, it seems the doc has more detail than `README` and `INSTALL`. So I wonder if there is a deployed version of the doc.

If not, I suggest using GitHub action and pages to support this feature. I believe this will ease the usage of this project.

**Comment by KeithWiles** [comment]
If you could submit a patch to add this support it would be great. I have very limited time now a days. :-(

**Comment by duskmoon314** [comment]
I've opened a PR. Please review my solution.
