### ISSUE TITLE
How to create 3-way  TCP handshake

### ISSUE THREAD

**Issue by jiawen94** [pktgen/Pktgen-DPDK#127]
I want to test a tunnel's throughput by pktgen-dpdk.In some reasons, I need to use TCP protocol instead of UDP.
The proto is set  tcp,and it failed.
I captured packets and found the TCP packet is retransmission.DUT replied RST to DPDK NIC. Maybe the tcp transmission is illegal because the 3-way handshake is not finished.
![image](https://user-images.githubusercontent.com/29114225/195275229-d984321a-ee21-4c1a-9769-627997bf0c39.png)

**Comment by KeithWiles** [comment]
Pktgen can send a TCP frame, but it does not handle the TCP protocol, which is why you see pktgen not handle the three-way handshake. Pktgen is not setup to handle the TCP protocol, sorry.
