### ISSUE TITLE
lua delay causes crash

### ISSUE THREAD

**Issue by joeswaminathan** [pktgen/Pktgen-DPDK#127]
If the lua script has a delay, and if I pass the script using -f option while starting DPDK it works fine. 

But if I open a socat session and pass the same file, it crashes. On the thread it is running, lcore_id is not defined.  lcore_id is defined only on EAL threads (if I read the code correctly). Seems when using socat it uses a different thread. 

Is this a known issue, and is there a work around ?

**Comment by pktgen** [comment]
This is a known problem and I do not have a good work around except then fixing the code.

**Comment by joeswaminathan** [comment]
I am new to pktgen and DPDK. If someone can give me some pointers on how to go about fixing it I can work on that. 

In the mean time I made one small change to the following functions. Now it doesnt crash. But it doesnt wait also. The call to delay returns immedieately.

int
cli_use_timers(void)
{
        if (!this_cli)
                return 0; /* was return 1 */
        return this_cli->flags & CLI_USE_TIMERS;
}
