### ISSUE TITLE
Location of the packets generated

### ISSUE THREAD

**Issue by SungHoHong2** [pktgen/Pktgen-DPDK#128]
Hello Currently, I am trying to find out where the dpdk-pktgen generates the packets. 
However it was difficult for me to access further than from pktgen-main.c to pktgen-client-start.c 

I assume that the functions are listed in an pointer array and invoked when the clients add the command in the client.

So would it be possible to know exactly where the packets are created in the source code?

**Comment by pktgen** [comment]
Look in pktgen.c for functions called pktgen_main_rxtx_loop, pktgen_main_rx_loop, pktgen_main_tx_loop. These are start via the call to launch DPDK and its thread processing code.

> On Nov 19, 2017, at 2:40 PM, SungHo Hong <notifications@github.com> wrote:
> 
> Hello Currently, I am trying to find out where the dpdk-pktgen generates the packets.
> However it was difficult for me to access further than from pktgen-main.c to pktgen-client-start.c
> 
> I assume that the functions are listed in an pointer array and invoked when the clients add the command in the client.
> 
> So would it be possible to know exactly where the packets are created in the source code?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by SungHoHong2** [comment]
Thank you very much
