### ISSUE TITLE
The unit of Tx rate in single mode might be incorrect

### ISSUE THREAD

**Issue by duskmoon314** [pktgen/Pktgen-DPDK#128]
## Description

I just set up Pktgen and learning how to use it. In single mode, I use the default setting (packet size 64) to send packets to another machine, and I get around `600 Mbps` in real with `MBits/s Rx/Tx	: 0/9,999` shown in the `page main`.

It seems 10000 packets with 64 Bytes is 625 MB, so I wonder if this is a mistake to show `MBps` instead of `Pps`.

## Env

- DPDK version: 22.07
- Pktgen version: 22.07
- OS: ubuntu 22.04

**Comment by KeithWiles** [comment]
Not sure I fully understand your statement. The display shows PPS and Mbits/s for the TX rate.

![Screen Shot 2022-10-13 at 8 27 48 AM](https://user-images.githubusercontent.com/86847941/195609704-0e21494a-15b1-4b79-ab86-f896eaf029f2.png)

Here we show about 28.7 Mbits/s at a rate of 42.8 Mpps.

**Comment by duskmoon314** [comment]
I have just tested the `Single mode`, and the `MBits/s Rx/Tx` is always around `0/9999` no matter what `size` is. That is, I get around 600 Mbps when the size is 64 and nearly 10 Gbps when the size is 1400. I set the `size` via `set <port> size <number>`

**Comment by KeithWiles** [comment]
Are you stopping the traffic before setting the packet size? The 600Mbps seems a bit low, but it depends on the number and type of cores you are using. As you can see I have in above screen shot 3 Rx and 3 TX cores driving 42.7Mpps getting 28.8 GBits/s.

What is the PPS rate at 64 byte frames is that close to wire rate. If you can show a screen shot, your command line and if you have the -v option on your command line can you show me the startup console output too.

**Comment by duskmoon314** [comment]
CPU: Intel(R) Xeon(R) CPU E3-1230 v3

My command is `sudo -E ./usr/local/bin/pktgen -l 0-4 -n 2 --proc-type auto --log-level 7 --file-prefix pg -a 01:00.0 -- -v -T -P -m [1-2:3-4].0`

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/20477228/195618771-02f10aaf-fbd4-47b4-99a0-0a8730f690ac.png">

after setting size to 1400
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/20477228/195618851-82d750d3-ff2c-4396-b056-7bfe8df79693.png">

**Comment by KeithWiles** [comment]
At 64 byte frames you are getting 14.8Mpps on a 10Gbit link, which is wire rate and 9.9Gbits is very close to the 10Gbits. On some NICs the 64 byte frames are limited and you may not be able to get 10Gbits because the PCI bus on the NIC.

You are using 3 cores for Rx and 3 cores for TX -m [1-2:3-4].0 in this setup you will be able to achieve wire rate at any packet size.

**Comment by KeithWiles** [comment]
I was looking at Pktgen sending rate and not the RX rate. I assume the text in the upper right is some application monitoring the RX rate. Pktgen is sending the correct amount of data, but the RX side is not able to receive that rate of traffic. You can adjust the rate via 'set 0 rate 10' for 10% rate if that is needed. On the receive side it appears the PPS rate is limited in some way as it is not getting the 14.8Mpps most likely being dropped at the phy layer or some place else.

**Comment by duskmoon314** [comment]
> On the receive side it appears the PPS rate is limited in some way as it is not getting the 14.8Mpps most likely being dropped at the phy layer or some place else.

Sounds reasonable. I will try to find out why this happened. Thanks for your help.

**Comment by KeithWiles** [comment]
The RX application is using standard Linux sockets then that is where the packet rate is being lost. The Linux socket layer has a lot of overhead and can only get at most 1Mpps rate. If you use a DPDK application on the RX side then you will see the correct rate is my guess.

**Comment by duskmoon314** [comment]
Oh, in my mind `nload` indeed use socket. Thanks
