### ISSUE TITLE
Generating packets with wrong packet sizes

### ISSUE THREAD

**Issue by Zendarsk** [pktgen/Pktgen-DPDK#129]
Each packet size is decreased by 4.
Command set 0 size 64 is generating packets with size 60.
Pktgen Ver: 3.4.2 (DPDK 17.11.0-rc0)

**Comment by pktgen** [comment]
The hardware should be adding the Frame checksum of 4 bytes making a 64 byte frame on the wire.

> On Nov 19, 2017, at 10:25 PM, Michal <notifications@github.com> wrote:
> 
> Each packet size is decreased by 4.
> Command set 0 size 64 is generating packets with size 60.
> Pktgen Ver: 3.4.2 (DPDK 17.11.0-rc0)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by Zendarsk** [comment]
It looks like the problem is somewhere in the VirtualBox network interface but when I view the packets in Wireshark they look fine but still they are smaller.
