### ISSUE TITLE
How to replay pcap based on `time` of entries?

### ISSUE THREAD

**Issue by duskmoon314** [pktgen/Pktgen-DPDK#129]
I want to replay the traffic based on the time in the pcap files. So, after filling pcap files in `default.cfg`, I run pktgen like this:

```
sudo -E ./usr/local/bin/pktgen -l 0-4 -n 2 --proc-type auto --log-level 7 --file-prefix pg -a 01:00.0 -- -v -T -P -m [1-2:3-4].0 -s 0:pcap/ssldosA.pcap -f themes/black-yellow.theme
```

When I start the transmission, it seems pktgen does its best to transmit, i.g., at line speed. Unfortunately, this is much faster than it should be. The pcap is a capture of SSL dos attack and around 3Mbps, and pktgen transmits it at 10Gbps.

Is there a way to replay pcap based on the `time` of entries? If so, how could I do that? Thanks for any help.

**Comment by KeithWiles** [comment]
Sorry, Pktgen does not support sending traffic using the timestamp in the pcap file. The only thing I can suggest is to set the rate to something closer to what you except the timestamp rate.

**Comment by duskmoon314** [comment]
I see. Thanks
