### ISSUE TITLE
ping4 with vlan tag

### ISSUE THREAD

**Issue by x1nas** [pktgen/Pktgen-DPDK#130]
set vlan doesn't afftect to ping4 command.
Is there any way to send ping with vlan tag?

**Comment by pktgen** [comment]
No sorry, did not support VLAN ID for ICMP Echo.

> On Nov 27, 2017, at 11:40 AM, x1nas <notifications@github.com> wrote:
> 
> set vlan doesn't afftect to ping4 command.
> Is there any way to send ping with vlan tag?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith
