### ISSUE TITLE
pktgen build fails

### ISSUE THREAD

**Issue by juliayyj** [pktgen/Pktgen-DPDK#131]
I run "make" and pktgen build fails like this:
== lua
Please do 'make PLATFORM' where PLATFORM is one of these:
   aix bsd c89 freebsd generic linux macosx mingw posix solaris
See doc/readme.html for complete instructions.

make[2]: *** No rule to make target“/root/pktgen-3.4.5/app/x86_64-native-linuxapp-gcc/../../lib/lua/src/x86_64-native-linuxapp-gcc/lib/librte_lua.a”. Stop.

**Comment by pktgen** [comment]
> On Dec 28, 2017, at 2:43 AM, juliayyj <notifications@github.com> wrote:
> 
> I run "make" and pktgen build fails like this:
> == lua
> Please do 'make PLATFORM' where PLATFORM is one of these:
> aix bsd c89 freebsd generic linux macosx mingw posix solaris
> See doc/readme.html for complete instructions.

I had to remove Lua code from Pktgen and download the code from lua.org. The scripts should have pulled the code down and applied the patch file to build Pktgen.

Look in the lib directory for the patch and apply it or it is possible you do not have patch installed.

> 
> make[2]: *** No rule to make target“/root/pktgen-3.4.5/app/x86_64-native-linuxapp-gcc/../../lib/lua/src/x86_64-native-linuxapp-gcc/lib/librte_lua.a”. Stop.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by juliayyj** [comment]
Thank you very much!
I have another compile error:
pktgen-3.4.6/app/pktgen-stats.c:17:25: fatal error: rte_bus_pci.h: No such file or directory
And I didn't find this file under DPDK or pktgen directory

**Comment by pktgen** [comment]
> On Jan 2, 2018, at 1:03 AM, juliayyj <notifications@github.com> wrote:
> 
> Thank you very much!
> I have another compile error:
> pktgen-3.4.6/app/pktgen-stats.c:17:25: fatal error: rte_bus_pci.h: No such file or directory
> And I didn't find this file under DPDK or pktgen directory

This files was added recently in drivers/bus/pci directory, which version of DPDK are you using?

My have to ifdef this code that is using the latest DPDK.

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by juliayyj** [comment]
I'm using verison 17.08.1 which don't have drivers/bus/pci directory ,I change it to verison 17.11 to solve it,so I think maybe you should change code in pktgen-states.c:
#if RTE_VERSION >= RTE_VERSION_NUM(17, 5, 0, 0)
#include <rte_bus_pci.h>
#endif

**Comment by youf3** [comment]
Hi, 

I had the similar issue with commit 7178fda2373a71d5b2b868ac036644fb8115039c (3.4.8).
This time it is pktgen-latency.c :

..../pktgen-dpdk/app/pktgen-latency.c:17:10: fatal error: rte_bus_pci.h: No such file or directory
 #include <rte_bus_pci.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
..../dpdk-stable-17.08.1/mk/internal/rte.compile-pre.mk:138: recipe for target 'pktgen-latency.o' failed
make[2]: *** [pktgen-latency.o] Error 1
..../dpdk-stable-17.08.1/mk/rte.extapp.mk:47: recipe for target 'pktgen' failed
make[1]: *** [pktgen] Error 2
..../dpdk-stable-17.08.1/mk/rte.extsubdir.mk:48: recipe for target 'app' failed
make: *** [app] Error 2

Changing the corresponding line in pktgen-latency.c with pktgen-states.c seems to solve the issue.
