### ISSUE TITLE
Performance does not improved with multiple queues when using pcap file

### ISSUE THREAD

**Issue by quanwenli** [pktgen/Pktgen-DPDK#132]
There is no performance difference with 1 queue and multiple queues when using pcap file under 100Gb network. 

1 queue: 
 /root/Pktgen-DPDK/build/app/pktgen -l 0,2 - n 4 -- -T -P -m "[2:2].0" -N  -s 0:big.pcap
Pktgen:/> enable 0 pcap
Pktgen:/> start 0
<img width="555" alt="1-queue-pcap-file" src="https://user-images.githubusercontent.com/26761971/207276034-aa3c4844-6be6-441a-a87b-b82a65ccd8b1.png">
Pktgen:/> page stats
<img width="707" alt="1-queue-page-stats" src="https://user-images.githubusercontent.com/26761971/207277213-9eede479-1876-4b69-9225-33844e96b5d4.png">

8 queues:

 /root/Pktgen-DPDK/build/app/pktgen -l 0,2,4,6,8,10,12,14,16 - n 4 -- -T -P -m "[2/4/6/8/10/12/14/16:2/4/6/8/10/12/14/16].0" -N  -s 0:big.pcap
Pktgen:/> enable 0 pcap
Pktgen:/> start 0
<img width="568" alt="8-queues-pcap-file" src="https://user-images.githubusercontent.com/26761971/207276061-8b03f49a-b3b4-4fc3-bc93-c348dd054309.png">
Pktgen:/> page stats
<img width="735" alt="8-queues-page-stats" src="https://user-images.githubusercontent.com/26761971/207277316-d6719ac8-b201-4520-8ca2-6ef59cb50c00.png">

**Comment by KeithWiles** [comment]
The configuration I would change a bit the lcores being used are on both RX and TX. Splitting up the lcores used for RX and TX would be 4 lcores for Rx and 4 lcores for TX

/root/Pktgen-DPDK/build/app/pktgen -l 0,2,4,6,8,10,12,14,16 - n 4 -- -T -P -m "[2/4/6/8:10/12/14/16].0" -N -s 0:big.pcap

If you have more lcores you can add them them each side. If you are only concerned with TX then you have one for the RX side and then use the reset on the TX side.

**Comment by quanwenli** [comment]
> The configuration I would change a bit the lcores being used are on both RX and TX. Splitting up the lcores used for RX and TX would be 4 lcores for Rx and 4 lcores for TX
> 
> /root/Pktgen-DPDK/build/app/pktgen -l 0,2,4,6,8,10,12,14,16 - n 4 -- -T -P -m "[2/4/6/8:10/12/14/16].0" -N -s 0:big.pcap
> 
> If you have more lcores you can add them them each side. If you are only concerned with TX then you have one for the RX side and then use the reset on the TX side.

I tired 12 queues, but the performance is the same with the 1 queue. 

/root/Pktgen-DPDK/build/app/pktgen -l 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52 - n 4 -- -T -P -m "[2/4/6/8/10/12/14/16/18/20/22/24:26/28/30/32/34/36/38/40/42/44/46/48].0" -N  -s 0:big.pcap

**Comment by KeithWiles** [comment]
hmmm, the logic in the code works I have a 40G nic with 2 lcores per RX/TX and I am able to push 42Mpps. I am not using a pcap file.

Please turn off PCAP mode and use the single packet mode, plus we the destination MAC address to the target NIC address just to eliminate anything. What is the NIC you are using?

**Comment by quanwenli** [comment]
> hmmm, the logic in the code works I have a 40G nic with 2 lcores per RX/TX and I am able to push 42Mpps. I am not using a pcap file.
> 
> Please turn off PCAP mode and use the single packet mode, plus we the destination MAC address to the target NIC address just to eliminate anything. What is the NIC you are using?

True off PCAP mode, get 123mpps with single packet mode with 8 tx/rx queues with 64 packet size.  the Nic is Mellanox ConnectX-6 Dx

With pcap mode, could you get 42mpps?

**Comment by KeithWiles** [comment]
I have not tried it yet. The way the PCAP support works is pktgen prefill the pcap data into mbufs and then loop sending the mbufs. The single packet mode prefills the mbufs and loops sending those mbufs. Very similar, but it looks like something is different.
