### ISSUE TITLE
!ERROR!: Could not read enough random data for PRNG seed

### ISSUE THREAD

**Issue by AlanLLLL** [pktgen/Pktgen-DPDK#132]
I have two servers with which has a 40G Intel NIC with two ports. Host1 has port0 and port1, Host2 has port0 and port1. 

Host2's two ports are in forwarding mode and the tested network path is something like the following:
Host1.port0 ==>Host2.port0 ==>Host2.port1 ==> Host1.port1

When one machine is running pkt-gen ver. 3.4.6 with dpdk 17.11 using the following command:
sudo ./app/x86_64-native-linuxapp-gcc/pktgen -l 0,1-8 -n 4 --socket-mem 2048 -- -T -P -m "[1-4].0, [5-8].1"

In the startup log, two ports show the following log:

Port  0: Link Up - speed 40000 Mbps - full-duplex <Enable promiscuous mode>
!ERROR!: Could not read enough random data for PRNG seed
Port  1: Link Up - speed 40000 Mbps - full-duplex <Enable promiscuous mode>
!ERROR!: Could not read enough random data for PRNG seed

Both two ports cannot transmit packet on pkt-gen ver. 3.4.6 but they can under ver. 3.4.5. I'm confused about this "!ERROR!: Could not read enough random data for PRNG seed". Would this error affect packet transmit performance?

Can you please help out this error?

Thanks in advance.

**Comment by pktgen** [comment]
Sent from my iPhone

> On Jan 8, 2018, at 7:08 PM, Alan Liu <notifications@github.com> wrote:
> 
> I have two servers with which has a 40G Intel NIC with two ports. Host1 has port0 and port1, Host2 has port0 and port1.
> 
> Host2's two ports are in forwarding mode and the tested network path is something like the following:
> Host1.port0 ==>Host2.port0 ==>Host2.port1 ==> Host1.port1
> 
> When one machine is running pkt-gen ver. 3.4.6 with command
> sudo ./app/x86_64-native-linuxapp-gcc/pktgen -l 0,1-8 -n 4 --socket-mem 2048 -- -T -P -m "[1-4].0, [5-8].1"
> 

Are you using the random mode that would be the only way to make this work?
> In the startup log, two ports show the following:
> 
> Port 0: Link Up - speed 40000 Mbps - full-duplex 
> !ERROR!: Could not read enough random data for PRNG seed
> Port 1: Link Up - speed 40000 Mbps - full-duplex 
> !ERROR!: Could not read enough random data for PRNG seed
> 

I get these error too but it does not seem to stop pktgen. 
> Both two ports cannot transmit packet on pkt-gen ver. 3.4.6 but they can under ver. 3.4.5. I'm confused about this "!ERROR!: Could not read enough random data for PRNG seed". Would this error affect packet transmit performance?
> 

Unless you are using the random packet data mode.

**Comment by AlanLLLL** [comment]
Thanks a lot for the prompt reply. Yes, I'm using the default random packet data mode. I'm quite new to pkt-gen dpdk. I will try to see if using pcap mode.
Since Ver. 3.4.5. works, I just worry about the performance...
