### ISSUE TITLE
how to quit pktgen from lua script

### ISSUE THREAD

**Issue by ellagxy** [pktgen/Pktgen-DPDK#133]
Hi,
I'm running pktgen version 3.4.2. When I start pktgen with -f option given script having "quit", pktgen does not seem like loading the script at all. If I put "quit()" in script, pktgen loads the script but will not quit.

I saw there's issue#16 is related, marked as bug but closed, so not sure what is the status of this issue now.

**Comment by pktgen** [comment]
Please update to pktgen 3.4.7 and I have added the support to quit from a command file or lua script using pktgen.quit()

> On Jan 9, 2018, at 11:25 AM, ellagxy <notifications@github.com> wrote:
> 
> Hi,
> I'm running pktgen version 3.4.2. When I start pktgen with -f option given script having "quit", pktgen does not seem like loading the script at all. If I put "quit()" in script, pktgen loads the script but will not quit.
> 
> I saw there's issue#16 is related, marked as bug but closed, so not sure what is the status of this issue now.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by ellagxy** [comment]
Got it. Thanks a lot!
