### ISSUE TITLE
Latency sampler writes 0 latencies to file on every attempt to run it

### ISSUE THREAD

**Issue by jyrge** [pktgen/Pktgen-DPDK#134]
Hi,

I'm using pktgen-dpdk to generate traffic for a simple l2fwd test case, utilizing 1 port for both rx/tx. I want to dump sample latencies to a file and found out that there is a latency sampler feature. However, every time I try to run latency sampler, I get warning, which says that 0 sample latencies were written to the file. The file samples.txt contains a single line "Latency" without any sample data.

Latency page shows values for latencies as expected.

Pktgen was run with:
sudo ./pktgen -c 0x7 -n 4 -- -m [1:2].0

Commands in pktgen:
enable 0 latency
set 0 latsampler simple 120 2 /home/ubuntu/samples.txt
start 0
start 0 latsampler

wait for a while...

stop 0 latsampler
_WARNING: Wrote 0 sample latencies to file /home/ubuntu/samples.txt_
stop 0

Tested with both Pktgen-DPDK 21.11.0 & DPDK 21.11 (on Ubuntu 20.04) and Pktgen-DPDK 22.04 & DPDK 22.03 (on Ubuntu 22.04).

**Comment by KeithWiles** [comment]
HI Jyrge, At one point the latency sampler depended on the size of the packet, because the time stamp needed to be inserted in the frame. If the frame size was too small 64 bytes the timestamp would not be valid and the RX side could not detect the time stamp. If you are using 64 byte frames please increase the size to say 76 or 78, I would have to check which version a patch was applied to make sure the packet was the correct size.

One of the limitation with latency measuring on older Intel CPUs was the timestamp counters per core were not synced, which means sending a latency packet from one core and receiving the packet on another core could give very different latency values. To fix that issue you need to send and receive the same lcore. If this is occurring please use -m 1.0

The other issue could be the packets are not being sent back to pktgen from the DPDK l2fwd application and a number of configuration issues could be the reason.

**Comment by jyrge** [comment]
Hi, and thank you for the answer! enable 0 latency seems to change pkt size to 80. I have also tried with different packet sizes from 80 to 1518, and it didn't seem to affect this.

Here's some more information about the test setup. The test environment runs on ARM-based processors (Graviton2) in AWS EC2 instances, and the Amazon's Elastic Network Adapters are being used as NICs via ENA PMD. I'm using Pktgen-DPDK 21.11.0 with DPDK 21.11 there, as it seemed to compile nice on Ubuntu 20.04.5. The device under test runs l2fwd sample application from [OpenDataPlane](https://github.com/OpenDataPlane/odp-dpdk) project, with DPDK enabled. Pktgen running in the another instance sends traffic from port 0 to the DUT, on which the l2fwd forwards packets back to the same port. I have tested that the traffic flows through the setup, though there may be some packet drop occurring on the way. I have also tested with different wire rates from 1 to 100 % from the pktgen side. I could otherwise manage with the average latency values shown in the Latency page (or via Lua script...), but I wish to calculate some other metrics (average jitter in ms, for example) for a certain period of time, so the latency samples would be beneficial.

I try with a single core for rx/tx next, and return here when I have some results on that.

**Comment by jyrge** [comment]
Running pktgen with -m 1.0 did not have the desired effect in AWS.

I replicated the setup in VirtualBox (two Ubuntu 20.04 VMs) on my own laptop, even though it doesn't exactly match the real test setup (as the VBox setup runs on x86_64 arch and with emulated Intel NICs). CPU on the host is Intel Core i5-1145G7, NICs in VMs are emulated Intel PRO/1000 MT Desktop (82540 EM). Same issue occurred. Then I tried running DPDK l2fwd (DPDK 20.11) example instead of odp_l2fwd in the DUT side. The same issue occurred again.

DPDK-l2fwd was run with `-l 0 -n 4 -- -p 1`, pktgen with `-l 0,1 -n 4 -- -P -m 1.0` (promiscuous mode enabled to enable traffic flowing back to the traffic generator when running dpdk-l2fwd, with odp_l2fwd I could achieve this without promiscuous mode by updating MAC in the odp_l2fwd).

Output and commands in the pktgen side:
```
- Ports 0-0 of 1   <Latency Page>  Copyright(c) <2010-2021>, Intel Corporation
  Flags:Port        : P------Lat        :0
Link State          :           <--Down-->    ----TotalRate----
Pkts/s Max/Rx       :        762535/360849        762535/360849
       Max/Tx       :        490339/466845        490339/466845
MBits/s Rx/Tx       :              288/373              288/373
                    :
Latency usec        :                 7315
Jitter Threshold    :                   50
Jitter count        :               635370
Total Rx pkts       :             16696416
Jitter percent      :                    3
                    :
Pattern Type        :              abcd...
Tx Count/% Rate     :        Forever /100%
PktSize/Tx Burst    :            80 /  128
Src/Dest Port       :       64/ 1234/ 5678
Pkt Type:VLAN ID    :      IPv4 / UDP:0001
Dst  IP Address     :          192.168.1.1
Src  IP Address     :       192.168.0.1/24
Dst MAC Address     :    08:00:27:7c:79:3b
Src MAC Address     :    08:00:27:bd:ac:a9
VendID/PCI Addr     :    8086:100e/00:08.0

-- Pktgen 21.11.0 (DPDK 21.11.3)  Powered by DPDK  (pid:14882) ----------------

Pktgen:/> history
   0: set 0 dst mac 08:00:27:7c:79:3b
   1: enable 0 latency
   2: set 0 latsampler simple 50100 835 /home/ubuntu/samples
   3: start 0
   4: start 0 latsampler
   5: page latency
   6: history
Pktgen:/>
```
After stopping the latsampler:
```
Pktgen:/> stop 0 latsampler
WARNING: Wrote 0 sample latencies to file /home/ubuntu/samples
```
Pkt size seems to revert automatically to 64, when latsampler is stopped. Here's the output from log page:
```
/                  <Logged messages>  Copyright(c) <2010-2021>, Intel Corporation
L     Time Function                         Message
I 12:39:36 pktgen_config_ports              Initialize Port 0 -- TxQ 1, RxQ 1
I 12:39:37 pktgen_config_ports              Src MAC 08:00:27:bd:ac:a9
I 12:39:37 pktgen_config_ports               <Promiscuous mode Enabled>
I 12:39:37 pktgen_config_ports
I 12:39:39 pktgen_config_ports
I 12:39:39 port_map_info                      RX/TX processing lcore:   1 rx:  1 tx:  1
I 12:39:39 main                             === Timer Setup

I 12:39:39 main                             === After Timer Setup

I 12:39:39 main                             === Run CLI

I 12:40:59 pktgen_start_latency_sampler     Assigning 50100 sample latencies to queue 0
I 12:43:22 pktgen_stop_latency_sampler      Writing to file /home/ubuntu/samples
I 12:43:22 pktgen_stop_latency_sampler      Writing sample latencies of queue 0
W 12:43:22 pktgen_stop_latency_sampler      Wrote 0 sample latencies to file /home/ubuntu/samples

-- Pktgen 21.11.0 (DPDK 21.11.3)  Powered by DPDK  (pid:14882) ----------------
```

**Comment by jyrge** [comment]
On the other hand, it seems to be possible to access avg_latency, min_avg_latency and max_avg_latency values from pktgen.pktStats, while running Lua scripts. They seem to update in real time when called in scripts, and the field names indicate that some kind of average is calculated from latency samples (?). Is there a significant difference in accuracy compared to latency sampler, if I take samples from avg_latency in a script? I'm considering that as a workaround.

**Comment by KeithWiles** [comment]
The same values are taken for latsampler, so the values should be the same.

Did you try reducing the TX rate to 1% or even 0.01% as I noticed packet loss can cause a number of problems, but I think you did try a lower rate already.

For a different project I was requested to allow latency packets to be sent while sending PCAP file. I created a new branch https://github.com/pktgen/Pktgen-DPDK/tree/latency-changes to create this support, but it meant I needed to rewrite the way latency packets are sent. If you have time please have a look at this branch. I do not think it will fix this problem per say and this is a work in progress.

I still need to look at the latsampler not writing any events into the file and when I do that I will do that work in the new branch.

Hope this helps.

**Comment by jyrge** [comment]
Yes, the problem occurred with 1% wire rate as well. I was also suspecting that packet loss may have something to do with it.

If I can achieve the same result by taking avg_latency values in a script and dumping them in a file, I think I'll stick to that workaround for now in my testing. But for the future, I try to keep an eye on this issue and test things out if there is some progress.
