### ISSUE TITLE
Jitter calculations

### ISSUE THREAD

**Issue by joeswaminathan** [pktgen/Pktgen-DPDK#134]
Pktgen reports jitter as inter arrival time greater than the jitter threshold. 

Ideally jitter is the difference in the sent & received packet delays between two packets. 

Would this community be interested in changing the logic ? If so I have a fix, that I can send for review

**Comment by pktgen** [comment]
> On Jan 9, 2018, at 4:09 PM, Joseph Swaminathan <notifications@github.com> wrote:
> 
> Pktgen reports jitter as inter arrival time greater than the jitter threshold.
> 
> Ideally jitter is the difference in the sent & received packet delays between two packets.
> 
> Would this community be interested in changing the logic ? If so I have a fix, that I can send for review

If you want I can take a look at the patch and see if we can support both or is that what you did?

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by joeswaminathan** [comment]
Thanks Keith, Here is the diff. Let me know what you think

[pktgen-0001-Correct-latency-calculation.txt](https://github.com/pktgen/Pktgen-DPDK/files/1623722/pktgen-0001-Correct-latency-calculation.txt)

**Comment by joeswaminathan** [comment]
Hi Keith,
    Any thoughts ?
thanks
Joe

**Comment by pktgen** [comment]
The code looked fine to me and I applied the patch. Please verify jitter works as you expect. The code is now on the ‘dev’ branch at dpdk.org.

> On Jan 19, 2018, at 12:43 PM, Joseph Swaminathan <notifications@github.com> wrote:
> 
> Hi Keith,
> Any thoughts ?
> thanks
> Joe
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by joeswaminathan** [comment]
Thanks Keith. Will try it

**Comment by ChengjunJia** [comment]
It seems that 
if I enable the **_latency_** and **_range_**/**_seq_** at the same time, the latency calculation is wrong?

**Comment by joeswaminathan** [comment]
Hi ChengjunJia,

     Could you please describe your observation a bit more. The steps you did and what you observed without setting both and with setting both latency and range/seq

thanks
Joe

**Comment by ChengjunJia** [comment]
Two machines with Intel 10Gbps NIC:
One uses the l2fwd in DPDK/example
`sudo -E ./build/l2fwd -c 0xf -n 4 -- -p 1`
The other uses the pktgen
 ` sudo -E ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0xff -n 4 -- -P -m "3.1"`

When I use the following command:
`set 1 size 1000`
`set 1 rate 100`
`enable 1 latency`
`page latency`
`start 1 `
The result is 

\- Ports 0-1 of 2   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :                       P--------L-----:1
Link State        :                           <UP-10000-FD>--
Pkts/s Max/Rx     :                             122432/122432
       Max/Tx     :                             122432/122432
MBits/s Rx/Tx     :                                   999/999
                  :
Latency usec      :                                      69
Jitter Threshold  :                                      50
Jitter count      :                                   17860
Total Rx pkts     :                                 1439936
Jitter percent    :                                       1
                  :
Pattern Type      :                                 abcd...
Tx Count/% Rate   :                            Forever /10%
PktSize/Tx Burst  :                             1000 /   64
Src/Dest Port     :                             1234 / 5678
Pkt Type:VLAN ID  :                         IPv4 / TCP:0001
Dst  IP Address   :                             192.168.0.1
Src  IP Address   :                          192.168.1.1/24
Dst MAC Address   :                       00:00:00:00:00:00
Src MAC Address   :                       3c:fd:fe:ab:06:39
VendID/PCI Addr   :                       8086:1572/01:00.1

-- Pktgen Ver: 3.4.9 (DPDK 16.11.3)  Powered by DPDK --------------------------


When I use the following:
`set 1 size 1000`
`set 1 rate 100`
`enable 1 latency`
`enable 1 range`
`page latency`
`start 1 `

I get these:

\- Ports 0-1 of 2   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :                       P-----R--L-----:1
Link State        :                           <UP-10000-FD>--
Pkts/s Max/Rx     :                             122304/122304
       Max/Tx     :                             122304/122304
MBits/s Rx/Tx     :                                     82/82
                  :
Latency usec      :                                       0
Jitter Threshold  :                                      50
Jitter count      :                                       0
Total Rx pkts     :                                  315200
Jitter percent    :                                       0
                  :
Pattern Type      :                                 abcd...
Tx Count/% Rate   :                            Forever /10%
PktSize/Tx Burst  :                             1000 /   64
Src/Dest Port     :                             1234 / 5678
Pkt Type:VLAN ID  :                         IPv4 / TCP:0001
Dst  IP Address   :                             192.168.0.1
Src  IP Address   :                          192.168.1.1/24
Dst MAC Address   :                       00:00:00:00:00:00
Src MAC Address   :                       3c:fd:fe:ab:06:39
VendID/PCI Addr   :                       8086:1572/01:00.1

-- Pktgen Ver: 3.4.9 (DPDK 16.11.3)  Powered by DPDK --------------------------
