### ISSUE TITLE
Pktgen should probably not set own flags for CPU family optimization

### ISSUE THREAD

**Issue by panicgh** [pktgen/Pktgen-DPDK#135]
Pkgten has options to optimize compilation per CPU family, e.g. `enable-avx2`. DPDK already exports the CPU family it was built with via the pkg-config file. It is settable via DPDK's  [`machine` option](https://git.dpdk.org/dpdk/tree/meson_options.txt#n35), e.g. "meson -Dmachine=x86-64-v4 ...", which propagates to a `-march=x86-64-v4` flag in `libdpdk-libs.pc` and the appropriate `RTE_COMPILE_TIME_CPUFLAGS` defines in rte_build_config.h.

Therefore, it may not make much sense to have these options in Pkgten and it could just use what it inherits from DPDK.

**Comment by KeithWiles** [comment]
Can you please submit a pull request to fix the issue, thanks.
