### ISSUE TITLE
Number of queues per port limited to 16

### ISSUE THREAD

**Issue by bansalcheryl** [pktgen/Pktgen-DPDK#137]
Hi,

Is there a reason why the number of queues are limited to 16 per port?

app/pktgen-constants.h

    NUM_Q = 16, /**< Number of queues per port. */

**Comment by pktgen** [comment]
Some of the devices I started with years ago only had 16 queues. Did you need to use more than 16 queues?

**Comment by bansalcheryl** [comment]
Yes currently I need 30 queues per port but it can go upto 64 queues.

**Comment by bansalcheryl** [comment]
Updated in https://github.com/pktgen/Pktgen-DPDK/commit/44b6d94be7ec48e9eab972ff4c519bfb21bcc0aa
Thanks Keith
