### ISSUE TITLE
pktgen range mode stops transmit packets after sending a few packets

### ISSUE THREAD

**Issue by ellagxy** [pktgen/Pktgen-DPDK#137]
Hi,

I'm running pktgen version 3.4.7. I've configured range traffic like below (basically 64 flows with different dst IP, traffic is sent unidirectional from port 0 to port1). The problem is for pkt size 512, if I start sending traffic with 50% rate from port 0, it will send a few packets and stopped. After that, no matter which rate I chose, it will not sending any packets. Same issue not seen for pkt size 64:

/ Ports 0-1 of 2   <Range Page>  Copyright (c) <2010-2017>, Intel Corporation
Port #                           Port-0              Port-1
dst.ip            :             1.0.1.2             1.0.0.2
    inc           :             0.0.0.1             0.0.0.0
    min           :             1.0.1.2             1.0.0.2
    max           :            1.0.1.65             1.0.0.2
                  :
src.ip            :             1.0.0.2             1.0.1.2
    inc           :             0.0.0.0             0.0.0.1
    min           :             1.0.0.2             1.0.1.2
    max           :             1.0.0.2            1.0.1.65
                  :
ip_proto          :                 UDP                 UDP
                  :
dst.port / inc    :          5678/    0          5678/    0
     min / max    :          5678/ 5678          5678/ 5678
                  :
src.port / inc    :          1234/    0          1234/    0
     min / max    :          1234/ 1234          1234/ 1234
                  :
vlan.id / inc     :              1/   0              1/   0
    min / max     :              1/4095              1/4095
                  :
cos / inc         :                 0/0                 0/0
    min / max     :                 0/7                 0/7
                  :
tos / inc         :               0/  0               0/  0
    min / max     :               0/255               0/255
                  :
pkt.size / inc    :            512/   0            512/   0
     min / max    :             64/1518             64/1518
                  :
dst.mac           :   52:54:00:65:42:55   52:54:00:65:42:55
    inc           :   00:00:00:00:00:00   00:00:00:00:00:00
    min           :   00:00:00:00:00:00   00:00:00:00:00:00
    max           :   00:00:00:00:00:00   00:00:00:00:00:00
                  :
src.mac           :   a0:36:9f:eb:47:e8   a0:36:9f:eb:43:ed
    inc           :   00:00:00:00:00:00   00:00:00:00:00:00
    min           :   00:00:00:00:00:00   00:00:00:00:00:00
    max           :   00:00:00:00:00:00   00:00:00:00:00:00
                  :
gtpu.teid / inc   :             0/    0             0/    0
      min / max   :             0/    0             0/    0
-- Pktgen Ver: 3.4.7 (DPDK 17.05.0)  Powered by DPDK --------------------------  

/ Ports 0-1 of 2   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P-----R--------:0   P-----R--------:1
Link State        :       <UP-10000-FD>       <UP-10000-FD>     ----TotalRate----
Pkts/s Max/Rx     :                 0/0              4842/0                4842/0
       Max/Tx     :              9982/0                 0/0                9982/0
MBits/s Rx/Tx     :                 0/0                 0/0                   0/0
Broadcast         :                   0                   0
Multicast         :                   0                   0
  64 Bytes        :                   0                   0
  65-127          :                   0                   0
  128-255         :                   0                   0
  256-511         :                   0                   0
  512-1023        :                   0                4842
  1024-1518       :                   0                   0
Runts/Jumbos      :                 0/0                 0/0
Errors Rx/Tx      :                 0/0                 0/0
Total Rx Pkts     :                   0                4842
      Tx Pkts     :                9982                   0
      Rx MBs      :                   0                  20
      Tx MBs      :                  42                   0
ARP/ICMP Pkts     :                 0/0                 0/0
                  :
Pattern Type      :             abcd...             abcd...
Tx Count/% Rate   :        Forever /50%        Forever /50%
PktSize/Tx Burst  :           64 /   64           64 /   64
Src/Dest Port     :         1234 / 5678         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / TCP:0001     IPv4 / TCP:0001
802.1p CoS        :                   0                   0
ToS Value:        :                   0                   0
  - DSCP value    :                   0                   0
  - IPP  value    :                   0                   0
Dst  IP Address   :             1.0.1.2             1.0.0.2
Src  IP Address   :          1.0.0.2/24         1.0.1.65/24
Dst MAC Address   :   52:54:00:65:42:55   52:54:00:65:42:55
Src MAC Address   :   a0:36:9f:eb:47:e8   a0:36:9f:eb:43:ed
VendID/PCI Addr   :   8086:1563/00:05.0   8086:1563/00:10.0

-- Pktgen Ver: 3.4.7 (DPDK 17.05.0)  Powered by DPDK --------------------------

Pktgen:/> set all rate 50
Pktgen:/> start 0
Pktgen:/> stop 0

**Comment by ellagxy** [comment]
![screen shot 2018-01-17 at 4 54 46 pm](https://user-images.githubusercontent.com/35269874/35075341-5d9f44fa-fba7-11e7-82a6-0530bf9357d7.png)
![screen shot 2018-01-17 at 4 55 26 pm](https://user-images.githubusercontent.com/35269874/35075343-6094b924-fba7-11e7-9de1-79367076665c.png)

**Comment by pktgen** [comment]
Can you use 3.4.8 as it has a couple fixes for virtio and a TX wait time was too short.

> On Jan 17, 2018, at 6:52 PM, ellagxy <notifications@github.com> wrote:
> 
> Hi,
> 
> I'm running pktgen version 3.4.7. I've configured range traffic like below (basically 64 flows with different dst IP, traffic is sent unidirectional from port 0 to port1). The problem is for pkt size 512, if I start sending traffic with 50% rate from port 0, it will send a few packets and stopped. After that, no matter which rate I chose, it will not sending any packets. Same issue not seen for pkt size 64:
> 
> / Ports 0-1 of 2 Copyright (c) <2010-2017>, Intel Corporation
> Port # Port-0 Port-1
> dst.ip : 1.0.1.2 1.0.0.2
> inc : 0.0.0.1 0.0.0.0
> min : 1.0.1.2 1.0.0.2
> max : 1.0.1.65 1.0.0.2
> :
> src.ip : 1.0.0.2 1.0.1.2
> inc : 0.0.0.0 0.0.0.1
> min : 1.0.0.2 1.0.1.2
> max : 1.0.0.2 1.0.1.65
> :
> ip_proto : UDP UDP
> :
> dst.port / inc : 5678/ 0 5678/ 0
> min / max : 5678/ 5678 5678/ 5678
> :
> src.port / inc : 1234/ 0 1234/ 0
> min / max : 1234/ 1234 1234/ 1234
> :
> vlan.id / inc : 1/ 0 1/ 0
> min / max : 1/4095 1/4095
> :
> cos / inc : 0/0 0/0
> min / max : 0/7 0/7
> :
> tos / inc : 0/ 0 0/ 0
> min / max : 0/255 0/255
> :
> pkt.size / inc : 512/ 0 512/ 0
> min / max : 64/1518 64/1518
> :
> dst.mac : 52:54:00:65:42:55 52:54:00:65:42:55
> inc : 00:00:00:00:00:00 00:00:00:00:00:00
> min : 00:00:00:00:00:00 00:00:00:00:00:00
> max : 00:00:00:00:00:00 00:00:00:00:00:00
> :
> src.mac : a0:36:9f:eb:47:e8 a0:36:9f:eb:43:ed
> inc : 00:00:00:00:00:00 00:00:00:00:00:00
> min : 00:00:00:00:00:00 00:00:00:00:00:00
> max : 00:00:00:00:00:00 00:00:00:00:00:00
> :
> gtpu.teid / inc : 0/ 0 0/ 0
> min / max : 0/ 0 0/ 0
> -- Pktgen Ver: 3.4.7 (DPDK 17.05.0) Powered by DPDK --------------------------
> 
> / Ports 0-1 of 2
> 
> Copyright (c) <2010-2017>, Intel Corporation
> Flags:Port : P-----R--------:0 P-----R--------:1
> Link State : ----TotalRate----
> Pkts/s Max/Rx : 0/0 4842/0 4842/0
> Max/Tx : 9982/0 0/0 9982/0
> MBits/s Rx/Tx : 0/0 0/0 0/0
> Broadcast : 0 0
> Multicast : 0 0
> 64 Bytes : 0 0
> 65-127 : 0 0
> 128-255 : 0 0
> 256-511 : 0 0
> 512-1023 : 0 4842
> 1024-1518 : 0 0
> Runts/Jumbos : 0/0 0/0
> Errors Rx/Tx : 0/0 0/0
> Total Rx Pkts : 0 4842
> Tx Pkts : 9982 0
> Rx MBs : 0 20
> Tx MBs : 42 0
> ARP/ICMP Pkts : 0/0 0/0
> :
> Pattern Type : abcd... abcd...
> Tx Count/% Rate : Forever /50% Forever /50%
> PktSize/Tx Burst : 64 / 64 64 / 64
> Src/Dest Port : 1234 / 5678 1234 / 5678
> Pkt Type:VLAN ID : IPv4 / TCP:0001 IPv4 / TCP:0001
> 802.1p CoS : 0 0
> ToS Value: : 0 0
> 
> 	• DSCP value : 0 0
> 	• IPP value : 0 0
> Dst IP Address : 1.0.1.2 1.0.0.2
> Src IP Address : 1.0.0.2/24 1.0.1.65/24
> Dst MAC Address : 52:54:00:65:42:55 52:54:00:65:42:55
> Src MAC Address : a0:36:9f:eb:47:e8 a0:36:9f:eb:43:ed
> VendID/PCI Addr : 8086:1563/00:05.0 8086:1563/00:10.0
> -- Pktgen Ver: 3.4.7 (DPDK 17.05.0) Powered by DPDK --------------------------
> 
> Pktgen:/> set all rate 50
> Pktgen:/> start 0
> Pktgen:/> stop 0
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by BAOLONGtrann** [comment]
This maybe related to #138.

**Comment by ellagxy** [comment]
latest version seems resolved this issue
