### ISSUE TITLE
when range mode packet size and default mode packet size not matching pktgen is not sending pkt correctly

### ISSUE THREAD

**Issue by ellagxy** [pktgen/Pktgen-DPDK#139]
Hi,

I'm using pktgen version 3.4.8 and I enabled range on both port 0 and port 1 and configure 1 flow using range (nothing increments) with packet size 512 (the default mode pkt size is 64 by default). But when start traffic on port 0 I saw huge packet drop, however if I change default mode pkt size to 512, I don't see any pkt drop. I was guessing pktgen was sending 64byte packet when default mode pkt size was 64 but from tcpdump I don't see that.

![screen shot 2018-01-18 at 4 02 36 pm](https://user-images.githubusercontent.com/35269874/35127970-32ab461e-fc69-11e7-9ecf-46165377716c.png)
![screen shot 2018-01-18 at 4 03 13 pm](https://user-images.githubusercontent.com/35269874/35127985-42947b7c-fc69-11e7-9b46-d89d0b9ff4ea.png)
![screen shot 2018-01-18 at 4 03 46 pm](https://user-images.githubusercontent.com/35269874/35127992-45e4d0ec-fc69-11e7-996c-c778fb320289.png)

There seems to be something wrong or my expectation is wrong?

**Comment by pktgen** [comment]
> On Jan 18, 2018, at 6:04 PM, ellagxy <notifications@github.com> wrote:
> 
> Hi,
> 
> I'm using pktgen version 3.4.8 and I enabled range on both port 0 and port 1 and configure 1 flow using range (nothing increments) with packet size 512 (the default mode pkt size is 64 by default). But when start traffic on port 0 I saw huge packet drop, however if I change default mode pkt size to 512, I don't see any pkt drop. I was guessing pktgen was sending 64byte packet when default mode pkt size was 64 but from tcpdump I don't see that.

DPDK holds on to TX done packets and sometimes the first size of packets will be reused. This means if you start with 64 then switch to 512 you will see some 64 and 512 bytes packets. Getting DPDK to release all of the buffers is not easy in some versions of DPDK. I thought 17.05 fixed the problem.

The only way to make it work correctly is only run a specific size per startup of Pktgen, which means you have to stop pktgen and start it then change the size before starting the traffic again. Is this what you are seeing?

> 
> 
> 
> 
> 
> There seems to be something wrong or my expectation is wrong?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by ellagxy** [comment]
Hi Keith,

What we are currently doing is start pktgen with -f lua script where range test is applied to different pkt size one by one so what you said makes sense. Restarting pktgen to test different pkt size can be an option or actually I found if I change default mode pkt size after I change range mode pkt size, it will also work around. 

Thanks!

**Comment by ellagxy** [comment]
Hi Keith,

If you know which bug this is in DPDK, can you please point me out? I think my work arounds does not seem always working so thinking if we know this issue is fixed in which version of DPDK then we'll try to upgrade.

Thanks!

**Comment by pktgen** [comment]
Version 3.4.8 is latest version. 

The default single packet mode will use the configurations on the default screen or main. 

Range mode has its own packet sizes and are independent from any other mode like single or sequence modes. 

When you setup the range mode it should send packets based on that configuration on the ‘page range’ screen. 

Also the range mode needs to be enabled for the TX port to make it work or it will most likely send single mode as that is the default.
