### ISSUE TITLE
Segmentation Fault when using large number of cores.

### ISSUE THREAD

**Issue by sekhonramneek** [pktgen/Pktgen-DPDK#140]
Hi 
I have two systems with large number of cores, and i am interested in testing the 40G performance between the two systems. On one of the systems i am running pktgen and other system i.e. the DUT is running ovs in kernel mode.
I am using Intel xl710 40g NIC for testing. It is dual port, however i am just using a single port for testing right now.

I am trying to use the following command line arguments to run the pktgen: 
sudo ./app/x86_64-native-linuxapp-gcc/pktgen -l 48-64 -n 8 -- -P -m "[49-56:57-64].[0]" -T -N -f test/tx-rx-loopback.lua

dpdk version: 17.08.1
pktgen version: 3.4.2
The nic device is plugged on cpu 2, cores 48-71, hence i tried to allocate the cores local to the cpu. 
I tried testing with 1024, 2048 and 4096 2M hugepages, however, I get a segmentation fault if I use more than 8 cores for tx on port 0.
If I use 8 cores then the maximum tx rate achieved for 64 bytes packet size is around 28 Gbps ( around 42 million pps). 
I wanted to increase the number of cores and test if that will help to achieve the line rate of 40G for the 64 bytes packet size, however I get "segmentation fault". Also, the Rx rate is very very low ( around 9Gbps for 1500 bytes packet size and as low as 500Mbps for 64 bytes pkt size with a tx rate of 28Gbps).

Can you please help me with the following:
1)  How can I optimize the setup to achieve line rate of 40G with 64 bytes packet size, since the system has enough resources.
2) Why do I get segmentation fault on increasing the number of tx cores beyond 6 for a single port (total number of queues >15 gives seg fault). 
3) How can I optimize the Rx rate? The other system running ovs-kernel mode also has large number of cores available to it, however the Rx on the pktgen end needs to be optimized.
4) Is it possible to send and receive multiple flows in parallel in order to achieve a higher rate? If yes, how can that be done. 

Any  help in this regards will be appreciated.

Thanks and Regards
Rem

**Comment by pktgen** [comment]
Not sure why 8 cores is a limit I do not remember one off hand so will have to look at it when I get back home next week. 

Make sure you are using the range mode to split the rx packets across the rx cores with RSS.

**Comment by sekhonramneek** [comment]
Hi
Thank you for your comments. I will test with the range mode and post the results for you to have a look when you are back.

Thanks and Regards
Rem

**Comment by sekhonramneek** [comment]
I tried using the range mode as per your recommendation.

The script used is as follows (modified version of test/test_range.lua):
------------------------------------------------------------------------------
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
--pktgen.page("range");
pktgen.range.src_mac("0", "start", "3c:fd:fe:9c:5c:d8");

pktgen.range.dst_ip("0", "start", "10.0.1.100");
pktgen.range.dst_ip("0", "inc", "0.0.0.1");
pktgen.range.dst_ip("0", "min", "10.0.1.100");
pktgen.range.dst_ip("0", "max", "10.0.1.100");

pktgen.range.src_ip("0", "start", "10.0.1.102");
pktgen.range.src_ip("0", "inc", "0.0.0.1");
pktgen.range.src_ip("0", "min", "10.0.1.102");
pktgen.range.src_ip("0", "max", "10.0.1.104");

pktgen.set_proto("0", "udp");

pktgen.range.dst_port("0", "start", 2000);
pktgen.range.dst_port("0", "inc", 1);
pktgen.range.dst_port("0", "min", 2000);
pktgen.range.dst_port("0", "max", 2034);

pktgen.range.src_port("0", "start", 5000);
pktgen.range.src_port("0", "inc", 1);
pktgen.range.src_port("0", "min", 5000);
pktgen.range.src_port("0", "max", 5034);

pktgen.range.pkt_size("0", "start", 64);
--pktgen.range.pkt_size("0", "start", 100);
--pktgen.range.pkt_size("0", "start", 128);
--pktgen.range.pkt_size("0", "start", 256);
--pktgen.range.pkt_size("0", "start", 512);
--pktgen.range.pkt_size("0", "start", 1024);
--pktgen.range.pkt_size("0", "start", 1500);
pktgen.range.pkt_size("0", "inc", 0);
pktgen.range.pkt_size("0", "min", 64);
pktgen.range.pkt_size("0", "max", 1500);

pktgen.set_proto("all", "udp");

-----------------------------------------------------------------------------

System specs are as follows:

Device under test is running OVS kernel mode TXing all the Rx packets on the incoming port. 
DPDK Pktgen running on the other node (dpdk version:17.08.1 ;pktgen version:3.4.2 ; Linux kernel:4.4.0-98-generic)
Both the nodes are many-core machines having large number of cores, and are connected by Intel xl710 40G interface.


Initially I was running the packet gen as follows, without the range mode:

 sudo ./app/x86_64-native-linuxapp-gcc/pktgen -l 48-58 -n 16  -b 0000:01:00.0 -b 0000:01:00.1 -b 0000:01:00.2 -b 0000:01:00.3 -b 0000:55:00.1 -- -P -m "[49-54:55-58].[0]" -T -N -f test/tx-rx-loopback.lua

In that case, although I was able to achieve the full Tx rate of 40G for packet sizes as low as 100Bytes. For 64 Bytes packet size, the max Tx rate achieved was 28Gbits/s.
However, the Rx was much lower than expected, as shown below:


64 Bytes packet size

/ Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P--------------:0
Link State        :       <UP-40000-FD>     ----TotalRate----
Pkts/s Max/Rx     :       841328/831956         841328/831956
       Max/Tx     :   42826265/42600805     42826265/42600805
MBits/s Rx/Tx     :           559/28627             559/28627
Broadcast         :                   0
Multicast         :                   0
  64 Bytes        :                   0
  65-127          :                   1
  128-255         :                   0
  256-511         :                   0
  512-1023        :                   0
  1024-1518       :                   0
Runts/Jumbos      :                 0/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :            11890347
      Tx Pkts     :           605954277
      Rx MBs      :                7990
      Tx MBs      :              407201
ARP/ICMP Pkts     :                 0/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :       Forever /100%
PktSize/Tx Burst  :           64 /   64
Src/Dest Port     :        22136 /39304
Pkt Type:VLAN ID  :     IPv4 / UDP:0001
Dst  IP Address   :          10.0.1.100
Src  IP Address   :       10.0.1.200/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   3c:fd:fe:9e:d6:f8
VendID/PCI Addr   :   8086:1583/55:00.0

-- Pktgen Ver: 3.4.2 (DPDK 17.08.1)  Powered by DPDK -------------------------


** Version: DPDK 17.08.1, Command Line Interface with timers
Pktgen:/> For RX found 1 port(s) for lcore 49
For RX found 1 port(s) for lcore 50
For RX found 1 port(s) for lcore 51
For RX found 1 port(s) for lcore 52
For RX found 1 port(s) for lcore 53
For RX found 1 port(s) for lcore 54
For TX found 1 port(s) for lcore 55
For TX found 1 port(s) for lcore 56
For TX found 1 port(s) for lcore 57
For TX found 1 port(s) for lcore 58
Tx: 418692359. Rx: 8227206. Dropped: 410465153
DEBUG portStats = {
  [0] = {
    ["ipackets"] = 8227206,
    ["rx_nombuf"] = 0,
    ["ibytes"] = 493632150,
    ["obytes"] = 25121541120,
    ["oerrors"] = 0,
    ["opackets"] = 418692359,
    ["ierrors"] = 0,
  },
  ["n"] = 1,
}



1500 Bytes packet size

- Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P--------------:0
Link State        :       <UP-40000-FD>     ----TotalRate----
Pkts/s Max/Rx     :       841328/816434         841328/816434
       Max/Tx     :    42826265/3289415      42826265/3289415
MBits/s Rx/Tx     :          9927/39999            9927/39999
Broadcast         :                   0
Multicast         :                   0
  64 Bytes        :                   0
  65-127          :                   1
  128-255         :                   0
  256-511         :                   0
  512-1023        :                   0
  1024-1518       :                   0
Runts/Jumbos      :                 0/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :            39041101
      Tx Pkts     :          1797306359
      Rx MBs      :               74641
      Tx MBs      :             1401442
ARP/ICMP Pkts     :                 0/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :       Forever /100%
PktSize/Tx Burst  :         1500 /   64
Src/Dest Port     :        22136 /39304
Pkt Type:VLAN ID  :     IPv4 / UDP:0001
Dst  IP Address   :          10.0.1.100
Src  IP Address   :       10.0.1.200/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   3c:fd:fe:9e:d6:f8
VendID/PCI Addr   :   8086:1583/55:00.0

-----------------------------------------------------------------------------------

I then tested with range mode, as described above,  to increase the Rx flows and the observed performance is as follows:

 sudo ./app/x86_64-native-linuxapp-gcc/pktgen -l 48-62 -n 16  -b 0000:01:00.0 -b 0000:01:00.1 -b 0000:01:00.2 -b 0000:01:00.3 -b 0000:55:00.1 -- -P -m "[49-53:57-62].[0]" -T -N -f test/test_range_mytest.lua

64 Bytes packet size

| Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P-----R--------:0For RX found 1 port(s) for lcore 53
Link State        :       <UP-40000-FD>     ----TotalRate----
Pkts/s Max/Rx     :     6757655/6619522       6757655/6619522
       Max/Tx     :   41125664/41125664     41125664/41125664
MBits/s Rx/Tx     :          4448/27636            4448/27636
Broadcast         :                   0
Multicast         :                   0
  64 Bytes        :            20198200
  65-127          :                   1
  128-255         :                   0
  256-511         :                   0
  512-1023        :                   0
  1024-1518       :                   0
Runts/Jumbos      :                 0/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :            16893524
      Tx Pkts     :           102850679
      Rx MBs      :               11352
      Tx MBs      :               69115
ARP/ICMP Pkts     :                 0/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :       Forever /100%
PktSize/Tx Burst  :           64 /   64
Src/Dest Port     :         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / UDP:0001
Dst  IP Address   :         192.168.1.1
Src  IP Address   :      192.168.0.1/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   3c:fd:fe:9e:d6:f8
VendID/PCI Addr   :   8086:1583/55:00.0

-- Pktgen Ver: 3.4.2 (DPDK 17.08.1)  Powered by DPDK --------------------------

However, as the pktgen is run for some time, the Rx rate decreases in the same run. 
( the Mem usage in the htop in the DUT shows an increase)
Note the difference in max pps and current pps.

/ Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P-----R--------:0For RX found 1 port(s) for lcore 53
Link State        :       <UP-40000-FD>     ----TotalRate----
Pkts/s Max/Rx     :     7013808/4262667       7013808/4262667
       Max/Tx     :   41587386/41587386     41587386/41587386
MBits/s Rx/Tx     :          2864/27946            2864/27946
Broadcast         :                   0
Multicast         :                   0
  64 Bytes        :           395515284
  65-127          :                   1
  128-255         :                   0
  256-511         :                   0
  512-1023        :                   0
  1024-1518       :                   0
Runts/Jumbos      :                 0/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :           393903053
      Tx Pkts     :          3172573322
      Rx MBs      :              264702
      Tx MBs      :             2131969
ARP/ICMP Pkts     :                 0/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :       Forever /100%
PktSize/Tx Burst  :           64 /   64
Src/Dest Port     :         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / UDP:0001
Dst  IP Address   :         192.168.1.1
Src  IP Address   :      192.168.0.1/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   3c:fd:fe:9e:d6:f8
VendID/PCI Addr   :   8086:1583/55:00.0

-- Pktgen Ver: 3.4.2 (DPDK 17.08.1)  Powered by DPDK --------------------------




1500 Bytes packet size ( Main Page always shows pktsize of 64, when running range mode and doesnt show the correct packet size set in the lua script)

\ Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P-----R--------:0For RX found 1 port(s) for lcore 53
Link State        :       <UP-40000-FD>     ----TotalRate----
Pkts/s Max/Rx     :     3282788/3282788       3282788/3282788
       Max/Tx     :     3289456/3289143       3289456/3289143
MBits/s Rx/Tx     :         39918/39995           39918/39995
Broadcast         :                   0
Multicast         :                   0
  64 Bytes        :                   0
  65-127          :                   1
  128-255         :                   0
  256-511         :                   0
  512-1023        :                   0
  1024-1518       :            13320100
Runts/Jumbos      :                 0/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :            10432074
      Tx Pkts     :            10476631
      Rx MBs      :              126853
      Tx MBs      :              127395
ARP/ICMP Pkts     :                 0/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :       Forever /100%
PktSize/Tx Burst  :           64 /   64
Src/Dest Port     :         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / UDP:0001
Dst  IP Address   :         192.168.1.1
Src  IP Address   :      192.168.0.1/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   3c:fd:fe:9e:d6:f8
VendID/PCI Addr   :   8086:1583/55:00.0

-- Pktgen Ver: 3.4.2 (DPDK 17.08.1)  Powered by DPDK --------------------------

----------------------------------------------------------------------------------------------------------------------------------

Following is what i observed: 


I tried to vary the number of src and dst ports and src ip address in an attempt to find an optimal value for Tx and Rx data rate.  
If I use smaller number of src ips and ports, as described in lua script above, i see a better performance for most packet sizes.

Q1: How can i choose the number of ips and ports so that i can get optimum performance for different packet sizes.

Q2: Can you please explain/point to some documentation about how the range mode works? 

Q3: The performance  (Rx rate) is not consistent through subsequent runs of pktgen, even if I quit and restart the pktgen. What could be the possible cause/fix.

Q4:  If I try to use more number of  Tx/Rx cores, the pktgen generates segmentation fault ( more than 8 for tx and more than 16 for rx gives segmentation fault).
What could be the possible cause and how can i fix it. 
I am particularly interested in this because i want to see if that has any impact on the performance.

Q5: For 64Bytes packet size, the max Tx achieved is 28GBits/s. How can I achieve full line rate (40G) for 64 Bytes packet size?

**Comment by pktgen** [comment]
> On Jan 31, 2018, at 1:21 AM, sekhonramneek <notifications@github.com> wrote:
> 
> I tried using the range mode as per your recommendation.
> 
> The script used is as follows (modified version of test/test_range.lua):
> 
> package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
> --pktgen.page("range");
> pktgen.range.src_mac("0", "start", "3c:fd:fe:9c:5c:d8");
> 
> pktgen.range.dst_ip("0", "start", "10.0.1.100");
> pktgen.range.dst_ip("0", "inc", "0.0.0.1");
> pktgen.range.dst_ip("0", "min", "10.0.1.100");
> pktgen.range.dst_ip("0", "max", "10.0.1.100");
> 
> pktgen.range.src_ip("0", "start", "10.0.1.102");
> pktgen.range.src_ip("0", "inc", "0.0.0.1");
> pktgen.range.src_ip("0", "min", "10.0.1.102");
> pktgen.range.src_ip("0", "max", "10.0.1.104");
> 
> pktgen.set_proto("0", "udp");
> 
> pktgen.range.dst_port("0", "start", 2000);
> pktgen.range.dst_port("0", "inc", 1);
> pktgen.range.dst_port("0", "min", 2000);
> pktgen.range.dst_port("0", "max", 2034);
> 
> pktgen.range.src_port("0", "start", 5000);
> pktgen.range.src_port("0", "inc", 1);
> pktgen.range.src_port("0", "min", 5000);
> pktgen.range.src_port("0", "max", 5034);
> 
> pktgen.range.pkt_size("0", "start", 64);
> --pktgen.range.pkt_size("0", "start", 100);
> --pktgen.range.pkt_size("0", "start", 128);
> --pktgen.range.pkt_size("0", "start", 256);
> --pktgen.range.pkt_size("0", "start", 512);
> --pktgen.range.pkt_size("0", "start", 1024);
> --pktgen.range.pkt_size("0", "start", 1500);
> pktgen.range.pkt_size("0", "inc", 0);
> pktgen.range.pkt_size("0", "min", 64);
> pktgen.range.pkt_size("0", "max", 1500);
> 
> pktgen.set_proto("all", "udp");
> 
> System specs are as follows:
> 
> Device under test is running OVS kernel mode TXing all the Rx packets on the incoming port.
> DPDK Pktgen running on the other node (dpdk version:17.08.1 ;pktgen version:3.4.2 ; Linux kernel:4.4.0-98-generic)
> Both the nodes are many-core machines having large number of cores, and are connected by Intel xl710 40G interface.
> 
> Initially I was running the packet gen as follows, without the range mode:
> 
> sudo ./app/x86_64-native-linuxapp-gcc/pktgen -l 48-58 -n 16 -b 0000:01:00.0 -b 0000:01:00.1 -b 0000:01:00.2 -b 0000:01:00.3 -b 0000:55:00.1 -- -P -m "[49-54:55-58].[0]" -T -N -f test/tx-rx-loopback.lua
> 
> In that case, although I was able to achieve the full Tx rate of 40G for packet sizes as low as 100Bytes. For 64 Bytes packet size, the max Tx rate achieved was 28Gbits/s.
> However, the Rx was much lower than expected, as shown below:
> 
> 64 Bytes packet size
> 
> / Ports 0-0 of 1
> 
> Copyright (c) <2010-2017>, Intel Corporation
> Flags:Port : P--------------:0
> Link State : ----TotalRate----
> Pkts/s Max/Rx : 841328/831956 841328/831956
> Max/Tx : 42826265/42600805 42826265/42600805
> MBits/s Rx/Tx : 559/28627 559/28627
> Broadcast : 0
> Multicast : 0
> 64 Bytes : 0
> 65-127 : 1
> 128-255 : 0
> 256-511 : 0
> 512-1023 : 0
> 1024-1518 : 0
> Runts/Jumbos : 0/0
> Errors Rx/Tx : 0/0
> Total Rx Pkts : 11890347
> Tx Pkts : 605954277
> Rx MBs : 7990
> Tx MBs : 407201
> ARP/ICMP Pkts : 0/0
> :
> Pattern Type : abcd...
> Tx Count/% Rate : Forever /100%
> PktSize/Tx Burst : 64 / 64
> Src/Dest Port : 22136 /39304
> Pkt Type:VLAN ID : IPv4 / UDP:0001
> Dst IP Address : 10.0.1.100
> Src IP Address : 10.0.1.200/24
> Dst MAC Address : 00:00:00:00:00:00
> Src MAC Address : 3c:fd:fe:9e:d6:f8
> VendID/PCI Addr : 8086:1583/55:00.0
> 
> -- Pktgen Ver: 3.4.2 (DPDK 17.08.1) Powered by DPDK -------------------------
> 
> ** Version: DPDK 17.08.1, Command Line Interface with timers
> Pktgen:/> For RX found 1 port(s) for lcore 49
> For RX found 1 port(s) for lcore 50
> For RX found 1 port(s) for lcore 51
> For RX found 1 port(s) for lcore 52
> For RX found 1 port(s) for lcore 53
> For RX found 1 port(s) for lcore 54
> For TX found 1 port(s) for lcore 55
> For TX found 1 port(s) for lcore 56
> For TX found 1 port(s) for lcore 57
> For TX found 1 port(s) for lcore 58
> Tx: 418692359. Rx: 8227206. Dropped: 410465153
> DEBUG portStats = {
> [0] = {
> ["ipackets"] = 8227206,
> ["rx_nombuf"] = 0,
> ["ibytes"] = 493632150,
> ["obytes"] = 25121541120,
> ["oerrors"] = 0,
> ["opackets"] = 418692359,
> ["ierrors"] = 0,
> },
> ["n"] = 1,
> }
> 
> 1500 Bytes packet size
> 
> 	• Ports 0-0 of 1 Copyright (c) <2010-2017>, Intel Corporation
> Flags:Port : P--------------:0
> Link State : ----TotalRate----
> Pkts/s Max/Rx : 841328/816434 841328/816434
> Max/Tx : 42826265/3289415 42826265/3289415
> MBits/s Rx/Tx : 9927/39999 9927/39999
> Broadcast : 0
> Multicast : 0
> 64 Bytes : 0
> 65-127 : 1
> 128-255 : 0
> 256-511 : 0
> 512-1023 : 0
> 1024-1518 : 0
> Runts/Jumbos : 0/0
> Errors Rx/Tx : 0/0
> Total Rx Pkts : 39041101
> Tx Pkts : 1797306359
> Rx MBs : 74641
> Tx MBs : 1401442
> ARP/ICMP Pkts : 0/0
> :
> Pattern Type : abcd...
> Tx Count/% Rate : Forever /100%
> PktSize/Tx Burst : 1500 / 64
> Src/Dest Port : 22136 /39304
> Pkt Type:VLAN ID : IPv4 / UDP:0001
> Dst IP Address : 10.0.1.100
> Src IP Address : 10.0.1.200/24
> Dst MAC Address : 00:00:00:00:00:00
> Src MAC Address : 3c:fd:fe:9e:d6:f8
> VendID/PCI Addr : 8086:1583/55:00.0
> I then tested with range mode, as described above, to increase the Rx flows and the observed performance is as follows:
> 
> sudo ./app/x86_64-native-linuxapp-gcc/pktgen -l 48-62 -n 16 -b 0000:01:00.0 -b 0000:01:00.1 -b 0000:01:00.2 -b 0000:01:00.3 -b 0000:55:00.1 -- -P -m "[49-53:57-62].[0]" -T -N -f test/test_range_mytest.lua
> 
> 64 Bytes packet size
> 
> | Ports 0-0 of 1
> 
> Copyright (c) <2010-2017>, Intel Corporation
> Flags:Port : P-----R--------:0For RX found 1 port(s) for lcore 53
> Link State : ----TotalRate----
> Pkts/s Max/Rx : 6757655/6619522 6757655/6619522
> Max/Tx : 41125664/41125664 41125664/41125664
> MBits/s Rx/Tx : 4448/27636 4448/27636
> Broadcast : 0
> Multicast : 0
> 64 Bytes : 20198200
> 65-127 : 1
> 128-255 : 0
> 256-511 : 0
> 512-1023 : 0
> 1024-1518 : 0
> Runts/Jumbos : 0/0
> Errors Rx/Tx : 0/0
> Total Rx Pkts : 16893524
> Tx Pkts : 102850679
> Rx MBs : 11352
> Tx MBs : 69115
> ARP/ICMP Pkts : 0/0
> :
> Pattern Type : abcd...
> Tx Count/% Rate : Forever /100%
> PktSize/Tx Burst : 64 / 64
> Src/Dest Port : 1234 / 5678
> Pkt Type:VLAN ID : IPv4 / UDP:0001
> Dst IP Address : 192.168.1.1
> Src IP Address : 192.168.0.1/24
> Dst MAC Address : 00:00:00:00:00:00
> Src MAC Address : 3c:fd:fe:9e:d6:f8
> VendID/PCI Addr : 8086:1583/55:00.0
> 
> -- Pktgen Ver: 3.4.2 (DPDK 17.08.1) Powered by DPDK --------------------------
> 
> However, as the pktgen is run for some time, the Rx rate decreases in the same run.
> ( the Mem usage in the htop in the DUT shows an increase)
> Note the difference in max pps and current pps.
> 
> / Ports 0-0 of 1
> 
> Copyright (c) <2010-2017>, Intel Corporation
> Flags:Port : P-----R--------:0For RX found 1 port(s) for lcore 53
> Link State : ----TotalRate----
> Pkts/s Max/Rx : 7013808/4262667 7013808/4262667
> Max/Tx : 41587386/41587386 41587386/41587386
> MBits/s Rx/Tx : 2864/27946 2864/27946
> Broadcast : 0
> Multicast : 0
> 64 Bytes : 395515284
> 65-127 : 1
> 128-255 : 0
> 256-511 : 0
> 512-1023 : 0
> 1024-1518 : 0
> Runts/Jumbos : 0/0
> Errors Rx/Tx : 0/0
> Total Rx Pkts : 393903053
> Tx Pkts : 3172573322
> Rx MBs : 264702
> Tx MBs : 2131969
> ARP/ICMP Pkts : 0/0
> :
> Pattern Type : abcd...
> Tx Count/% Rate : Forever /100%
> PktSize/Tx Burst : 64 / 64
> Src/Dest Port : 1234 / 5678
> Pkt Type:VLAN ID : IPv4 / UDP:0001
> Dst IP Address : 192.168.1.1
> Src IP Address : 192.168.0.1/24
> Dst MAC Address : 00:00:00:00:00:00
> Src MAC Address : 3c:fd:fe:9e:d6:f8
> VendID/PCI Addr : 8086:1583/55:00.0
> 
> -- Pktgen Ver: 3.4.2 (DPDK 17.08.1) Powered by DPDK --------------------------
> 
> 1500 Bytes packet size ( Main Page always shows pktsize of 64, when running range mode and doesnt show the correct packet size set in the lua script)
> 
> \ Ports 0-0 of 1
> 
> Copyright (c) <2010-2017>, Intel Corporation
> Flags:Port : P-----R--------:0For RX found 1 port(s) for lcore 53
> Link State : ----TotalRate----
> Pkts/s Max/Rx : 3282788/3282788 3282788/3282788
> Max/Tx : 3289456/3289143 3289456/3289143
> MBits/s Rx/Tx : 39918/39995 39918/39995
> Broadcast : 0
> Multicast : 0
> 64 Bytes : 0
> 65-127 : 1
> 128-255 : 0
> 256-511 : 0
> 512-1023 : 0
> 1024-1518 : 13320100
> Runts/Jumbos : 0/0
> Errors Rx/Tx : 0/0
> Total Rx Pkts : 10432074
> Tx Pkts : 10476631
> Rx MBs : 126853
> Tx MBs : 127395
> ARP/ICMP Pkts : 0/0
> :
> Pattern Type : abcd...
> Tx Count/% Rate : Forever /100%
> PktSize/Tx Burst : 64 / 64
> Src/Dest Port : 1234 / 5678
> Pkt Type:VLAN ID : IPv4 / UDP:0001
> Dst IP Address : 192.168.1.1
> Src IP Address : 192.168.0.1/24
> Dst MAC Address : 00:00:00:00:00:00
> Src MAC Address : 3c:fd:fe:9e:d6:f8
> VendID/PCI Addr : 8086:1583/55:00.0
> 
> -- Pktgen Ver: 3.4.2 (DPDK 17.08.1) Powered by DPDK --------------------------
> 
> Following is what i observed:
> 
> I tried to vary the number of src and dst ports and src ip address in an attempt to find an optimal value for Tx and Rx data rate.
> If I use smaller number of src ips and ports, as described in lua script above, i see a better performance for most packet sizes.
> 
> Q1: How can i choose the number of ips and ports so that i can get optimum performance for different packet sizes.

Looks like you are setting up the values correctly, but it would require we calculate the RSS values to see if it works. :-(

> 
> Q2: Can you please explain/point to some documentation about how the range mode works?

The range information is not reflected in the main single mode screen use ‘page range’ to see the range configuration and ‘page main’ to see the single mode configuration.

> 
> Q3: The performance (Rx rate) is not consistent through subsequent runs of pktgen, even if I quit and restart the pktgen. What could be the possible cause/fix.

Not sure this is a pktgen problem, but a system configuration or the configuration to your system.

> 
> Q4: If I try to use more number of Tx/Rx cores, the pktgen generates segmentation fault ( more than 8 for tx and more than 16 for rx gives segmentation fault).
> What could be the possible cause and how can i fix it.
> I am particularly interested in this because i want to see if that has any impact on the performance.

Using my X710 NICs I am able to get more then 8 or 16 as my NIC supports more then 8 or 16 rx/tx queue pairs. It is possible the NIC you are using does not support that many.

The lcore and port list strings in the -m option uses ‘/‘ not ‘,’ to split up the lcores or ports. The reason is the -m can take more then one item.

 -m “[12:13].0, [14:15].1, ….’ 

So use ‘/‘ in side the [] like [12/15-17:18/20/22].0



> 
> Q5: For 64Bytes packet size, the max Tx achieved is 28GBits/s. How can I achieve full line rate (40G) for 64 Bytes packet size?

The performance of you system to get to 40G with 64b packets is based on a number of factors. The PCI bandwidth, PCI slot width, CPU speed, PCI to NUMA zone locations, … as you can see I can not give you a simple solution you have to investigate the different areas and make sure they are correct.

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by sekhonramneek** [comment]
Hi Keith 

Thanks a lot for your response and clarification on various concerns that I had, and for the pointers to achieve the desired performance. 

The NIC card that I am using (Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+) supports a large number of multiqueues, however, I still get a segmentation fault. 
ethtool -l ens68f0
Channel parameters for ens68f0:
Pre-set maximums:
RX:             0
TX:             0
Other:          1
Combined:       120
Current hardware settings:
RX:             0
TX:             0
Other:          1
Combined:       120

Still trying to figure out the cause.

Also, Can you please explain how the range mode works? OR If there is any documentation that explains the working of range mode, please let me know so that I can have a better idea about how to select the optimum number of ips/ports etc to be used, according to the RSS capabilities of DUT.


Thanks and Regards
Rem

**Comment by pktgen** [comment]
> On Feb 5, 2018, at 7:01 PM, sekhonramneek <notifications@github.com> wrote:
> 
> Hi Keith
> 
> Thanks a lot for your response and clarification on various concerns that I had, and for the pointers to achieve the desired performance.
> 
> The NIC card that I am using (Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+) supports a large number of multiqueues, however, I still get a segmentation fault.
> ethtool -l ens68f0
> Channel parameters for ens68f0:
> Pre-set maximums:
> RX: 0
> TX: 0
> Other: 1
> Combined: 120
> Current hardware settings:
> RX: 0
> TX: 0
> Other: 1
> Combined: 120
> 
> Still trying to figure out the cause.
> 
> Also, Can you please explain how the range mode works? OR If there is any documentation that explains the working of range mode, please let me know so that I can have a better idea about how to select the optimum number of ips/ports etc to be used, according to the RSS capabilities of DUT.

Range mode is pretty simple it just modifies each TX packet based on the configuration on the ‘page range’ for the given port. The values are incremented per the increment value for that item and port. The range of the given field is defined by the user.

> 
> Thanks and Regards
> Rem
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith
