### ISSUE TITLE
Disabling TTY Allocation

### ISSUE THREAD

**Issue by sacheth003** [pktgen/Pktgen-DPDK#141]
I want to use `pktgen` on a pure scripting basis, without any user interaction. It seems like this can almost be done using the `-f` option, but still requires a TTY to be allocated. Is this feature supported?

**Comment by tbarbette** [comment]
Any answer on this? This question was actually interesting. Not sure why it has been closed?

**Comment by pktgen** [comment]
I did not close it unless by mistake. At this point you can use the -G option with -f or use the socket connection that -G gives to send commands to pktgen. But turning off try is not supported at this point should not be to hard to add.
