### ISSUE TITLE
PKTGEN inside VM

### ISSUE THREAD

**Issue by alp317** [pktgen/Pktgen-DPDK#142]
I am trying to benchmark the performance of OVS-DPDK. For that i have two virtual machines connected using the OVS-DPDK brdge. For the most basic testing i have added rules on the OVS to pass traffic between both node, no matching, output whatever is input from the other port. 

When I run PKTGEN inside a virtual machine, the max PPS only reach about 2 Milliion, is there a way to run PKTGEN inside VM and achieve 14 Million PPS.

**Comment by pktgen** [comment]
> On Feb 16, 2018, at 6:59 AM, Alp Arslan <notifications@github.com> wrote:
> 
> I am trying to benchmark the performance of OVS-DPDK. For that i have two virtual machines connected using the OVS-DPDK brdge. For the most basic testing i have added rules on the OVS to pass traffic between both node, no matching, output whatever is input from the other port.
> 
> When I run PKTGEN inside a virtual machine, the max PPS only reach about 2 Milliion, is there a way to run PKTGEN inside VM and achieve 14 Million PPS.

It is difficult to determine as you have not provide a lot of details.

Pktgen inside a VM is difficult to get high performance as you have a number of areas slowing down the performance. The bottlenecks are around virtio, VM exit/entry and the number of cores assigned the VM. Also you need to make sure the two VMs are not on the different CPU sockets.

All I can suggest is adding more then one core to the TX and RX in pktgen -m [1-3:4-7].0 or something like it.

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by alp317** [comment]
The VM has 4 vCPUs (pinned on same NUMA Node), i am using 3 for PKTGEN. 1 for TX, 1 for RX and 1 for master-lcore. 
In another test i have seen 7 MPPS transferred over the same vhost-user-client interface.

**Comment by alp317** [comment]
Added two cores for TX and it jumped to 4.4 MPPS. Thank you.

**Comment by alp317** [comment]
On another point, i see that PKTGEN detects the speed of virtio interface as 10 Gbps, although i have seen more than 10 Gbps transferred (large packet size) over virtio interfaces.

**Comment by pktgen** [comment]
Software interfaces do not really have speed and it can not detect the speed. All I can suggest is someone needs to adjust the default speed to something higher.

Same problem with tap interface and it was defaulted to 10M :-(

> On Feb 16, 2018, at 9:08 AM, Alp Arslan <notifications@github.com> wrote:
> 
> On another point, i see that PKTGEN detects the speed of virtio interface as 10 Gbps, although i have seen more than 10 Gbps transferred (large packet size) over virtio interfaces.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by gkenaley** [comment]
You will need to use a DPDK polled-mode driver (PMD) in your guest to get the last 50% of performance over vhost-user-virtio. See [http://docs.openvswitch.org/en/latest/howto/dpdk/](url)  The downside is that inside that VM you will need to provide your own network stack for user space (if needed).
