### ISSUE TITLE
DPDK packetgen receiving packets for non existent IP/MAC

### ISSUE THREAD

**Issue by msidana** [pktgen/Pktgen-DPDK#144]
I am testing a scenario for dpdk-pktgen where I have a sender and receiver in two separate VMs.
Sender IP: 11.0.86.8
Sender MAC: fa:16:3e:0c:37:bf
Receiver IP: 11.0.86.10
Receiver MAC: fa:16:3e:8d:d4:db

In the sender, I am setting non-existent src/dst IP and MAC. However, I can still see the packets being received at the receiver machine. I tested for both TCP and UDP and I am wonder how can TCP connection be made when the IPs being set are not existing.

**Comment by pktgen** [comment]
> On Mar 26, 2018, at 10:22 PM, Manik Sidana <notifications@github.com> wrote:
> 
> I am testing a scenario for dpdk-pktgen where I have a sender and receiver in two separate VMs.
> Sender IP: 11.0.86.8
> Sender MAC: fa:16:3e:0c:37:bf
> Receiver IP: 11.0.86.10
> Receiver MAC: fa:16:3e:8d:d4:db
> 
> In the sender, I am setting non-existent src/dst IP and MAC. However, I can still see the packets being received at the receiver machine. I tested for both TCP and UDP and I am wonder how can TCP connection be made when the IPs being set are not existing.

In Pktgen it does not have a network stack it is only sending packets formatted as if they were TCP/UDP.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by msidana** [comment]
Thanks Keith for your reply. 
Another observation.
In my sender-receiver setup, I generated TCP packets from sender (with sender IP/MAC) to receiver(with receiver IP/MAC). I did not see any TCP session getting established (unlike iperf3, which sets up a tcp session and transmits SYN,ACK,SYN-ACK). I saw only TCP re-transmission packets in my packet capture.
I want to measure pps between sender and receiver with TCP packets. Is there a way to do that using pktgen by setting up tcp session between 2 VMs.

**Comment by shelbyt** [comment]
You may be misunderstanding what DPDK does. At its core it is a packet processor with kernel bypass. If you want to have a full tcp/ip network stack you'll have to implement it yourself or use open-source user-space tcp/ip implementations. Such as [f-stack](https://github.com/F-Stack/f-stack), [Seastar](https://github.com/scylladb/seastar), or [OpenFastPath](https://github.com/OpenFastPath/ofp). If you want a more academic perspective you can take a look at [mTCP](https://www.usenix.org/node/179774).
