### ISSUE TITLE
MTU is never actually configured with DPDK: Causing overflow/MDD event

### ISSUE THREAD

**Issue by akberg** [pktgen/Pktgen-DPDK#146]
When launching with `-j` jumboframes, the new mtu value is never configured in the underlying device (`rte_eth_dev_set_mtu`). Jumbo sized packets are then created by the application, but rejected by the driver.

Is there a reason for this, has the jumboframes feature never been tested, or do some devices have other means of updating the MTU? Mellanox drivers apparently allow configurations through `ethtool` which are persistent with a DPDK application. In any case, as DPDK should be in full control of the network device, the DPDK application should also be responsible for updating the configured MTU.

## System
* OS: Linux 4.18.0-448.el8
* NIC: Intel E810-C for QSFP 1592
* Driver: uio_pci_generic 0.01.0 & ice 0.8.2-k
* DPDK 22.07 & Pktgen 22.07.1

**Comment by KeithWiles** [comment]
I did not write the jumbo frame support for Pktgen, so I have not personally tested its support. The person that did add the support I assumed they had tested it and he was using the code. With that stated, we do need to fix the issue. I do not have time to make this change and if you could submit a pull request to fix the problem it would be great or is will have to be put on the list of things to fix when I have time.

**Comment by akberg** [comment]
I confirmed with colleagues that it might very well be the case that testing has been done with a driver like Mellanox, thus hiding this issue. Pull request coming in a minute!

**Comment by akberg** [comment]
#148
