### ISSUE TITLE
PKtgen Port 0, link down, No traffic 

### ISSUE THREAD

**Issue by rida914-4** [pktgen/Pktgen-DPDK#146]
Hi,

I am running pktgen DPDK 17.11.1 using this command.
./app/build/pktgen -c 0x0f -l 0-4 -n 3 -- -P -m "[1:3].0, [2:4].1"

I am aware that lcore0 displays the traffic /packet stats/timer so i have skipped that and used lcore 1 and lcore 2. So that's probably not the reason why there is no packet transfer appearing on the display stats page.

I am constantly seeing this error due to which no traffic is being generated. I have gone through other issues similar to this and tried all of them but it does not work for me.
__________________________________________________________________________________
                                                                       Port memory used = 147601 KB
Initialize Port 1 -- TxQ 1, RxQ 1,  Src MAC a0:36:9f:07:32:e6
                                                                      Total memory used = 295202 KB
PMD: ixgbe_dev_link_status_print():  Port 0: Link Down
PMD: ixgbe_dev_link_status_print():  Port 1: Link Down
Port  0: Link Down <Enable promiscuous mode>
Port  1: Link Down <Enable promiscuous mode>

 Ports 0-1 of 2   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P--------------:0   P--------------:1
Link State        :          <--Down-->          <--Down-->     ----TotalRate----
Pkts/s Max/Rx     :                 0/0                 0/0                   0/0
       Max/Tx     :                 0/0                 0/0                   0/0
MBits/s Rx/Tx     :                 0/0                 0/0                   0/0
Broadcast         :                   0                   0
Multicast         :                   0                   0
  64 Bytes        :                   0                   0
  65-127          :                   0                   0
  128-255         :                   0                   0
  256-511         :                   0                   0
  512-1023        :                   0                   0
  1024-1518       :                   0                   0
Runts/Jumbos      :                 0/0                 0/0
Errors Rx/Tx      :                 0/0                 0/0
Total Rx Pkts     :                   0                   0
      Tx Pkts     :                   0                   0
      Rx MBs      :                   0                   0
      Tx MBs      :                   0                   0
ARP/ICMP Pkts     :                 0/0                 0/0
                  :
Pattern Type      :             abcd...             abcd...
Tx Count/% Rate   :       Forever /100%       Forever /100%
PktSize/Tx Burst  :           64 /   64           64 /   64
Src/Dest Port     :         1234 / 5678         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / TCP:0001     IPv4 / TCP:0001
802.1p CoS        :                   0                   0
ToS Value:        :                   0                   0
  - DSCP value    :                   0                   0
  - IPP  value    :                   0                   0
Dst  IP Address   :         192.168.1.1         192.168.0.1
Src  IP Address   :      192.168.0.1/24      192.168.1.1/24
Dst MAC Address   :   a0:36:9f:07:32:e6   a0:36:9f:07:32:e4
Src MAC Address   :   a0:36:9f:07:32:e4   a0:36:9f:07:32:e6
VendID/PCI Addr   :   8086:154d/42:00.0   8086:154d/42:00.1

________________________________________________________________________________
Checked out 
https://github.com/pktgen/Pktgen-DPDK/issues/39
https://github.com/pktgen/Pktgen-DPDK/issues/51

**Comment by pktgen** [comment]
Send me a ‘lspci | grep Ether’ output most likely you have a number of ports. Did you install the igb_uio or pci_uio module? Did you use the dpdk-bind command to bind the ports to the uio module?

**Comment by rida914-4** [comment]
lspci | grep Ether
01:00.0 Ethernet controller: Broadcom Corporation NetXtreme BCM5720 Gigabit Ethernet PCIe
01:00.1 Ethernet controller: Broadcom Corporation NetXtreme BCM5720 Gigabit Ethernet PCIe
02:00.0 Ethernet controller: Broadcom Corporation NetXtreme BCM5720 Gigabit Ethernet PCIe
02:00.1 Ethernet controller: Broadcom Corporation NetXtreme BCM5720 Gigabit Ethernet PCIe
04:00.0 Ethernet controller: Intel Corporation Ethernet 10G 2P X520 Adapter (rev 01)
04:00.1 Ethernet controller: Intel Corporation Ethernet 10G 2P X520 Adapter (rev 01)
42:00.0 Ethernet controller: Intel Corporation Ethernet 10G 2P X520 Adapter (rev 01)
42:00.1 Ethernet controller: Intel Corporation Ethernet 10G 2P X520 Adapter (rev 01)

Yes, dpdk-bind is ok.

python tools/dpdk-devbind.py  --status

Network devices using DPDK-compatible driver
============================================
<none>

Network devices using kernel driver
===================================
0000:01:00.0 'NetXtreme BCM5720 Gigabit Ethernet PCIe' if=eno1 drv=tg3 unused= *Active*
0000:01:00.1 'NetXtreme BCM5720 Gigabit Ethernet PCIe' if=eno2 drv=tg3 unused= 
0000:02:00.0 'NetXtreme BCM5720 Gigabit Ethernet PCIe' if=eno3 drv=tg3 unused= 
0000:02:00.1 'NetXtreme BCM5720 Gigabit Ethernet PCIe' if=eno4 drv=tg3 unused= 
0000:04:00.0 'Ethernet 10G 2P X520 Adapter' if=enp4s0f0 drv=ixgbe unused= 
0000:04:00.1 'Ethernet 10G 2P X520 Adapter' if=enp4s0f1 drv=ixgbe unused= 
0000:42:00.0 'Ethernet 10G 2P X520 Adapter' if=enp66s0f0 drv=ixgbe unused= 
0000:42:00.1 'Ethernet 10G 2P X520 Adapter' if=enp66s0f1 drv=ixgbe unused= 

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>


Not sure about this.
 igb_uio or pci_uio module

**Comment by rida914-4** [comment]
I have a single interface on the machine eno1. It is up.

Settings for eno1:
	Supported ports: [ TP ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Advertised pause frame use: Symmetric
	Advertised auto-negotiation: Yes
	Link partner advertised link modes:  10baseT/Half 10baseT/Full 
	                                     100baseT/Half 100baseT/Full 
	                                     1000baseT/Full 
	Link partner advertised pause frame use: No
	Link partner advertised auto-negotiation: Yes
	Speed: 1000Mb/s
	Duplex: Full
	Port: Twisted Pair
	PHYAD: 1
	Transceiver: internal
	Auto-negotiation: on
	MDI-X: on
	Supports Wake-on: g
	Wake-on: d
	Current message level: 0x000000ff (255)
			       drv probe link timer ifdown ifup rx_err tx_err
	Link detected: yes

**Comment by pktgen** [comment]
Are you trying to use the 10G NICs then you must blacklist the 1G NICs. 

Also run ‘sudo lsmod’ look for igb_uio or the pci_uio module. This information is in the pktgen read me file. 

You need to bind the ports you want to use to igb or pci uio module in the kernel. 

The dpdk-devbind needs to report the drv=igb_uio or pci-uio the bund tool has options to the right driver.

**Comment by rida914-4** [comment]
I have modified a few things.

dpkd-dev bind is reporting drv=ioc_pc :

Network devices using DPDK-compatible driver
============================================
0000:01:00.1 'NetXtreme BCM5720 Gigabit Ethernet PCIe' drv=uio_pci_generic unused=tg3,igb_uio
0000:42:00.0 'Ethernet 10G 2P X520 Adapter' drv=uio_pci_generic unused=ixgbe,igb_uio
0000:42:00.1 'Ethernet 10G 2P X520 Adapter' drv=uio_pci_generic unused=ixgbe,igb_uio

Network devices using kernel driver
===================================
0000:01:00.0 'NetXtreme BCM5720 Gigabit Ethernet PCIe' if=eno1 drv=tg3 unused=igb_uio,uio_pci_generic *Active*
0000:02:00.0 'NetXtreme BCM5720 Gigabit Ethernet PCIe' if=eno3 drv=tg3 unused=igb_uio,uio_pci_generic 
0000:02:00.1 'NetXtreme BCM5720 Gigabit Ethernet PCIe' if=eno4 drv=tg3 unused=igb_uio,uio_pci_generic 
0000:04:00.0 'Ethernet 10G 2P X520 Adapter' if=enp4s0f0 drv=ixgbe unused=igb_uio,uio_pci_generic 
0000:04:00.1 'Ethernet 10G 2P X520 Adapter' if=enp4s0f1 drv=ixgbe unused=igb_uio,uio_pci_generic 

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>




‘sudo lsmod’ :

sudo lsmod | grep -iP 'igb_uio|pci_uio'
igb_uio                16384  0
uio                    20480  2 uio_pci_generic,igb_uio

Not sure how to use -b parameter for blacklist.

**Comment by rida914-4** [comment]
The solution @pktgen mentioned in another issue #39 "The next thing is to loop back the cable from one port to the other on the Pktgen machine and make sure you can the performance at wire rate. Then you can debug the other machine." worked for me.

Closing the issue.
