### ISSUE TITLE
range question

### ISSUE THREAD

**Issue by ChengjunJia** [pktgen/Pktgen-DPDK#149]
Did anyone test the range command?
I found that:
If the range is used, 'set the packet size' does not work?

**Comment by pktgen** [comment]
The range command has its own set size command were you using the set portlist size n command, which is the single port command.

**Comment by ChengjunJia** [comment]
I use the following commands to send the packets in port 1, of which the size is 100 and the ip is random.
`set 1 size 100`
`enable 1 range`
`range 1 size min 100`
`start 1`
Then, I look at the packet size on the other machine, it is always 64. Is there anything wrong?
Or what should I do to send the flow with constant packet size and random ip?
Besides, when I set the `range 1 size inc 1` or `range 1 size inc 100`, the `page range` only shows that the `pkt.size/inc 64/64`. Is there anything wrong?

**Comment by ChengjunJia** [comment]
I use the following commands to send the packets in port 1, of which the size is 100 and the ip is random.
`set 1 size 100`
`enable 1 range`
`range 1 size min 100`
`start 1`
Then, I look at the packet size on the other machine, it is always 64. Is there anything wrong?
Or what should I do to send the flow with constant packet size and random ip?
Besides, when I set the `range 1 size inc 1` or `range 1 size inc 100`, the `page range` only shows that the `pkt.size/inc 64/64`. Is there anything wrong?

**Comment by ChengjunJia** [comment]
OK, I got it.
`range 1 size min 100`
`range 1 size max 100`
`range 1 size inc 1`
I can achieve my goal. But the `page range` still shows that the `pkt.size/inc 64/64`, I do not know why.

**Comment by pktgen** [comment]
Ok thanks I will have a look at the output code.

**Comment by pktgen** [comment]
OK, I found the problem and fixed the code. It should be the latest code at dpdk.org
