### ISSUE TITLE
Intel X540-AT2 rate setting problem

### ISSUE THREAD

**Issue by GDanii** [pktgen/Pktgen-DPDK#15]
Hi,
We recently started to use Pktgen with X540-AT2 NICs besides 82599 ones. While the rate setting works fine on the 82599s, it looks like as if Pktgen would calculate the TX rate for the X540s as they would be 40Gbit cards.

Some examples:
rate 1 --> Sending with 400Mbit/s
rate 10 --> Sending with 4000Mbit/s
rate 20 --> Sending with 8000Mbit/s
The speed is capped by 10000Mbit/s.

Also, when Pktgen starts the rate is on 100% by default, however, when I start the transmission it starts to transmit with 400Mbit/s (as if the rate would be 1%).
set 1 rate 100 fixes this.

Daniel

**Comment by pktgen** [comment]
Please see the version on DPDK.org
