### ISSUE TITLE
Compiling on rhel7.4

### ISSUE THREAD

**Issue by ric79** [pktgen/Pktgen-DPDK#153]
Hello,
I still have compiling errors on lua section:

```
$ yum install -y gcc readline readline-devel
$ wget http://dpdk.org/browse/apps/pktgen-dpdk/snapshot/pktgen-3.5.0.tar.gz
$ tar -xzvf pktgen-3.5.0.tar.gz
$ export RTE_SDK=/usr/share/dpdk
$ export RTE_TARGET=x86_64-default-linuxapp-gcc
$ cd pktgen-3.5.0/lib/lua/
$ make
...
== src
  CC lapi.o
  CC lauxlib.o
  CC lbaselib.o
  CC lbitlib.o
  CC lcode.o
  CC lcorolib.o
  CC lctype.o
  CC ldblib.o
  CC ldebug.o
  CC ldo.o
  CC ldump.o
  CC lfunc.o
  CC lgc.o
  CC linit.o
  CC liolib.o
  CC llex.o
  CC lmathlib.o
  CC lmem.o
  CC loadlib.o
  CC lobject.o
  CC lopcodes.o
  CC loslib.o
  CC lparser.o
  CC lstate.o
  CC lutf8lib.o
  CC lstring.o
  CC lstrlib.o
  CC ltable.o
  CC ltablib.o
  CC ltm.o
  CC lua_shell.o
  CC lundump.o
  CC lvm.o
  CC lzio.o
  CC luasocket.o
  LD librte_lua.so.1
lmathlib.o: In function `math_tan':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:61: undefined reference to `tan'
lmathlib.o: In function `math_sqrt':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:167: undefined reference to `sqrt'
lmathlib.o: In function `math_sin':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:51: undefined reference to `sin'
lmathlib.o: In function `math_log':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:191: undefined reference to `log10'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:183: undefined reference to `log'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:188: undefined reference to `log2'
lmathlib.o: In function `math_exp':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:200: undefined reference to `exp'
lmathlib.o: In function `math_cos':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:56: undefined reference to `cos'
lmathlib.o: In function `math_atan':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:78: undefined reference to `atan2'
lmathlib.o: In function `math_asin':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:66: undefined reference to `asin'
lmathlib.o: In function `math_acos':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:71: undefined reference to `acos'
lmathlib.o: In function `math_modf':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:157: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:157: undefined reference to `ceil'
lmathlib.o: In function `math_fmod':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:138: undefined reference to `fmod'
lmathlib.o: In function `math_ceil':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:120: undefined reference to `ceil'
lmathlib.o: In function `math_floor':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:109: undefined reference to `floor'
loadlib.o: In function `lsys_sym':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:134: undefined reference to `dlsym'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:135: undefined reference to `dlerror'
loadlib.o: In function `lsys_load':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:127: undefined reference to `dlopen'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:128: undefined reference to `dlerror'
loadlib.o: In function `lsys_unloadlib':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:122: undefined reference to `dlclose'
loadlib.o: In function `lsys_sym':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:134: undefined reference to `dlsym'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:135: undefined reference to `dlerror'
loadlib.o: In function `lsys_load':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:127: undefined reference to `dlopen'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:128: undefined reference to `dlerror'
lobject.o: In function `numarith':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:115: undefined reference to `fmod'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:111: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:110: undefined reference to `pow'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:111: undefined reference to `floor'
lvm.o: In function `luaV_tointeger':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
lvm.o: In function `luaV_execute':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:1001: undefined reference to `fmod'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:1016: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:1026: undefined reference to `pow'
lvm.o: In function `luaV_tointeger':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
lvm.o:/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: more undefined references to `floor' follow
luasocket.o: In function `lua_server':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/luasocket.c:272: undefined reference to `pthread_detach'
luasocket.o: In function `lua_init_socket':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/luasocket.c:307: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[5]: *** [librte_lua.so.1] Error 1
make[4]: *** [all] Error 2
make[3]: *** [src] Error 2
make[2]: *** [all] Error 2
make[1]: *** [lua] Error 2
make: *** [lib] Error 2
```

I think it is somthing related to missing gcc options (ie:  lm lpthread lrt). How can I specify them.

PS:
I can compile lua in standard way
```
$ curl -R -O http://www.lua.org/ftp/lua-5.3.4.tar.gz
$ tar zxf lua-5.3.4.tar.gz
$ cd lua-5.3.4
$ make linux
cd src && make linux
make[1]: Entering directory `/root/lua-5.3.4/src'
make all SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl -lreadline"
make[2]: Entering directory `/root/lua-5.3.4/src'
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lapi.o lapi.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lcode.o lcode.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lctype.o lctype.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o ldebug.o ldebug.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o ldo.o ldo.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o ldump.o ldump.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lfunc.o lfunc.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lgc.o lgc.c
...
```

**Comment by pktgen** [comment]
> On May 4, 2018, at 1:35 PM, Riccardo <notifications@github.com> wrote:
> 
> Hello,
> I still have compiling errors on lua section:
> 
> $ yum install -y gcc readline readline-devel
> $ wget http://dpdk.org/browse/apps/pktgen-dpdk/snapshot/pktgen-3.5.0.tar.gz
> $ tar -xzvf pktgen-3.5.0.tar.gz
> $ export RTE_SDK=/usr/share/dpdk
> $ export RTE_TARGET=x86_64-default-linuxapp-gcc

What version of DPDK are you using we do not use -default- but -native- ?

> $ cd lib/lua/
> $ make
> ...
> == src
>   CC lapi.o
>   CC lauxlib.o
>   CC lbaselib.o
>   CC lbitlib.o
>   CC lcode.o
>   CC lcorolib.o
>   CC lctype.o
>   CC ldblib.o
>   CC ldebug.o
>   CC ldo.o
>   CC ldump.o
>   CC lfunc.o
>   CC lgc.o
>   CC linit.o
>   CC liolib.o
>   CC llex.o
>   CC lmathlib.o
>   CC lmem.o
>   CC loadlib.o
>   CC lobject.o
>   CC lopcodes.o
>   CC loslib.o
>   CC lparser.o
>   CC lstate.o
>   CC lutf8lib.o
>   CC lstring.o
>   CC lstrlib.o
>   CC ltable.o
>   CC ltablib.o
>   CC ltm.o
>   CC lua_shell.o
>   CC lundump.o
>   CC lvm.o
>   CC lzio.o
>   CC luasocket.o
>   LD librte_lua.so.1
> lmathlib.o: In function `math_tan':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:61: undefined reference to `tan'
> lmathlib.o: In function `math_sqrt':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:167: undefined reference to `sqrt'
> lmathlib.o: In function `math_sin':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:51: undefined reference to `sin'
> lmathlib.o: In function `math_log':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:191: undefined reference to `log10'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:183: undefined reference to `log'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:188: undefined reference to `log2'
> lmathlib.o: In function `math_exp':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:200: undefined reference to `exp'
> lmathlib.o: In function `math_cos':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:56: undefined reference to `cos'
> lmathlib.o: In function `math_atan':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:78: undefined reference to `atan2'
> lmathlib.o: In function `math_asin':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:66: undefined reference to `asin'
> lmathlib.o: In function `math_acos':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:71: undefined reference to `acos'
> lmathlib.o: In function `math_modf':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:157: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:157: undefined reference to `ceil'
> lmathlib.o: In function `math_fmod':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:138: undefined reference to `fmod'
> lmathlib.o: In function `math_ceil':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:120: undefined reference to `ceil'
> lmathlib.o: In function `math_floor':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:109: undefined reference to `floor'
> loadlib.o: In function `lsys_sym':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:134: undefined reference to `dlsym'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:135: undefined reference to `dlerror'
> loadlib.o: In function `lsys_load':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:127: undefined reference to `dlopen'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:128: undefined reference to `dlerror'
> loadlib.o: In function `lsys_unloadlib':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:122: undefined reference to `dlclose'
> loadlib.o: In function `lsys_sym':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:134: undefined reference to `dlsym'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:135: undefined reference to `dlerror'
> loadlib.o: In function `lsys_load':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:127: undefined reference to `dlopen'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/loadlib.c:128: undefined reference to `dlerror'
> lobject.o: In function `numarith':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:115: undefined reference to `fmod'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:111: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:110: undefined reference to `pow'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lobject.c:111: undefined reference to `floor'
> lvm.o: In function `luaV_tointeger':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> lvm.o: In function `luaV_execute':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:1001: undefined reference to `fmod'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:1016: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:1026: undefined reference to `pow'
> lvm.o: In function `luaV_tointeger':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: undefined reference to `floor'
> lvm.o:/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lvm.c:99: more undefined references to `floor' follow
> luasocket.o: In function `lua_server':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/luasocket.c:272: undefined reference to `pthread_detach'
> luasocket.o: In function `lua_init_socket':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/luasocket.c:307: undefined reference to `pthread_create'
> collect2: error: ld returned 1 exit status
> make[5]: *** [librte_lua.so.1] Error 1
> make[4]: *** [all] Error 2
> make[3]: *** [src] Error 2
> make[2]: *** [all] Error 2
> make[1]: *** [lua] Error 2
> make: *** [lib] Error 2
> 
> I think it is somthing related to missing gcc options (ie: lm lpthread lrt). How can I specify them.
> 
> PS:
> I can compile lua in standard way
> 
> $ curl -R -O http://www.lua.org/ftp/lua-5.3.4.tar.gz
> $ tar zxf lua-5.3.4.tar.gz
> $ cd lua-5.3.4
> $ make linux
> cd src && make linux
> make[1]: Entering directory `/root/lua-5.3.4/src'
> make all SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl -lreadline"
> make[2]: Entering directory `/root/lua-5.3.4/src'
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lapi.o lapi.c
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lcode.o lcode.c
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lctype.o lctype.c
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o ldebug.o ldebug.c
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o ldo.o ldo.c
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o ldump.o ldump.c
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lfunc.o lfunc.c
> gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lgc.o lgc.c
> ...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by ric79** [comment]
Hello, thank for replying!

Unfortunately DPDK was installed using Satellite.

```
[root@vm-aa lua]# ls -la /usr/share/dpdk/
total 16
drwxr-xr-x.  6 root root   79 May  4 19:02 .
drwxr-xr-x. 78 root root 4096 May  4 18:40 ..
drwxr-xr-x.  8 root root 4096 May  4 19:02 mk
drwxr-xr-x.  3 root root 4096 May  4 19:02 scripts
drwxr-xr-x.  2 root root 4096 May  4 18:40 tools
drwxr-xr-x.  3 root root   58 May  4 19:02 x86_64-default-linuxapp-gcc
```

**Comment by pktgen** [comment]
If you can you can pull the DPDk from dpdk.org as I normally only support the latest version of DPDK in pktgen, but I do have some ifdefs to handle some changes.

> On May 4, 2018, at 1:54 PM, Riccardo <notifications@github.com> wrote:
> 
> Hello, thank for replying!
> 
> Unfortunately DPDK was installed using Satellite.
> 
> [root@vm-aa lua]# ls -la /usr/share/dpdk/
> total 16
> drwxr-xr-x.  6 root root   79 May  4 19:02 .
> drwxr-xr-x. 78 root root 4096 May  4 18:40 ..
> drwxr-xr-x.  8 root root 4096 May  4 19:02 mk
> drwxr-xr-x.  3 root root 4096 May  4 19:02 scripts
> drwxr-xr-x.  2 root root 4096 May  4 18:40 tools
> drwxr-xr-x.  3 root root   58 May  4 19:02 x86_64-default-linuxapp-gcc
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by pktgen** [comment]
look for the rte_version.h header file and it tells you the version.

> On May 4, 2018, at 1:54 PM, Riccardo <notifications@github.com> wrote:
> 
> Hello, thank for replying!
> 
> Unfortunately DPDK was installed using Satellite.
> 
> [root@vm-aa lua]# ls -la /usr/share/dpdk/
> total 16
> drwxr-xr-x.  6 root root   79 May  4 19:02 .
> drwxr-xr-x. 78 root root 4096 May  4 18:40 ..
> drwxr-xr-x.  8 root root 4096 May  4 19:02 mk
> drwxr-xr-x.  3 root root 4096 May  4 19:02 scripts
> drwxr-xr-x.  2 root root 4096 May  4 18:40 tools
> drwxr-xr-x.  3 root root   58 May  4 19:02 x86_64-default-linuxapp-gcc
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by ric79** [comment]
Unfortunately the DPDK release (dpdk-16.11.2-4.el7.x86_64) cannot be changed (this is part of Openstack DPDK installation). 
:(

Thanks anyway. I will try to reinstall everything using CentOS and latest packages

Rr

**Comment by pktgen** [comment]
Did you try the build from the top level pktgen directory or just in the lib/lua directory?

> On May 4, 2018, at 2:00 PM, Riccardo <notifications@github.com> wrote:
> 
> Unfortunately the DPDK release (dpdk-16.11.2-4.el7.x86_64) cannot be changed (this is part of Openstack DPDK installation).
> :(
> 
> Thanks anyway. I will try to reinstall everything using CentOS and latest packages
> 
> Rr
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by ric79** [comment]
When I try to compile the top level directory the error is on lea section. 
When I build pktgen I generally compile first ./lib/lua and the ./

The error that you are seeing is about make in lib/lua directory.

**Comment by pktgen** [comment]
You only need to build from the top level pktgen-dpdk directory. Build lib/lua first is not required.

> On May 4, 2018, at 2:05 PM, Riccardo <notifications@github.com> wrote:
> 
> When I try to compile the top level directory the error is on lea section.
> When I build pktgen I generally compile first ./lib/lua and the ./
> 
> The error that you are seeing is about make in lib/lua directory.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by ric79** [comment]
As you can see the result is the same:

```
[root@vm-aa pktgen-3.5.0]# make
== lib
== common
  CC copyright_info.o
  CC port_config.o
...
  LD libcommon.so.1
  SYMLINK-FILE include/cksum.h
  SYMLINK-FILE include/copyright_info.h
  SYMLINK-FILE include/core_info.h
  SYMLINK-FILE include/coremap.h
  SYMLINK-FILE include/cmdline_parse_args.h
  SYMLINK-FILE include/cycles.h
  SYMLINK-FILE include/pg_ether.h
  SYMLINK-FILE include/l2p.h
  SYMLINK-FILE include/lscpu.h
  SYMLINK-FILE include/mbuf.h
  SYMLINK-FILE include/_pcap.h
  SYMLINK-FILE include/port_config.h
  SYMLINK-FILE include/utils.h
  INSTALL-LIB libcommon.so.1
== lua
--2018-05-04 21:08:22--  https://www.lua.org/ftp/lua-5.3.4.tar.gz
Saving to: ‘lua-5.3.4.tar.gz’

100%[=========================================================================================================================================>] 303,586     --.-K/s   in 0.1s

2018-05-04 21:08:22 (2.38 MB/s) - ‘lua-5.3.4.tar.gz’ saved [303586/303586]

patching file Makefile
patching file Makefile.lua
patching file src/lauxlib.c
patching file src/lauxlib.h
patching file src/liolib.c
patching file src/lstate.h
patching file src/luac.c
patching file src/luaconf.h
patching file src/lua.h
patching file src/lua_shell.c
patching file src/lua_shell.h
patching file src/luasocket.c
patching file src/luasocket.h
patching file src/lua_version.map
patching file src/Makefile
patching file src/Makefile.lua
== src
  CC lapi.o
  CC lauxlib.o
  CC lbaselib.o
  CC lbitlib.o
  CC lcode.o
  CC lcorolib.o
  CC lctype.o
  CC ldblib.o
  CC ldebug.o
  CC ldo.o
  CC ldump.o
  CC lfunc.o
  CC lgc.o
  CC linit.o
  CC liolib.o
  CC llex.o
  CC lmathlib.o
  CC lmem.o
  CC loadlib.o
  CC lobject.o
  CC lopcodes.o
  CC loslib.o
  CC lparser.o
  CC lstate.o
  CC lutf8lib.o
  CC lstring.o
  CC lstrlib.o
  CC ltable.o
  CC ltablib.o
  CC ltm.o
  CC lua_shell.o
  CC lundump.o
  CC lvm.o
  CC lzio.o
  CC luasocket.o
  LD librte_lua.so.1
lmathlib.o: In function `math_tan':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:61: undefined reference to `tan'
lmathlib.o: In function `math_sqrt':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:167: undefined reference to `sqrt'
lmathlib.o: In function `math_sin':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:51: undefined reference to `sin'
lmathlib.o: In function `math_log':
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:191: undefined reference to `log10'
/root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:183: undefined reference to `log'
```

**Comment by pktgen** [comment]
Then something in the old build system is not supporting this version of Pktgen build now.

> On May 4, 2018, at 2:10 PM, Riccardo <notifications@github.com> wrote:
> 
> As you can see the result is the same:
> 
> [root@vm-aa pktgen-3.5.0]# make
> == lib
> == common
>   CC copyright_info.o
>   CC port_config.o
> ...
>   LD libcommon.so.1
>   SYMLINK-FILE include/cksum.h
>   SYMLINK-FILE include/copyright_info.h
>   SYMLINK-FILE include/core_info.h
>   SYMLINK-FILE include/coremap.h
>   SYMLINK-FILE include/cmdline_parse_args.h
>   SYMLINK-FILE include/cycles.h
>   SYMLINK-FILE include/pg_ether.h
>   SYMLINK-FILE include/l2p.h
>   SYMLINK-FILE include/lscpu.h
>   SYMLINK-FILE include/mbuf.h
>   SYMLINK-FILE include/_pcap.h
>   SYMLINK-FILE include/port_config.h
>   SYMLINK-FILE include/utils.h
>   INSTALL-LIB libcommon.so.1
> == lua
> --2018-05-04 21:08:22--  https://www.lua.org/ftp/lua-5.3.4.tar.gz
> Saving to: ‘lua-5.3.4.tar.gz’
> 
> 100%[=========================================================================================================================================>] 303,586     --.-K/s   in 0.1s
> 
> 2018-05-04 21:08:22 (2.38 MB/s) - ‘lua-5.3.4.tar.gz’ saved [303586/303586]
> 
> patching file Makefile
> patching file Makefile.lua
> patching file src/lauxlib.c
> patching file src/lauxlib.h
> patching file src/liolib.c
> patching file src/lstate.h
> patching file src/luac.c
> patching file src/luaconf.h
> patching file src/lua.h
> patching file src/lua_shell.c
> patching file src/lua_shell.h
> patching file src/luasocket.c
> patching file src/luasocket.h
> patching file src/lua_version.map
> patching file src/Makefile
> patching file src/Makefile.lua
> == src
>   CC lapi.o
>   CC lauxlib.o
>   CC lbaselib.o
>   CC lbitlib.o
>   CC lcode.o
>   CC lcorolib.o
>   CC lctype.o
>   CC ldblib.o
>   CC ldebug.o
>   CC ldo.o
>   CC ldump.o
>   CC lfunc.o
>   CC lgc.o
>   CC linit.o
>   CC liolib.o
>   CC llex.o
>   CC lmathlib.o
>   CC lmem.o
>   CC loadlib.o
>   CC lobject.o
>   CC lopcodes.o
>   CC loslib.o
>   CC lparser.o
>   CC lstate.o
>   CC lutf8lib.o
>   CC lstring.o
>   CC lstrlib.o
>   CC ltable.o
>   CC ltablib.o
>   CC ltm.o
>   CC lua_shell.o
>   CC lundump.o
>   CC lvm.o
>   CC lzio.o
>   CC luasocket.o
>   LD librte_lua.so.1
> lmathlib.o: In function `math_tan':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:61: undefined reference to `tan'
> lmathlib.o: In function `math_sqrt':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:167: undefined reference to `sqrt'
> lmathlib.o: In function `math_sin':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:51: undefined reference to `sin'
> lmathlib.o: In function `math_log':
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:193: undefined reference to `log'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:191: undefined reference to `log10'
> /root/pktgen-3.5.0/lib/lua/lua-5.3.4/src/lmathlib.c:183: undefined reference to `log'
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by ric79** [comment]
yes. I'm just not recompiling all on a new image with a brand new DPDK. Thanks for you support

**Comment by pktgen** [comment]
You need to edit the Makefile and add -lm -lpthread I believe to the CFLAGS
line. I do not know why your system does this and I can not reproduce.
