### ISSUE TITLE
Running Pktgen with Lua enabled not compatible with DPDK version 

### ISSUE THREAD

**Issue by vorbrodt** [pktgen/Pktgen-DPDK#157]
Hello, I'm trying to run Pktgen with Lua but keep getting warnings when running `ninja -C build` in Pktgen. The version of Pktgen that I'm using is `22.07.1` and I'm on the `dev` branch. I have tried with both using DPDK version  `23.02.0-rc0` (latest version on Github) and `dpdk-stable-21.11.1`. Both are generating the same errors. Below I show the errors for `23.02.0-rc0`.

It's worth mentioning that I'm only getting these errors when I run with Lua enabled `meson -Denable_lua=true build` and then `ninja -C build`. When running without enabling Lua (that is  `meson build`) it works as expected. 

When using `dpdk-stable-21.11.1` or `23.02.0-rc0`, I receive this warning messages when running `ninja -C build`:

![image](https://user-images.githubusercontent.com/64839037/220077518-f8aad59f-d9c2-4b1b-ac0b-09fe3909cddc.png)

* Am I missing something or are the versions not compatible? 
* If that is the case what version of DPDK would be compatible with using Pktgen with Lua enabled?

**Comment by pktgen** [comment]
Please have a look at #158 and see if that fixes the problem.

**Comment by vorbrodt** [comment]
It works for `ninja -C build` now without any warnings! 

However, I'm still running into an issue with Lua. First I run `meson -Denable_lua=true`, `ninja -C build` and then `ninja -C build install`. Then I try from Pktgen directory with `./usr/local/bin/pktgen --no-telemetry -l 4,6,8 -n 4 -a 0000:03:02.0 -m 1024 -- -T -m [6:8].0 -f test/hello-world.lua`

I get this error:
![image](https://user-images.githubusercontent.com/64839037/220296672-b62165b3-9516-49d9-9ced-0e60cb468f82.png)

Is this not what `meson -Denable_lua=true` is suppose to solve? What am I doing wrong?

**Comment by KeithWiles** [comment]
Use the Makefile 'make clean buildlua' this is how I tested the Lua builds. Also make sure Lua found in the meson output.

**Comment by vorbrodt** [comment]
Thank you! It worked using ` make clean buildlua`
