### ISSUE TITLE
pktgen hangs when using "quit" command in script

### ISSUE THREAD

**Issue by zendes** [pktgen/Pktgen-DPDK#16]
When starting pktgen using the -f flag and pointing it to a script that has the "quit" command in it, pktgen hangs after that line instead of actually quitting. A Ctrl-C will make it quit for real.

I use the following (mimimal) command line to start pktgen:
sudo ./app/build/app/pktgen -c 0xff -n 4 -w 0000:01:00.1 -- -m "[1:2].0" -f script.pkt

And script.pkt has the following contents:
quit

I'm using pktgen version 2.7.7 with commit id 5e8633. The rest of pktgen fucntions normally on this machine, aka loading pcap files, generating traffic and manually typing quit all work. Other commands in the -f script file also work, like set all rate 50, sleep 10, etc.

**Comment by simson** [comment]
Hi,
Using the 2.8.6 version the bug seems to remain.  Is there a workaround ?

**Comment by pktgen** [comment]
Sorry, I have not been able to work on that bug. I will try next weekend.

**Comment by ellagxy** [comment]
Hi,

Just want to check what is the status of this bug? I'm using pktgen version 3.4.2 and after start pktgen with -f option with script having "quit", pktgen does not even load the script. If I put quit() in script, pktgen load the script but not quit.
