### ISSUE TITLE
Sending packets from Pktgen to UDP socket with specified destination port

### ISSUE THREAD

**Issue by vorbrodt** [pktgen/Pktgen-DPDK#161]
### Problem
I'm trying to send data packets from the traffic generator Pktgen to an UDP socket I have implemented so that it will forward the packets back to their source. The problem I have run into is that I cannot find any way of sending data packets from Pktgen to the UDP socket as there seems to be no way of specifying the destination port for packets using UDP protocol in Pktgen. 

### Setup
The UDP socket uses the IP address `192.168.1.100` with port `8080`. I verified that it is open for receiving packets and forwarding through using `nc -vz -u 192.168.1.100 8080`. It is using IPv4 which is also what I'm using for Pktgen. 

Pktgen is running on 03:00.0 and is of version `22.07.2`.
[![setup][2]][2]    

UDP socket is setup on this interface:

[![udpinterface][3]][3]

### What I have tired

I have looked through the [Pktgen documentation][1] for commands to set the destination port but can only find support for setting the destination IP address without the port number (`set <portlist> src|dst ip ipaddr`). Destination port is mentioned a few times in the documentation, but none of the commands seem to work while others are TCP specific. Here are a few that I have tried:

    rate <portlist> dport <value>        - Destination port number for TCP
    rate 0 dport 8080 - Tried this just in case it worked UDP as well, but unfortunately it didn't
    
    set <portlist> [src|dst] ip ipaddr - Set IP addresses, Source must include network mask e.g. 10.1.2.3/24
    set 0 dst ip 192.168.1.100:8000 - Invalid syntax
    set 0 dst ip 192.168.1.100 8000 - Invalid syntax
    set 0 dst ip 192.168.1.100/8000 - Invalid syntax

It didn't work either to only set the IP address through `set 0 dst ip 192.168.1.100` and start sending packets from Pktgen as the packets never reach the socket then.

Setting the range didn't work either.

    range <portlist> src|dst port <SMMI> <value>  - Set UDP/TCP source/dest port number
    range 0 dst port start 8080 
    range 0 dst port min 8079
    range 0 dst port max 8081
    range 0 dst port inc 1

I have one NIC with 2 interfaces, you can see it above in the images. The NIC is the `XL710`, where one of the interfaces have been bound using `dpdk-devbind -b vfio-pci enp3s0f0` so that it may be used for Pktgen and the other interface on the NIC `enp3s0f01` I have set to the IP address `192.168.1.100` for the UDP socket to use

Previously I have run Pktgen and TestPMD together which worked great, but in that case I could simply use TestPMD´s MAC address (`set <portlist> dst mac <addr>`) to help the packets find their way which is not a possibility with UDP sockets. 

### Questions

* Is there no way of sending packets from Pktgen to an UDP socket? It feels like there should be, but I can't find it.
* What am I missing and how do you set the destination port for an UDP socket from within Pktgen so packets may be received on the socket and forwarded back to Pktgen?

  [1]: https://pktgen-dpdk.readthedocs.io/en/latest/commands.html#runtime-options-and-commands
  [2]: https://i.stack.imgur.com/Owzzj.png
  [3]: https://i.stack.imgur.com/fQesP.png

**Comment by KeithWiles** [comment]
Did you try `set <portlist> dport NNN` and/or `set <portlist> sport NNN` ?

The range and sequence setting of port addresses is only for those modes.

**Comment by vorbrodt** [comment]
I think I tried it before, but just to be sure I tried it again now. Unfortunately, it didn't work.

Here are the commands I ran in the exact order:

    set 0 size 64
    set 0 proto udp
    set 0 rate 0.1
    set 0 dst ip 192.168.1.100
    set 0 dport 8080
    start 0 
    //Nothing happens
    stop 0
    set 0 sport 8080
    start 0
    //Nothing happens



Here is how it looked in the end:

![image](https://user-images.githubusercontent.com/64839037/222270680-d139d9ec-45cb-4a75-9bd6-eb012dc959b4.png)

**Comment by KeithWiles** [comment]
The dport and sport commands work as it changes the field on the screen. If you were to capture packets on the DUT with wireshark or tcpdump, you should see the correct packets. If you do not see any packets (via wireshark or tcpdump) then I am expecting the packets are not being received and dropped someplace. I did notice the Destination MAC is 00:00:00:00:00:00 and some hardware will not accept this MAC address (as it was a broadcast address years ago). (I am assuming you are not able to see any packets arriving at the DUT)

**Comment by vorbrodt** [comment]
I tried changing the mac destination but it didn't seem to make any difference.

I have two PFs on the NIC, where I now use one of the PFs for trying to send and receive packets. I have Pktgen (`03:0a.0`) on a VF and the socket is on another VF (`enp3s0f1v1`)  and both connect to the same PF. 

Could it be some issues with sending packets between VFs? Is this something you have been tried recently? 

![image](https://user-images.githubusercontent.com/64839037/222676046-1534243d-9f95-4d64-bf67-8aaaeb6b0ba1.png)

**Comment by KeithWiles** [comment]
It is possibly the problem. I have not tried your configuration and I only have tried looping back packets only with external cables between ports and not between VFs or VF-PF. Some NICs do not like sending traffic with the destination MAC being the port sending the packets.

**Comment by vorbrodt** [comment]
Still trying to figure this one out. Have you any other idea of what might be could potentially be the issue or where to start troubleshooting? Really want to figure this one out.

Nothing shows up via tcpdump or wireshark, but I Pktgen is sending packets so where do they go then? It seems difficult to check without tcpdump or wireshark.

**Comment by KeithWiles** [comment]
If pktgen is sending traffic and the DUT is not receiving than it normally means the MAC address is wrong or the interface is not in promiscuous mode. In your case it seems to be getting dropped at the NIC level and not the receiving side. That is the best I can suggest.

**Comment by vorbrodt** [comment]
Thanks a lot! Seemed as setting the interface, which the UDP socket was on, to promiscuous mode and changing the MAC address did the trick. Now the UDP socket can receive the packet from Pktgen, so now I'm half way there!

The issue I am having now is that the UDP socket is not forwarding packets back to Pktgen. When using tcpdump it only sees the packets sent by Pktgen to the UDP socket and does not show that the UDP socket is sending anything back to Pktgen.

I have tested the UDP socket with other network interfaces to make sure that it is responding correctly and in that case I can see via tcpdump that the UDP socket both receives and sends back the packet. 

So, could the issue have something to do with Pktgen being bound to a DPDK-compatible driver? Or that it is not using promiscuous mode even though I specified it in the run command with the `-P` flag.

*Why is the UDP socket not forwarding the packets back to Pktgen? It is working when using interfaces together like `enp3s0f0v2` (UDP socket) and `enp3s0f0v5` (a server sending a packet to the UDP socket and receiving a response for the UDP socket), so why would it not work for Pktgen?

**Comment by KeithWiles** [comment]
Pktgen receive side is super simple. If it gets a packet arriving on the port it will show it was received, so I assume it is not pktgen being the problem. Because you have Pktgen port in promiscuous mode.

Make sure you do this command 'enable <portlist> process' to make sure Pktgen responds to ARP requests. As the DUT will want to get the destination MAC. Using 'arp -a' to see the ARP table. The UDP socket application needs to be setup correctly to forward the packet back to Pktgen. If the UDP socket is not sending packets then the UDP packet being sent is not configured correctly for forwarding packets.

If the UDP application is receiving the data and sending the data back to the same port, then is should work and is not a pktgen problem. I would investigate the UDP socket application or the system running the application.

**Comment by vorbrodt** [comment]
I found the issue. I had to add the IP route like `ip route add 192.168.0.0/24 dev <network interface>` and also like you said enable processing of ARP packets through `enable 0 process`
