### ISSUE TITLE
Can pktgen support configuring link speed and negotiation abilities for NICs?

### ISSUE THREAD

**Issue by Oosl** [pktgen/Pktgen-DPDK#164]
Hi there,

I'm currently using Intel X550-T2 NICs with pktgen, and I've noticed that the default configuration disables negotiation abilities for 2.5G and 5G, only allowing 100M, 1G, and 10G speeds to be negotiated. I would like to enable negotiation for all available speeds.

Is it currently possible to configure the link speed and negotiation abilities in pktgen? I have looked through the documentation and source code but have not found any options for this.

If it's not currently possible, would it be possible to add support for configuring link speed and negotiation abilities in a future release of pktgen? This would be very helpful for users like myself who need to configure NICs with specific negotiation abilities.

Thank you for your time and consideration.

**Comment by pktgen** [comment]
Pktgen does not attempt to change link speeds normally the speed is negotiated by the two ports. Plus DPDK PMD does all of the NIC setup, so I am not convinced add something to Pktgen would work without modifying the DPDK PMD. Maybe look at the DPDK PMD and see if it has a configuration and if DPDK have an API I can use to set the link speed or force it then I could look into adding it to pktgen.

**Comment by Oosl** [comment]
a good news and a bad news(●'◡'●)  

## good news: 

I found that how to enable X550`s negotiation abilities for 2.5G and 5G in [this](http://patches.dpdk.org/project/dpdk/patch/20200612032410.20864-20-guinanx.sun@intel.com/).  

##  bad news: 

I did not found any API about changing port speed dynamically in the newest DPDK. only can force the speed when start the port by the [rte_eth_conf.link_speeds ](https://doc.dpdk.org/api/structrte__eth__conf.html#ad8c15e528dccff643adf7fc96fec6473).

**Comment by KeithWiles** [comment]
If you can force the non-pktgen side to be 2.5 or 5G then the pktgen side will be forced to use those speeds. If both sides are DPDK then you have a problem, which needs to be solved by DPDK.
