### ISSUE TITLE
Incorrect Recived packet details statistics for port 2

### ISSUE THREAD

**Issue by Oosl** [pktgen/Pktgen-DPDK#165]
I've noticed a bug in the packet details statistics feature of pktgen version 22.07.1(DPDK version 22.11.2). Specifically, when using an Intel x550-t2 NIC with two ports, the packet details statistics for port 2 are incorrect. It appears that the packet statistics for both ports are being aggregated together and reported as the statistics for port 2.

Steps to Reproduce:

1. Install pktgen 22.07.1 and DPDK 22.11.2
2. Configure an Intel x550-t2 NIC with two ports
    `sudo dpdk-devbind.py -b=vfio-pci 01:00.0 01:00.1 && sudo dpdk-hugepages.py -p 2M --setup 8G`
4. Start pktgen and send traffic through both ports
     `sudo ./pktgen -l 0-10 -n 2 -- -T -P -N -v -m "[1-3:4/9].0,[5-7:8/10].1"`
5. Observe the packet details statistics for port 2

Expected Behavior:

The packet details statistics for port 2 should reflect the actual packet statistics for that port only.

Actual Behavior:

The packet details statistics for port 2 reflect the aggregated statistics for both ports.

Additional Information:

I have attached screenshots of the packet details statistics for both ports and can provide additional information upon request.
![image_2023-03-09_20-54-23](https://user-images.githubusercontent.com/27420243/224031576-ae6d9151-4ab4-499b-8691-387e0c22a1f9.png)

**Comment by pktgen** [comment]
This was a bug that was reported and fixed. Look at the latency-fixes branch and see if that fixes this issue. I will be merging this branch to the main branch soon.

**Comment by Oosl** [comment]
Yes, I found this bug had been fixed at the latency-fixes branch, and I also found it had been fixed at the main branch too. (when I manual updated my DPDK to 22.11.1 from 21.11.2, I can compile the newest code in this repo.)
Thanks a lot!
