### ISSUE TITLE
Calculating latency of each packet using timestamps

### ISSUE THREAD

**Issue by vorbrodt** [pktgen/Pktgen-DPDK#171]
## Problem

I want to calculate the latency of each packet, in order to then generate a histogram of different latency values (e.g.` {0-150: xxx, 151-300: yyy, 301 and above: zzz}`). After looking around in the code of where this calculation could possibly be done, I found `pktgen_recv_tstamp` in `pktgen.c`. 

What I thought would be a reasonable approach would be use current time minus the time stamp of when the packet was sent, meaning something like `pktgen_get_time() - tstamp->timestamp`. However this does not generate the results that I was expecting. The results show extremely large numbers (uncertain what the exact metric it is, it does not seem to be nano seconds which I originally thought it would be).  Here are the results of printing within the function:

## Results 

![image](https://user-images.githubusercontent.com/64839037/226976360-abf4bf9a-551c-4beb-ae31-8c8584a0c045.png)

One thing that strikes me as odd in the results is that for every other packet `tstamp->timestamp` is `0` or it is some number containing 19 digits. `pktgen_get_time()` seems to always be generating some value containing 16 digits, which may be why the calculation of latency for each packet becomes so large.

## Code
Here is the code for `pktgen_recv_tstamp` where the lines containing `==================`  are lines that I have added. 

    static __inline__ void
    pktgen_recv_tstamp(port_info_t *info, struct rte_mbuf **pkts, uint16_t nb_pkts)
    {
    int lid = rte_lcore_id();
    int qid = get_rxque(pktgen.l2p, lid, info->pid);
    int i;
    uint64_t cycles, jitter;

    for (i = 0; i < nb_pkts; i++) {
        printf("Pktnumber: %d", i); //======================
        if (pktgen_tst_port_flags(info, ENABLE_LATENCY_PKTS | SEND_RATE_PACKETS)) {
            tstamp_t *tstamp;
            tstamp = pktgen_tstamp_pointer(info, rte_pktmbuf_mtod(pkts[i], char *));

            uint64_t latency_ns = (pktgen_get_time() - tstamp->timestamp); //======================
            printf(" pktgen_get_time: %" PRIu64, pktgen_get_time() ); //======================
            printf(" tstamp->timestamp: %" PRIu64, tstamp->timestamp ); //======================
            printf(" Latency (ns): %" PRIu64 "\n", latency_ns); //======================

            //TODO - add functionality here to record latency to a hash table //============================================

            if (tstamp->magic == TSTAMP_MAGIC) {
                latency_t *lat = &info->latency;

                tstamp->magic = 0; /* clear timestamp magic cookie */
                cycles        = (pktgen_get_time() - tstamp->timestamp);

                if (tstamp->index != lat->expect_index) {
                    lat->expect_index = tstamp->index + 1;
                    lat->num_skipped++;
                    continue; /* Skip this latency packet */
                }
                lat->expect_index++;

                lat->num_latency_pkts++;

                if (pktgen_tst_port_flags(info, ENABLE_LATENCY_PKTS | SEND_RATE_PACKETS)) {
                    lat->running_cycles += cycles;

                    if (lat->min_cycles == 0 || cycles < lat->min_cycles)
                        lat->min_cycles = cycles;
                    if (lat->max_cycles == 0 || cycles > lat->max_cycles)
                        lat->max_cycles = cycles;

                    jitter = (cycles > lat->prev_cycles) ? cycles - lat->prev_cycles
                                                         : lat->prev_cycles - cycles;
                    if (jitter > lat->jitter_threshold_cycles)
                        lat->jitter_count++;

                    lat->prev_cycles = cycles;
                }
                if (pktgen_tst_port_flags(info, SAMPLING_LATENCIES)) {
                    /* Record latency if it's time for sampling (seperately per lcore) */
                    latsamp_stats_t *stats = &info->latsamp_stats[qid];
                    uint64_t now           = pktgen_get_time();

                    stats->pkt_counter++;
                    if (stats->next == 0 || now >= stats->next) {
                        if (stats->idx < stats->num_samples) {
                            stats->data[stats->idx] = (cycles * Billion) / rte_get_tsc_hz();
                            stats->idx++;
                        }

                        /* Calculate next sampling point */
                        if (info->latsamp_type == LATSAMPLER_POISSON) {
                            double next_possion_time_ns = next_poisson_time(info->latsamp_rate);

                            stats->next = now + next_possion_time_ns * (double)rte_get_tsc_hz();
                        } else        // LATSAMPLER_SIMPLE or LATSAMPLER_UNSPEC
                            stats->next = now + rte_get_tsc_hz() / info->latsamp_rate;
                    }
                }
            }
        }
    }
    }

## Questions
How can the calculation of each packets latency be done? And why does  `tstamp->timestamp` sometimes generate `0` or a value containing 19 digits. It feels like both  `tstamp->timestamp` and  `pktgen_get_time()` should be generating values of the same scale, thus causing the latency value to become smaller.

**Comment by KeithWiles** [comment]
The code you added is when Latency measurements are enabled 'ENABLE_LATENCY_PKTS', not when the packet contains a valid timestamp. If you look a few lines lower you will see the 'if' trying to detect if the packet is a valid time stamp packet testing the MAGIC value is valid in the structure.

You should move the code to below the MAGIC test line at least. Also remember the timestamp value is not in ns, but in cycles based on the CPU counter. If you look a bit farther in the code you will see the line to calculate the 'cycles' this is the value you want to use. When you display this value you need to convert it to ns from cycles, which I have a routine in the display section to convert cycles to time.

IMO it seems like cycles is the value you want to put in the hash after converting it to micro-seconds or nano-seconds and  the code you added does not need to be done.

**Comment by vorbrodt** [comment]
Okay I see. I tried to add it after the if-statment with the MAGIC value before but the issue I had that it never actually got into the if-statement. Any idea why the MAGIC is never valid?

**Comment by KeithWiles** [comment]
Did you enable the sending and receiving ports for latency? 'enable 0 latency' and 'enable 1 latency' If forwarding packets the receive side needs to have latency enabled. I sometimes forget to enable both :-(

**Comment by vorbrodt** [comment]
I did not get `TSTAMP_MAGIC` working but instead replaced it with the value `tstam->magic` was producing. The code I ended up with is:

    static __inline__ void
    pktgen_recv_tstamp(port_info_t *info, struct rte_mbuf **pkts, uint16_t nb_pkts)
    {
    int lid = rte_lcore_id();
    int qid = get_rxque(pktgen.l2p, lid, info->pid);
    int i;
    uint64_t cycles, jitter;

    for (i = 0; i < nb_pkts; i++) {

        if (pktgen_tst_port_flags(info, ENABLE_LATENCY_PKTS | SEND_RATE_PACKETS)) {
            tstamp_t *tstamp;
            tstamp = pktgen_tstamp_pointer(info, rte_pktmbuf_mtod(pkts[i], char *));

            if (tstamp->magic == 3617077065010936441) { //================= Replaced TSTAMP_MAGIC with expected 
    number from tstamp->magic
                latency_t *lat = &info->latency;

                tstamp->magic = 0; /* clear timestamp magic cookie */
                cycles        = (pktgen_get_time() - tstamp->timestamp);

                int latency_ms = ((cycles * Billion) / rte_get_tsc_hz()) / Million; //====================== New Line
                if(latency_ms > 0) { //====================== New Line
                    printf("Pkt number: %d",i); //====================== New Line
                    printf("   Latency (ms): %d", latency_ms); //====================== New Line
                    printf("   Rounded (ms): %d\n", ((latency_ms/10)*10)); //====================== New Line
                    add_to_hash_table(((latency_ms/10)*10));//====================== New Line
                } //====================== New Line

                if (tstamp->index != lat->expect_index) {
                    lat->expect_index = tstamp->index + 1;
                    lat->num_skipped++;
                    continue; /* Skip this latency packet */
                }
                lat->expect_index++;

                lat->num_latency_pkts++;

                if (pktgen_tst_port_flags(info, ENABLE_LATENCY_PKTS | SEND_RATE_PACKETS)) {
                    lat->running_cycles += cycles;

                    if (lat->min_cycles == 0 || cycles < lat->min_cycles)
                        lat->min_cycles = cycles;
                    if (lat->max_cycles == 0 || cycles > lat->max_cycles)
                        lat->max_cycles = cycles;

                    jitter = (cycles > lat->prev_cycles) ? cycles - lat->prev_cycles
                                                         : lat->prev_cycles - cycles;
                    if (jitter > lat->jitter_threshold_cycles)
                        lat->jitter_count++;

                    lat->prev_cycles = cycles;
                }
                if (pktgen_tst_port_flags(info, SAMPLING_LATENCIES)) {
                    /* Record latency if it's time for sampling (seperately per lcore) */
                    latsamp_stats_t *stats = &info->latsamp_stats[qid];
                    uint64_t now           = pktgen_get_time();

                    stats->pkt_counter++;
                    if (stats->next == 0 || now >= stats->next) {
                        if (stats->idx < stats->num_samples) {
                            stats->data[stats->idx] = (cycles * Billion) / rte_get_tsc_hz();
                            stats->idx++;
                        }

                        /* Calculate next sampling point */
                        if (info->latsamp_type == LATSAMPLER_POISSON) {
                            double next_possion_time_ns = next_poisson_time(info->latsamp_rate);

                            stats->next = now + next_possion_time_ns * (double)rte_get_tsc_hz();
                        } else        // LATSAMPLER_SIMPLE or LATSAMPLER_UNSPEC
                            stats->next = now + rte_get_tsc_hz() / info->latsamp_rate;
                    }
                }
            }
        }
    }
    }


But it gives high values for latency: 
![image](https://user-images.githubusercontent.com/64839037/227269118-1de98481-a4e4-4c17-ac90-c3b5f5c5d160.png)

Looking at the output it seems like the lower packet numbers have lower latency, while higher packet numbers has higher latency (even though it might not look like it based on the image). 

I also enabled both ports for latency with the following (but it didn't seem to do any difference):

    pktgen.latency(0, "enable");
    pktgen.latency(1, "enable");

Is the calculation I'm doing correct? If so why is the latency so high for a lot of packets?

**Comment by KeithWiles** [comment]
What is the processor you are using as it appears the MAGIC is wrong in the packet, but most likely the tstamp->magic is not pointing to the correct location in the packet. That would also explain the timestamp value being very high.

**Comment by vorbrodt** [comment]
Okay thanks, I will have to take a look at that. Is the calculation using `int latency_ms = ((cycles * Billion) / rte_get_tsc_hz()) / Million` correct?
