### ISSUE TITLE
pktgen_packet_rate() calculations on aarch64 impacted by TSC frequency

### ISSUE THREAD

**Issue by leearoberts** [pktgen/Pktgen-DPDK#173]
I am seeing issues with packet rate control/configuration when trying to run Pktgen-DPDK on a system
with an Ampere M128-30 processor.  While the processor cores operate at 3.0 GHz, the TSC frequency
is only 25 MHz.

On x86_64 systems, it seems that the TSC frequency is approximately the processor core frequency.
It’s close enough that programmers may take them as one and the same.  Consider the following code
from pktgen.c, in particular, lines 98-99:

  80 
  81 /**
  82  *
  83  * pktgen_packet_rate - Calculate the transmit rate.
  84  *
  85  * DESCRIPTION
  86  * Calculate the number of cycles to wait between sending bursts of traffic.
  87  *
  88  * RETURNS: N/A
  89  *
  90  * SEE ALSO:
  91  */
  92 
  93 void
  94 pktgen_packet_rate(port_info_t *info)
  95 {
  96     uint64_t wire_size = (pktgen_wire_size(info) * 8);
  97     uint64_t lk        = (uint64_t)info->link.link_speed * Million;
  98     uint64_t pps       = (((lk / wire_size) * info->tx_rate) / 100);
  99     uint64_t cpp       = (pps > 0) ? (pktgen.hz / pps) : pktgen.hz;
 100 
 101     info->tx_pps    = pps;
102     info->tx_cycles = ((cpp * info->tx_burst) * get_port_txcnt(pktgen.l2p, info->pid));
103 }
104

On line 98, the “packets per second” or “pps” is calculated.

On line 99, the “cycles per packet” or “cpp” is calculated.  If “pktgen.hz” is the processor core frequency,
this is essentially instructions per packet.  Since it’s being assigned to an integer, it is expected that
processing a packet requires several instructions (or cycles).  When I was debugging earlier on an x86_64
system with 1.7 GHz clock (Intel Xeon 8470N), it calculated “11” as the value for “cpp”.

However, with a 25 MHz clock for the TSC on the aarch64 system (Ampere M128-30), the value for “cpp” 
becomes zero due to the integer assignment, rather than a fractional cycle.

Here’s the report from “cpupower” regarding the processor frequency on the aarch64 system,
followed by debugger output showing that Pktgen-DPDK is seeing a frequency of 25000000:

[root@rl111 pktgen-dpdk-pktgen-23.03.0]# cpupower frequency-info
analyzing CPU 0:
  driver: cppc_cpufreq
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 1000 MHz - 3.00 GHz
  available cpufreq governors: conservative ondemand userspace powersave performance
  current policy: frequency should be within 2.00 GHz and 3.00 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency: 3.00 GHz (asserted by call to hardware)
[root@rl111 pktgen-dpdk-pktgen-23.03.0]# gdb ./Builddir/app/pktgen
GNU gdb (GDB) Red Hat Enterprise Linux 10.2-9.el9
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Builddir/app/pktgen...
(gdb) b pktgen_get_timer_hz
Breakpoint 1 at 0x4062fc: pktgen_get_timer_hz. (5 locations)
(gdb) run -c 3e -n 8 --proc-type auto --file-prefix pg -- -p 0x3 -P -m "[2:3].0, [4:5].1" -f test/set_seq.lua
Starting program: /home/lroberts/pktgen-dpdk-pktgen-23.03.0/Builddir/app/pktgen -c 3e -n 8 --proc-type auto --file-prefix pg -- -p 0x3 -P -m "[2:3].0, [4:5].1" -f test/set_seq.lua
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

*** Copyright(c) <2010-2023>, Intel Corporation. All rights reserved.
*** Pktgen  created by: Keith Wiles -- >>> Powered by DPDK <<<

[Detaching after vfork from child process 15935]
[Detaching after vfork from child process 15938]
[Detaching after vfork from child process 15939]
[Detaching after vfork from child process 15940]
EAL: Detected CPU lcores: 128
EAL: Detected NUMA nodes: 1
EAL: Auto-detected process type: PRIMARY
EAL: Detected shared linkage of DPDK
[New Thread 0xffffe60b2f40 (LWP 15941)]
EAL: Multi-process socket /var/run/dpdk/pg/mp_socket
[New Thread 0xffffe58a2f40 (LWP 15942)]
EAL: Selected IOVA mode 'VA'
EAL: VFIO support initialized
[New Thread 0xffffe5092f40 (LWP 15943)]
[New Thread 0xffffe4882f40 (LWP 15944)]
[New Thread 0xffffe4072f40 (LWP 15945)]
[New Thread 0xffffe3862f40 (LWP 15946)]
EAL: Probe PCI driver: mlx5_pci (15b3:101d) device: 0002:01:00.0 (socket 0)
EAL: Probe PCI driver: mlx5_pci (15b3:101d) device: 0002:01:00.1 (socket 0)
EAL: Probe PCI driver: mlx5_pci (15b3:101d) device: 0003:01:00.0 (socket 0)
EAL: Probe PCI driver: mlx5_pci (15b3:101d) device: 0003:01:00.1 (socket 0)
[New Thread 0xffffbf03cf40 (LWP 15947)]
TELEMETRY: No legacy callbacks, legacy socket not created
Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio

Thread 1 "pktgen" hit Breakpoint 1, pktgen_get_timer_hz () at ../app/pktgen.h:406
406         if (pktgen.flags & CLOCK_GETTIME_FLAG) {
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-28.el9_0.2.aarch64 libatomic-11.2.1-9.4.el9.aarch64 libgcc-11.2.1-9.4.el9.aarch64 libibverbs-58mlnx43-1.58112.aarch64 libnl3-3.5.0-10.el9.aarch64 libpcap-1.10.0-4.el9.aarch64 lua-libs-5.4.2-4.el9_0.3.aarch64 numactl-libs-2.0.14-8.el9.aarch64 openssl-libs-3.0.1-43.el9_0.aarch64 zlib-1.2.11-32.el9_0.aarch64
(gdb) n
410             return rte_get_timer_hz();
(gdb) n
411     }
(gdb) n
main (argc=8, argv=0xfffffffff330) at ../app/pktgen-main.c:492
492         scrn_create_with_defaults(pktgen.flags & ENABLE_THEME_FLAG);
(gdb) print pktgen.hz
$2 = 25000000
(gdb) b get_tsc_freq_arch
Breakpoint 2 at 0xfffff7d40a20
(gdb) quit
A debugging session is active.

        Inferior 1 [process 15932] will be killed.

Quit anyway? (y or n) y
[root@rl111 pktgen-dpdk-pktgen-23.03.0]#

Performing the same operation on an Intel Xeon 8470N processor, I found pktgen.hz to be 1700000000 (1.7 GHz),
which corresponds to the nominal speed of the processor.

**Comment by davidzengxhsh** [comment]
I am not sure why the handling of tx_next_cycle in pktgen_main_rxtx_loop and pktgen_main_tx_loop is different:
https://github.com/pktgen/Pktgen-DPDK/blob/20f0571bf3eca850a16c5a856b8fde1d27532059/app/pktgen.c#L1236-L1242
https://github.com/pktgen/Pktgen-DPDK/blob/20f0571bf3eca850a16c5a856b8fde1d27532059/app/pktgen.c#L1325-L1332

As the cpp and tx_cycles calculated by pktgen_packet_rate is always 0 with 25MHz TSC and 144.8Mpps (100GNIC),  it will always hit the "continue" in the pktgen_main_tx_loop(). And no packet send out.

**Comment by KeithWiles** [comment]
I do not see the reason per say as well and the continue can be removed. Please remove it and try it on your system, then let me know.

**Comment by davidzengxhsh** [comment]
Removing the continue works on my system. I will let @leearoberts to double confirm.

**Comment by leearoberts** [comment]
The removal of the "continue" only partially works.  When I use a configuration such as 
./build/app/pktgen -c 3e -n 8 --proc-type auto --file-prefix pg -- -p 0x3 -P -m "[2:3].0, [4:5].1" -f test/set_seq.lua
with one Rx and one Tx queue per port, it will now produce 64-byte packets at 100% rate specification.  However,
it continues to fail at 64-bytes, 100% rate with the following configuration:
./build/app/pktgen -c 3fe -n 8 --proc-type auto --file-prefix pg -- -p 0x3 -P -m "[2-3:4-5].0, [6-7:8-9].1" -f test/set_seq.lua
where I now have two Rx and two Tx queues per port.  This configuration works on x86_64.

**Comment by KeithWiles** [comment]
The only way to fix this issue is to come up with a calculation to allow for a much slower tick rate. A slow tick rate is going to be a problem for high speed interfaces as 10G, 40G, 100G, 200G and 400G interfaces. The problem is the software will have a problem sending packets at a given rate. The burst rate meaning the time between bursts of packets is below the ticks rate of the timer it will not be able to send traffic at a given rate.

If say the system tick rate is 10ms per tick and the burst rate needs to be 560ns between bursts to get a given rate it will not be able to achieve that rate. The burst rate is limit by the number of ticks per second. If the software needs to send at 50% link speed and the burst rate (a burst rate is the number of packets per second to achieve a percent rate) is faster then the tick rate we have a problem. I am not sure how this problem can be fixed with a slow tick rate.

Please suggest a solution to this problem as I do not have one.

**Comment by davidzengxhsh** [comment]
How about using clock_gettime? But "enable clock_gettime" on the fly has some issue. So need to add an option to enable it from the command. Here is the commit:
https://github.com/davidzengxhsh/Pktgen-DPDK-1/commit/08fc608cda9537ec4229b5e4329ef516f65fcea9

Will make a PR if this works.

**Comment by KeithWiles** [comment]
This seems reasonable to me. Make sure you test this in the case when using the CLI to enable/disable clock_gettime on the fly.
I did not see the reason for adding a command line option to enable clock_gettime, was something else not work as expected if it was not enabled at startup?

**Comment by davidzengxhsh** [comment]
@KeithWiles  the problem with "changing clock_gettime on the fly" is with the tx_cycles update.
https://github.com/pktgen/Pktgen-DPDK/blob/aeb281fbeb01568081a8e2d05fab17d7a04dd08d/app/pktgen.c#L1326

For example, with 25MHz tsc, the tx_cycle=0, the above if statement will always exected. Then "enable clock_gettime", the pktgen_packet_rate() will recalculate the  tx_cycle based on system clock and it is not 0. 
Next when "disable clock_gettime", the tx_cycle will have no chance to be updated. The enable_clock_gettime doens't has port_info as input, so couldn't reset it inside. 
The 
https://github.com/pktgen/Pktgen-DPDK/blob/aeb281fbeb01568081a8e2d05fab17d7a04dd08d/app/pktgen-cmds.c#L1393

**Comment by KeithWiles** [comment]
If in enable_clock_gettime() we set tx_cycles to zero for all port_info_t structures that should fix the problem, correct?

I do not expect anyone to enable or disable clock_gettime() while transmitting, but it can happen. The command line flag is reasonable to make sure it is in a given state at startup. Need to look at adding the enable/disable of clock_gettime() from the command files.

The save command needs to be updated to make sure the state is saved to be loaded on the next startup and loading of the command file. We can add this change as an enhancement in github issues, if you do not want to do this work.

I can also accept this PR and then add setting of the tx_cycles to 0 on enable/disable of clock_gettime() if you do not have the time for this at this time.
