### ISSUE TITLE
关于发送pcap文件，wireshark无法抓到正常数据包

### ISSUE THREAD

**Issue by yangtian0421** [pktgen/Pktgen-DPDK#174]
I selected Pktgen to replay and send my own packet and IPv6 pcap
OS：Ubuntu 18.04
DPDK：20.11.7
Pktgen：21.03.1
Pktgen can be started normally

Send IPv6 Packet （ Extension Header）
![image](https://user-images.githubusercontent.com/70353496/227815640-f8e58367-b325-4bdb-a849-bbd36b18142f.png)
![image](https://user-images.githubusercontent.com/70353496/227815681-a6c2d652-6b15-4d72-8020-c39c787005ca.png)

![image](https://user-images.githubusercontent.com/70353496/227815401-302d2c96-3a4f-4922-bd0f-5f7509fc4c03.png)

Wireshark
![image](https://user-images.githubusercontent.com/70353496/227815393-12a13e2d-9a2a-4a14-ade6-318f6016e847.png)

At first, I thought that Pktegn did not support IPv6 extension header format. Later, I changed to one without extension header, which still cannot be captured by wireshark，The same is true for sending IPv4 packets, perhaps something you've never seen before

I choose Pktgen because of its powerful sending speed. I want to use my own pcap file to replay and send on Pktgen. I hope you can help me solve the problem

Please let me know if there are other send instructions. I have tested TRex sent based on dpdk before, and the support for IPv6 header is insufficient. Please let me know if there are packet tools with faster send speed or other send tools based on DPDK

**Comment by KeithWiles** [comment]
From the data above it seems like the pcap file is not valid. The wireshark screen I assume is the pcap file loaded into wireshark. If that is the case then the pcap data is invalid and Pktgen is only sending what it thinks is a valid frame.

The ethernet type/length field 0xafc4 is an invalid type/length value for an ethernet frame. Please look into verifying the PCAP file is a valid set of packets.

**Comment by yangtian0421** [comment]
> 0xafc

谢谢你的答复，其实在我最初想法来看，Pktgen在我的项目中作为一个重放工具，应该是不会对数据包的格式进行鉴别，只负责发送
