### ISSUE TITLE
Displayed total Rx MBs does not match MBs fetched from within Lua script

### ISSUE THREAD

**Issue by vorbrodt** [pktgen/Pktgen-DPDK#177]
Trying to get the total Rx  MBs through using `pktgen.portStats(port, "port")`.  The issue I am having is that the results that  I am getting from `pktgen.portStats(port, "port")` does not match what is displayed in Pktgen.  

After running Pktgen for 10 seconds and then stopping it give me this display:

![image](https://user-images.githubusercontent.com/64839037/228837085-316eea9c-2009-4b47-865f-8b4bae4bfb68.png)

And through printing:

```
pktgen.portStats(port, "port")[0];
pktgen.portStats(port, "rate")[0];
pktgen.pktStats(port)[0];
```

I get these values:

```
{ ["opackets"] = 179228800,["ibytes"] = 248892828,["ipackets"] = 4444228,["obytes"] = 10754360064,["rx_nombuf"] = 0,["oerrors"] = 0,["imissed"] = 0,["ierrors"] = 0,} 
{ ["ipackets"] = 0,["obytes"] = 0,["mbits_rx"] = 0,["oerrors"] = 0,["opackets"] = 0,["ibytes"] = 0,["mbits_tx"] = 0,["pkts_tx"] = 0,["rx_nombuf"] = 0,["pkts_rx"] = 0,["ierrors"] = 0,["imissed"] = 0,} 
{ ["echo_pkts"] = 0,["tx_failed"] = 0,["ipv6_pkts"] = 0,["vlan_pkts"] = 0,["unknown_pkts"] = 0,["latency"] = { ["jitter_count"] = 8,["min_us"] = 97.4325,["jitter_threshold"] = 50,["min_cycles"] = 233838,["num_pkts"] = 8,["max_us"] = 979.71625,["num_skipped"] = 242,["avg_us"] = 0.0,["rate_ms"] = 1,["max_cycles"] = 2351319,["avg_cycles"] = 0,} ,["arp_pkts"] = 0,["dropped_pkts"] = 0,["mac_addr"] = 1A:66:25:07:7D:21,["ip_pkts"] = 4443898,} 
```

The calculation I am doing based on this to get the MBs is taking `ipackets = 4444228`, and calculating the total amount of data received in bits. That is `4444228*64*8=2275444736`, then divide to get MBs `2275444736/1000000=2275` which is quite far from the displayed value which is `2844`. `ibytes` does not either seem to contain the correct value.

Is there something missing from this calculation? If not, which one should be trusted?

**Comment by pktgen** [comment]
In the calculation 4444228*64*8=2275444736 using ipackets * frame_size * 8 gives total bits received. In the screen shot above I see 250 packets between the range or 128-255, I would expect you would need to account for these as well in the calculation as well.

Also remember the number of bits on the wire contains the inter-frame gap + frame-delimiter + preamble + FCS + (frame_size - FCS) in the case of 64 byte frames it would be 60 bytes.

``` c
    INTER_FRAME_GAP       = 12, /**< in bytes */
    START_FRAME_DELIMITER = 1,
    PKT_PREAMBLE_SIZE     = 7, /**< in bytes */
    PKT_OVERHEAD_SIZE =
        (INTER_FRAME_GAP + START_FRAME_DELIMITER + PKT_PREAMBLE_SIZE + RTE_ETHER_CRC_LEN),
```

For each frame_size (60) you need to add (frame_size * PKT_OVERHEAD_SIZE) * 8bits = frame_bit_size, (frame_bit_size * ipackets) = total_bits, assuming all of the packets are the same size.

**Comment by vorbrodt** [comment]
By my calculation this would mean `PKT_OVERHEAD_SIZE=24`,  `frame_bit_size=(60*24)*8=11520`, which would then result in `total_bits=11520*4444228=51197506560` dividing this by `8*1000000` should give total MBs. `51197506560/8000000=6400 MBs`, this value seem to be neither close to `2275444736 bits` or `2844 MBs`.

**Comment by KeithWiles** [comment]
Sorry, mis-type `(frame_size + PKT_OVERHEAD_SIZE) * 8bits = frame_bit_size` should be plus not times `(60 + 24) * 8 = 672 bits`  per frame. Total bits `672 * 4444228 = 2986521216 bits over 10 seconds or 298652121.6Bits per second or 298.6 Mbits/s`.

BTW, I get the ibytes/ipackets/... directly from the NIC hardware.

In the code I use: `((ipackets * pkt_overhead) + ibytes) * 8) = ibitstotal` over time, then take using 10 seconds in your case `(ibitstotal/10s) / Million=Mbits`. The reason I use ibytes is to account for different size frames, in this case they are all 64 byte frames.

The value 2844 is in MBytes not Mbits over 10 seconds, which would be 284.4 Mbytes per second or
`((284.4 * 1000000) * 8)/1000000 = 2275.2Mbits per second or 2.276 Gbits`

`pktgen.portSizes(port)` Will return the number of packets per size or type using the total ippackets could be an issue if you are just wanting the 64 Byte frames and the other 250 packets were not in this 10s run.

The number of 64 bytes frames are shown as 4443648, I would have expected the value to be the same with `(4444228 - 250) should equal 4443978 64 packets, going to have to look at it more. The ipackets value come from hardware and sometimes are some hardware they do not count all of the RX frames when errors or other problems with the packets happen.

Hopefully I have the math right now.
