### ISSUE TITLE
Exporting results

### ISSUE THREAD

**Issue by tbarbette** [pktgen/Pktgen-DPDK#182]
Hi all,

It is not very clear to me how I can export the results from Pktgen-DPDK. Eg I'd like to "extract" the throughput achieved at the end of the test.

Is that possible?

Thanks !

**Comment by pktgen** [comment]
Using lua is the only way extract data from pktgen. The command line method via -f is just run and forget type commands. The lua scripting or the -G using using lua are the only ways to extract data.

**Comment by tbarbette** [comment]
Ok. Is there some documentation about the lua methods exported by lua? Eg pktgen.what should I call to get the throughput statistics? I found pktgen.portStats(0, "port") in some example, but I only have ipackets there. I looked around readthedocs but could not find an API description.

**Comment by pktgen** [comment]
Going to have look at the scripts and code in lpktgenlib.c the stats have two type stats and rates. Run some of the examples and you should see what you want.

**Comment by tbarbette** [comment]
Ok there is one reference to pktgen.portStats for "rate". But then one needs to use prints to see what are the fields, then find the one of interest... Some API description would not be overrated.

But I got what I need ! Thanks !
