### ISSUE TITLE
uint16 overflow in port range wrapping causes it to stuck.

### ISSUE THREAD

**Issue by blaa** [pktgen/Pktgen-DPDK#183]
It caught us by surprise that in certain conditions the port wrapping fails and instead of scanning through the full port range it sticks to the max port.
Set min to 1, max to 65535 and inc to 1:

https://github.com/pktgen/Pktgen-DPDK/blob/34d1e6bf5b4c67e08ae02d8d019081a262c2a111/app/pktgen-range.c#L71
```
if (unlikely(range->src_port_inc != 0)) {
    uint16_t sport = pkt->sport; // 65535
    sport += range->src_port_inc; // Overflow -> 0
    if (sport < range->src_port_min) // Oops, that's below 1.
        sport = range->src_port_max; // Back to 65535.
    if (sport > range->src_port_max)
        sport = range->src_port_min;
    pkt->sport = sport;
} else
```

Either this behaviour should be documented, or if checking for `<min` should check if inc is negative as well.

Similarly 0-65534 and -1 - but that combination is less likely to occur.

**Comment by KeithWiles** [comment]
That is a problem for sure. Need to handle the overflow correctly. Maybe something like this and the compiler may complain a bit and need casting, I have not tried the change.

```
if (unlikely(range->src_port_inc != 0)) {
    uint32_t sport = pkt->sport; // 65535
    sport += range->src_port_inc; // sport can not overflow 65536
    if (sport < range->src_port_min) // sport will be 65536
        sport = range->src_port_max; // Back to 65535.
    if (sport > range->src_port_max)
        sport = range->src_port_min;
    pkt->sport = sport;
} else
```

I did not try this, but it seems reasonable. Please have a look and verify. If that works I can add the change or you can submit a Pull Request. Thanks

**Comment by blaa** [comment]
Seems like a pretty ok fix. I thought about increasing the pkt->sport bitwidth but that should be enough to fix this problem. 

I'll try to test it. We have older version on the environment though (same code in this place though).

**Comment by blaa** [comment]
Hm. uint32_t, 0-65534, -1:
```
if (unlikely(range->src_port_inc != 0)) {
    uint32_t sport = pkt->sport; // 0
    sport += range->src_port_inc; // Overflow -> INT32_MAX
    if (sport < range->src_port_min) // Nah
        sport = range->src_port_max; 
    if (sport > range->src_port_max) // YES
        sport = range->src_port_min; // 0.
    pkt->sport = sport;
} else
```
I'd suggest int32_t - I don't see a problem (yet) with it.

**Comment by KeithWiles** [comment]
The size of pkt->sport and range->src_port_inc are uint16_t values, how can sport become -1 or overflow a int32_t to -1. The range->src_port_inc is limited to 0 - 64 then the max value of sport is (65535 + 64).

**Comment by blaa** [comment]
Ah, if the inc is unsigned then that's a non-issue. True. I'll update the PR. It builts - at least.

**Comment by blaa** [comment]
BTW, our fix will change the behaviour with greater increments; eg. Starting from 1, inc 40: you would reach 65521 and overflow to 25. Then, different ports would be reached on a second pass. Currently we will force starting from 1 on each overflow and scan the same ports.

I don't think it's a real concern though. To get the previous behaviour one would have to use modulo division or additional if checks. So for now, I'll close this issue, thanks. ;)
