### ISSUE TITLE
No free hugepages reported

### ISSUE THREAD

**Issue by grantcurell** [pktgen/Pktgen-DPDK#184]
![image](https://user-images.githubusercontent.com/35169230/48972124-ebf63600-efe9-11e8-9d59-00b3cfc76e7b.png)

pktgen says there are no free huge pages available, but according to dpdk's utility tool there are free huge pages available. What am I missing?

![image](https://user-images.githubusercontent.com/35169230/48972132-1942e400-efea-11e8-8f9f-ddd16e637a4f.png)

**Comment by pktgen** [comment]
Sent from my iPhone

> On Nov 24, 2018, at 1:09 PM, Grant Curell <notifications@github.com> wrote:
> 
> 
> pktgen says there are no free huge pages available, but according to dpdk's utility tool there are free huge pages available. What am I missing?
> 

It maybe you have option -m or —socket-mem on the command line which limits the memory to allocate. In the 18.08 and 18.11 releases of dpdk you can drop the -m and —socket-men options. 

If not then I need the command line to review.

**Comment by grantcurell** [comment]
> Sent from my iPhone
> On Nov 24, 2018, at 1:09 PM, Grant Curell ***@***.***> wrote: pktgen says there are no free huge pages available, but according to dpdk's utility tool there are free huge pages available. What am I missing?
> It maybe you have option -m or —socket-mem on the command line which limits the memory to allocate. In the 18.08 and 18.11 releases of dpdk you can drop the -m and —socket-men options. If not then I need the command line to review.
> […](#)
> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

This one might have been stupid user syndrome. I'm still working on it - I'll get back to you.

**Comment by grantcurell** [comment]
@pktgen here's what I'm currently using: `./app/x86_64-native-linuxapp-gcc/app/pktgen -l 0-8 -n 3 --proc-type auto -- -P -m "[1:3].0, [2:4].1, [5:7].2, [6:8].3" -s 0:/root/test_pcap.pcap`

**Comment by grantcurell** [comment]
And here's my memory info:

```
MemTotal:       528073448 kB
MemFree:        521161280 kB
MemAvailable:   520690264 kB
Buffers:            2252 kB
Cached:           781680 kB
SwapCached:            0 kB
Active:           692184 kB
Inactive:         173660 kB
Active(anon):      89480 kB
Inactive(anon):     9992 kB
Active(file):     602704 kB
Inactive(file):   163668 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 4 kB
Writeback:             0 kB
AnonPages:         82328 kB
Mapped:            28468 kB
Shmem:             17220 kB
Slab:             265156 kB
SReclaimable:     100376 kB
SUnreclaim:       164780 kB
KernelStack:       12400 kB
PageTables:         4548 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    262985076 kB
Committed_AS:     293512 kB
VmallocTotal:   34359738367 kB
VmallocUsed:     1160856 kB
VmallocChunk:   34089986044 kB
HardwareCorrupted:     0 kB
AnonHugePages:     12288 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:    1027
HugePages_Free:      944
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      307992 kB
DirectMap2M:     6916096 kB
DirectMap1G:    531628032 kB
```

**Comment by pktgen** [comment]
How big is the pcap file?

**Comment by grantcurell** [comment]
> How big is the pcap file?
> […](#)
> Sent from my iPhone
> On Nov 25, 2018, at 9:40 AM, Grant Curell ***@***.***> wrote: @pktgen here's what I'm currently using: ./app/x86_64-native-linuxapp-gcc/app/pktgen -l 0-8 -n 3 --proc-type auto -- -P -m "[1:3].0, [2:4].1, [5:7].2, [6:8].3" -s 0:/root/test_pcap.pcap — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

[root@trafficgenerator pktgen-dpdk]# ls -alh /root/test_pcap.pcap
-rw-r--r--. 1 root root 363M Oct 25 07:18 /root/test_pcap.pcap

It definitely has something to do with that size because your pcap: pcap/large.pcap works, but mine does not.

[root@trafficgenerator pktgen-dpdk]# ls -alh pcap/large.pcap
-rw-r--r--. 1 root root 6.9M Nov 22 17:35 pcap/large.pcap

**Comment by grantcurell** [comment]
When I use my PCAP I get on startup:
![image](https://user-images.githubusercontent.com/35169230/48981353-ddffee00-f099-11e8-9fa1-fba830473bfa.png)

**Comment by pktgen** [comment]
thanks
