### ISSUE TITLE
Question about output from pktgen latency sampler

### ISSUE THREAD

**Issue by HikaruYam** [pktgen/Pktgen-DPDK#186]
Hello,

I recently used the latency sampler feature in pktgen, and the output generated a log similar to the attached image.

What does this output mean? I'm unsure about the units, and I'm not sure how to interpret the results. Can you please provide some guidance?

Thank you.
<img width="421" alt="スクリーンショット 2023-04-27 201534" src="https://user-images.githubusercontent.com/71537797/234846627-3713f6eb-e1e2-4ab0-83cb-3d011f5192b0.png">

**Comment by KeithWiles** [comment]
I did not author this code, but it appears it is the number of CPU cycles per second. In file app/pktgen.c around line 360.

We have this line:
`  cycles        = (pktgen_get_time() - tstamp->timestamp);`
`  stats->data[stats->idx] = (cycles * Billion) / rte_get_tsc_hz();`

Cycles is the number of cycles elapsed from the timestamp and current time. It is multiplied by a Billion is to make sure the value is larger then the number of cycles in a second. As this code does integer math we need to make sure the calculation does not become zero. A CPU cycles is the time per tick of the clock, which on Intel CPUs is based on the CPU clock speed 2.4, 2.7, 3.0 GHz need to look at your clock speed.

This value should have been normalized to the micro-seconds, but it does not appear to be.

from the app/pktgen-latency.c file. The sampler was not updated.
```
// cycles is the number of cycles between timestamp packets
// per_cycle is (1.0 / pktgen.hz) where hz is the number of clock ticks per second.
static inline double
cycles_to_us(uint64_t cycles, double per_cycle)
{
    return (cycles == 0) ? 0.0 : (per_cycle * (double)cycles)*Million;
}
```
Which version of pktgen are you using? A fair amount of changes to latency measurement is being worked in the fix-latency-bug branch on github. The sampler code was not changed in that branch. Most developers are using Lua to grab the latency stats and not using the sampler code. I will have to rework the sampler code to make it easier to consume.

You can find a latency lua scripts/latency-samples.lua, need to build Pktgen with Lua enabled. `make clean buildlua` Then using the command line in pktgen to load the lua script `script scripts/latency-samples.lua`

Plus you need to install Lua package.

**Comment by HikaruYam** [comment]
I am using version 23.03 of pktgen.
I understand about the sampler code. I will try using the Lua script.
Thank you very much.
