### ISSUE TITLE
Send rate ？

### ISSUE THREAD

**Issue by yangtian0421** [pktgen/Pktgen-DPDK#187]
How do I set the send rate after startup

**Comment by KeithWiles** [comment]
set <portlist> rate <value>

Portlist is the list of ports to set the portlist can not have spaces i.e.,
`0` this sets port 0 only.
`1,3-4` this sets ports 1, 3 and 4
`all` this sets all ports to the value

The value is a decimal number greater then zero and not greater than 100. Decimal numbers are allowed 0.005 or 10.6 or 99.999

Type `help` at the pktgen command line prompt to see the complete set of commands.
