### ISSUE TITLE
How to use a dpkd driven network card to send data packets to a regular network card

### ISSUE THREAD

**Issue by CP3164094** [pktgen/Pktgen-DPDK#188]
At first, I wanted to verify the order in which dpdk sends and receives packets, but the program I wrote myself couldn't receive the packets.
So the leader asked me to verify the communication between the regular network card and the DPdK network card instead.

**Comment by KeithWiles** [comment]
I am not sure I understand your question. For a standard NIC card Pktgen must use the NICs MAC address as the destination address in the frame. For Pktgen to receive a Ethernet frame the sender can send to the Pktgen NIC MAC address or make sure that Pktgen is using the -P command to set the port into promiscuous mode.

**Comment by CP3164094** [comment]
perfect! 3q!
