### ISSUE TITLE
No latency meassurements

### ISSUE THREAD

**Issue by VAPuerta** [pktgen/Pktgen-DPDK#189]
Hi!

I am new to dpdk-pktgen and I am trying to use it to measure latency of a simple network. I am using two ports for pktegn, one sending and the other receiving, and in another machine a basic DPDK forwarder that send back the packets to the Packet Generator. 

The point is that i send and receive packets, but in the latency page, the latency measure don't change, is always 10ms, even if I connect the the tx port to the rx port. 

My default.cfg file that i execute for run pktegn is the next: 

description = 'A Pktgen default simple configuration'

--Setup configuration
setup = {
    'exec': (
	'sudo', '-E'
        ),

    'devices': (
	    '05:00.0', '04:00.0'
	    ),
    # UIO module type, igb_uio, vfio-pci or uio_pci_generic
    'uio': '-b igb_uio'
    }

-- Run command and options
run = {
    'exec': ('sudo', '-E'),

    # Application name and use app_path to help locate the app
    'app_name': 'pktgen',

    # using (sdk) or (target) for specific variables
    # add (app_name) of the application
    # Each path is tested for the application
    'app_path': (
		'./usr/local/bin/%(app_name)s',
		'/usr/local/bin/%(app_name)s'
        ),

	'cores': '0-4',
	'nrank': '4',
	'proc': 'auto',
	'log': '7',
	'prefix': 'pg',

	'blocklist': (
		#'03:00.0', '05:00.0',
		#'81:00.0', '84:00.0'
		),
	'allowlist': (
		'05:00.0', '04:00.0',
		
		),

	'opts': (
		'-v',
		'-T',
		'-P',
		),
	'map': (
		'[1:2].0',
		'[3:4].1'
		),

	'theme': 'themes/black-yellow.theme',
	#'shared': '/usr/local/lib/x86_64-linux-gnu/dpdk/pmds-21.1'
	}

Also I am using the latest versions of pktgen and DPDK. The comans in pkteg that i used are:
  35: set 0 size 128
  36: set 0 dst mac 04:42:1a:94:e2:89
  37: enable 0 latency
  38: enbale 1 latency
  39: enable 1 latency
  40: start 0
  41: page latency
  42: stop 0

The Latency page looks like this:

![image](https://github.com/pktgen/Pktgen-DPDK/assets/128382504/ad85a4d2-bcfe-49f8-b2d4-c77a49850fdd)

Also these are the model of the NICs:

![image](https://github.com/pktgen/Pktgen-DPDK/assets/128382504/127911a1-0307-4077-b15c-f339fde96d96)

Also supports time stamping:
![image](https://github.com/pktgen/Pktgen-DPDK/assets/128382504/af49eb6c-29df-41c0-b87a-60fcd30fc7c6)

I don´t know if I am doing something wrong...

Thanks!

**Comment by KeithWiles** [comment]
You are looking at the wrong value the 'Rate (ms)' line is the rate at which latency packets are sent every 10ms.

The "Cycles/Min" line is the minumum number of cycles or (20.32us) The average is (24.48 us), Max is 31.90us

**Comment by VAPuerta** [comment]
Ahh, Okey! Thanks so much! 

And another question, is there any way to configure pktegn for send packets in a interval? for example: send a brust of packets every 30ms. 

Thanks!

**Comment by KeithWiles** [comment]
Not directly, but you can set the percent rate and the burst size. Currently Pktgen does send all packets in burst of packets every burst interval of N number of packets based on burst size. Setting the `set <portlist> rate <percent>` and `set <portlist> burst N` you can get close to a burst rate. The rate value can be a decimal number `0.001` rate.

If you change the burst rate to be greater than the latency rate, the latency packets will be sent every TX burst rate. If you set it to 30ms then you need to change the latency rate to 30ms as it will become 30ms anyway.

**Comment by VAPuerta** [comment]
Thanks a lot!

So for instance change the latency to 30 ms, the command is also: set <portlist> latency <value>

I don´t see it in the documentation.

**Comment by KeithWiles** [comment]
Try `latency <portlist> rate N` Where N is in ms.

**Comment by VAPuerta** [comment]
Okey, thanks a lot!

I really I appreciate it!

**Comment by VAPuerta** [comment]
latency <portlist> rate N, is invalid but it seem that it can be changed into the latencysampler?

![image](https://github.com/pktgen/Pktgen-DPDK/assets/128382504/c68281ef-72c7-4976-8b3d-4c137e82dfa2)

**Comment by KeithWiles** [comment]
Using `latency 0 rate 32` works for me. Check and make sure you are using the latest version on the fix-latency-bug branch  in this repo.

**Comment by VAPuerta** [comment]
Hi, for my this command is not working. I downloaded de repository a week ago, so I think that is the latest version. 
![image](https://github.com/pktgen/Pktgen-DPDK/assets/128382504/2d758fce-b7e7-43a5-bb07-204467c6c81e)

Instead <set latency rate 20> works but don't change in the GUI, it still says 10

**Comment by KeithWiles** [comment]
Did you checkout the branch named `fix-latency-bug` as it has not be merge into main yet and it works here plus it has been synced to the repo under that branch. I need to find some time to merge this into main. I also updated the version to 23.05.0

**Comment by VAPuerta** [comment]
Okey, thanks! I will check!
