### ISSUE TITLE
TCP checksum incorrect when using latency test.

### ISSUE THREAD

**Issue by lenky0401** [pktgen/Pktgen-DPDK#189]
dpdk: 17.11.4
pktgen: 3.4.8

app/x86_64-native-linuxapp-gcc/pktgen -c 0x1f -n3 -- -T -P -m "[1:3].0,[2:4].1"

Pktgen:/> page latency
Pktgen:/> enable all latency
Pktgen:/> set all rate 1
Pktgen:/> set all size 96
Pktgen:/> set all jitter 17
Pktgen:/> clr
Pktgen:/> start 0

using wireshark to capture traffic and i seeing all of packets with incorrect TCP checksums.

 why?

**Comment by pktgen** [comment]
Make sure that wireshark is not being effected by checksum offloads. If I remember correctly I saw the same problem and it came from the some type of offload issue. 

The code creates the checksum for tcp at start time and it should not change.

**Comment by lenky0401** [comment]
thx  :)
