### ISSUE TITLE
 Packet loss and Count on Rx port not same as Tx port on using pktgen-DPDK

### ISSUE THREAD

**Issue by bkrakesh** [pktgen/Pktgen-DPDK#19]
Hello,

    Observed packet loss in Rx Side on using Pktgen-DPDK when configured for various Burst Size (the packet count displayed on pktgen shell is not same as transmit count).

    I am Using linux-3.10.63 with NIC card "10-Gigabit X540-AT2" with two ports configured as Tx and Rx. Is there any way to create the setup to get the zero packet loss in the Rx port; such that there is surity on X no. of transmitted packet from tx_port  get received on rx_port w/o any packet loss?

    pktgen command with options and  results generated as follows,

    ./app/build/pktgen -c 1f -n 4 --proc-type auto --socket-mem 512 --file-prefix pg -- -T -P -m "[1:3].0, [2:4].1"  -l pktgen.log

    \ Ports 0-1 of 2  ** Main Page **  Copyright (c) <2010-2014>, Wind River Systems, Inc. All rights reserved. Powered by Intel® DPDK
      Flags:Port    :  P-------------:0  P-------------:1
    Link State      :      <UP-10000-FD>      <UP-10000-FD>                                          ---TotalRate---
    Pkts/s  Rx      :                  0            822372                                                  822372
            Tx      :            822373                  0                                                  822373
    MBits/s Rx/Tx  :            0/10000            10000/0                                              10000/10000
    Broadcast      :                  0                  0
    Multicast      :                  0                  0
      64 Bytes      :                  0                  0
      65-127        :                  0                  0
      128-255      :                  0                  0
      256-511      :                  0                  0
      512-1023      :                  0                  0
      1024-1518    :                  0          60023855
    Runts/Jumbos    :                0/0                0/0
    Errors Rx/Tx    :                0/0                0/0
    Total Rx Pkts  :                  0          59201796
          Tx Pkts  :          59214194                  0
          Rx MBs    :                  0            719893
          Tx MBs    :            720044                  0
    ARP/ICMP Pkts  :                0/0                0/0
                    :
    Tx Count/% Rate :      Forever/100%      Forever/100%
    PktSize/Tx Burst:            1500/32            1500/32
    Src/Dest Port  :          1234/5678          1234/5678
    Pkt Type:VLAN ID:      IPv4/TCP:0001      IPv4/TCP:0001
    Dst  IP Address :        192.168.1.1        192.168.0.1
    Src  IP Address :    192.168.0.1/24    192.168.1.1/24
    Dst MAC Address :  d8:9d:67:ee:55:f1  d8:9d:67:ee:55:f0
    Src MAC Address :  d8:9d:67:ee:55:f0  d8:9d:67:ee:55:f1
    -- Pktgen Ver:2.7.7(DPDK-1.7.1) -------------------------------------------------------------------------------------
    Pktgen> set 1 size 256
    Pktgen> start 1
    Pktgen> start 0
    Pktgen> rst
    Pktgen> set 1 size 512
    Pktgen> set 0 size 512
    Pktgen> start 1
    Pktgen> start 0
    Pktgen> rst
    Pktgen> set 0 size 1500
    Pktgen> set 1 size 1500
    Pktgen> start 1
    Pktgen> start 0
    Pktgen>

Thanks,

**Comment by pktgen** [comment]
Please try the version on dpdk.org
