### ISSUE TITLE
lua dependency in meson.build should be changed from lua5.3 to lua-5.3 for lua enabled compilation on Redhat/Centos 7.x

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#19]
Dear Keith,

I am compiling pktgen with lua enabled on RHEL/Centos 7.7 but it fails as shown below, I updated it from lua5.3 to lua-5.3 in meson.build to make it work as per ldconfig output, lua is installed using standard rpm downloaded via yum.

[root@cloud Pktgen-DPDK]# ldconfig -p|grep lua
	liblua-5.3.so (libc6,x86-64) => /lib64/liblua-5.3.so
	liblua-5.1.so (libc6,x86-64) => /lib64/liblua-5.1.so

[root@cloud Pktgen-DPDK]# meson -Dbuildtype=debug Builddir
The Meson build system
Version: 0.47.2
Source dir: /home/ravi/Pktgen-Dev/Pktgen-DPDK
Build dir: /home/ravi/Pktgen-Dev/Pktgen-DPDK/Builddir
Build type: native build
Program cat found: YES (/bin/cat)
Project name: pktgen
Project version: 20.08.0-rc1
Native C compiler: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports arguments -Wno-pedantic -Wpedantic: YES
Compiler for C supports arguments -Wcast-qual: YES
Compiler for C supports arguments -Wdeprecated: YES
Compiler for C supports arguments -Wformat-nonliteral: YES
Compiler for C supports arguments -Wformat-security: YES
Compiler for C supports arguments -Wmissing-declarations: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wnested-externs: YES
Compiler for C supports arguments -Wold-style-definition: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Wsign-compare: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Wundef: YES
Compiler for C supports arguments -Wwrite-strings: YES
Compiler for C supports arguments -Wno-address-of-packed-member -Waddress-of-packed-member: NO
Compiler for C supports arguments -Wno-packed-not-aligned -Wpacked-not-aligned: NO
Compiler for C supports arguments -Wno-missing-field-initializers -Wmissing-field-initializers: YES
Found pkg-config: /bin/pkg-config (0.27.1)
Native dependency libbsd found: YES 0.8.3
Native dependency libdpdk found: YES 20.08.0
Message: ************** LUA is enabled
Dependency lua5.3 found: NO

**meson.build:84:8: ERROR:  C library 'lua5.3' not found**

A full log can be found at /home/ravi/Pktgen-Dev/Pktgen-DPDK/Builddir/meson-logs/meson-log.txt

**Comment by pktgen** [comment]
What is the name of the lua pkg-config file. In Ubuntu it is called lua5.3pc or lua53.pc or lua-5.3.pc

It is possible Centos does not provide a .pc file or that put it in a do place the pkg-confit can not find.

**Comment by Ravi-t** [comment]
Please find the lua pkg-confilg file name

**/usr/lib64/pkgconfig/lua-5.3.pc**
