### ISSUE TITLE
Not able to generate VLAN tagged traffic

### ISSUE THREAD

**Issue by VAPuerta** [pktgen/Pktgen-DPDK#190]
Hi again!

I am trying to send traffic tagged with a VLAN_id. The configuration that I have set is as follows:

![Screenshot from 2023-05-30 16-48-40](https://github.com/pktgen/Pktgen-DPDK/assets/128382504/bd7fe720-bcd0-4b4a-813c-78bc38424a4c)

I don´t know if I am missing something. When i capture traffic with Wiresshar, I the packet does not have any VLAN field. I show you a screenshot:

![image](https://github.com/pktgen/Pktgen-DPDK/assets/128382504/bedf6e2c-0e86-49c0-bff4-73d3886807e5)

As you see there is not anything related to VLAN.

Thanks in advance! Kind regards! 

-Victor Puerta

**Comment by KeithWiles** [comment]
I do not see anything wrong in the command lines except `set 1 burst 0.5` the burst can only be whole numbers as it is the number of packets to send per burst. When set the `set 1 rate 0.5` is appears to be set to 0.01 instead.

I will have to look at this problem when I find the time, sorry I do not have much time this week except maybe next weekend.

**Comment by VAPuerta** [comment]
Yes, I have set the <burst to 1> in the next line. I have noticed it and fixed as is shown in the picture.

I appreciate, it! Thanks!

**Comment by VAPuerta** [comment]
Hi again! 

Any solution to this? 

PD: I know that you are bussy and I dond't want to disturb. I only wanted to know if you have had time to chek it!  Thanks!!!

**Comment by pktgen** [comment]
Sorry for the delay many things going on. I tried duplicating this problem and I do see VLAN packets.

![Screenshot 2023-06-12 at 8 01 59 AM](https://github.com/pktgen/Pktgen-DPDK/assets/4572170/6482087d-8845-46bb-9fce-a64814f3a16b)

It seems I can not reproduce the problem. I used the same commands to get the result.

**Comment by pktgen** [comment]
Please upgrade to the latest version as that is the version I am using, which I just updated a couple days ago.

**Comment by VAPuerta** [comment]
I have tried with last version and its working now! Thanks a lot!

One last question, as I have seen in the code, the way that pktgen meassure the latency is not with hardware timestamping. It uses the clock of the CPU, ist't it?

Thanks!

**Comment by KeithWiles** [comment]
Correct not all hardware is able to timestamp packets and I have to use the CPU cycles counter (rdtsc) which is a timestamp time stamp counter for the CPU.

**Comment by VAPuerta** [comment]
Ok, perfect! Thanks a lot! I reaally apreciate your help!
