### ISSUE TITLE
gcc 9.1 support？

### ISSUE THREAD

**Issue by jerrychunfenghao** [pktgen/Pktgen-DPDK#2]
Hi, 

I upgrade the gcc to 9.1. 
gcc version 9.1.0 (Ubuntu 9.1.0-2ubuntu2~18.04)
Kernel version
5.0.0-32-generic #34~18.04.2-Ubuntu
DPDK 19.08
My platform is aarch64.
But when compiling the pktgen-dpdk 19.10.0, warnings report and the test can't be executed successfully. 

errors:
CC lua_dpdk.o
In file included from /root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ethdev.h:160,
                 from /root/pktgen-19.10.0/lib/lua/lua_dpdk.c:11:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_same_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:84:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
   84 |  const unaligned_uint16_t *w1 = (const uint16_t *)ea1;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:85:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
   85 |  const unaligned_uint16_t *w2 = (const uint16_t *)ea2;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_zero_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:102:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  102 |  const unaligned_uint16_t *w = (const uint16_t *)ea;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_broadcast_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:149:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  149 |  const unaligned_uint16_t *ea_words = (const unaligned_uint16_t *)ea;
      |  ^~~~~
  CC lua_pktmbuf.o
In file included from /root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ethdev.h:160,
                 from /root/pktgen-19.10.0/lib/lua/lua_pktmbuf.c:10:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_same_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:84:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
   84 |  const unaligned_uint16_t *w1 = (const uint16_t *)ea1;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:85:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
   85 |  const unaligned_uint16_t *w2 = (const uint16_t *)ea2;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_zero_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:102:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  102 |  const unaligned_uint16_t *w = (const uint16_t *)ea;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_broadcast_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:149:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  149 |  const unaligned_uint16_t *ea_words = (const unaligned_uint16_t *)ea;
      |  ^~~~~
  CC lua_vec.o
In file included from /root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ethdev.h:160,
                 from /root/pktgen-19.10.0/lib/lua/lua_vec.c:10:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_same_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:84:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
   84 |  const unaligned_uint16_t *w1 = (const uint16_t *)ea1;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:85:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
   85 |  const unaligned_uint16_t *w2 = (const uint16_t *)ea2;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_zero_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:102:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  102 |  const unaligned_uint16_t *w = (const uint16_t *)ea;
      |  ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_broadcast_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:149:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
  149 |  const unaligned_uint16_t *ea_words = (const unaligned_uint16_t *)ea;
      |  ^~~~~

Thanks
Jerry

**Comment by pktgen** [comment]
I had to edit the rte_ethdev.h and remove the attribute around the structure rte_ether_addr.

Out of town this week so repo sea will be slow.
Sent from my iPhone

On Nov 11, 2019, at 10:25 PM, jerrychunfenghao <notifications@github.com> wrote:

﻿

Hi,

I upgrade the gcc to 9.1.
gcc version 9.1.0 (Ubuntu 9.1.0-2ubuntu218.04)
Kernel version
5.0.0-32-generic #3418.04.2-Ubuntu
DPDK 19.08
My platform is aarch64.
But when compiling the pktgen-dpdk 19.10.0, warnings report and the test can't be executed successfully.

errors:
CC lua_dpdk.o
In file included from /root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ethdev.h:160,
from /root/pktgen-19.10.0/lib/lua/lua_dpdk.c:11:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_same_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:84:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
84 | const unaligned_uint16_t *w1 = (const uint16_t *)ea1;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:85:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
85 | const unaligned_uint16_t *w2 = (const uint16_t *)ea2;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_zero_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:102:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
102 | const unaligned_uint16_t *w = (const uint16_t *)ea;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_broadcast_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:149:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
149 | const unaligned_uint16_t *ea_words = (const unaligned_uint16_t *)ea;
| ^~~~~
CC lua_pktmbuf.o
In file included from /root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ethdev.h:160,
from /root/pktgen-19.10.0/lib/lua/lua_pktmbuf.c:10:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_same_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:84:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
84 | const unaligned_uint16_t *w1 = (const uint16_t *)ea1;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:85:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
85 | const unaligned_uint16_t *w2 = (const uint16_t *)ea2;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_zero_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:102:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
102 | const unaligned_uint16_t *w = (const uint16_t *)ea;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_broadcast_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:149:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
149 | const unaligned_uint16_t *ea_words = (const unaligned_uint16_t *)ea;
| ^~~~~
CC lua_vec.o
In file included from /root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ethdev.h:160,
from /root/pktgen-19.10.0/lib/lua/lua_vec.c:10:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_same_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:84:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
84 | const unaligned_uint16_t *w1 = (const uint16_t *)ea1;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:85:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
85 | const unaligned_uint16_t *w2 = (const uint16_t *)ea2;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_zero_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:102:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
102 | const unaligned_uint16_t *w = (const uint16_t *)ea;
| ^~~~~
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h: In function ‘rte_is_broadcast_ether_addr’:
/root/dpdk-19.08/arm64-armv8a-linuxapp-gcc/include/rte_ether.h:149:2: warning: converting a packed ‘const struct rte_ether_addr’ pointer (alignment 1) to a ‘unaligned_uint16_t’ {aka ‘const short unsigned int’} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]
149 | const unaligned_uint16_t *ea_words = (const unaligned_uint16_t *)ea;
| ^~~~~

Thanks
Jerry
