### ISSUE TITLE
pktgen_main_receive receive from the wrong queue.

### ISSUE THREAD

**Issue by chanwai1219** [pktgen/Pktgen-DPDK#20]
hi,  in function pktgen_main_receive, when pid is not equal to idx, this function may receive from the wrong queue;

for example, the starting args like this:
./app/build/pktgen -c 1f -n 4 -- -p 3 -m 1.0,2.2,3.2

diff --git a/dpdk/examples/pktgen/app/pktgen.c b/dpdk/examples/pktgen/app/pktgen.c
index 1fc8ceb..2aa64b3 100644
--- a/dpdk/examples/pktgen/app/pktgen.c
+++ b/dpdk/examples/pktgen/app/pktgen.c
@@ -974,7 +974,7 @@ pktgen_main_transmit(port_info_t * info, uint16_t qid)
 */
 
 static __inline__ void
-pktgen_main_receive(port_info_t * info, uint8_t lid, uint8_t idx, struct rte_mbuf *pkts_burst[])
+pktgen_main_receive(port_info_t * info, uint8_t lid, __rte_unused uint8_t idx, struct rte_mbuf *pkts_burst[])
 {
 	uint8_t pid;
 	uint16_t qid, nb_rx;
@@ -982,7 +982,7 @@ pktgen_main_receive(port_info_t * info, uint8_t lid, uint8_t idx, struct rte_mbu
 	capture_t *capture;
 
 	pid = info->pid;
-	qid = wr_get_rxque(pktgen.l2p, lid, idx);
+	qid = wr_get_rxque(pktgen.l2p, lid, pid);
 
 	/*
 	 * Read packet from RX queues and free the mbufs

**Comment by pktgen** [comment]
Thanks for the fix, please use the version on dpdk.org
