### ISSUE TITLE
Please remove C++ style comments from lua_dapi.c for lua enabled compilation on Redhat/Centos 7.x

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#20]
Dear Keith,

Compilation fails for lua_dapi.c as it has below C++ style comments, please replace them wirh C style comments.

luaL_newmetatable(L, Dapi);	// create and push new table called Vec
	lua_pushvalue(L, -1);		// dup the table on the stack

	lua_setfield(L, -2, "__index");	//

Thanks

**Comment by pktgen** [comment]
Must be something with your GCC as these are accepted in Ubuntu 20.04

**Comment by Ravi-t** [comment]
I am compiling it on Redhat/Centos 7.7

**gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.**
