### ISSUE TITLE
Silent failure causing seg.fault (set MAC addr)

### ISSUE THREAD

**Issue by akberg** [pktgen/Pktgen-DPDK#204]
`pg_ether_aton` returns NULL when failing to parse a MAC address, and `single_set_dst_mac` uses this return value directly. Suggestion to add a quick NULL check, aborting the command and signalling the failure to the user.

**Comment by KeithWiles** [comment]
Thanks I will add the checks.

**Comment by akberg** [comment]
Added what seemed most prone to crashes in #205

**Comment by pktgen** [comment]
Added #206 to address all of the locations using pg_ether_aton() function. Please review and see if it works for you. Thanks

**Comment by KeithWiles** [comment]
Fixed in #206
