### ISSUE TITLE
Is it possible to set the packet type to raw without using IP headers ?

### ISSUE THREAD

**Issue by adibacco** [pktgen/Pktgen-DPDK#208]
I wonder if there is a setting to set the pkt type to raw, meaning only the ethernet addresses and VLAN without any IP headers.

In general it would be useful to see the line rate, meaning the rate of all bytes sent (including preamble, mac addresses, vlan tag).

**Comment by KeithWiles** [comment]
In Ethernet the min packet size is 60 bytes not counting the 4 bytes FCS. Then removing the IP/UDP or TCP headers will not buy any extra performance as the L2+VlanID+L3+L4+payload will fit in a 60 byte frame. The min packet size is fixed at frame size(60) + FCS + interpacket gap,  preamble and START_FRAME_DELIMITER. The last three are about 20Bytes and pktgen accounts for the size of the frame on the wire to calculate the PPS or Bitrate.

**Comment by adibacco** [comment]
I understand. Please close this
