### ISSUE TITLE
How to generate dns query traffic?

### ISSUE THREAD

**Issue by siphonelee** [pktgen/Pktgen-DPDK#210]
I can set some common fields like:

set 0 proto udp 
set 0 size 96
set 0 src mac xxxxxxx
set 0 dst mac xxxxxx
set 0 src ip xxxxxx 
set 0 dst ip xxxxxxx

But how to set DNS query specific fields like DNS question count, DNS query name etc? 

Thanks for your help!

**Comment by KeithWiles** [comment]
Pktgen does not support setting DNS protocol fields. The only way would be to create a pcap file with the packets you would like to send.
