### ISSUE TITLE
Request to update getting_started.rst document

### ISSUE THREAD

**Issue by Memorywzd** [pktgen/Pktgen-DPDK#211]
The getting_started.rst documentation was last updated three years ago, however, the way dpdk and pktgen are compiled has changed dramatically with version changes, so please keep the documentation up to date to avoid confusing more people!

**Comment by KeithWiles** [comment]
Thank you for the comments.

If you can please point out what is wrong with the documentation it would help understand what needs to be changed. What would be great is if you would update the documentation and make it better with a pull request.

**Comment by KeithWiles** [comment]
Some updates to the docs have been done lately.
