### ISSUE TITLE
When setting a range of pkt size, rate is always 100%

### ISSUE THREAD

**Issue by freespacebird** [pktgen/Pktgen-DPDK#216]
Hello,

I am trying to use a range for packet size, but it seems when I do the `rate` setting isn't honored. 

Thanks

**Comment by KeithWiles** [comment]
The range mode and rate mode are two different modes of operations. The Rate mode is used to do packet pacing of packets and does not handle ranges.

Both the Range and Rate mode support sending at different rates. The Rate mode to set the packet pacing values is different from the 'set 0 rate 50' command which works on the single, range, sequence modes. The Rate mode has its own commands to set the packet pacing rate.

Using `page range` helps to set the range values, but the `set <portlist> rate <percent>` will adjust the rate when sending packets from the `range` mode.

I hope that clear it up, I know they use the same term `rate` but send packets in a different way.
