### ISSUE TITLE
Packet size can't set more than 1518

### ISSUE THREAD

**Issue by FarhatUllah999** [pktgen/Pktgen-DPDK#217]
Hi, I want to generate jumbo packets from pktgen but it seems pktgen only supports 1518 max size.
Can someone guide me what are the limitations? Or is there a method to set larger packet size?

Regards
Farhat

**Comment by Phikimon** [comment]
Have you tried using -j option?

**Comment by 117104010497** [comment]
Hello everyone！ I has used -- -j option and  then set all size 2000. However, after I start all, pktgen gets a segment fault.
My cards are i210 and the pktgen version is 19.12.0.
Are there problems with my cmd? If I do not add -j option and just send pkts smaller than 1518, there are no problems.

```
./app/x86_64-native-linux-gcc/app/pktgen -l 0-3 -n 3 -- -P -m"1.0,2.1" -j
set all size 2000
str
```
