### ISSUE TITLE
Pktgen-2.8.0 with dpdk1.8.0 doesn't receive packets

### ISSUE THREAD

**Issue by lapnd** [pktgen/Pktgen-DPDK#22]
Hi Keith Wiles,
I tried test L3FWD using pktgen dpdk with same config file (mac address, rate, ip, port....) for Pktgen2.7.7-dpdk1.7.1 from github and Pktgen-2.8.0 with dpdk1.8.0 from http://dpdk.org/.  However the former case, data is forwarded, ports on traffic generator machine received data, but in the later case, there is no received data on these ports.
Pktgen2.7.7-dpdk1.7.1 on github contains both dpdk and pktgen app. There are some different between dpdk-1.7.1 (from http://dpdk.org/) and dpdk here (ex code, build config files....).
Could you please tell me,  are there any special version of dpdk1.8.0 to work with  Pktgen-2.8.0?
Thank and Best Regards.
Lap

**Comment by pktgen** [comment]
Pktgen 2.8.0 should work with DPDK 1.8.0, now they did change a number of things on how you startup DPDK and select ports. Did you verify your startup code brings up DPDK correctly and the ports are correctly attached to the UIO driver.

**Comment by lapnd** [comment]
Thank Keith for your suggestion. I'm able to make pktgen generate packets now.
