### ISSUE TITLE
Information needed: How to read a pcap file through lua script

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#22]
I am trying to write a lua script which can read data from a pcap file and send all the pcap packets from source mac address to destination mac address mentioned in the pcap file. Please let me know the exact format of the command to achieve this functionality through lua script.

I am able to perform this during startup time using -s switch like **-s Port:Pcap** file but unable to trigger it via lua script.

**Comment by pktgen** [comment]
Setting the pcap file at start up is the only ATM

**Comment by Ravi-t** [comment]
Thanks for the update
