### ISSUE TITLE
How to set TCP flag when enable range.

### ISSUE THREAD

**Issue by jeromechen75** [pktgen/Pktgen-DPDK#229]
As shown in the figure, I want to set SYN packets in range mode. However, I couldn't find the corresponding configuration command. How can I configure it? The command "range <port> tcp flag set syn" doesn't work.
![image](https://github.com/pktgen/Pktgen-DPDK/assets/149370715/96b5e4bb-a363-4b98-9a9a-c29ab9efcb27)

**Comment by jeromechen75** [comment]
DPDK Version：23.03.0
Pktgen Version：23.06.1

**Comment by KeithWiles** [comment]
In the app/cli-functions.c we have the following commands:

    {42, "range %P tcp flag set %|urg|ack|psh|rst|syn|fin|all"},
    {43, "range %P tcp flag clr %|urg|ack|psh|rst|syn|fin|all"},

The command `range 0 tcp flag set syn` should work. In the command above you forgot the `<portlist>` value after `range`

**Comment by jeromechen75** [comment]
In fact, I have used portlist, the command can be executed, no error is reported, but the TCP flag is still not changed, and I found that the range help doesn't have these commands. 
![image](https://github.com/pktgen/Pktgen-DPDK/assets/149370715/7f0c5bd7-61cb-48c4-87a9-e96ba8587b53)

**Comment by pktgen** [comment]
Do the packet being sent have the correct flag? I noticed the code does not range over the TCP flags only sets the value.

I will have to find some time to look at the code again. The current code does not range over TCP flags, but it should set the flag correctly.

**Comment by KeithWiles** [comment]
Have a look at Version 23.10.2 I believe this fixes the display problem. Let me know if it does not.

**Comment by jeromechen75** [comment]
OK, I will try version 23.10.2 and give feedback as soon as possible. By the way, which DPDK version matchs it？I always have to spend a lot of time looking for the right DPDK version, otherwise it will compile incorrectly. Or is there a table for the DPDK version used for each version?

**Comment by KeithWiles** [comment]
I try to release a version that matches the latest DPDK and latest Pktgen, sometimes my day job makes it hard to keep up with all of the changes in DPDK.

**Comment by jeromechen75** [comment]
Thanks. I understand. Maybe you can just provide us with the version of DPDK you use for each pktgen version, it would be fine.

**Comment by KeithWiles** [comment]
DPDK - 23.11.0-rc1
Pktgen - 23.10.2
