### ISSUE TITLE
"proto udp 0" does not work with "range 0 enable"

### ISSUE THREAD

**Issue by henriqueng** [pktgen/Pktgen-DPDK#23]
Hi,

The "proto udp 0" does not work only when I try to use a range of sources (IP).
The wireshark (in another PC) receives UDP packets when I try to send from a single ip source. [config 1]
Unfortunately, when I try to send udp packets from a range of sources (IP), the wireshark (in another PC) receives TCP segments. [config 2]

[config 1]
------------------------------------------------------------------
set mac  0 8c:dc:d4:a9:b5:3c
set ip dst 0 192.168.17.1
set ip src 0 192.168.17.2/24

set 0 sport 5678
set 0 dport 1234
type ipv4 0
proto udp 0

[config 2]
------------------------------------------------------------------
set mac  0 8c:dc:d4:a9:b5:3c
#set ip dst 0 192.168.17.1
#set ip src 0 192.168.17.2/24 (I tried to uncomment the two lines)

range 0 on
src.ip start 0 192.168.17.2
src.ip min 0 192.168.17.2
src.ip max 0 192.168.17.5
src.ip inc 0 0.0.0.1

dst.ip start 0 192.168.17.1
dst.ip min 0 192.168.17.1
dst.ip max 0 192.168.17.1
dst.ip inc 0 0.0.0.0

src.port start 0 5678
src.port min 0 5678
src.port max 0 5678
src.port inc 0 0

dst.port start 0 1234
dst.port min 0 1234
dst.port max 0 1234
dst.port inc 0 0

set 0 sport 5678
set 0 dport 1234
type ipv4 0
proto udp 0

**Comment by pktgen** [comment]
Please look at the version on DPDK.org

**Comment by a1boyband** [comment]
@pktgen “look at the version on dpdk.org”, what means?

**Comment by pktgen** [comment]
Please look at the latest version on dpdk.org Pktgen-3.1.0, thanks.
