### ISSUE TITLE
Input/output error on start-up and quit

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#23]
I always get input/output error whenever I start or quit the Pktgen CLI.

I start my pktgen with below command using root login.
pktgen -l 2-3 -n 4 --proc-type auto --log-level 7 --socket-mem 1024 --file-prefix pg2 -w 0000:02:06.0 -- -m [3].0 

Startup Error:

![image](https://user-images.githubusercontent.com/27767393/90812875-0f692480-e327-11ea-91e6-f86cbcf06e0f.png)

Quit Error:

![image](https://user-images.githubusercontent.com/27767393/90812513-8356fd00-e326-11ea-8758-72256351f609.png)

**Comment by pktgen** [comment]
This is more of a DPDK question then a Pktgen question. I am not sure why it is giving you this message.

**Comment by Ravi-t** [comment]
ok...Thanks for the update.
