### ISSUE TITLE
Issue with buildlua and latest pkgen 23.10.0

### ISSUE THREAD

**Issue by NicNull** [pktgen/Pktgen-DPDK#230]
It builds OK without lua, at least the RTE_STD_C11 build issue is gone now.
Using a Ubuntu 22.04-lts host with DPDK 23.11.0-rc1.
I'll move back to an older release for now.

<details>

<summary>build output </summary>
`# git reset pktgen-23.10.0  --hard 
HEAD is now at 57b9452 clang-format update
# make buildlua 

./tools/pktgen-build.sh clean buildlua
>>  SDK Path          : /root
>>  Install Path      : /root/Pktgen-DPDK
>>  Build Directory   : /root/Pktgen-DPDK/Builddir
>>  Target Directory  : usr/local
>>  Build Path        : /root/Pktgen-DPDK/Builddir
>>  Target Path       : /root/Pktgen-DPDK/usr/local

 Build and install values:
   lua_enabled       : -Denable_lua=false
   gui_enabled       : -Denable_gui=false

*** Removing '/root/Pktgen-DPDK/Builddir' directory
 Build and install values:
   lua_enabled       : -Denable_lua=true
   gui_enabled       : -Denable_gui=false

>>> Ninja build in '/root/Pktgen-DPDK/Builddir' buildtype=release
meson setup -Dbuildtype=release -Denable_lua=true -Denable_gui=false /root/Pktgen-DPDK/Builddir
The Meson build system
Version: 0.61.2
Source dir: /root/Pktgen-DPDK
Build dir: /root/Pktgen-DPDK/Builddir
Build type: native build
Program cat found: YES (/usr/bin/cat)
Project name: pktgen
Project version: 23.10.0
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -mavx: YES 
Compiler for C supports arguments -mavx2: YES 
Compiler for C supports arguments -Wno-pedantic: YES 
Compiler for C supports arguments -Wno-format-truncation: YES 
Message: >>>>>>>>>>>>> Lua enabled <<<<<<<<<<<<<<
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency lua found: YES 5.4.4
Run-time dependency libdpdk found: YES 23.11.0-rc1
Message: prefix: /usr/local libdir: lib/x86_64-linux-gnu
Message: DPDK lib path: /usr/local/lib/x86_64-linux-gnu
Library librte_net_bond found: YES
Program python3 found: YES (/usr/bin/python3)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Library rte_net_i40e found: YES
Library rte_net_ixgbe found: YES
Library rte_net_ice found: YES
Library rte_bus_vdev found: YES
Run-time dependency threads found: YES
Run-time dependency numa found: YES 2.0.14
Run-time dependency pcap found: YES 1.10.1
Library dl found: YES
Library m found: YES
Program doxygen found: NO
Program sphinx-build found: NO
Build targets in project: 9
NOTICE: Future-deprecated features used:
 * 0.56.0: {'Dependency.get_pkgconfig_variable'}

pktgen 23.10.0

  User defined options
    buildtype : release
    enable_gui: false
    enable_lua: true

Found ninja-1.10.1 at /usr/bin/ninja
ninja: Entering directory `/root/Pktgen-DPDK/Builddir'
[77/77] Linking target app/pktgen
FAILED: app/pktgen 
cc  -o app/pktgen app/pktgen.p/cli-functions.c.o app/pktgen.p/pktgen-cmds.c.o app/pktgen.p/pktgen.c.o app/pktgen.p/pktgen-cfg.c.o app/pktgen.p/pktgen-main.c.o app/pktgen.p/pktgen-pcap.c.o app/pktgen.p/pktgen-range.c.o app/pktgen.p/pktgen-cpu.c.o app/pktgen.p/pktgen-seq.c.o app/pktgen.p/pktgen-dump.c.o app/pktgen.p/pktgen-capture.c.o app/pktgen.p/pktgen-stats.c.o app/pktgen.p/pktgen-port-cfg.c.o app/pktgen.p/pktgen-ipv6.c.o app/pktgen.p/pktgen-ipv4.c.o app/pktgen.p/pktgen-arp.c.o app/pktgen.p/pktgen-gre.c.o app/pktgen.p/pktgen-ether.c.o app/pktgen.p/pktgen-tcp.c.o app/pktgen.p/pktgen-udp.c.o app/pktgen.p/pktgen-vlan.c.o app/pktgen.p/pktgen-random.c.o app/pktgen.p/pktgen-display.c.o app/pktgen.p/pktgen-log.c.o app/pktgen.p/pktgen-gtpu.c.o app/pktgen.p/pktgen-latency.c.o app/pktgen.p/pktgen-rate.c.o app/pktgen.p/lpktgenlib.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/local/lib/x86_64-linux-gnu -Wl,--start-group lib/common/libcommon.a lib/utils/libutils.a lib/vec/libvec.a lib/plugin/libplugin.a lib/cli/libcli.a lib/lua/liblua.a -Wl,--as-needed /usr/local/lib/x86_64-linux-gnu/librte_node.so /usr/local/lib/x86_64-linux-gnu/librte_graph.so /usr/local/lib/x86_64-linux-gnu/librte_pipeline.so /usr/local/lib/x86_64-linux-gnu/librte_table.so /usr/local/lib/x86_64-linux-gnu/librte_pdump.so /usr/local/lib/x86_64-linux-gnu/librte_port.so /usr/local/lib/x86_64-linux-gnu/librte_fib.so /usr/local/lib/x86_64-linux-gnu/librte_pdcp.so /usr/local/lib/x86_64-linux-gnu/librte_ipsec.so /usr/local/lib/x86_64-linux-gnu/librte_vhost.so /usr/local/lib/x86_64-linux-gnu/librte_stack.so /usr/local/lib/x86_64-linux-gnu/librte_security.so /usr/local/lib/x86_64-linux-gnu/librte_sched.so /usr/local/lib/x86_64-linux-gnu/librte_reorder.so /usr/local/lib/x86_64-linux-gnu/librte_rib.so /usr/local/lib/x86_64-linux-gnu/librte_mldev.so /usr/local/lib/x86_64-linux-gnu/librte_regexdev.so /usr/local/lib/x86_64-linux-gnu/librte_rawdev.so /usr/local/lib/x86_64-linux-gnu/librte_power.so /usr/local/lib/x86_64-linux-gnu/librte_pcapng.so /usr/local/lib/x86_64-linux-gnu/librte_member.so /usr/local/lib/x86_64-linux-gnu/librte_lpm.so /usr/local/lib/x86_64-linux-gnu/librte_latencystats.so /usr/local/lib/x86_64-linux-gnu/librte_jobstats.so /usr/local/lib/x86_64-linux-gnu/librte_ip_frag.so /usr/local/lib/x86_64-linux-gnu/librte_gso.so /usr/local/lib/x86_64-linux-gnu/librte_gro.so /usr/local/lib/x86_64-linux-gnu/librte_gpudev.so /usr/local/lib/x86_64-linux-gnu/librte_dispatcher.so /usr/local/lib/x86_64-linux-gnu/librte_eventdev.so /usr/local/lib/x86_64-linux-gnu/librte_efd.so /usr/local/lib/x86_64-linux-gnu/librte_dmadev.so /usr/local/lib/x86_64-linux-gnu/librte_distributor.so /usr/local/lib/x86_64-linux-gnu/librte_cryptodev.so /usr/local/lib/x86_64-linux-gnu/librte_compressdev.so /usr/local/lib/x86_64-linux-gnu/librte_cfgfile.so /usr/local/lib/x86_64-linux-gnu/librte_bpf.so /usr/local/lib/x86_64-linux-gnu/librte_bitratestats.so /usr/local/lib/x86_64-linux-gnu/librte_bbdev.so /usr/local/lib/x86_64-linux-gnu/librte_acl.so /usr/local/lib/x86_64-linux-gnu/librte_timer.so /usr/local/lib/x86_64-linux-gnu/librte_hash.so /usr/local/lib/x86_64-linux-gnu/librte_metrics.so /usr/local/lib/x86_64-linux-gnu/librte_cmdline.so /usr/local/lib/x86_64-linux-gnu/librte_pci.so /usr/local/lib/x86_64-linux-gnu/librte_ethdev.so /usr/local/lib/x86_64-linux-gnu/librte_meter.so /usr/local/lib/x86_64-linux-gnu/librte_net.so /usr/local/lib/x86_64-linux-gnu/librte_mbuf.so /usr/local/lib/x86_64-linux-gnu/librte_mempool.so /usr/local/lib/x86_64-linux-gnu/librte_rcu.so /usr/local/lib/x86_64-linux-gnu/librte_ring.so /usr/local/lib/x86_64-linux-gnu/librte_eal.so /usr/local/lib/x86_64-linux-gnu/librte_telemetry.so /usr/local/lib/x86_64-linux-gnu/librte_kvargs.so /usr/local/lib/x86_64-linux-gnu/librte_log.so /usr/local/lib/x86_64-linux-gnu/librte_net_i40e.so /usr/local/lib/x86_64-linux-gnu/librte_net_ixgbe.so /usr/local/lib/x86_64-linux-gnu/librte_net_ice.so /usr/local/lib/x86_64-linux-gnu/librte_bus_vdev.so -pthread /usr/lib/x86_64-linux-gnu/libnuma.so /usr/lib/x86_64-linux-gnu/libpcap.so -ldl -lm /usr/lib/x86_64-linux-gnu/liblua5.4.so /usr/local/lib/x86_64-linux-gnu/librte_net_bond.so -Wl,--end-group -Wl,--as-needed -Wl,--as-needed -Wl,--as-needed -Wl,--as-needed -Wl,--as-needed -Wl,--as-needed
/usr/bin/ld: lib/lua/liblua.a.p/lua_socket.c.o: in function `lua_start_socket':
lua_socket.c:(.text+0x7e0): undefined reference to `rte_thread_setname'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make: *** [Makefile:21: buildlua] Error 1
`
</details>

**Comment by NicNull** [comment]
With older version 23.03.0 and 23.06.1 I get something else, dpdk must have renamed some functions due to improper naming.
`../app/pktgen-cmds.c: In function ‘enable_bonding’:
../app/pktgen-cmds.c:1949:19: error: implicit declaration of function ‘rte_eth_bond_slaves_get’; did you mean ‘rte_eth_bond_members_get’? [-Werror=implicit-function-declaration]
 1949 |     num_workers = rte_eth_bond_slaves_get(info->pid, workers, RTE_MAX_ETHPORTS);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                   rte_eth_bond_members_get
../app/pktgen-cmds.c:1956:9: error: implicit declaration of function ‘rte_eth_bond_active_slaves_get’; did you mean ‘rte_eth_bond_active_members_get’? [-Werror=implicit-function-declaration]
 1956 |         rte_eth_bond_active_slaves_get(info->pid, active_workers, RTE_MAX_ETHPORTS);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         rte_eth_bond_active_members_get
../app/pktgen-cmds.c: In function ‘show_bonding_mode’:
../app/pktgen-cmds.c:2088:47: error: storage size of ‘conf’ isn’t known
 2088 |         struct rte_eth_bond_8023ad_slave_info conf;
      |                                               ^~~~
../app/pktgen-cmds.c:2091:9: error: implicit declaration of function ‘rte_eth_bond_8023ad_slave_info’; did you mean ‘rte_eth_bond_8023ad_member_info’? [-Werror=implicit-function-declaration]
 2091 |         rte_eth_bond_8023ad_slave_info(info->pid, workers[i], &conf);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         rte_eth_bond_8023ad_member_info
`

**Comment by NicNull** [comment]
After patching that the same buildlua issue still appears.

**Comment by KeithWiles** [comment]
Normally you can not use any version of pktgen with any version of DPDK as they have changed a lot of defines and functions. This is why I only try to  support the latest DPDK and latest Pktgen.

I seem to be able to build Pktgen without any issues, but I need to try with Lua again.

**Comment by KeithWiles** [comment]
The latest version of DPDK and Pktgen build, but the buildlua fails as then changed rte_thread_setname to rte_thread_set_name.

Look in app/pktgen-gui.c and lib/lua/lua_socket.c then rename all three instances.

**Comment by NicNull** [comment]
Thanks, you're the best! Now it works.
