### ISSUE TITLE
Port stats in page stats are not cumulative

### ISSUE THREAD

**Issue by weiranwu** [pktgen/Pktgen-DPDK#233]
Hello, I am doing some automation tests with the latest main branch. I found that the port stats from the page stats were not cumulative anymore. They were all real time stats currently. When the traffic stopped, the stats display would turn to 0. I failed to get an total packets/bytes number through this page. I have confirmed that this implementation was not consistent with the previous version. Is it something wrong with the latest version?

**Comment by KeithWiles** [comment]
Can you give the the version that worked and not worked.

Can you show a screenshot of a working version and non-working version? I do not know which stats you are talking about.

**Comment by weiranwu** [comment]
Add some screenshot and version info here.
Version worked: Pktgen 22.07.1 (DPDK 23.07.0)
I sent 100 packets through port 0 Q 0, the stats can be obtained from stats page like below:
![image](https://github.com/pktgen/Pktgen-DPDK/assets/95612157/c870b8ac-7d54-4a2f-8f81-014b8a332e10)

Version not worked: Pktgen 23.10.2 (DPDK 23.11.0-rc1)
I sent 100 packets through port 0 Q 0. When traffic stopped, the stats display turned to 0 like below:
![image](https://github.com/pktgen/Pktgen-DPDK/assets/95612157/172713bb-2894-4fb4-b0b9-ddba0c1d140d)
The total packets sent out can be seen from main page as below:
![image](https://github.com/pktgen/Pktgen-DPDK/assets/95612157/2cf4e269-4167-4e7e-9cfa-879d764f03eb)

**Comment by KeithWiles** [comment]
It looks like the `page stats` was changed to not be cumulative and was changed to delta a while back, but I will look into it.

One question is if you run continuous traffic do you see the counters reporting the per-second rate or no value?

**Comment by weiranwu** [comment]
Thank you! With continuous traffic, the counters reported the per-second rate.
