### ISSUE TITLE
I cant finish make the project on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by gas-93** [pktgen/Pktgen-DPDK#234]
When I start make command ,I have next problems
make
>>> Use 'make help' for more commands

./tools/pktgen-build.sh build
>>  SDK Path          : /root
>>  Install Path      : /root/Pktgen-DPDK-pktgen-23.10.0
>>  Build Directory   : /root/Pktgen-DPDK-pktgen-23.10.0/Builddir
>>  Target Directory  : usr/local
>>  Build Path        : /root/Pktgen-DPDK-pktgen-23.10.0/Builddir
>>  Target Path       : /root/Pktgen-DPDK-pktgen-23.10.0/usr/local

 Build and install values:
   lua_enabled       : -Denable_lua=false
   gui_enabled       : -Denable_gui=false

>>> Ninja build in '/root/Pktgen-DPDK-pktgen-23.10.0/Builddir' buildtype=release
meson setup -Dbuildtype=release -Denable_lua=false -Denable_gui=false /root/Pktgen-DPDK-pktgen-23.10.0/Builddir
The Meson build system
Version: 0.61.2
Source dir: /root/Pktgen-DPDK-pktgen-23.10.0
Build dir: /root/Pktgen-DPDK-pktgen-23.10.0/Builddir
Build type: native build
Program cat found: YES (/usr/bin/cat)
Project name: pktgen
Project version: 23.10.0
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -mavx: YES 
Compiler for C supports arguments -mavx2: YES 
Compiler for C supports arguments -Wno-pedantic: YES 
Compiler for C supports arguments -Wno-format-truncation: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libdpdk found: YES 21.11.4
Message: prefix: /usr libdir: lib/x86_64-linux-gnu
Message: DPDK lib path: /usr/lib/x86_64-linux-gnu
Library librte_net_bond found: YES
Program python3 found: YES (/usr/bin/python3)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Library rte_net_i40e found: YES
Library rte_net_ixgbe found: YES
Library rte_net_ice found: YES
Library rte_bus_vdev found: YES
Run-time dependency threads found: YES
Run-time dependency numa found: YES 2.0.14
Run-time dependency pcap found: YES 1.10.1
Library dl found: YES
Library m found: YES
Program doxygen found: YES (/usr/bin/doxygen)
Program generate_doxygen.sh found: YES (/root/Pktgen-DPDK-pktgen-23.10.0/doc/api/generate_doxygen.sh)
Program generate_examples.sh found: YES (/root/Pktgen-DPDK-pktgen-23.10.0/doc/api/generate_examples.sh)
Program doxy-html-custom.sh found: YES (/root/Pktgen-DPDK-pktgen-23.10.0/doc/api/doxy-html-custom.sh)
Configuring doxy-api.conf using configuration
Program sphinx-build found: NO
Build targets in project: 11
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.build_root', 'meson.source_root', 'Dependency.get_pkgconfig_variable'}

pktgen 23.10.0

  User defined options
    buildtype : release
    enable_gui: false
    enable_lua: false

Found ninja-1.10.1 at /usr/bin/ninja
ninja: Entering directory `/root/Pktgen-DPDK-pktgen-23.10.0/Builddir'
[42/69] Compiling C object app/pktgen.p/pktgen-cmds.c.o
FAILED: app/pktgen.p/pktgen-cmds.c.o 
cc -Iapp/pktgen.p -Iapp -I../app -Ilib/common -I../lib/common -Ilib/utils -I../lib/utils -Ilib/vec -I../lib/vec -Ilib/plugin -I../lib/plugin -Ilib/cli -I../lib/cli -Ilib/lua -I../lib/lua -I/usr/include/dpdk -I/usr/include/libnl3 -I/usr/include/dpdk/../x86_64-linux-gnu/dpdk -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -pthread -include rte_config.h -march=corei7 '-D__PROJECT_VERSION="23.10.0"' -MD -MQ app/pktgen.p/pktgen-cmds.c.o -MF app/pktgen.p/pktgen-cmds.c.o.d -o app/pktgen.p/pktgen-cmds.c.o -c ../app/pktgen-cmds.c
../app/pktgen-cmds.c: In function ‘enable_bonding’:
../app/pktgen-cmds.c:1948:19: error: implicit declaration of function ‘rte_eth_bond_members_get’; did you mean ‘rte_eth_bond_slaves_get’? [-Werror=implicit-function-declaration]
 1948 |     num_workers = rte_eth_bond_members_get(info->pid, workers, RTE_MAX_ETHPORTS);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
      |                   rte_eth_bond_slaves_get
../app/pktgen-cmds.c:1955:9: error: implicit declaration of function ‘rte_eth_bond_active_members_get’; did you mean ‘rte_eth_bond_active_slaves_get’? [-Werror=implicit-function-declaration]
 1955 |         rte_eth_bond_active_members_get(info->pid, active_workers, RTE_MAX_ETHPORTS);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         rte_eth_bond_active_slaves_get
../app/pktgen-cmds.c: In function ‘show_bonding_mode’:
../app/pktgen-cmds.c:2087:48: error: storage size of ‘conf’ isn’t known
 2087 |         struct rte_eth_bond_8023ad_member_info conf;
      |                                                ^~~~
../app/pktgen-cmds.c:2090:9: error: implicit declaration of function ‘rte_eth_bond_8023ad_member_info’; did you mean ‘rte_eth_bond_8023ad_slave_info’? [-Werror=implicit-function-declaration]
 2090 |         rte_eth_bond_8023ad_member_info(info->pid, workers[i], &conf);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         rte_eth_bond_8023ad_slave_info
../app/pktgen-cmds.c:2087:48: error: unused variable ‘conf’ [-Werror=unused-variable]
 2087 |         struct rte_eth_bond_8023ad_member_info conf;
      |                                                ^~~~
cc1: all warnings being treated as errors
[47/69] Compiling C object app/pktgen.p/pktgen.c.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:15: build] Ошибка 1

I try different version of dpdk and pktgen and have this error.

**Comment by KeithWiles** [comment]
Are using the latest version of DPDK 23.11.0-rc1 with the latest version of Pktgen 23.10.2?

The errors above are because DPDK changed the names of functions and defines.

**Comment by gas-93** [comment]
Now I try to use DPDK 23.11.0-rc1 with the latest version of Pktgen 23.10.2 and have the same problem.

**Comment by KeithWiles** [comment]
Try `make rebuild` sometimes the cache can be out of sync or old objects in the build directory.

I just did a `git pull` for DPDK and then did `meson setup _build; ninja -C _build; sudo ninja -C _build install`

Then build pktgen `cd pktgen; make rebuild` and the build completed. Could also be you have and old version of DPDK installed someplace and pktgen is picking up that version.

**Comment by gas-93** [comment]
Thank you very much everything came together successfully. I apologize for perhaps the stupid question, but I’m new to this topic. Can Pktgen-DPDK
generate traffic to a remote host. For example, I have a machine in my case, ubuntu, with dpdk and pktgen-dpdk compiled on it, and another machine, a regular ubuntu, with a network running on the Linux kernel network stack. I need to send a large number of packets per second to determine the throughput packets per second of the Linux kernel network stack. Can I implement this check using dpdk and pktgen-dpdk. Thanks again for your help in building projects.

**Comment by KeithWiles** [comment]
You can have the Linux based machine act like a simple router send packets between two interfaces and use the other machine running Pktgen sending traffic and seeing what the performance is on the RX side. If I understand your needs here.

**Comment by gas-93** [comment]
I have a computer with Ubuntu on which DPDK and PKTGEN are deployed. This computer is rampally with another computer on Ubuntu, on this computer there is no DPDK and PKTGEN and network interfaces are controlled by the Linux kernel. I need to send the maximum possible number of packages from a computer with DPDK and PKTGEN to another computer without DPDK and PKTGEN and find out what number of packages per second can process the Linux core. At the moment, I was faced with the problem of sending these packages to a remote machine.  Therefore, I ask if there is a functionality of sending packages to a remote host that does not contain DPDK and PKTGEN.

**Comment by KeithWiles** [comment]
Sorry, I do not know what `rampally` means and google search gave me a city.

If you have a machine running Pktgen and another machine running Linux (or no DPDK or Pktgen) then you need to configure Pktgen to send packets to Linux and then Linux will route the packets back to Pktgen.

Pktgen Port 0 TX --> Linux Port 0 RX
Pktgen Port 1 RX <-- Linux Port 1 TX

Two ports on Pktgen and two ports on Linux, then make sure Linux is setup to forward IPv4 frames from on port to the other. You should be able to search for setting up Linux to forward traffic between to interfaces.

On Linux each interface needs to be setup on two different subnets i.e. Interface #1 10.0.0.2/24 Interface #2 20.0.0.2/24
Linux will route traffic from 10.0.0.0 subnet to the 20.0.0.0 subnet if configured correctly.

On pktgen set the IP address of each port to src 10.0.0.1/24 dst 20.0.0.1/24 and src 20.0.0.1/24 dst 10.0.0.1/24, then make sure the destination MAC address of port 0 is the MAC address of Linux port 0 and pktgen port 1 destination MAC address is Linux port 1.

This is a simple routing setup and I most likely left out some details, but you should be able to search for the setup.

**Comment by gas-93** [comment]
rampally means the computers are connected directly, this is my mistake, sorry. Thanks for the explanation, I only used one interface and it was my mistake.

**Comment by KeithWiles** [comment]
One option with having a single port between machines is to use vfio, which allows you to create multiple virtual function ports on the same NIC, which would need to be done on both machines. It is a lot of setup and your NIC's may not support the feature. Good luck.
