### ISSUE TITLE
Port stats broken when accessing via lua function

### ISSUE THREAD

**Issue by synnack** [pktgen/Pktgen-DPDK#235]
I wanted to report my tests with lua and pktgen:

- pktgen -f test/main.lua does not work because the pktgen object does not contain the decompile function, I'm not sure why, but several functions do not export correctly to lua.
- pktgen.seqTable does not load the values from the seqTable
- save xxx.lua results in a file that cannot be loaded, because the range object is missing in the generated output
- Adding the range does not really work. 

In the end I gave up on lua, and went back to CLI commands which do work correctly.

**Comment by ntyunyayev** [comment]
I am facing similar issues. In my case the pktgen.portStats structure is not filled correctly in my LUA scripts with Pktgen 23.10. All the fields are set to 0 even though I receive and send packets. The CLI shows the correct information. Everything is working fine with Pktgen 23.06.

**Comment by KeithWiles** [comment]
Hi @synnack and @ntyunyayev, I have been super busy at work and not able to work on Pktgen lately :-(

The decompile/compile/sendPkt/recvPkt in the help screen should have been removed. I am working on another solution for these features, but it is on the back burner while I get to the other issues.

The seqTable should work and I will look into it.
In the saved file I must have left something in the out that is no longer supported. If you have the time please send/port the save file or why the load failed.

The range function should also work and I will look into it.

I will look into the portStats problem as well, it would be good to send me the fragment of the script to grab the portStats to make sure I have the correct way you are using it most likely nothing special.

It may take some time to find these problems due to my schedule and free time, but thank you for reporting the issues.

**Comment by ntyunyayev** [comment]
Hi, no worries :)

The following line display the correct stats on 23.06, but return all zeros on 23.10.

`prints("portStats", pktgen.portStats("all", "port"));
`

Thank you,

Nikita

**Comment by bwtigeree** [comment]
Hi,

Recently, I faced the same issue with `prints("portStats", pktgen.portStats("all", "port"));` as @ntyunyayev. Do you have outlook for fixing the issue?

Best regards,
Michael

**Comment by KeithWiles** [comment]
Sorry, I do not have a timeframe

**Comment by KeithWiles** [comment]
Looking at the current version 23.10.2 of Pktgen I see the following.

Created a new file call test/portstats.lua I have four ports running on my system.

``` bash
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"

require "Pktgen"
-- A list of the test script for Pktgen and Lua.
-- Each command somewhat mirrors the pktgen command line versions.
-- A couple of the arguments have be changed to be more like the others.
--

prints("portStats", pktgen.portStats('all', 'port'));
prints("portStats", pktgen.portStats('2', 'port'));
```

Here is the output after starting all ports sending traffic and running the following command `load test/portstats.lua`

``` bash
Pktgen:/> start all
Pktgen:/> load test/portstats.lua

Executing 'test/portstats.lua'
portStats = {
  [1] = {
    ["ibytes"] = 0,
    ["imissed"] = 0,
    ["rx_nombuf"] = 0,
    ["opackets"] = 234193567,
    ["oerrors"] = 0,
    ["ipackets"] = 0,
    ["obytes"] = 14051613764,
    ["ierrors"] = 0,
  },
  [2] = {
    ["ibytes"] = 0,
    ["imissed"] = 0,
    ["rx_nombuf"] = 0,
    ["opackets"] = 254372374,
    ["oerrors"] = 0,
    ["ipackets"] = 0,
    ["obytes"] = 15262341608,
    ["ierrors"] = 0,
  },
  [3] = {
    ["ibytes"] = 0,
    ["imissed"] = 0,
    ["rx_nombuf"] = 0,
    ["opackets"] = 254369536,
    ["oerrors"] = 0,
    ["ipackets"] = 0,
    ["obytes"] = 15262170624,
    ["ierrors"] = 0,
  },
  [0] = {
    ["ibytes"] = 0,
    ["imissed"] = 0,
    ["rx_nombuf"] = 0,
    ["opackets"] = 242623362,
    ["oerrors"] = 0,
    ["ipackets"] = 0,
    ["obytes"] = 14557401080,
    ["ierrors"] = 0,
  },
  ["n"] = 4,
}
portStats = {
  [2] = {
    ["ibytes"] = 0,
    ["imissed"] = 0,
    ["rx_nombuf"] = 0,
    ["opackets"] = 254372374,
    ["oerrors"] = 0,
    ["ipackets"] = 0,
    ["obytes"] = 15262341608,
    ["ierrors"] = 0,
  },
  ["n"] = 1,
}
```

The lua function seems to work here, did I miss something?

**Comment by KeithWiles** [comment]
Running the command `load test/set_seq.lua` seems to work.

``` bash
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
-- Lua uses '--' as comment to end of line read the
-- manual for more comment options.
require "Pktgen"
local seq_table = {			-- entries can be in any order
    ["eth_dst_addr"] = "0011:4455:6677",
    ["eth_src_addr"] = "0011:1234:5678",
    ["ip_dst_addr"] = "10.12.0.1",
    ["ip_src_addr"] = "10.12.0.1/16",	-- the 16 is the size of the mask value
    ["sport"] = 9,			-- Standard port numbers
    ["dport"] = 10,			-- Standard port numbers
    ["ethType"] = "ipv4",	-- ipv4|ipv6|vlan
    ["ipProto"] = "udp",	-- udp|tcp|icmp
    ["vlanid"] = 1,			-- 1 - 4095
    ["pktSize"] = 128,		-- 64 - 1518
    ["teid"] = 3,
    ["cos"] = 5,
    ["tos"] = 6
  };
-- seqTable( seq#, portlist, table );
pktgen.seqTable(0, "all", seq_table );
pktgen.set("all", "seq_cnt", 1);
```

``` bash
Pktgen> page seq
Port:  0, Sequence Count:  1 of 16                                                               GTP-u
Seq        Dst MAC        Src MAC          Dst IP            Src IP TTL/Port S/D   Protocol:VLAN CoS/ToS TEID Flag/Group/vxlan  Size
 0: 0011:4455:6677 0011:1234:5678       10.12.0.1      10.12.0.1/16      64/9/10   IPv4/UDP:0001   5/  6    0 0000/    0/    0   128

-- Pktgen 23.10.2 (DPDK 24.03.0)  Powered by DPDK  (pid:313405) ---------------
```

**Comment by KeithWiles** [comment]
The command `save foobar` and then `load foobar` seems to work as well.

``` bash
Pktgen> load test/set_seq.lua
Pktgen> save foobar
Pktgen> load foobar
```

Doing a `page seq` command seems to show the correct information as well and the load did not error out. I did change the save and load command as some of the commands changed or were removed. Please try with a clean saved file after you configure pktgen.

**Comment by KeithWiles** [comment]
I tested the command `load test/range.lua` command and it appears this works as well.

Can you give me more information and examples as to how these commands do not work.

**Comment by KeithWiles** [comment]
BTW, I just noticed you used the command `save xxx.lua` and that one does not work. The `save foobar` saves the information in command lines not lua code.

I will have a look at why saving a lua configuration does not work.

**Comment by pktgen** [comment]
Please test out the newly pushed code to fix the problem with `save foobar.lua` command. The changes were merged into the main branch.

Thanks

**Comment by ntyunyayev** [comment]
Thank you for taking a look. Here is what I observe with the following script passed through the -f argument:
`
sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH ~/Workspace/Pktgen-DPDK/build_$(hostname)/app/pktgen -l 0-5 -a 0000:18:00.0  -- -m [1:2/3/4/5].0  -f pktgen_lua_tmp.lua -P -j -T
`
```LUA
package.path = package.path .. ";?.lua;test/?.lua;"
require("Pktgen")
pktgen.start("0");
TEST_DURATION = 10
pktgen.delay(TEST_DURATION * 1000);
pktgen.stop("0");
prints("portStats", pktgen.portStats('all', 'port'));
pktgen.quit();
```

![image](https://github.com/pktgen/Pktgen-DPDK/assets/36966638/3815f791-4adf-4151-bebc-a4e1bae9b62a)


![image](https://github.com/pktgen/Pktgen-DPDK/assets/36966638/21951845-4b1f-4618-b264-711c22c2cabb)

In both cases, packets are actually correctly received by a server on the other side.

When I run the script as you proposed (starting Pktgen + load script) everything is working correctly. The behavior of "pktgen.delay" may be different between the two versions? On 23.06 the screen seems active when I run the script, whereas it seems to be frozen on 23.10.

Best regards,

Nikita

**Comment by pktgen** [comment]
I found the problem between the two versions with updating the stats when using delay/lua and pushed a new update. Please check it out when you have time.

**Comment by ntyunyayev** [comment]
Sorry for the delay, your fix is working for me. Thank you very much !

**Comment by KeithWiles** [comment]
thank you
