### ISSUE TITLE
problem replaying a pcap file

### ISSUE THREAD

**Issue by tiamilani** [pktgen/Pktgen-DPDK#239]
Dear all,

I'm currently approaching DPDK and Pktgen-DPDK for the first time and I'm facing a problem while replaying a small pcap file.
I've read the documentation but I didn't find any settings or parameter that I should tweak to make my experiment work, but if I missed something please let me know the section I should look into.

The versions are the following ones:
DPDK: 23.11.0
Pktgen: 23.10.2

Environment:
Both DPDK and packetgen are using a virtual interface, on the firstone DPDK is running with the BBDev plugin for encoding and decoding, [example here](https://doc.dpdk.org/guides/sample_app_ug/bbdev_app.html).
Running with the following command:
`./dpdk-bbdev_app --vdev='baseband_turbo_sw,max_nb_queues=8,socket_id=0' -vdev=net_tap0,iface=foo0,mac="da:14:de:b0:55:63" -c 0x38 --socket-mem=4000 --file-prefix=bbdev -- -e 0x10 -d 0x20`

While i run Pktgen with the following command:
`./Builddir/app/pktgen -c 0x3 --socket-mem=20000 --file-prefix=pg --vdev=net_tap1,iface=foo1,mac="56:3b:be:a9:92:4c" -- -m 1.0 -P -T -f themes/black-yellow.theme -s 0:<path-to-pcap-file>/file.pcap`

The pcap file has been generate following this Matlab 5G tutorial [CU-Plane Messages for O-RAN Fronthaul](https://uk.mathworks.com/help/5g/ug/generate-cu-plane-messages-for-oran-fronthaul-test.html).
The pcap file has been generated correctly and from wireshark I can see that there are 2540 packets, with no malformed packets.

I use this commands on the new interfaces:
```
udo ip link set foo0 up; sudo ip addr add 192.168.0.250/24 dev foo0
sudo ip link set foo1 up; sudo ip addr add 192.168.1.250/24 dev foo1
sudo socat interface:foo0 interface:foo1
```

From pktgen I thenk run the following CLI commands:
`pcap show` to ensure that actually Pktgen sees the same number of packets
`rate 0 count 2540` to transmit only the packets in the pcap files and then stop
`start 0` to start transmitting

On the bbdev statistics interface I can see that it's receiving packets, but way less than what I was expecting.
But, using tcpdump on the receiving interface foo0, I can see that the number of packets recorded is way less than expected, 454 packets (but the number changes at each execution).
And opening this reception flow with wireshark I can see that there are a lot of malformed packets.
Below a plain text expample of what I receive and what I expected from the original pcap file

Obtained:
```
    1   0.000000 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1492 U-Plane, Id: 0 (PRB: 68-101)
    2   0.000020 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1492 U-Plane, Id: 0 (PRB: 102-135)
    3   0.000023 56:3b:be:a9:92:4c → da:14:de:b0:55:63 eCPRI 211 Message Type: IQ Data[Malformed Packet]
    4   0.000036 56:3b:be:a9:92:4c → da:14:de:b0:55:63 eCPRI 211 Message Type: IQ Data[Malformed Packet]
    5   0.000052 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1492 U-Plane, Id: 0 (PRB: 136-169)
    6   0.000067 56:3b:be:a9:92:4c → da:14:de:b0:55:63 eCPRI 211 Message Type: IQ Data[Malformed Packet]
    7   0.000083 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1492 U-Plane, Id: 0 (PRB: 170-203)
    8   0.000097 56:3b:be:a9:92:4c → da:14:de:b0:55:63 eCPRI 211 Message Type: IQ Data[Malformed Packet]
    9   0.000114 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1492 U-Plane, Id: 0 (PRB: 204-237)
   10   0.000128 56:3b:be:a9:92:4c → da:14:de:b0:55:63 eCPRI 211 Message Type: IQ Data[Malformed Packet]
```

Expected from the original pcap file:
```
    1   0.000000 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-C 60 C-Plane, Type: 1 (Most channels), Id: 0 (all PRBs)
    2   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 0-33)
    3   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 34-67)
    4   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 68-101)
    5   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 102-135)
    6   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 136-169)
    7   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 170-203)
    8   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 204-237)
    9   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 1496 U-Plane, Id: 0 (PRB: 238-271)
   10   0.000120 56:3b:be:a9:92:4c → da:14:de:b0:55:63 O-RAN-FH-U 77 U-Plane, Id: 0 (PRB: 272)
```

Going a little bit further and looking into the sending interface with tcpdump i can see that there are exactly 2540 packets dropped by the interface, could it be because there is not enough memory dedicated to it? I've setted up my hugepages according to the DPDK guidelines

Update: I've increase the number of hugepages up to a total of 24GB
Update: I've assigned the same MAC address in the pcap file in the tap interfaces
I still get the same problem and the tap1 interface from pktgen drops all the packets

Which configuration parameters am I missing? I expect pktgen to be capable to replay this kind of pcap files but I don't know what I overlooked or missed.

Thank you very much for the help, best regards,
Mattia

**Comment by pktgen** [comment]
The pktgen command line is a bit odd.
`./Builddir/app/pktgen -c 0x3 --socket-mem=200 --file-prefix=pg --vdev=net_tap1,iface=foo1 -- -m 1.0 -P -T -f themes/black-yellow.theme -s 0:<path-to-pcap-file>/file.pcap`
The `-s 0:<path-to-pcap-file>/file.pcap` is not valid option should be a real path, but I assume you are using supplying the real path.

Personally I would not use `-c 0x03` option, but use the easier to read option `-l 0-1`, but up to you because at one point they may remove the -c option.

I would not use the --socket-mem` in the command line it does not do what you expected.  The reason is you only seem to have one NUMA zone (or socket) and the socket-mem is to assign memory to specific sockets. If you want to limit DPDK to a fixed amount of memory then use `-m` option i.e, `-m 512' for 512MBs of memory. Pktgen manages its own memory, but will respect the 512MB limit in most cases. This means you can reduce the amount of hugepages to match your needs.

The `rate 0 count 2540` is not the correct way to send only a fixed number of packets. Use the `set 0 count 2540`, if you want to adjust the rate of sending use `set 0 rate 80` for 80% line rate.

The way DPDK sends packets can be confusing at times. The reason is the mempool if using the per lcore cache it can seem to only send packets from the cache and not all of the packets in the pcap file. At one point I had used a cache of 256 packets, which would not send all of the packets in the pcap file, but the ones in the cache. I later changed the pcap mempool to not have a cache, which reduced it performance, but it did send all of the packet.

You need not say where you got the Pktgen source code and the one on dpdk.org is a bit behind the one on github.com. Please try using the version on `https://github.com/pktgen/Pktgen-DPDK`

The packets being sent appear to be from the cache of packets and not the full list of packets in the pcap file, which is why I suggested the one on github.com. Giving is more hugepages then needed will not help send all of the packets.

The tap interfaces are very slow and can drop packets at a very low rate.

**Comment by tiamilani** [comment]
Thank you very much for the quick reply,  in line my answers and comments.

> The pktgen command line is a bit odd. `./Builddir/app/pktgen -c 0x3 --socket-mem=200 --file-prefix=pg --vdev=net_tap1,iface=foo1 -- -m 1.0 -P -T -f themes/black-yellow.theme -s 0:<path-to-pcap-file>/file.pcap` The `-s 0:<path-to-pcap-file>/file.pcap` is not valid option should be a real path, but I assume you are using supplying the real path.

Yes the `-s 0:<path-to-pcap-file>/file.pcap` was just to avoid putting the full path in my comment, in reality I'm using a valid path.

> Personally I would not use `-c 0x03` option, but use the easier to read option `-l 0-1`, but up to you because at one point they may remove the -c option.

Thanks, I don't see any counter point in substituting it with `-l`

> I would not use the --socket-mem`in the command line it does not do what you expected. The reason is you only seem to have one NUMA zone (or socket) and the socket-mem is to assign memory to specific sockets. If you want to limit DPDK to a fixed amount of memory then use`-m`option i.e,`-m 512' for 512MBs of memory. Pktgen manages its own memory, but will respect the 512MB limit in most cases. This means you can reduce the amount of hugepages to match your needs.

Thanks, I knew the existence of `-m` but I was not awere of this difference in respect of `--socket-mem` I though that `-m` was just a more generic version of the second one.

> The `rate 0 count 2540` is not the correct way to send only a fixed number of packets. Use the `set 0 count 2540`, if you want to adjust the rate of sending use `set 0 rate 80` for 80% line rate.

Thanks, I'll try using the `set` command!

> The way DPDK sends packets can be confusing at times. The reason is the mempool if using the per lcore cache it can seem to only send packets from the cache and not all of the packets in the pcap file. At one point I had used a cache of 256 packets, which would not send all of the packets in the pcap file, but the ones in the cache. I later changed the pcap mempool to not have a cache, which reduced it performance, but it did send all of the packet.

So now the current version of Pktgen doesn't use any cache for the pcap files?

> You need not say where you got the Pktgen source code and the one on dpdk.org is a bit behind the one on github.com. Please try using the version on `https://github.com/pktgen/Pktgen-DPDK`

Actually I've used the `Pktgen` version here on github, updated to the commit from Oct 31 2023. I see there has been a new commit the 3rd of February, I'll update to that version.

> The tap interfaces are very slow and can drop packets at a very low rate.

Unfortunately for me right now I don't have any other choice, I have only one nic that it's reserved by the kernel and I cannot assign it to dpdk. Right now I'm setting up the tools, later I'll probably switch to a system with more nics.

Thank you very much for all your useful comments, I'll come back to you as soon as possible, I'll adjust my commands and try some ideas that I've in mind :)

**Comment by tiamilani** [comment]
Hi, I've looked into it a little bit more.

I've used the commands you mentioned to configure my Pktgen instance, I've also configured mac and ip addresses accordingly to the pcap file, both  src and destination using `set 0 src|dst ip|mac <addr>`.

After `start 0` packets are still dropped by the interface where Pktgen is assigned.
Looking into the interface statistics (`ip -s -s link show dev foo1` and `for f in /sys/class/net/foo1/statistics/*; do echo "${f} - $(cat $f)"; done`) after the attempted transmission.
With both commands I can see `rx_packets 2540` and `rx_dropped 2540`, which are exactly the packets I would like to send.

Following what is written in the [kernel statistics documentation](https://docs.kernel.org/networking/statistics.html) `rx_dropped` show the numer of packets discarded due to lack of resources or unsupported protocol.

Now, I'm using a CPU that does not support AVX512, which is a mandatory requirement to compile FlexRAN with 5G libraries.
Therefore I've compile it only with 4G support, with the idea of moving later the toolchain to a more powerful machine with AVX512 support. The traces that I've generate with matlab are already 5G.
The idea was that I would have been capable to transmit the packets but not to process those at the receiver, but could it be that the packets are discarded already at the sender because I'm missing the 5G related AVX512 support?

Thanks,
Mattia

**Comment by KeithWiles** [comment]
Yes, pktgen is setting the cache to zero in app/pktgen-pcap.c file.

**Comment by KeithWiles** [comment]
Some interfaces and NICs will drop packets is the src MAC address is correct or not the same as the interface. They think you are spoofing the packets. The dst MAC is only of the receive side and it needs to match the target.

Can you post a screen shot or just copy and past the main screen and pcap show screen.

**Comment by tiamilani** [comment]
> Some interfaces and NICs will drop packets is the src MAC address is correct or not the same as the interface. They think you are spoofing the packets. The dst MAC is only of the receive side and it needs to match the target.

So I should not configure the MAC address of the receiver but just the ipv4 address assigned to the interface?

> Can you post a screen shot or just copy and past the main screen and pcap show screen.

Sure, attached the two screenshot requested after loading my configuration
![image](https://github.com/pktgen/Pktgen-DPDK/assets/22966293/d4c845a4-5127-4009-bcc3-31d482eae247)
![image](https://github.com/pktgen/Pktgen-DPDK/assets/22966293/8208b7f7-0f79-427c-9f94-41a79713627b)

**Comment by KeithWiles** [comment]
Thanks, this looks fine. I assume the ethertype is fine for this pcap file.

The src MAC address should be the source address for the interface and the dst is pointing to the remote end MAC address.

**Comment by tiamilani** [comment]
> The src MAC address should be the source address for the interface and the dst is pointing to the remote end MAC address.

Yes exactly, I've setted the mac address directly from the `--vdev` command on both dpdk and pktgen-dpdk.
But I'm still puzzling myself why the packet should be dropped and what parameter I'm forgetting that the interface requires.

**Comment by KeithWiles** [comment]
This looks like a tap interface issue and not a pktgen configuration IMO. Can you use tcpdump on the tap interface and see if it is receiving anything or sending?

**Comment by tiamilani** [comment]
yeah, that's definetly something not related to Pktgen in particular, sorry for bothering you, probably this is not the correct place for this kind of problems.

By the way, the tcdpump on the interface shows that the interface receives the packets but also that the interface drops them

**Comment by KeithWiles** [comment]
Something needs to be changed in the packets or the interface to make it work, sorry not a lot of help here.

**Comment by tiamilani** [comment]
> Something needs to be changed in the packets or the interface to make it work, sorry not a lot of help here.

Don't worry you helped me quite a lot in the end to better understand Pktgen, thanks and all the best :)
I'll close this for the moment.
