### ISSUE TITLE
Unable to exchange packets on a VM between two virtual NICs

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#26]
I have created two virtual NICs on a VM and have binded an instance of pktgen to each NIC.
But when I send packets from NIC 1 to NIC 2, the packet generator shows that its sending packets but nothing is received at packet receiver listening on NIC 2. I also enabled packet capture but it doesn't even captures transmitted packets.
Below I have pasted the snapshot of generator (left side) and receiver (right side)

![image](https://user-images.githubusercontent.com/27767393/91669360-98950e00-eb14-11ea-9c36-faf286b5317c.png)

Startup trace for packet generator shows

![image](https://user-images.githubusercontent.com/27767393/91669376-cbd79d00-eb14-11ea-8993-af6ee1bb282f.png)

Startup trace for packet receiver shows

![image](https://user-images.githubusercontent.com/27767393/91669398-fa557800-eb14-11ea-8a3d-8e44b200e9d0.png)

**./dpdk-devbind.py -s**
Network devices using DPDK-compatible driver
0000:02:06.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio unused=e1000
0000:02:07.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio unused=e1000

Network devices using kernel driver
0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' if=ens33 drv=e1000 unused=igb_uio *Active*
0000:02:05.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' if=ens37 drv=e1000 unused=igb_uio *Active*

**numactl --hardware**
available: 1 nodes (0)
node 0 cpus: 0 1 2 3
node 0 size: 8191 MB
node 0 free: 237 MB
node distances:
node   0 
  0:  10 

**./cpu_layout.py** 
Core and Socket Information (as reported by '/sys/devices/system/cpu')
cores =  [0]
sockets =  [0, 2, 4, 6]

       Socket 0   Socket 2   Socket 4   Socket 6  
       --------   --------   --------   --------  
Core 0 [0]        [1]        [2]        [3]

**Comment by pktgen** [comment]
Other than trying with the -P option on the pktgen command lines I do not see anything right off hand, unless you did not set the correct dst MAC addresses in the range command. Capture does not capture TX packets only RX. The screen you are showing is the single packet mode information and those destination MAC addresses look right. Use ‘page range’ to see the Range configuration of a port.

**Comment by Ravi-t** [comment]
Thanks a lot for the feedback Keith.
I reviewed the config again and confirmed it through range page but didn't find anything wrong.

So, I finally rebooted the VM and binded the dpdk driver again, and it worked after it, not sure why it needed a reboot.
Closing the issue for the time-being, would let you know if I see the issue again.
