### ISSUE TITLE
Stats not cleared on rfc2544_tput_test.lua script

### ISSUE THREAD

**Issue by sebymiano** [pktgen/Pktgen-DPDK#27]
If I am not wrong, the `rfc2544_tput_test` should calculate the stats independently from each run.
For this reason, line https://github.com/pktgen/Pktgen-DPDK/blob/54731bf0d84a9dcd5bf401a6dda98b591e710413/scripts/rfc2544_tput_test.lua#L43 attempts to reset the stats counters at every trial so that the number of packets dropped in calculated per-run.

Unfortunately, this does not work for me in the current version (while it was working on the previous versions).

For instance, trial 3 in the example below should have a #dropped packets almost 0 (since the receiver side is able to forward all the packets). However, since the number is not reset, the script continues to decrease the rate.

```
Running trial 1. % Rate: 50. Packet Size: 64. Duration (mS):10000
Tx: 416617984. Rx: 177111571. Dropped: 239506413
Running trial 2. % Rate: 25.5. Packet Size: 64. Duration (mS):10000
Tx: 629023744. Rx: 353396814. Dropped: 275626930
Running trial 3. % Rate: 13.25. Packet Size: 64. Duration (mS):10000
Tx: 736732032. Rx: 461031514. Dropped: 275700518
Running trial 4. % Rate: 7.125. Packet Size: 64. Duration (mS):10000
```

**Comment by pktgen** [comment]
If you issue the ‘clr’ command in the pktgen command line does it work in that case? Run some traffic, then stop traffic and do clr command the screen should clear the stats.

**Comment by sebymiano** [comment]
> If you issue the ‘clr’ command in the pktgen command line does it work in that case? Run some traffic, then stop traffic and do clr command the screen should clear the stats. 

Yes, it is working on the CLI but not on the script. 
I mean, when the `pktgen.clr()` command is called, the screen clears all the stats but the cleaning does not affect the variable at line https://github.com/pktgen/Pktgen-DPDK/blob/54731bf0d84a9dcd5bf401a6dda98b591e710413/scripts/rfc2544_tput_test.lua#L57 and https://github.com/pktgen/Pktgen-DPDK/blob/54731bf0d84a9dcd5bf401a6dda98b591e710413/scripts/rfc2544_tput_test.lua#L58

As a consequence, the `num_dropped` variable reflects the global dropped packets from the beginning of the test, and not from the single run.

**Comment by pktgen** [comment]
Pull the ‘dev’ branch and give it a try. I think it will fix the stats clearing problem.

**Comment by sebymiano** [comment]
> Pull the ‘dev’ branch and give it a try. I think it will fix the stats clearing problem.

Yep! Now the issue is gone. Thanks for the fix.
