### ISSUE TITLE
pktgen does not want to start transmitting

### ISSUE THREAD

**Issue by kaminek** [pktgen/Pktgen-DPDK#27]
Hi all,
I installed dpdk pktgen 2.8.4 on 2 vms , one with virtio driver and the other with e1000.
dpdk is working fine , but when i launch pktgen with : 
./app/app/x86_64-native-linuxapp-gcc/app/pktgen -c 1 -n 1 --proc-type auto -- -p 0x1 -P -f test/set_seq.lua -m="0.0"
and i get pktgen CLI , it's ok but after that i got some issues 
first the config in the set_seq.lua file isn't up (i had to reconfigure all things ), and the main issues is that the pktgen doen't want to start transmitting although i used "start 0"
thanks for reply

**Comment by pktgen** [comment]
Using the -m "0.0" will not work you can not use the first core for Rx/Tx. The master lcore is just for display and timers in pktgen. You need to use at least 2 lcores with -m "1.0".

**Comment by kaminek** [comment]
Hi, thanks for reply,
now i have 3cpus for the Vm, and i used 2 for pktgen as you said -c 3 with -m"1.0", but it still not working :/

**Comment by pktgen** [comment]
What is you full command line now?

**Comment by kaminek** [comment]
this is the full cmd :
./app/app/x86_64-native-linuxapp-gcc/app/pktgen -c 3 -n 2 --proc-type auto -- -p 0x1 -P -m="1.0"

**Comment by kaminek** [comment]
i had a warning on launching pktgen i don't know if it's important but 

PMD: eth_em_rx_init(): forcing scatter mode
PMD: eth_em_start(): <<
Port  0: Link Up - speed 1000 Mbps - full-duplex <Enable promiscuous mode>
=== Display processing on lcore 0
WARNING: Nothing to do on lcore 1: exiting

**Comment by pktgen** [comment]
The -p 0x01 is not required anymore in the Pktgen 2.8.5-2

**Comment by pktgen** [comment]
Yes, that is a very important warning. This means the -m �1.0� which means
the lcore 1 is not managing the Rx/TX for port 0.

Can you send me the complete output from startup.

**Comment by kaminek** [comment]
this is the complet output : 
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 3 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up memory...
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7fab36c00000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7fab36800000 (size = 0x200000)
EAL: Ask a virtual area of 0x1fc00000 bytes
EAL: Virtual area found at 0x7fab16a00000 (size = 0x1fc00000)
EAL: Requesting 256 pages of size 2MB from socket 0
EAL: TSC frequency is ~3392298 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=37faf900;cpuset=[0])
PMD: ENICPMD trace: rte_enic_pmd_init
EAL: lcore 1 is ready (tid=161fe700;cpuset=[1])
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   PCI memory mapped at 0x7fab36e00000
PMD: eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x100e
=1.0             lcores: RX( 0 )TX( 0 ) ports: RX( 0 )TX( 0 )

Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
>>> Packet Burst 32, RX Desc 512, TX Desc 512, mbufs/port 4096, mbuf cache 512

=== port to lcore mapping table (# lcores 2) ===
   lcore:     0     1 
port   0:  D: T  0: 0 =  1: 1
Total   :  1: 1  0: 0
    Display and Timer on lcore 0, rx:tx counts per port/lcore

Configuring 1 ports, MBUF Size 1920, MBUF Cache Size 512
Lcore:
    0, RX-TX  
                RX( 1): ( 0: 0) 
                TX( 1): ( 0: 0) 

Port :
    0, nb_lcores  1, private 0x85f9d0, lcores:  0 



** Dev Info (rte_em_pmd:0) **
   max_vfs        :   0 min_rx_bufsize    : 256 max_rx_pktlen : 16128 max_rx_queues         :   1 max_tx_queues:   1
   max_mac_addrs  :  15 max_hash_mac_addrs:   0 max_vmdq_pools:     0
   rx_offload_capa:   0 tx_offload_capa   :   0 reta_size     :     0 flow_type_rss_offloads:0000000000000000
   vmdq_queue_base:   0 vmdq_queue_num    :   0 vmdq_pool_base:     0
** RX Conf **
   pthreash       :   0 hthresh          :   0 wthresh        :     0
   Free Thresh    :   0 Drop Enable      :   0 Deferred Start :     0
** TX Conf **
   pthreash       :   0 hthresh          :   0 wthresh        :     0
   Free Thresh    :   0 RS Thresh        :   0 Deferred Start :     0 TXQ Flags:00000000

Initialize Port 0 -- TxQ 1, RxQ 1,  Src MAC 52:54:00:40:f8:14
    Create: Default RX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 1581248 =   9737 KB
PMD: eth_em_rx_queue_setup(): sw_ring=0x7fab174eb380 hw_ring=0x7fab36c31500 dma_addr=0x431500

    Create: Default TX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 1581248 =   9737 KB
    Create: Range TX    0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 1581248 =   9737 KB
    Create: Sequence TX 0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 1581248 =   9737 KB
    Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 1581248 =   1673 KB
PMD: eth_em_tx_queue_setup(): sw_ring=0x7fab174e8e80 hw_ring=0x7fab369a1100 dma_addr=0xfa1100

                                                                       Port memory used =  40617 KB
                                                                      Total memory used =  40617 KB
PMD: eth_em_rx_init(): forcing scatter mode
PMD: eth_em_start(): <<
Port  0: Link Up - speed 1000 Mbps - full-duplex <Enable promiscuous mode>


=== Display processing on lcore 0
WARNING: Nothing to do on lcore 1: exiting

**Comment by kaminek** [comment]
and my Cpus : 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                3
On-line CPU(s) list:   0-2
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             3
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Stepping:              7
CPU MHz:               3392.292
BogoMIPS:              6784.58
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-2

**Comment by pktgen** [comment]
Remove the �=� in the command line -m �1.0� I am thinking that is causing
Pktgen to think lcore 0 is the manager of the port 0.

**Comment by kaminek** [comment]
Yes this is it , thank you so much , i was having trouble since one month.
Great Job man , well done for this project

**Comment by pktgen** [comment]
Thanks for sticking with me, with all of my traveling last week. Glad it
works :-)
