### ISSUE TITLE
dpdk-version.sh does not work with new version of DPDK

### ISSUE THREAD

**Issue by Binary-Vanguard-12138** [pktgen/Pktgen-DPDK#273]
`dpdk-version.sh` tries to open and parse `dpdk/lib/librte_eal/common/include/rte_version.h`.
But this file moved to `dpdk/lib/eal/include/rte_version.h` in the new version of DPDK.

**Comment by KeithWiles** [comment]
Looks like we need to update the script to try both locations to support older DPDK version :-(

**Comment by KeithWiles** [comment]
Looking at the script it has a number of issues as the information in is now contained in two files rte_config.h and rte_build_config.h. This script is not used anymore inside Pktgen and it appears it was created back in 2017.

Pktgen only builds against the installed version of DPDK anyway, so I am going to remove the script unless you have an objection.

**Comment by Binary-Vanguard-12138** [comment]
> Looking at the script it has a number of issues as the information in is now contained in two files rte_config.h and rte_build_config.h. This script is not used anymore inside Pktgen and it appears it was created back in 2017.
> 
> Pktgen only builds against the installed version of DPDK anyway, so I am going to remove the script unless you have an objection.

Yeah, that should be fine. I have no objection.

**Comment by KeithWiles** [comment]
Ok, thanks. I will remove it in an upcoming update. I will close this issue.
