### ISSUE TITLE
Pktgen works when not sending pcap, but fails when sending pcap

### ISSUE THREAD

**Issue by ldnelson16** [pktgen/Pktgen-DPDK#274]
For example: a working command is: sudo -E ./usr/local/bin/pktgen -l 1-3 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 02:00.0 -- -v -T -P -m [2].0 -f themes/black-yellow.theme

vs a non-working one: sudo -E ./usr/local/bin/pktgen -l 1-3 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 02:00.0 -- -v -T -P -m [2].0 -f themes/black-yellow.theme -s 0:pcap/test1.pcap

The error occurs at pktgen_clear_stats called in pktgen_config_ports, and the error manifests within the eth_igc_stats_get call many function calls deep. 

It seems to fail in reading registers from the NIC. 

While the failed aspect is in part more DPDK, it only happens when I use pktgen. DPDK testpmd works just fine. 
I have no theories as to what could be wrong. Any ideas?

**Comment by KeithWiles** [comment]
In the function pktgen_clear_stats() it is calling rte_eth_stats_get() with pinfo->pid could be -1 (or 65535) most likely 2 and causes the igb driver to crash as the port id is invalid. I guess it is possible that testpmd is forcing the value to or something when it calls rte_eth_stats_get().

The following function is called in testpmd to validate a port_id.

```c
int
port_id_is_invalid(portid_t port_id, enum print_warning warning)
{
        uint16_t pid;

        if (port_id == (portid_t)RTE_PORT_ALL)
                return 0;

        RTE_ETH_FOREACH_DEV(pid)
                if (port_id == pid)
                        return 0;

        if (warning == ENABLED_WARN)
                fprintf(stderr, "Invalid port %d\n", port_id);

        return 1;
}
```

The define RTE_PORT_ALL is uint16_t 0xFFFF or -1, which the above will return 0 or 1 if not found.

Do not see the problem yet, in this quick look. Something must be something pktgen is not doing that testpmd is doing???

Also the command line by adding the pcap file option seems to be a trigger for this error, testpmd does not support pcap in this way. It seems to start pointer to a memory overrun someplace.

**Comment by ldnelson16** [comment]
It seems that my pid is 0, but it somehow goes back to initializing the hardware access struct (for this driver it is of type igc_hw)
That would indicate to me it is more of a DPDK error, but it works correctly without the pcap attached to the EAL parameters. 

For example, around line 1348 in igc_ethdev.c, it assigns the important variables to this struct, but when I run the command below using pcap, it overwrites the hw_addr pointer, invalidating the ability to read/write the device. I will post on DPDK I guess, although I am still unsure what the nature of the problem even is.


> Also the command line by adding the pcap file option seems to be a trigger for this error, testpmd does not support pcap in this way. It seems to start pointer to a memory overrun someplace.

In regards to this, sorry I think I miswrote, I am trying (and failing) to run this: 
 >> sudo -E ./usr/local/bin/pktgen -l 1-3 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 02:00.0 -- -v -T -P -m [2].0 -f themes/black-yellow.theme -s 0:pcap/test1.pcap

... but simply removing the '-s 0:pcap/test1.pcap' allows it to successfully run.

**Comment by KeithWiles** [comment]
Having the pcap option should not effect or cause the system to crash. It seems to me the pcap code in Pktgen is corrupting something by doing some type of overrun of a buffer. 

What is the size and number of packets in the pcap file as pktgen has a limitation on the number of packet to be supported?

**Comment by ldnelson16** [comment]
It is one of the sample pcap files provided by pktgen. It is 8 KB, 28 packets. Size shouldn't be an issue I imagine. Does this have something to do with hugepages?

**Comment by KeithWiles** [comment]
It should not have anything to do with hugepages, unless you run out of hugepages for all applications. If not use hugepages this should be OK as well.

**Comment by ldnelson16** [comment]
It corrupts itself inside of rte_mempool_obj_iter, called by pktgen_pcap_open (which is called during input of EAL parameters). Inside of rte_mempool_obj_iter, simply removing this line: obj_cb(mp, obj_cb_arg, obj, n), allows it to get through the initialization phase, but from interactive pktgen command line, it says that the PCAP file is not loaded on port 0.

**Comment by KeithWiles** [comment]
Great, that is what we needed. The pcap buffers are not inited or the data from the pcap file is not copied into the mbuf and a counter is setup to detect if pcap on a port is setup.

**Comment by KeithWiles** [comment]
In the file app/pktgen-pcap.c function mbuf_iterate_cb() is what the mempool iter is calling. Need to print out the hdr.incl_len as no checks are done for the length and may be convert the endianness incorrectly.

**Comment by ldnelson16** [comment]
Will continue looking, but this call ...

> if (fread(rte_pktmbuf_mtod(m, char *), 1, hdr.incl_len, pcap->fp) == 0)  rte_exit(EXIT_FAILURE, "%s: failed to read packet data from PCAP file\n", __func__); // located in mbuf_iterate_cb

... is what causes everything to go invalid. The if doesn't trigger anything to happen, but it invalidates information about the pcap and the struct that allows memory access of the NIC which has been the problem, idk why. 

hdr.incl_len when being fed to this function is 1040187392 which obviously seems wrong, however it is 62 before this call ... 

> pcap_convert(pcap, &hdr);

**Comment by ldnelson16** [comment]
> hdr.incl_len = 1040187392

**Comment by KeithWiles** [comment]
Value is 0x3e000000 and this is the wrong endian and it should be 0x3e, can you do a file command on the pcap file. Plus is the machine you are running on Big Endian or Little?

**Comment by ldnelson16** [comment]
> can you do a file command on the pcap file

file pktgen-dpdk/pcap/test1.pcap 
pktgen-dpdk/pcap/test1.pcap: pcap capture file, microsecond ts (little-endian) - version 2.4 (Ethernet, capture length 65535)

> Plus is the machine you are running on Big Endian or Little?

Device is Little Endian

**Comment by KeithWiles** [comment]
Please give the branch fix-pcap-crash a test drive. It turns out the size of each mbuf was not accounting for the mbuf header size :-(

**Comment by ldnelson16** [comment]
This does fix my issue, thank you Keith. :)
