### ISSUE TITLE
Pktgen throws Segment Fault in save any .lua

### ISSUE THREAD

**Issue by WENPIN1** [pktgen/Pktgen-DPDK#275]
Pktgen throws Segment Fault in save any .lua
<img width="984" alt="截圖 2024-08-08 15 11 11" src="https://github.com/user-attachments/assets/a2d23646-9e7b-4da1-9971-8367b4e513ba">

command:
pktgen -l 0,1-16 -n 8 -m 13000 -a 8a:00.0 -- -T -P -m "[1-8:9-16].0" --txd=4096 --rxd=2048

env.
Pktgen 24.07.0  Powered by DPDK 23.11.1

Suspected code 
pktgen_lua_save

https://github.com/pktgen/Pktgen-DPDK/blob/2c8819d2b1364e8144e7bac5c8ae5ce428f5801f/app/pktgen-cmds.c#L467
for (i = 0; i < RTE_MAX_ETHPORTS; i++) { // 

Is using  'pktgen.nb_ports' available instead ?

Thank you!
-Patrick

**Comment by KeithWiles** [comment]
I do not see why not, please give it a try.

**Comment by WENPIN1** [comment]
Thank you for your handsome reply!
It did work after replacement. (alignment with pktgen_script_save function ?)
```
/* for (i = 0; i < RTE_MAX_ETHPORTS; i++) { */
    for (i = 0; i < pktgen.nb_ports; i++) {
```
Thank you again!

We may close this issue if available.

-Patrick

**Comment by KeithWiles** [comment]
Thank you.
