### ISSUE TITLE
Get old version of Pktgen-DPDK

### ISSUE THREAD

**Issue by qcy1024** [pktgen/Pktgen-DPDK#276]
I got this error while I build Pktgen-DPDK with ninja:

../app/pktgen-port-cfg.h:374:10: error: ‘RTE_ETH_TX_OFFLOAD_MBUF_FAST_FREE’ undeclared (first use in this function); did you mean ‘DEV_TX_OFFLOAD_MBUF_FAST_FREE’?
  374 |         {RTE_ETH_TX_OFFLOAD_MBUF_FAST_FREE, _(MBUF_FAST_FREE)},
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          DEV_TX_OFFLOAD_MBUF_FAST_FREE
../app/pktgen-port-cfg.h:375:10: error: ‘RTE_ETH_TX_OFFLOAD_SECURITY’ undeclared (first use in this function); did you mean ‘DEV_TX_OFFLOAD_SECURITY’?
  375 |         {RTE_ETH_TX_OFFLOAD_SECURITY, _(SECURITY)},
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          DEV_TX_OFFLOAD_SECURITY
../app/pktgen-port-cfg.h:376:10: error: ‘RTE_ETH_TX_OFFLOAD_UDP_TNL_TSO’ undeclared (first use in this function); did you mean ‘DEV_TX_OFFLOAD_UDP_TNL_TSO’?
  376 |         {RTE_ETH_TX_OFFLOAD_UDP_TNL_TSO, _(UDP_TNL_TSO)},
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          DEV_TX_OFFLOAD_UDP_TNL_TSO
../app/pktgen-port-cfg.h:377:10: error: ‘RTE_ETH_TX_OFFLOAD_IP_TNL_TSO’ undeclared (first use in this function); did you mean ‘DEV_TX_OFFLOAD_IP_TNL_TSO’?
  377 |         {RTE_ETH_TX_OFFLOAD_IP_TNL_TSO, _(IP_TNL_TSO)},
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          DEV_TX_OFFLOAD_IP_TNL_TSO
../app/pktgen-port-cfg.h:378:10: error: ‘RTE_ETH_TX_OFFLOAD_OUTER_UDP_CKSUM’ undeclared (first use in this function); did you mean ‘DEV_TX_OFFLOAD_OUTER_UDP_CKSUM’?
  378 |         {RTE_ETH_TX_OFFLOAD_OUTER_UDP_CKSUM, _(OUTER_UDP_CKSUM)},
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          DEV_TX_OFFLOAD_OUTER_UDP_CKSUM
ninja: build stopped: subcommand failed.

My dpdk version is 20.11.10, Pktgen-DPDK is got with`git clone http://dpdk.org/git/apps/pktgen-dpdk`.
It looks like it has some version conflicts with my dpdk. I have enough reson to use dpdk20.11.10, I don't know how to get old version of pktgen-dpdk, so what can I do? Can I solve my problem by get old version of pktgen-dpdk?

**Comment by KeithWiles** [comment]
The only option is to use git to check out the older versions of ptkgen, clone the repo and do `git tags` to list tags and checkout an older version.

**Comment by KeithWiles** [comment]
Please use the repo on GitHub as sometimes DPDK version is not updated as often.
https://github.com/pktgen/Pktgen-DPDK
