### ISSUE TITLE
illegal instruction in "in numa_nodeX_cpus" with standard build - and other crash with debug: caused by gcc option -mavx

### ISSUE THREAD

**Issue by Golvanig** [pktgen/Pktgen-DPDK#28]
Hello,
This is my first trial with pktgen. Sorry if I forgot some major points.

I am using a bare Ubuntu 20.04 (not a VM) - (Ubuntu 9.3.0-10ubuntu2)
I compiled DPDK tags 'v20.08'
and it works with my setup vfio-pci with 2 SFP+ 

I have my two interfaces binded

-----------------------------------------
dpdk-devbind.py -s
     Network devices using DPDK-compatible driver

    0000:05:00.0 'Ethernet Connection X553 10 GbE SFP+ 15c4' drv=vfio-pci unused=ixgbe
    0000:05:00.1 'Ethernet Connection X553 10 GbE SFP+ 15c4' drv=vfio-pci unused=ixgbe

--------------------------------------
I updated the default.cfg file (by the way some 'cfg' needs missing comma :)

1) When I use the standard build
I got straight an Illegal Instruction 
since this is not a debug build I tried gdb and got only this message "
Program received signal SIGILL, Illegal instruction.
0x0000555555595355 in numa_nodeX_cpus ()
"
2) When I use the debug build
I can get the CLI input. **BUT** pkgen crashes as soon as I type more that 16 chars in the cli with 'Illegal Instruction' 
at:
Thread 1 "pktgen" received signal SIGILL, Illegal instruction.
0x00005555556696e5 in _mm_loadu_si128 (__P=0x555555885690) at /usr/lib/gcc/x86_64-linux-gnu/9/include/emmintrin.h:703
703	  return *__P;

-----------------------------------------------------------------

Here is the build trace:
./tools/pktgen-build.sh clean
>>> lua_enabled      : '-Denable_lua=false'
>>> gui_enabled      : '-Denable_gui=false'
>>> SDK Directory    : '/opt/pktgen'
>>> Build Directory  : '/opt/pktgen/Builddir'
>>> Target Directory : '/opt/pktgen/usr'

*** Removing '/opt/pktgen/Builddir' directory
*** Removing '/opt/pktgen/usr' directory
./tools/pktgen-build.sh debug
>>> lua_enabled      : '-Denable_lua=false'
>>> gui_enabled      : '-Denable_gui=false'
>>> SDK Directory    : '/opt/pktgen'
>>> Build Directory  : '/opt/pktgen/Builddir'
>>> Target Directory : '/opt/pktgen/usr'

>>> Ninja build in '/opt/pktgen/Builddir' buildtype='debug'
meson -Dbuildtype=debug -Denable_lua=false -Denable_gui=false Builddir
The Meson build system
Version: 0.53.2
Source dir: /opt/pktgen
Build dir: /opt/pktgen/Builddir
Build type: native build
Program cat found: YES (/usr/bin/cat)
Project name: pktgen
Project version: 20.08.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-pedantic -Wpedantic: YES 
Compiler for C supports arguments -Wno-format-truncation -Wformat-truncation: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libdpdk found: YES 20.08.0
Program python3 found: YES (/usr/bin/python3)
Run-time dependency threads found: YES
Library numa found: YES
Library pcap found: YES
Library dl found: YES
Library m found: YES
Program sphinx-build found: NO
Build targets in project: 8

Option buildtype is: debug [default: release]
Found ninja-1.10.0 at /usr/bin/ninja
ninja: Entering directory `/opt/pktgen/Builddir'
[66/66] Linking target app/pktgen.
>>> Ninja install to '/opt/pktgen/usr'
__________________________________________________
Thanks for your support

**Comment by pktgen** [comment]
What is the pktgen config file or command line you are using? If using a .cfg file please paste it in your response. Are you running pktgen as sudo if you are crafting the command line without using the ‘./tools/run.py default’ script?

Another question it seems everyone is using the ./tools/pktgen-build.sh script directly. Why is that, when ‘make clean debug’ would work too?

Also I am about to release 20.09 version of pktgen, which you can try doing a ‘git co dev’ if you did a git clone of the repo.

**Comment by Golvanig** [comment]
Thanks for this very fast reply.
I joined the default I am using, but I also tried with direct command.

Not sure I understand your comment about using (or not) pkgtgen-build.sh
I am not :). I mean, I am using the make ...
By the way, we need to hack it to have lua + debug ...

I tried the dev -- Pktgen 20.09.0 (DPDK 20.08.0) , but this did not change anything. Not sure the modifications are related to the "issues" I got.

Ready to help, and try... Do not hesitate.

My goal is to use pktgen instead of TRex for a stateless 5GB test.
And to use pktgen remotely with the most appropriate method (not sure I am clear today about which is the appropriate for pktgen). I will have to vary parameters, etc...

Thanks again.

[default.cfg.txt](https://github.com/pktgen/Pktgen-DPDK/files/5169977/default.cfg.txt)

**Comment by Golvanig** [comment]
As a complement:

in "DEBUG" I can "launch*" this command with the parameters (removing the -m ...)
sudo -E ./usr/local/bin/pktgen -l 2,3-4,5-6 -n 4 --proc-type auto --log-level 7 --file-prefix pg -w 05:00.1 -w 05:00.0 -- -v -T -P -j 

If I add
-m [3:4].0 -m [5:6].1 
it crashes 'directly'

If I add -f themes/black-yellow.theme
then it crashes in the "CLI issue" and consider only the first 16 letters
**theme default wh**Illegal instruction

The CLI issue is reproducible by entering letters interactively or by the -f parameters...

launch*: means I get the Interactive CLI, but after 16 letters, it crashes.
I though played and appreciated all the short commands :+1:

**Comment by pktgen** [comment]
OK, mistake on the build script.

OK, pktgen side seems OK.

The next step is to look at the DPDK build. I assume you are doing the follow commands to build dpdk and pktgen

# cd dpdk
# meson builddir
# ninja -C builddir
# sudo ninja -C builddir install

# cd pktgen
# make rebuild

Make sure you do not have an old DPDK installed someplace.

**Comment by Golvanig** [comment]
Well, Yes close.
I built dpdk in debug mode (but I also tried in standard with the same result :( )
sudo meson -Dbuildtype=debug build 
...
sudo ldconfig

There is no other dpdk installed.
BUT what seems strange is that though I have a VERSION as 20.08.0 the libraries built and installed by ninja are tagged 20.0.3
 I will investigate this.

**Comment by Golvanig** [comment]
Hello,
I retried this morning with the source package "dpdk-20.08.tar.xz" (instead of tagged git )
And I do have the exact same issues, and information 

I do not know where I should now investigate....
KR
Thierry

**Comment by pktgen** [comment]
Can you run test-pmd DPDK application?

If you can't then it seems the image being created in DPDK is trying to use instructions that are not allowed on your hardware. If test-pmd works and runs then, I do not know how to debug the problem. If test-pmd also fails with the same SIGV then please send an email to users@dpdk.org and ask them. Do not state anything about Pktgen as they will most likely ignore your email expecting me to handle the question.

**Comment by Golvanig** [comment]
Thanks,

Since this morning I am using  dpdk-testpmd. I did not get any issue with it, and use the same exact binding.

**Comment by pktgen** [comment]
Can you run pktgen without the -j option as that turns on jumbo frames, did you need jumbo frames enabled?

Also does test-pmd enable jumbo frames?

**Comment by pktgen** [comment]
Can you send me a copy of the startup text when you start pktgen?

If you get to the CLI then please quit and copy that too.

**Comment by Golvanig** [comment]
I used -j at the end since this was added by run.py, but at start I was not using it.

Here is a simplified launch:

**$ sudo -E ./usr/local/bin/pktgen  --log-level 7 --file-prefix pg -w 05:00.1 -w 05:00.0 -- -v -T -P** 

Copyright (c) <2010-2020>, Intel Corporation. All rights reserved. Powered by DPDK
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/pg/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL:   Invalid NUMA socket, default to 0
EAL:   using IOMMU type 1 (Type 1)
EAL: Probe PCI driver: net_ixgbe (8086:15c4) device: 0000:05:00.0 (socket 0)
EAL:   Invalid NUMA socket, default to 0
EAL: Probe PCI driver: net_ixgbe (8086:15c4) device: 0000:05:00.1 (socket 0)
EAL: No legacy callbacks, legacy socket not created

*** Copyright (c) <2010-2020>, Intel Corporation. All rights reserved.
*** Pktgen  created by: Keith Wiles -- >>> Powered by DPDK <<<

>>> Packet Burst 64, RX Desc 1024, TX Desc 2048, mbufs/port 16384, mbuf cache 2048
 Port: Name         IfIndex Alias        NUMA  PCI
    0: net_ixgbe       0                   0   8086:15c4/05:00.0
    1: net_ixgbe       0                   0   8086:15c4/05:00.1


=== port to lcore mapping table (# lcores 3) ===
   lcore:    0       1       2      Total
Total   : ( 0: 0) ( 0: 0) ( 0: 0)
  Display and Timer on lcore 0, rx:tx counts per port/lcore

>>>> Configuring 2 ports, MBUF Size 9746, MBUF Cache Size 2048
Lcore:

Port :


                                                                      Total memory used =      0 KB

**Comment by pktgen** [comment]
sudo -E ./usr/local/bin/pktgen -l 2,3-4,5-6 -n 4 --proc-type auto --log-level 7 --file-prefix pg -w 05:00.1 -w 05:00.0 -- -v -T -P -m [3:4].0 -m [5:6].1

The -m values are required and the -l option is required here too. Test-pmd does not require it, but pktgen does. Run this command and send me the output.

How many hugepages do you have setup? Pktgen does require a fair number of 2MB update pages I think 128 is the min number.

**Comment by Golvanig** [comment]
I tried before but it crashes :(
Just for info I isolated with isolcpus the last 6 cores " isolcpus=2,3,4,5,6,7"

sudo -E ./usr/local/bin/pktgen -l 2,3-4,5-6 -n 4 --proc-type auto --log-level 7 --file-prefix pg -w 05:00.1 -w 05:00.0 -- -v -T -P -m [3:4].0 -m [5:6].1

Copyright (c) <2010-2020>, Intel Corporation. All rights reserved. Powered by DPDK
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /var/run/dpdk/pg/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL:   Invalid NUMA socket, default to 0
EAL:   using IOMMU type 1 (Type 1)
EAL: Probe PCI driver: net_ixgbe (8086:15c4) device: 0000:05:00.0 (socket 0)
EAL:   Invalid NUMA socket, default to 0
EAL: Probe PCI driver: net_ixgbe (8086:15c4) device: 0000:05:00.1 (socket 0)
EAL: No legacy callbacks, legacy socket not created

*** Copyright (c) <2010-2020>, Intel Corporation. All rights reserved.
*** Pktgen  created by: Keith Wiles -- >>> Powered by DPDK <<<

>>> Packet Burst 64, RX Desc 1024, TX Desc 2048, mbufs/port 16384, mbuf cache 2048
 Port: Name         IfIndex Alias        NUMA  PCI
    0: net_ixgbe       0                   0   8086:15c4/05:00.0
    1: net_ixgbe       0                   0   8086:15c4/05:00.1


=== port to lcore mapping table (# lcores 5) ===
   lcore:    2       3       4       5       6      Total
port   0: ( D: T) ( 1: 0) ( 0: 1) ( 0: 0) ( 0: 0) = ( 1: 1)
port   1: ( D: T) ( 0: 0) ( 0: 0) ( 1: 0) ( 0: 1) = ( 1: 1)
Total   : ( 0: 0) ( 1: 0) ( 0: 1) ( 1: 0) ( 0: 1)
  Display and Timer on lcore 2, rx:tx counts per port/lcore

>>>> Configuring 2 ports, MBUF Size 9746, MBUF Cache Size 2048
Lcore:
    3, RX-Only
                RX_cnt( 1): (pid= 0:qid= 0) 
    4, TX-Only
                TX_cnt( 1): (pid= 0:qid= 0) 
    5, RX-Only
                RX_cnt( 1): (pid= 1:qid= 0) 
    6, TX-Only
                TX_cnt( 1): (pid= 1:qid= 0) 

Port :
    0, nb_lcores  2, private 0x55a0c7bfed68, lcores:  3  4 
    1, nb_lcores  2, private 0x55a0c7c025a8, lcores:  5  6 


Initialize Port 0 -- TxQ 1, RxQ 1
**Illegal instruction**


I have 256 pages defined in my /etc/sysctl.conf

**Comment by pktgen** [comment]
I do not use isolcpus at all. Does this happen without the isolcpus ?

**Comment by Golvanig** [comment]
Yes 
It happens also without the isolcpu.

I introduced the isolcpu this afternoon with the dpdk-testpmd to see if this has any effect of performance.
I was just referring to isolcpu for the -m parameters 

Sorry to perturbate you with this.
I can remove it. But it crashed before.

**Comment by pktgen** [comment]
The only thing we can do now is add a sleep(10) to some place in main() then attach gdb to the process and try to debug the problem with breakpoints and stepping thru the code.

Do you know how to do that ?

**Comment by Golvanig** [comment]
Hello Keith,
:)
I installed dpdk and pktgen on my linux laptop (debian bullseye, ..)
and it works.
Then I guess there is something specific with the "DELL VEP1445" I plan to use as my traffic generator.
I will investigate, and may need your help if the future.
Many thanks for your very fast support.
Kr,
Thierry

**Comment by Golvanig** [comment]
Hi again,
I finally found the point.
I replaced the gcc optimization written in meson.build (-mavx) by a 'lower one' (-O3).
And now pktgen works 
..
Well now I have to tune my memory issue :)
But this is another story 

!PANIC!: Cannot create mbuf pool (Rate TX     0:0) port 0, queue 0, nb_mbufs 16384, socket_id 0: Cannot allocate memory
PANIC in pktgen_mbuf_pool_create():
Cannot create mbuf pool (Rate TX     0:0) port 0, queue 0, nb_mbufs 16384, socket_id 0: Cannot allocate memory

**Comment by Golvanig** [comment]
Wrong gcc compilation option

**Comment by vincentmli** [comment]
I ran into similar issue and found this report, I also had to disable avx2 option, my server is kind of old Dell 730 with Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz that does not have avx flag, I guess maybe that is the reason?

<pre>

processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping	: 2
microcode	: 0x1f
cpu MHz		: 2572.925
cache size	: 12288 KB
physical id	: 0
siblings	: 8
core id		: 10
cpu cores	: 4
apicid		: 21
initial apicid	: 21
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4788.57


root@vli-lab:/tmp/pktgen-build# gdb pktgen
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pktgen...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/pktgen 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".



Copyright(c) <2010-2021>, Intel Corporation. All rights reserved. Powered by DPDK

Program received signal SIGILL, Illegal instruction.
0x0000555555590bb0 in numa_nodeX_cpus ()
(gdb) bt
#0  0x0000555555590bb0 in numa_nodeX_cpus ()
#1  0x000055555559125f in lscpu_info ()
#2  0x000055555557f39a in pktgen_cpu_init ()
#3  0x000055555555ceba in main ()


build steps to disable avx2:

meson /usr/src/pktgen-dpdk pktgen-build
cd pktgen-build/
meson configure -Denable-avx2=false
ninja -j1 -v
ninja install

root@vli-lab:/tmp/pktgen-build# pktgen

Copyright(c) <2010-2021>, Intel Corporation. All rights reserved. Powered by DPDK
EAL: Detected 16 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: No available 1048576 kB hugepages reported
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)
EAL: Ignore mapping IO port bar(2)
EAL: Probe PCI driver: net_ixgbe (8086:10fb) device: 0000:04:00.0 (socket 0)
EAL: Ignore mapping IO port bar(2)
EAL: Probe PCI driver: net_ixgbe (8086:10fb) device: 0000:04:00.1 (socket 0)
TELEMETRY: No legacy callbacks, legacy socket not created

*** Copyright(c) <2010-2021>, Intel Corporation. All rights reserved.
*** Pktgen  created by: Keith Wiles -- >>> Powered by DPDK <<<

 Port: Name         IfIndex Alias        NUMA  PCI
    0: net_ixgbe       0                   0   8086:10fb/04:00.0
    1: net_ixgbe       0                   0   8086:10fb/04:00.1



WARNING: Nothing to do on lcore 1: exiting
WARNING: Nothing to do on lcore 2: exiting
WARNING: Nothing to do on lcore 3: exiting
WARNING: Nothing to do on lcore 4: exiting
WARNING: Nothing to do on lcore 5: exiting
WARNING: Nothing to do on lcore 6: exiting
WARNING: Nothing to do on lcore 7: exiting
WARNING: Nothing to do on lcore 8: exiting
WARNING: Nothing to do on lcore 9: exiting
WARNING: Nothing to do on lcore 10: exiting
WARNING: Nothing to do on lcore 11: exiting
WARNING: Nothing to do on lcore 12: exiting
WARNING: Nothing to do on lcore 13: exiting
WARNING: Nothing to do on lcore 14: exiting
WARNING: Nothing to do on lcore 15: exiting

- Ports 0-1 of 2   <Main Page>  Copyright(c) <2010-2021>, Intel Corporation
  Flags:Port        : 
Link State          :     ---Total Rate---
Pkts/s Rx           :                    0
       Tx           :                    0
MBits/s Rx/Tx       :                  0/0
Pkts/s Rx Max       :                    0
       Tx Max       :                    0
Broadcast           : 
Multicast           : 
Sizes 64            : 
      65-127        : 
      128-255       : 
      256-511       : 
      512-1023      : 
      1024-1518     : 
Runts/Jumbos        : 
ARP/ICMP Pkts       : 
Errors Rx/Tx        : 
Total Rx Pkts       : 
      Tx Pkts       : 
      Rx/Tx MBs     : 
Pattern Type        : 
Tx Count/% Rate     : 
Pkt Size/Tx Burst   : 
TTL/Port Src/Dest   : 
Pkt Type:VLAN ID    : 
802.1p CoS/DSCP/IPP : 
VxLAN Flg/Grp/vid   : 
IP  Destination     : 
    Source          : 
MAC Destination     : 
    Source          : 
PCI Vendor/Addr     : 
-- Pktgen 21.03.0 (DPDK 21.05.0-rc0)  Powered by DPDK  (pid:9445) -------------


** Version: DPDK 21.05.0-rc0, Command Line Interface without timers
Pktgen:/> 

</pre>
