### ISSUE TITLE
Can not run multiple instances on the same machine.

### ISSUE THREAD

**Issue by Groundsea** [pktgen/Pktgen-DPDK#28]
Hi all,

From the readme, I saw such description
"A new feature for pktgen and DPDK is to run multiple instances of pktgen. This
allows the developer to share ports on the same machine."

But when I try to run multiple instances, it failed.

First, when I execute the command 2nd time, it report "Cannot create lock on '/var/run/.rte_config'. Is another primary process running?" so I modify the #define RUNTIME_CONFIG_FMT "%s/.%s_config" in DPDK after 1st pktgen started. then it doesn't report this failure again, but when 2nd instance is in starting, the 1st instance run segment fault.

the command I execute like below:
./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x1f -n 3 --proc-type auto --socket-mem 2048,2048 -b 0000:0a:02.1 -b 0000:0a:0a.1 --file-prefix pg -- -p 0x5 -P -m "[1:3].0, [2:4].1"
./pktgen1 -c 0x300E0 -n 3 --proc-type auto --socket-mem 2048,2048 -b 0000:0a:02.0 -b 0000:0a:0a.0 --file-prefix pg -- -p 0xA -P -m "[6:16].0, [7:17].1"

BTW: pktgen1 is built after I modify the MACRO RUNTIME_CONFIG_FMT.

Any help would be appreciated!

**Comment by zendes** [comment]
You shouldn't need to rebuild the source to make this work. Try starting both of them with --no-shconf and a different --file-prefix like pktgen1 & pktgen2

**Comment by pktgen** [comment]
Using the same prefix for both pktgens is the problem. The --no-shconf should not be required at least in my tests.

**Comment by Groundsea** [comment]
I have tried again, and just assign the different prefix is ok.
Thank you very much!

**Comment by tttd** [comment]
Sorry for this stupid question as I really quite dumb. I have 1 socket (socket 0) with 8 lcore and I want to run 2 instances of pktgen in loop back scenario which means 1 send/receive packets from the other and vice versa.
My 2 commands are:
./pktgen -c 0xB -n 3 --socket-mem 2048 --proc-type auto --file-prefix pg1 -- -P -m "[1:3].0"
and
./pktgen -c 0xB0 -n 3 --socket-mem 2048 --proc-type auto --file-prefix pg2 -- -P -m "[5:7].1"
in order of executing.
There was no problem until I started sending packet from port 0 (start 0) and nothing happened. Turning to port 1, it could send packets but port 0 didn't receive any single one. That's so suspicious.
Is there anything that I misunderstood?

One more thing, when I tried to blacklist port 0 on later command, it got segment fault with total memory = 0. Was it wrong with PCI memory mapping?

**Comment by pktgen** [comment]
Comment inline
�
Regards,
++Keith
Intel Corporation

**Comment by tttd** [comment]
Sorry if I get you wrong, as I understand setting [5:7].0 means lcore 5 and 7 will handle port 0, but what i want is using port 0 to port 1. So how is it possible?
And as I stated, the second command could execute with no problem, it even could send packets (that could be seen on display). What troublesome is first command, it did nothing (neither sending nor receiving). Can you please explain me that?

**Comment by pktgen** [comment]
Hi I am out of town till Wednesday and will have limited access to mail and a machine to test. The first command looked fine. Please run the dpdk_nic_bind.py --status and see what is attached.

**Comment by tttd** [comment]
Hi, 
Sorry for this late reply. Here below is what I got from dpdk_nic_bind.py.

Network devices using DPDK-compatible driver
============================================
0000:01:00.0 '82599EB 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=
0000:01:00.1 '82599EB 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:00:19.0 'Ethernet Connection I217-LM' if=eth1 drv=e1000e unused=igb_uio 
0000:04:00.0 'I210 Gigabit Network Connection' if=eth0 drv=igb unused=igb_uio *Active*

Other network devices
=====================
none

and those are the screenshot from my computer, after running such 2 commands mentioned previously. As you can see, port 0 did nothing as I said.

![screenshot from 2015-09-01 08_31_58](https://cloud.githubusercontent.com/assets/13888448/9596167/b2207ede-5025-11e5-90ad-22ef09bd10ac.png)
![screenshot from 2015-09-01 08_32_23](https://cloud.githubusercontent.com/assets/13888448/9596168/b222f466-5025-11e5-9b13-da69db7c59f6.png)

**Comment by pktgen** [comment]
I think I see the problem here, you need to make sure you blacklist the ports correctly from each version of DPDK running.
./pktgen -c 0xB -n 3 --socket-mem 2048 --proc-type auto --file-prefix pg1 -b 01:00.1 -- -P -m "[1:3].0"
and
./pktgen -c 0xB0 -n 3 --socket-mem 2048 --proc-type auto --file-prefix pg2 -b 01.00.0 -- -P -m "[5:7].0"

Note that we blacklist the port not used in each DPDK instance, plus pktgen starts at zero for the port numbers and the second one need to use '0' for the port number.

**Comment by tttd** [comment]
I feel so bad that despite executing exactly 2 commands that you wrote, I was stuck at segment fault. When I started any port/instance, the other got that error and quit immediately. As you can see from my pics, the version of pktgen and dpdk are 2.9.1 and 2.0.0, respectively. Is there any solution for my case?
I think this should be helpful: when I ran pktgen with l2fwd sample application (transmitting was disable) in loop back scenario, they both worked well, which meant l2fwd can receive all input packet sent from pktgen (according to statistic displayed on terminal).
