### ISSUE TITLE
Can Pktgen be used to send packets to the public IP address of another server?

### ISSUE THREAD

**Issue by lclliang** [pktgen/Pktgen-DPDK#280]
I have two network cards on Server A. One is used for login, and the other is bound to DPDK. When sending UDP packets to the internal IP of Server B, Server B can receive them. However, when sending UDP packets to the public IP of Server B, Server B cannot receive them.

Why might this be happening?

**Comment by KeithWiles** [comment]
If you have
Host-A <--> Server-A <--> Server-B <--> Host-B and sending from Server-A to Host-B then you need to make sure Server-B has IP forwarding enabled to allow sending to the other interface which had Host-B. That is the best I can figure out from the limited information.

**Comment by lclliang** [comment]
> If you have Host-A <--> Server-A <--> Server-B <--> Host-B and sending from Server-A to Host-B then you need to make sure Server-B has IP forwarding enabled to allow sending to the other interface which had Host-B. That is the best I can figure out from the limited information.

Hello, I have now enabled IP forwarding, but the test results show that when Server A's pktgen sends packets to Server B's public IP, Server B still cannot receive them.

**Comment by KeithWiles** [comment]
Does the interface on server B connected to server A see packets arriving? If it does then I do not know why it is not working.

The packets being sent from ServerA to ServerB interface must have the destination MAC address of the ServerB port connected to ServerA. Use wireshark or TCP dump on server B to verify the packets.
