### ISSUE TITLE
The MAC destination address shows abbormal on the version pktgen-24.05.2 and newer

### ISSUE THREAD

**Issue by siriChiu** [pktgen/Pktgen-DPDK#282]
I saw a wired MAC destination  address "00:00:00:00:00:00" on the pktgen TUI when I was doing the pktgen test in the newest pktgen version ([pktgen-24.07.1](https://github.com/pktgen/Pktgen-DPDK/releases/tag/pktgen-24.07.1)).

![pktgen_24_07_01](https://github.com/user-attachments/assets/ba973f14-ace3-46a4-9d5f-944b6389adeb)

And then I found the version [pktgen-24.05.0](https://github.com/pktgen/Pktgen-DPDK/releases/tag/pktgen-24.05.0) shows the address like I want
![pktgen_24_05_00](https://github.com/user-attachments/assets/0508847a-110d-411b-8a01-736dd9ea4d75)

[pktgen-24.05.2](https://github.com/pktgen/Pktgen-DPDK/releases/tag/pktgen-24.05.2) is the version started to become abnormal of this issue.

![pktgen_24_05_02](https://github.com/user-attachments/assets/b42f13be-9228-40e1-8113-df4702e176d9)

I don't know if there's a error in these changes, or if this is a corrected logic to say that the starting MAC destination address for port 1 as "00:00:00:00:00:00".

These are my tested ethernet devices:
- Intel Ethernet Controller E810-C
- Ethernet Controller X710 for 10GbE SFP+ 1572
- XGMAC 10GbE Controller 1458

I really hope someone can help me here.

Sincerity,

**Comment by KeithWiles** [comment]
Please have a look at branch fix-startup. I can't spend a lot of time on pktgen and this fix seems like a hack :-(

Give it a try and see if it fixes the problem and not create a new one.

**Comment by siriChiu** [comment]
Hi @KeithWiles,

Thanks for your sincere reply. After I try the version of fix-startup, the issue is no longer occurs.
![image](https://github.com/user-attachments/assets/bc554a94-efd2-44b5-b913-9565cfbd2f5e)

I hope this message finds you well. 
May I kindly ask when you plan to merge this fix into the new version, and could you please let me know if the next version (24.11) will include this fix?

Sincerity,

**Comment by KeithWiles** [comment]
Please look at fixes-for-release branch it should contain all of the fixes I am hoping to get done this month. I was waiting for a few other people to suggest the other fixes(branches) are work before merge. Thanks

**Comment by siriChiu** [comment]
Hi @KeithWiles,

Thanks for your reply. 
The branch, fixes-for-release, is fixed my issue, thanks again to you🙏.

**Comment by KeithWiles** [comment]
Please look at the new Pktgen release 24.10.0 and use the latest DPDK version as DPDK changed again, which caused compile problems.
