### ISSUE TITLE
Unable to set TCP flags

### ISSUE THREAD

**Issue by pchaseh** [pktgen/Pktgen-DPDK#284]
Hi,

I'm using this project with packets generated from an Lua script which appears as follows:
```lua
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"

require "Pktgen"

local seq_table = {
     ["eth_dst_addr"] = "xx:xx:xx:xx:xx:xx",
     ["eth_src_addr"] = "yy:yy:yy:yy:yy:yy",
     ["ip_dst_addr"] = "1.2.3.4",
     ["ip_src_addr"] = "4.3.2.1",
     ["sport"] = 9,
     ["dport"] = 10,
     ["ethType"] = "ipv4",
     ["ipProto"] = "tcp",
     ["vlanid"] = 11,
     ["pktSize"] = 128,
     ["tcp_flags"] = 2
 };
 pktgen.seqTable(0, "all", seq_table);
 pktgen.vlan("all", "enable");
 pktgen.set("all", "seqCnt", 1);
```

When I launch pktgen and run it (via `script myscript.lua` then `start all`) I'm seeing the generated TCP traffic still use `DEFAULT_TCP_FLAGS` (ACK) instead of the `tcp_flags` value. I'm not sure what representation it expects, but I've tried both the numerical value for the SYN flag (2) as well as `"S"` to no avail. Additionally, running `set all tcp flag set syn` yields no difference. When I recompile pktgen with `DEFAULT_TCP_FLAGS` set to `SYN_FLAG` it works, so it appears as if never overwrites the default value.

pktgen version: 24.07.0

**Comment by KeithWiles** [comment]
It looks like a bug, I see why it is not working and I will look at it this weekend.

**Comment by KeithWiles** [comment]
I think I have the TCP flags working, please give the fix-tcp-flags branch a try and let me know.

**Comment by pchaseh** [comment]
Thanks Keith, seems to be working a first glance, however I'm getting this crash when loading Lua scripts on the `fix-tcp-flags` branch when the `tcp_flags` field isn't specified. Likewise, if I change the IP protocol to UDP, it still occurs. I've verified that in switching over to `main`, recompiling, and relaunching pktgen, I don't see this problem

![Screenshot_5263](https://github.com/user-attachments/assets/2473d56b-80ec-46d0-b463-b7a7a151370d)

Note that my script doesn't start sending packets (that's left to the user), so appears to be an issue during packet initialization

**Comment by KeithWiles** [comment]
OK thanks, please try the fixes-for-release branch if you have time. It most likely will not fix this problem and it will take me a few days to be able to look into the problem.

**Comment by KeithWiles** [comment]
Please try the new Pktgen 24.10.0 release with the new DPDK release 24.11.0-rc1 DPDK changed and caused a compiler problem.
