### ISSUE TITLE
Unable to set ttl values using lua script

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#29]
I am able to change ttl values using set commands but when I try to do the same using lua script, I get below error

**lua-shell: data.lua:64: attempt to call a nil value (field 'ttl')
stack traceback:
	data.lua:64: in main chunk**

My lua script has below contents, please let me know if my command syntax is wrong or is there an issue with lua interface itself w.r.t setting ttl values, other values like dst_mac, dst_ip, src_mac, src_ip are working fine with lua script

pktgen.page("range");

pktgen.dst_mac("all", "start", "000d:49ef:016d");
pktgen.src_mac("all", "start", "000d:49ef:0163");

pktgen.delay(1000);
pktgen.dst_ip("all", "start", "10.10.10.1");
pktgen.dst_ip("all", "inc", "0.0.0.1");
pktgen.dst_ip("all", "min", "10.10.10.1");
pktgen.dst_ip("all", "max", "10.10.10.4");

pktgen.delay(1000);
pktgen.src_ip("all", "start", "20.20.20.1");
pktgen.src_ip("all", "inc", "0.0.0.1");
pktgen.src_ip("all", "min", "20.20.20.1");
pktgen.src_ip("all", "max", "20.20.20.8");

pktgen.delay(1000);
**pktgen.ttl("all", "start", 64);
pktgen.ttl("all", "inc", 0);
pktgen.ttl("all", "min", 64);
pktgen.ttl("all", "max", 64);**

**Comment by pktgen** [comment]
Hmm, seems some commands work for range without the correct calling syntax, will have to find out why later.

The working commands are:

pktgen.page("range");

pktgen.range.dst_mac("all", "start", "000d:49ef:016d");
pktgen.range.src_mac("all", "start", "000d:49ef:0163");

pktgen.delay(1000);
pktgen.range.dst_ip("all", "start", "10.10.10.1");
pktgen.range.dst_ip("all", "inc", "0.0.0.1");
pktgen.range.dst_ip("all", "min", "10.10.10.1");
pktgen.range.dst_ip("all", "max", "10.10.10.4");

pktgen.delay(1000);
pktgen.range.src_ip("all", "start", "20.20.20.1");
pktgen.range.src_ip("all", "inc", "0.0.0.1");
pktgen.range.src_ip("all", "min", "20.20.20.1");
pktgen.range.src_ip("all", "max", "20.20.20.8");

pktgen.delay(1000);
pktgen.range.ttl("all", "start", 64);
pktgen.range.ttl("all", "inc", 0);
pktgen.range.ttl("all", "min", 64);
pktgen.range.ttl("all", "max", 64);

**Comment by Ravi-t** [comment]
Thanks for the information
