### ISSUE TITLE
Try to replay a pcap file, but only irrelevant packets received

### ISSUE THREAD

**Issue by y9911** [pktgen/Pktgen-DPDK#291]
Hello,
    I am trying to using DPDK 24.11.0-rc1 and Pktgen-DPDK 24.10.0 in Ubuntu 22.04.5 LTS with two-port Intel E810 card to repaly a pcap file, however when I try to use Tcpdump to capture the replayed traffic with another port of the same card, only irrelevant packets are captured. It seems that the pktgen does not work properly. The replayed pcap seems to be normal:
![large_pcap](https://github.com/user-attachments/assets/9fe1c196-610e-4d5d-9c1c-06ea5c4ff8df)
&nbsp;
    The captured packets are as following:
![captured](https://github.com/user-attachments/assets/d54696f2-f0a3-4ea1-a68b-1f41605156ea)
 &nbsp;  
    The pcap for Pktgen to replay is from pktgen/pcap/large.pcap. The command line I use is  `sudo ./pktgen -l 10-12 -- -m [11:12].0 -s 0:large.pcap`
    The  `pcap show ` command in pktgen seems to indicate that the pcap file has been properly loaded:
![cmd](https://github.com/user-attachments/assets/1eb48200-b482-4cc0-9e02-721103363d29)
&nbsp;
    I have no clue about the cause or a solution of this phenomenon. Can you help me figure out the cause?

Thanks !

**Comment by KeithWiles** [comment]
I think you forgot to enable pcap mode with `enable 0 pcap` command. The packets you are seeing are from the single packet mode. Please give that a try.

**Comment by y9911** [comment]
> I think you forgot to enable pcap mode with `enable 0 pcap` command. The packets you are seeing are from the single packet mode. Please give that a try.

Thank you for your repaid and accurate response! After `enable 0 pcap` command, Pktgen repalys the pcap file properly.

**Comment by y9911** [comment]
> I think you forgot to enable pcap mode with `enable 0 pcap` command. The packets you are seeing are from the single packet mode. Please give that a try.

Thank you for your rapid and accurate response! After the `enable 0 pcap`  command, Pktgen replays pcap file properly.
