### ISSUE TITLE
Help needed to configure the two instances of pktgen sending traffics to the same port

### ISSUE THREAD

**Issue by madhura-a** [pktgen/Pktgen-DPDK#30]
Hello sir,

I have run the two pktgen instances to run simultaneously using the commands

1) sudo $PKTGENBUILD -c ffff -n 3 --socket-mem 512,512 --file-prefix pg0 $BLACK_LIST -- -p 0x3 -P -m "[4:8].0" -f $PKTGENCONFIG)

2) sudo $PKTGENBUILD -c ffff -n 3 --socket-mem 512,512 --file-prefix pg1 $BLACK_LIST -- -p 0x3 -P -m "[8:12].0" -f $PKTGENCONFIG)

Both of them are running together without any issue. But for my experiments, I need both of them to send traffic to the same destination port simultaneously. But in the current behavior, only one pktgen transmits the packets. Please let me know is there any mistake in the commands used or this is the expected behavior. I hope to hear from you soon. Thank you.

**Comment by pktgen** [comment]
With pktgen you can not share a port between two instances.  Also do not use -c use -l option instead, it is easier to assign lcores to processes. 

Also you are sharing lcores between pktgen instances which will not work very well. I am surprised it is working. 

Plus where did you get the -p 0x03 this option has no effect on pktgen and is not used.

**Comment by madhura-a** [comment]
Hello sir,

Thank you for the response.
For our experiment, we need to send multiple flows to the destination server with varying rates for a certain duration and after that time interval, again change the rates of these flows. Is there any way to achieve this using pktgen?

**Comment by pktgen** [comment]
Sequence mode would be the closest, but it will not meter packet at different rates. If you add multiple packets or create a pcap file that has the correct mix of packets then maybe you can get close.

**Comment by immadhavv** [comment]
I'm trying to do the same thing with two pktgen instances as packet generators and a testpmd instance as the victim(pktgen and testpmd applications running on containers connected via virtual ports on an OVS bridge)

@madhura-a  Were you able to achieve what you were trying to do? Did you use RSS on the other side to do this? And is it possible that our environments are similar?

**Comment by madhura-a** [comment]
Hi @immadhavv,

I was doing experiments with openNetVM and to test the setup, I needed to generate traffic with different flows. With a single point to point link, I wasn't able to generate more than one flow. So, I generated two flows by directly connecting the two NICs of two servers.

I did not try the sequence mode or pcap way suggested in the last post.
