### ISSUE TITLE
Does capture command can only capture the packets that port received?

### ISSUE THREAD

**Issue by Groundsea** [pktgen/Pktgen-DPDK#30]
I used run time command "capture 0 enable" to capture the packets that port 0 sent and received. But it seemed that it can only capture the received packets, the packets that this port sent can not be captured. Is it a problem or something else need to be set?

pktgen version: 2.8.4

Thanks a lot!

**Comment by pktgen** [comment]
Sent from my iPhone

> On May 19, 2015, at 3:21 AM, Haifeng Xie <notifications@github.com> wrote:
> 
> I used run time command "capture 0 enable" to capture the packets that port 0 sent and received. But it seemed that it can only capture the received packets, the packets that this port sent can not be captured. Is it a problem or something else need to be set?
> 

Pktgen only captures packet it receives. 

Regards 
Keith

**Comment by Groundsea** [comment]
OK, Thank you!

**Comment by Groundsea** [comment]
OK, Thank you!

**Comment by tttd** [comment]
Hi all,
Sorry for commenting on this thread (as it's closed) but I'm not sure my problem is enough to raise a new issue. I'm also a newbie here.
I use pktgen version 2.9.1, and what I want is to capture all input packets in a port and write them to a file (for other uses). When I come to pktgen_main_receive() function, as far as I understand, pktgen_packet_capture() is the one I need. But I don't have any clues where the output is or does it take any runtime command to work (I don't see any such).
Sorry for my bad English. Hope you can help me solve this. Thanks a lot :)

**Comment by pktgen** [comment]
To use the capture function you can only do one port at a time. The packets are written to disk when to turn off capture.

To enable capture on port 2, which is connected to port 0 do:

> capture 2 on
> set 0 count 10000
> start 0
> capture 2 off

A file will be written to the disk in the directory in which pktgen was started.

�
Regards,
++Keith
Intel Corporation

**Comment by tttd** [comment]
Thank you for the quick reply. I really appreciate it.
I'll check it tomorrow (I'm in different timezone) but before that can i ask where exactly it'll be written to and how I can control that?
One more question, in #28 it's said to be able to run multiple instances but looking at the code, I didn't see any rte_..._lookup function that I supposed is needed to be capable of share mem pool. So how is it possible for secondary instances to access?
I'm new to DPDK so please bear with me. Thank you a lot :)

**Comment by pktgen** [comment]
�
Regards,
++Keith
Intel Corporation

**Comment by tttd** [comment]
Thank you a bunch. I have checked the capture function and it worked fantastic. Although rte_pktmbuf_dump works well (as I wrote a simple app based on this), I'm trying to learn more from you. :)
I think I'll move the latter question to the dedicated thread after studying harder.
Thank you so much again :)

**Comment by tttd** [comment]
Sorry if I'm too much.
When I checked the order of packets in the generated pcap file, I realized that almost all packets were in wrong order in comparison with streamed pcap file even though the total packets in 2 file were the same. Is there anything wrong here?
