### ISSUE TITLE
Changing protocol type doesn't take effect when range is enabled

### ISSUE THREAD

**Issue by ajaypalsingh** [pktgen/Pktgen-DPDK#31]
Using pktgen-2.8.5-2  with DPDK 2.0.0 from the dpdk.org repository.

Enabled range of packets on port 1 using 

>range 1 enable

and set the protocol to UDP using

>proto udp 1

But pktgen still sends TCP packets.

Looking at the code, pktgen_set_proto doesn't set the protocol for RANGE_PKT:

>pktgen-2.8.5-2/app/pktgen-cmds.c

```c
void
pktgen_set_proto(port_info_t * info, char type)
{
  info->seq_pkt[SINGLE_PKT].ipProto = (type == 'u')? PG_IPPROTO_UDP :
                  (type == 'i') ? PG_IPPROTO_ICMP :
                  (type == 't') ? PG_IPPROTO_TCP :
                  /* TODO print error: unknown type */ PG_IPPROTO_TCP;

  // ICMP only works on IPv4 packets.
  if ( type == 'i' )
    info->seq_pkt[SINGLE_PKT].ethType = ETHER_TYPE_IPv4;

  pktgen_packet_ctor(info, SINGLE_PKT, -1);
}
```

>Following patch seems to do the trick:

```c
void
pktgen_set_proto(port_info_t * info, char type)
{
  info->seq_pkt[SINGLE_PKT].ipProto = (type == 'u')? PG_IPPROTO_UDP :
                  (type == 'i') ? PG_IPPROTO_ICMP :
                  (type == 't') ? PG_IPPROTO_TCP :
                  /* TODO print error: unknown type */ PG_IPPROTO_TCP;

  // ICMP only works on IPv4 packets.
  if ( type == 'i' )
    info->seq_pkt[SINGLE_PKT].ethType = ETHER_TYPE_IPv4;

  pktgen_packet_ctor(info, SINGLE_PKT, -1);

  info->seq_pkt[RANGE_PKT].ipProto = info->seq_pkt[SINGLE_PKT].ipProto;
  info->seq_pkt[RANGE_PKT].ethType = info->seq_pkt[SINGLE_PKT].ethType;
  pktgen_packet_ctor(info, RANGE_PKT, -1);
}
```

Thanks.

**Comment by pktgen** [comment]
The real change it to add a pkt.proto command to change the protocol type for range packets, but that one should work for now. The problem is it also changes the SINGLE packets too.

**Comment by ajaypalsingh** [comment]
If range is enabled on a particular port, then the SINGLE packets will not be transmitted unless range is disabled. Since both RANGE and SINGLE modes of tx are exclusive, I was wondering if the same protocol command can be used. Unless, we expect a range of protocols to be used as well, which is unlikely. Possible, but unlikely.

**Comment by pktgen** [comment]
On 5/22/15, 12:42 AM, "ajaypalsingh" <notifications@github.com> wrote:

>If range is enabled on a particular port, then the SINGLE packets will
>not be transmitted unless range is disabled. Since both RANGE and SINGLE
>modes of tx are exclusive, I was wondering if the same protocol command
>can be used. Unless, we expect a range of protocols to be used as well,
>which is unlikely. Possible, but unlikely.

Yes, that is true. The thing I like to do is setup range and single
packets and be able o which back and forth without having to change the
single or range packets. This way you can setup single, sequence, pcap and
range then switch between them without having to change things. Does that
make sense?

**Comment by ajaypalsingh** [comment]
Cool, that makes sense. You can close this if you are planning to add support for pkt.proto in next release. Thanks.

**Comment by pktgen** [comment]
thanks for the report.
