### ISSUE TITLE
One extra byte is being added by pktgen at the end of all odd length packets read from a pcap file

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#32]
I started pktgen to read the pcap file for sending packets, but I noticed that an extra byte is being added in all the odd length packets, and wireshark is reporting them as VSS-Monitoring Ethernet Trailer, Source Port as shown below

![image](https://user-images.githubusercontent.com/27767393/92481509-bcc4af00-f1e6-11ea-8013-aa2d072bc70a.png)

**Comment by pktgen** [comment]
This must be a wireshark or system issue. I ran pktgen and wireshark which worked correctly. The sizes were correct using an 81 byte packet or 77 byte frame minus the CRC.

[A screenshot of a social media post  Description automatically generated]

**Comment by Ravi-t** [comment]
I tried to verify the length of the packets read by pktgen, and found that Size-FCS column prints the sizes of all odd length packets as even by adding 1 to it.
In below snapshot every odd packet was having odd length but it shows as even. This means that 1 byte was added during call to "_pcap_read" function itself. 

![image](https://user-images.githubusercontent.com/27767393/92507466-52703680-f207-11ea-8d21-49d57a28dccc.png)

**Comment by pktgen** [comment]
The pcap header contains the size of the packet and if something which is written in the header, pktgen just converts the value to little endian and prints it. I looked at the other pcap files and they do have odd length packets. Where did you get the pcap file from a previous pktgen capture/save? If remember correctly (wayback when) some NICs may pad the length to an even number, but I thought all of those NICs we no longer used.

**Comment by Ravi-t** [comment]
Yes Keith, I got the pcap file which was generated by pktgen itself in a previous run.
Basically, in my setup there are 2 pktgen's running, one acting as generator and second as receiver.
In a previous run, I triggered some data from generator and captured the pcap file at receiver.

Then, I fed the same pcap file to generator in the next run and found that the packets that were having odd length in the pcap generated in previous run are converted into packets with even length (1 extra byte added in the end) in this run.

**Comment by pktgen** [comment]
What is the NIC you are using?

If this is in a VM then the interface maybe adjusting the length. The length for the  capture is taken from the mbuf length and that is set by the driver. If you are using Virtio or something like it then it most likely is the problem. I do not see the issue. I captured packets and saved them via pktgen and some of the packets are odd length.

**Comment by Ravi-t** [comment]
I am using e1000 NIC on a Centos 7.7 VM

Network devices using DPDK-compatible driver
============================================
0000:02:06.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio unused=e1000
0000:02:07.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio unused=e1000

**Comment by pktgen** [comment]
The e1000 NIC in a VM is not a real NIC it is a emulator version of the e1000, if I remember correctly. The real NIC on your system is most likely not a e1000 NIC. Is the VM in windows? If so look at the system configuration and see what the NIC is, but I am sure the e1000 in a VM is an emulation of the e1000.

**Comment by Ravi-t** [comment]
I am running Linux guest on Windows 10 host
After checking the vmware website, I found following information from "https://kb.vmware.com/s/article/1001805"

E1000: An emulated version of the Intel 82545EM Gigabit Ethernet NIC. A driver for this NIC is not included with all guest operating systems. Typically Linux versions 2.4.19 and later, Windows XP Professional x64 Edition and later, and Windows Server 2003 (32-bit) and later include the E1000 driver.

**Comment by Ravi-t** [comment]
Dear Keith,

I applied the GDB at function pktgen_pcap_mbuf_ctor and found that , the orig_len present in hdr pointer has the correct value, which is an odd number but incl_len is the one where additional 1 byte is added.


(gdb) 
263			if ( (i & 0x3ff) == 0) {
(gdb) 
268			if (unlikely(_pcap_read(pcap, &hdr, buffer,
(gdb) p hdr
$25 = {ts_sec = 0, ts_usec = 0, incl_len = 172, orig_len = 171}

**Comment by Ravi-t** [comment]
I found the piece of code thats causing this issue, it seems problem is while writing the pcap capture, not in reading the pcap.
During the function call **pktgen_packet_capture_bulk** as below, it seems you are adding +1 to data length and masking it with ~1, due to which odd numbers are increased by 1 but even numbers remain same.
Any particular reason for doing +1 to data length?

for (i = 0; i < nb_dump; i++) {
		pkt = pkts[i];

		/* If the packet is segmented by DPDK, only the contents of the first
		 * segment are captured. Capturing all segments uses too much CPU
		 * cycles, which causes packets to be dropped.
		 * Hence, data_len is used instead of pkt_len. */
		**plen = (pkt->data_len + 1) & ~1;**

**Comment by pktgen** [comment]
Hmmm. Someone else added the pcap support and it should not have been rounding the packet length up. I will fix that problem in the code and push a new version. Thanks for finding that one.

**Comment by Ravi-t** [comment]
Thanks Keith.
I have a question for you related to pcap packet sending, is it possible to send pcap packets from source IPs to destination IPs mentioned in the range page?
Basically, I want to that pcap packets should be played for each source IP (from source ip min to source ip max) mentioned in the range page.
Please let me know if its possible with current release or if you can please provide any hint to achieve it with minimal code change. Thanks for your help.

**Comment by pktgen** [comment]
Sorry, not the pcap and range modes are not able to be running at the same time.

**Comment by pktgen** [comment]
Fixed
