### ISSUE TITLE
How to investigate "!ERROR!: ICMP checksum failed"? When other setups work and 'standard linux' pings.... 

### ISSUE THREAD

**Issue by Golvanig** [pktgen/Pktgen-DPDK#33]
Hello,
My goal is to test a router.
I am using a linux system to inject with pktgen **udp** traffic.

I did test with back-to-back, and it worked
I added a router in between the 2 interfaces and it worked

Now I am trying to introduce a second router which is linked to the former as a chain.

I modified my script as:

set 1 src ip 90.20.0.1/8
set 1 dst mac 3c:2c:30:4f:65:85 #mac of the first router
set 1 dst ip 100.20.0.1

set 0 src ip 100.20.0.1/8
set 0 dst mac 00:90:0b:85:48:84 #mac of the second router
set 0 dst ip 90.20.0.1
 
enable all icmp
enable all process

and now, when I launch ping4 1 or ping4 0 I do have an '!ERROR!: ICMP checksum failed'.
I double checked the MAC and etc.
I tried with the standard linux etc.

I can see that the routers resolve each the interface on which they are connected to pktgen:
sh arp
Protocol Address  Hardware Address   Timeout      Interface              Type
100.20.0.1        18:5a:58:10:2d:e4  01:59:54     TenGigE 2/1            ARPA
and
sh arp
Protocol Address  Hardware Address   Timeout      Interface              Type
90.20.0.1         18:5a:58:10:2d:e5  01:59:55     GigabitEthernet 0/1    ARPA 

and I can ping the 2 routers from my linux (without pktgen).

Where should I investigate?
Thanks again for your support

P.S.
Do I need the ping4 to be able to start testing?
It seems yes, but I am learning every day.

**Comment by pktgen** [comment]
Where is the ICMP error coming from pktgen or linux or routers?

**Comment by Golvanig** [comment]
the issue comes from pktgen.
It is displayed in the screen.
![Screenshot from 2020-09-09 18-11-39](https://user-images.githubusercontent.com/11241673/92624561-ef92a400-f2c7-11ea-8a32-ca7a2fc14488.png)

**Comment by pktgen** [comment]
Do the packets have IP Options this is not handled by DPDK routines.

**Comment by Golvanig** [comment]
I did not activate anything in the routers,  and they work well when connected alone in face of pktgen.

I can put trace in the ping4 code library, but I doubt this could help.

Is this specific ICMP option that you check and do not hande?

**Comment by Golvanig** [comment]
The routing between my 2 routers may generate resolution to the pktgen server which was not 'treatable' with IP options.

I modified my routing and the IP/MAP resolution is now certainly cleaner from my routers and do not need additional "exchanges"...

Thanks again for your support
