### ISSUE TITLE
Segfault in pktgen.c:983

### ISSUE THREAD

**Issue by sluser** [pktgen/Pktgen-DPDK#33]
Hello,
         I'm getting either an error or a segfault when running pktgen.

My platform is Ubuntu 14.04 desktop, 64-bit running on VirtualBox. The VM has 1GB of RAM, 4 cores and a two network adaptors, both Intel 82540EMs. One network adaptor is set to use the igb_uio module, the other is using the e1000 driver.

The command line I'm using is:

./pktgen -x 0x03 -n 3 -- -p 0x02 -P -f test/set_seq.lua -m XX

Where XX is either 1.0 or 1.1

1.0 gives the error:

PMD: eth_em_tx_queue_setup(): TX WTHRESH must be set to 0 if tx_rs_thresh is greater than 1. (tx_rs_thresh=32 port=0 queue=0)
!PANIC!: rte_eth_tx_queue_setup: err =-22, port=0, Invalid argument
PANIC in pktgen_config_ports(): err =-22, port=0, Invalid argument

..followed by some stack information.

1.1 instead segfaults at the following point in logging (run under GDB):

=== Display processing on lcore 0
=== RX/TX processing on lcore 1, rxcnt 1, txcnt 1, port/qid,

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed1ff700 (LWP 8559)]
pktgen_main_receive (pkts_burst=0x7fffed1fe7ao, lid=1 '\001', info=0x0) at pktgen.c:983
983          pid = info->pid

You can see from this that info is a NULL pointer which is being dereferenced on line 983.

I presume the "1.0" case is a misconfiguration, but I am not sure why the 1.1 case wouldn't work.

Thanks for your help.

**Comment by pktgen** [comment]
What version of Pktgen are you using and what is the DPDK version?

Can you also send me the startup output.

Also please send me the �lspci | grep Ether� output.

Below is the command line to use, the -p 0x02 is not used any more.

On 5/27/15, 8:56 AM, "sluser" <notifications@github.com> wrote:

>Hello,
>         I'm getting either an error or a segfault when running pktgen.
>My platform is Ubuntu 14.04 desktop, 64-bit running on VirtualBox. The VM
>has 1GB of RAM, 4 cores and a two network adaptors, both Intel 82540EMs.
>One network adaptor is set to use the igb_uio module, the other is using
>the e1000 driver.
>The command line I'm using is:
>./pktgen -x 0x03 -n 3 -- -p 0x02 -P -f test/set_seq.lua -m XX

./pktgen -c 3 -n 3 � -P -f test/set_seq.lua -m �1.0"

**Comment by sluser** [comment]
DPDK version 2.0.0, pktgen version 2.8.6

The lspci output is:

00:03.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
00:08.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)

Is there any particular part of the startup log that might be relevant? I'm having to type all this out due to network segregation.

The change in command line didn't make a difference by the way (not that you said it would!).

Thanks

**Comment by pktgen** [comment]
On 5/27/15, 8:56 AM, "sluser" <notifications@github.com> wrote:

>Hello,
>         I'm getting either an error or a segfault when running pktgen.
>My platform is Ubuntu 14.04 desktop, 64-bit running on VirtualBox. The VM
>has 1GB of RAM, 4 cores and a two network adaptors, both Intel 82540EMs.
>One network adaptor is set to use the igb_uio module, the other is using
>the e1000 driver.

If you only have one nic attached to the igb_uio then -m �1.0� is the
correct usage. The second port is not seen by DPDK in that case and the
segfault can happen if you give a port outside of the list owned by
igb_uio. When you attach ports to igb_uio the ports start at zero for DPDK
not in the specific list reported by lspci.


In the file, pktgen-port-cfg.c you need to comment out a line for your
needs.

Please pull 2.9.0 from dpdk.org

**Comment by sluser** [comment]
I will give this a try, thanks for your help.

**Comment by purumishra** [comment]
Hi All,
       I have also done the same setup but getting segmentation fault core dumped whenever trying to attach core and port with -m option.
When I am giving port 0 or 1 then it is throwing error like PANIC in pktgen_config_port(); err=-22 , port=1 , Invalid argument.

And if I am giving any other port than 0, 1 then it is simply throwing segmentation fault.
Kindly guide me on this.

Thanks
Pratap
