### ISSUE TITLE
PCAP file size limits?

### ISSUE THREAD

**Issue by cjthedj** [pktgen/Pktgen-DPDK#34]
I am experimenting with pktgen running pcap files. IF the pcap files are 25M or less in size on my dual 710 centos version 2.6.32-358.el6.x86_64 it runs two channels at 10G rather well.
  If I try a 42M pcap file I need --scoket-mem set to1024 or higher but the PCAP file only runs at around 6.5G.
  An 80M pcap file crashes completly.
The command I am using is 
./app/build/pktgen -c 1f -n 2 --proc-type auto --socket-mem 1024,1024 --file-prefix pg -w 0000:06:00.0 -w 0000:06:00.1 -- -T -P -m "[1:3].0, [2:4].1" -s 0:/root/output2.pcap -s 1:/root/output2.pcap

Apart form the obvious issue of pktgen not dying gracefully for "over-sized" pcap files. I have two questions
1. Are there things I can do to increase the size fo PCAP file that pktgen will run with?
2. What are the expected limits on PCAP file size?

All my PCAP files have packet size limits of around 1536 bytes max. The average packet size of the 42M file  is 200 bytes.
version is dpdk 1.7.1 and pktgen 2.7.7.
I;ve tried experimenting with multiple cores on TX and RX but there does not appear to be any difference from just assigning one per TX & RX. I also tried larger socket-mems but that didn;t cahnge anything either.

**Comment by pktgen** [comment]
Yes, Pktgen needs to read the pcap file into memory and create a list of mbuf packets to send the pcap file. If you can use the latest version from here http://dpdk.org/browse/apps/pktgen-dpdk/refs/ It would help to fix the problems.

The amount of huge pages needs to support having the number of pcap packets. Notice you defined two ports with pcap files each port needs a copy of the pcap file and mbufs. The size of the pcap files assigned to the ports is for each port and you need that much more memory. This is the only way to get the packets sent quickly.

Regards,
++Keith

**Comment by cjthedj** [comment]
I had inherited only 4 x 1G  hugepages. When I changed it to 16 hugepages I could run the 80M  pcap file. Examining the memory used ouptut I realised that the memory used appears to only be related to the NUMBER of packets not the PCAP file size. With --socket-mem set to 4096,4096 I was able to run a 420M pcap fil ewith larger average packet size.  "Only" runs at 8.2G per channel but I haven't tried the latest software yet. I'll let you know what happens.

**Comment by ralequi** [comment]
It is a "reported bug".
Unless you have a fast raid-0 that can read up to 10Gbps, It is needed to
preload all the packets of the pcap in memory. Moreover, each packet in
memory takes up a bit more of 2048 Bytes, despite of the original packet
size.
Why 2048? It is a waste of memory! No, it's not, 2048 byte per packet is
required for low-level optimization (cache alignement, etc). And that's why
you need 16G to load 80M pcap-file.

Regards,
Rale

2015-07-09 17:03 GMT+02:00 cjthedj <notifications@github.com>:

**Comment by cjthedj** [comment]
Version 2.9.1 doesn;t work any faster (maybe 100m but no more). HOwever I am getting a couple of strange nasties that I don't remember with my limited testing of 2.7.7.   I'll raise a new issue or two for these.
