### ISSUE TITLE
link state goes down on restarts

### ISSUE THREAD

**Issue by cjthedj** [pktgen/Pktgen-DPDK#35]
Using version 2.9.1 of pktgen. If I use "str" to start traffic it always works . If I then stop and start traffic using stp and str the link state will report DOWN and my receiver will report no_sync. THis is intermittent. My two-port test may go down on either port  on a STP or subsequent "str". If either port does go down, then the quit command stops working and I have to use control-c to get out.  I do not remeber seeing this on the 2.7.7 version (and I;m pretty sure I tried it)
  Intel 710 card with latest NVM release.
  Two ports.
  Command was ./app/app/x86_64-native-linuxapp-gcc/pktgen -c fffc -n 2 --proc-type auto --socket-mem 4096,4096 --file-prefix pg -w 0000:06:00.0 -w 0000:06:00.1 -- -T -P -m "[2:3].0, [5:6].1" -s 0:filea.pcap -s 1:fileb.pcap
  I am 99% sure I am using version 2.0.0 of DPDK but I dont know how to check.

**Comment by cjthedj** [comment]
Tried the same thing on an ivy bridge server with a quad intel 710. rte_version.h in dpdk directory indicates version 2.1.0 of dpdk. I get the same issue."stp" or  subsequent "str" will take down a link at random.  Cannot quit afterwards. (but you can quit if the ports stay up)

**Comment by cjthedj** [comment]
It doesn;t come back up even after several minutes. It can also go down when you send a subsequent str command. i.e. it doesn;t just go down on stp. I currently have my quad with two channels working and two down after 3 str-stp cycles.

**Comment by lc7cl** [comment]
I also get this issue!!!
only start 0 may cause link down and can't become UP after reboot server!

**Comment by pktgen** [comment]
This one sounds like a problem with the card or system and not with pktgen. Pktgen does not control Link state per say and normally when you have to reboot it is a system/NIC problem.
