### ISSUE TITLE
Sometimes Rx Pkt counter > Tx Pkt counter when packets are exchanged between 2 ports of same pktgen instance

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#36]
![image](https://user-images.githubusercontent.com/27767393/94685357-9a2b3f00-0329-11eb-981e-08bc9797fc54.png)

Rx counter is 1 more than Tx counter for both the ports.
Is it because Broadcast/Multicast packets are being added to receiver stats but not added to transmitter stats?

**Comment by pktgen** [comment]
The values are collected from the NIC hardware and I assume they are always correct. If they are different then a packet was send from someplace to the port and counted.

**Comment by Ravi-t** [comment]
I tried to test it multiple times, and found that it only happens when Broadcast/Multicast counter values are non-zero.

**Comment by pktgen** [comment]
Sometimes the NIC counters include these broadcast and multicast in the total packets, which is the right thing to do.

**Comment by Ravi-t** [comment]
Thanks for the info.
