### ISSUE TITLE
Multiple MPLS labels

### ISSUE THREAD

**Issue by maq123** [pktgen/Pktgen-DPDK#4]
Hello,

how can I generate packets with more than just a single MPLS label?
I am setting the desired label with `range 0 mpls entry start 0002001` but it seems it does not accept more parameters.

**Comment by pktgen** [comment]
Also you will have to set the 'range 0 mpls inc XYZ'

**Comment by maq123** [comment]
Tried various values in place of 'XYZ' but it seems 'range 0 mpls inc' is just no a valid combination here...
Even if it worked, isn't the 'inc' intended to increment a specific field for each consecutive packet? 
What I am trying to achieve is, to phrase it differently, create a MPLS header with a stack depth larger than one i.e. 
```
[eth hdr]
[mpls label 1]
[mpls label 2]
[payload]
```

**Comment by pktgen** [comment]
Sorry that is not supported, but I do take patches for fixes or enhancements

**Comment by maq123** [comment]
Ok, thank you for clarifying!
