### ISSUE TITLE
pcap replay loopback point

### ISSUE THREAD

**Issue by cjthedj** [pktgen/Pktgen-DPDK#40]
HI
   I wanted to check that pktgen was generating expected seqeunces of packets with my pcap files.
I "stumbled" upon your capture feature (its really good but a bit under-documented) and used it to capture a pktgen stream of a ~60M  pcap file with 221408 packets in it.
   When I examoined the pcap output file I saw jumps in the pcap stream which, at first I thought was simply the loopback point in the buffer. However with a large buffer (16G) and a shortish capture time (so that the buffer does not ever loop round) I was still getting breaks in thecaptured stream.
  After a fair amount of examination I worked out that the "issue" is in the transmission of the packets. It appears to output exactly 2^18 (262144 packets) before repeating. Since my PCAP file does not have exactly 2^n packets it plays back one full copy of the pcap file followed by the first 40736 packets before starting again at teh start of the pcap file (40736 + 221408 = 2^18)
  Is thiswhat it is supposed to do? I expected it to playback the PCAP file from start to finish and then repeat the whole file over and over again.
  The capture feature is really good. Flawless capture at 10Gb/s for 16Gbytes is pretty impressive.

**Comment by pktgen** [comment]
What I do in the code is grab all of the packets for that port and start filling the packets from the pcap file. If the number of system packets is greater then the number of pcap packets I just wrap to the start of the pcap file and fill in the rest of the packets. This is why you see the small number of packets from the beginning of the pcap file then a it starts all over again. The code could be changed to allocate the exact number of pcap packets and you can look at the code to see if you want to make that change.

�
Regards,
++Keith
Intel Corporation

**Comment by cjthedj** [comment]
Hi
  I spent a day looking at the code trying to work out why it was rounding up to themext power-of-2. THe only thing I found was a comment in teh mempool stuff that powers-of-2 were more memory efficient.
I tried removing the round-up code (1 line) and my version now plays back-to-back pcap files with no extraneous packets. It hasn;t crashed yet!! 
    I'm no c-programmer but if you want me to find out how to incorporate this change into the proper code, I'll give it a try.
  Is there some other reason for the power-of-2 roundup that I can't see?

**Comment by pktgen** [comment]
The power of 2 give better page alignment along with cache alignment. Please send me your one line change. Thanks.
�
Regards,
++Keith
Intel Corporation

**Comment by cjthedj** [comment]
Hi
  I commented out line 351 of pktgen-pcap.c as shown

        // Round up the count and size to allow for TX ring size.
        if ( elt_count < MAX_MBUFS_PER_PORT )
        	elt_count = MAX_MBUFS_PER_PORT;
//commenting out the next line allows back-to-back pcap replay
        //elt_count = rte_align32pow2(elt_count);

        rte_printf_status("\r    Create: %-*s   \b", 16, name);
    	info->q[qid].pcap_mp = rte_mempool_create(name, elt_count, MBUF_SIZE, 0,

  I would like to bet that somewhere on planet earth, someone actually uses the roundup feature. 
Perhaps back-to-back pcap could be made a command line option in pktgen .  (suggest -x for eXact) with a new flag added so that no parameters need passed into the function.
  Feel free to ignore this last paragraph.

   The one line change would still roundup for tiny pcaps (< MAX_MBUS_PER_PORT)  I imagine that this limit is for cache related performance/alignment as well.
