### ISSUE TITLE
pktgen rate limited at 8.5Million

### ISSUE THREAD

**Issue by UsamaMehboob** [pktgen/Pktgen-DPDK#41]
I am using pktgen 2.9.1 with dpdk 2.0.0 with NIC intel x520 82599. when I run pktgen on host machine with 100%10G Nic. It runs on 14Million ~approx. But when I run it on a VM created from virtual functions of same physical NIC, the rate gets limited to 8.3Million . I cant figure out why and what I am missing. Have any other guys encountered the same problem?
My Virtual-Machine Specs are 4 cores (assigned from node-0) memory (8GB assigned from core 0) Huge pages(2048 of 2MB each) Flow-control disabled on NIC . We have also checked by disabling flow control on switch also.

**Comment by pktgen** [comment]
I need to check but I know running in a vm will cause a performance drop. I need to find out if that true.

**Comment by ralequi** [comment]
Hey Keith, check this paper. It will help you on the check.

Rale.

2015-10-09 15:45 GMT+02:00 Keith Wiles <notifications@github.com>:

**Comment by UsamaMehboob** [comment]
The issue is resolved, it had something related with NIC.
