### ISSUE TITLE
Get Compile Problem in Ubuntu 21.04

### ISSUE THREAD

**Issue by c6supper** [pktgen/Pktgen-DPDK#42]
1. DPDK 20.11
2. Ubuntu 21.04
3. Pktgen-dpdk 20.11.3
4. Install DPDK in /usr/local/dpdk/
5. export PKG_CONFIG_PATH=/usr/local/dpdk/lib/x86_64-linux-gnu/pkgconfig/ ( could been found by meson ,Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/dpdk/lib/x86_64-linux-gnu/pkgconfig/')
6. 100% sure the include path should right in that pc file.
7. make build/make buildlua.

[10/73] Compiling C object lib/utils/libutils.a.p/_atoip.c.o
FAILED: lib/utils/libutils.a.p/_atoip.c.o 
cc -Ilib/utils/libutils.a.p -Ilib/utils -I../lib/utils -Ilib/common -I../lib/common -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -DLUA_ENABLED -fPIC -MD -MQ lib/utils/libutils.a.p/_atoip.c.o -MF lib/utils/libutils.a.p/_atoip.c.o.d -o lib/utils/libutils.a.p/_atoip.c.o -c ../lib/utils/_atoip.c
In file included from ../lib/common/pg_strings.h:20,
                 from ../lib/utils/_atoip.c:5:
../lib/common/pg_compat.h:14:10: fatal error: rte_version.h: No such file or directory

**Comment by c6supper** [comment]
root@5f7dd73f367a:/pktgen-20.11.3# cat /usr/local/dpdk/lib/x86_64-linux-gnu/pkgconfig/libdpdk-libs.pc 
prefix=/usr/local/dpdk
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: dpdk-libs
Description: Internal-only DPDK pkgconfig file. Not for direct use.
Use libdpdk.pc instead of this file to query DPDK compile/link arguments
Version: 20.11.0
Libs: -Wl,--as-needed -L${libdir} -lrte_node -lrte_graph -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_regexdev -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs
Libs.private: -pthread -lm -ldl -lnuma -lpcap
Cflags: -I${includedir} -I${includedir} -include rte_config.h -march=native

**Comment by c6supper** [comment]
build lib/utils/libutils.a.p/_atoip.c.o: c_COMPILER ../lib/utils/_atoip.c
 DEPFILE = lib/utils/libutils.a.p/_atoip.c.o.d
 DEPFILE_UNQUOTED = lib/utils/libutils.a.p/_atoip.c.o.d
 ARGS = -Ilib/utils/libutils.a.p -Ilib/utils -I../lib/utils -Ilib/common -I../lib/common -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -DLUA_ENABLED -fPIC

**Comment by c6supper** [comment]
paste from Builddir/build.ninja, no dpdk included path found in the flags

build lib/utils/libutils.a.p/_atoip.c.o: c_COMPILER ../lib/utils/_atoip.c
 DEPFILE = lib/utils/libutils.a.p/_atoip.c.o.d
 DEPFILE_UNQUOTED = lib/utils/libutils.a.p/_atoip.c.o.d
 ARGS = -Ilib/utils/libutils.a.p -Ilib/utils -I../lib/utils -Ilib/common -I../lib/common -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -DLUA_ENABLED -fPIC

**Comment by c6supper** [comment]
bypass the problem by adding following arguments:
CFLAGS=-I${PREFIX_DIR}/dpdk/include meson build -Dprefix=${PREFIX_DIR}/dpdk/ -Denable_lua=true &&     ninja -C build install -j4

**Comment by pktgen** [comment]
The build system assumes that DPDK is installed in the normal location. It appears you moved the installed libs to /usr/local/dpdk, which would account for the build issues.

When I do the following steps to build DPDK:

meson builddir
ninja -C builddir
sudo ninja -C builddir install

It will place the libs and files in /usr/local/lib/x86_64-linux-gnu with the libdpdk.pc file below this directory and the DPDK includes in the /usr/local/include directory. These are the locations the libdpdk.pc expects the files to be located.

When you installed the files into /usr/local/dpdk then you would have to set the prefix and PKT_CONFIG_PATH variables.

Please close this bug if you agree pktgen does not have a bug.
Thanks

**Comment by c6supper** [comment]
If you checked my first post, you should know I definitely set the PKG_CONFIG_PATH variable , but it's OK since I already bypass that problem.
