### ISSUE TITLE
Fluctuations in pktgen-dpdk from 14M to 1Million

### ISSUE THREAD

**Issue by UsamaMehboob** [pktgen/Pktgen-DPDK#42]
I am using pktgen 2.9.1 with dpdk 2.0.0 with NICs intel x520 and 82599 (i have tried same and different NICs on both sides). I have tested it on two type of systems 

1. Dell Rack Server R620
2. Dell Blade Server M620

When pktgen is run on RackServer it smoothly generates traffic of 14M~approx. But when I run it on blade Server it shows fluctuations in traffic (from 14M  to 1M, back and forth). I have double checked all the memory and hugepages configurations and versions of dpdk are replicated on both machine. flow control configuration is also same on both NICs and switches. it is perhaps a memory issues or CPU architecture difference causing this, I dont know if I am missing something. Any help will be appreciated.

**Comment by pktgen** [comment]
All I can say is it does not appear to be pktgen but something with the blade server.  I wish I could help but I have not used or have these machines. 

The only thing I can think about is the possible you are getting pause frames that shutdown the rate. 

Next is the PCIe bus on the blade but these are just guesses sorry

**Comment by ralequi** [comment]
Have you tried cpu isolation?

Rale.

2015-10-10 18:33 GMT+02:00 Keith Wiles <notifications@github.com>:

**Comment by UsamaMehboob** [comment]
Yes I have 32 logical cores on each blade server and I have dedicated 2 cores for linux and isolated the rests. I have put the flag isolcpus=2-31 in grub on both machines. In Rack server it works smoothly and in blade server it doesnt.

**Comment by ralequi** [comment]
Then it can be cpu speed (it can be changing). Force it to stay at maximum
hz on the blade machine, and check if there is still fluctuations.


2015-10-13 4:26 GMT+02:00 UsamaMehboob <notifications@github.com>:

**Comment by UsamaMehboob** [comment]
@ralequi you were right it was problem with cpu speed. An electrical surge caused over temperature in system logs, so CPUs were running at low frequency. After deleting the logs and upgrading the BIOS, its back to normal 14MPPS
