### ISSUE TITLE
Packets not transmitted by dpdk vmxnet3 driver because mbuf pkt_len == 0

### ISSUE THREAD

**Issue by BeewitPookerdoun** [pktgen/Pktgen-DPDK#43]
In pktgen_send_pkts, mbufs returned from pg_pktmbuf_alloc_bulk have pkt_len set to 0. The dpdk vmxnet3 driver explicitly checks for this state and skips sending the packet, incrementing the driver's tx_qN_drop_total statistic instead.

mbuf.pkt_len is set to 0 in pktmbuf_reset() because union pktgen_data's 64-bit udata is populated from a 32-bit rte_mbuf.dynfield1[0] rather than the old 64-bit rte_mbuf.dynfield0[0].

**Comment by pktgen** [comment]
OK, I will have to look at it. thanks

**Comment by pktgen** [comment]
What versions of DPDK and Pktgen are you using? I only debug or fix problems related to using the latest Pktgen with the latest DPDK as I do not have the bandwidth to work on older versions or combos of new and old vesions.

**Comment by BeewitPookerdoun** [comment]
pktgen version 20.11.3 (tag: pktgen-20.11.3)
dpdk versions 20.11.0 (tag: v20.11) and 21.02-rc0 (commit: ecc69f98c, current HEAD on master)

**Comment by pktgen** [comment]
most likely the vmxnet3 PMD is setting the length to zero before freeing the mbuf or setting the mbuf.udata64 field to zero or using that field. I will try to look at it next year.

I do not use the dpdk dynamic mbuf fields correctly it appears :-( The vmxnet3 driver does use these fields, not sure a PMD should be using these fields as it requires the application and PMD to use them the same way.

**Comment by pktgen** [comment]
Can not test or reproduce this problem. Closing issue, but you reopen it if you like.
