### ISSUE TITLE
Pktgen just exits right after starting on RHEL 6.5 without showing console for command

### ISSUE THREAD

**Issue by CoderSpinoza** [pktgen/Pktgen-DPDK#43]
I am using pktgen 2.9.5 on RHEL 6.5 with kernel version 2.6.32-573.7.1.el6.x86_64. The problem is that pktgen just exits on starting without giving me a console for command...

I have also tested with pktgen 2.9.1 on Ubuntu 14.04 LTS and was able to send and receive packets with pktgen-dpdk with no problem. My own code using DPDK runs without any problem on RHEL 6.5.

I was just wondering if anybody has seen the same issue with pktgen on RHEL 6.5.

**Comment by CoderSpinoza** [comment]
Sorry I was inputing a wrong argument.

I wrote
sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -c f -n 4 -- -p 6 -P -m 1.0,2.1

instead of
sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -c f -n 4 -- -p 6 -P -m 1.0, 2.1

and pktgen was just returning.. I made it work on my machine with the right argument. Sorry about the confusion.

**Comment by pktgen** [comment]
BTW you do not need the -p 6 option any more and I normally out quotes around the -m options.
