### ISSUE TITLE
Pktgen rarely receives packets after 'set count'

### ISSUE THREAD

**Issue by chengweiw** [pktgen/Pktgen-DPDK#45]
Hi, 

I use two machines, one runs pktgen and the other runs DPDK l2fwd application. The l2fwd application forward the packets from pktgen and send them back to pktgen. The pktgen can always receive packets when I do not use 'set <portlist> count value'. When I use this command, the pktgen can only occasionally receives packets. For example.

1. set 0 count 1 
2. start 0
3. In the console, Total Rx Pkts shows 0 and Total Tx Pkts shows 1 (assuming no packet has been sent before)
4．However, in the l2fwd application console, it shows 1 packet received and 1 packet sent (also assuming no packet has been sent/received before)

Please advise. Thanks!

Chad

**Comment by pktgen** [comment]
I get the stats from the NIC hardware, so it is possible the hardware counter has a problem. Have you try 2, 4, 8, … TX packets to see if they start to show up. The l2fwd is counting the packets it processes not from the NIC counter I believe.

**Comment by chengweiw** [comment]
Thanks for your reply.

I just tried 2 and 4. RX counter in the pktgen showed up for the first one or two times when I typed 'start 0'. After that, it did not change. 

Yes, l2fwd records pkt processed. I am wondering if the pkts are read by pktgen NIC. I tried to trace the code to see if the pkt is caught in the 'pktgen_main_receive' function. It seemed to me it wasn't. Is 'pktgen_main_receive' the function to rx pkts or there is somewhere else? 

Thanks

**Comment by pktgen** [comment]
I have 4 NIC of 82599 for a total of 8 ports in my machine. When I send one packet from port to port 4 of a different NIC I see that one packet getting received. I can also do the start 0 command many times and will see the same results.

Not sure what is going on here, but the NIC must be ignoring the RX packet or the counters are not working.

**Comment by chengweiw** [comment]
I updated my pktgen to the latest version, then the problem went away. Thanks
