### ISSUE TITLE
dpdk-pktgen runtime error with the XL 710 card

### ISSUE THREAD

**Issue by rajitharlt1** [pktgen/Pktgen-DPDK#46]
I just tried the dpdk-pktgen with the XL710 NIC and it does not work. I am trying to push much throughput as possible to check one of my DPDK-based implementations and trying to use dpdk-pktgen as the traffic generator on a separate pc.
Can you help me with the issue.
Thank you and Kind Regards.

Rajitha L. TENNEKOON

Command:
./app/app/x86_64-native-linuxapp-gcc/pktgen -c 3f -n 2 --proc-type auto --file-prefix pg -w 0000:81:00.1 -w 0000:81:00.0 -- -T -P -m "[3:5].0, [2:4].1" -s 0:pcap/large.pcap -s 1:pcap/large.pcap

Error:
PMD: eth_i40e_dev_init(): Failed to init adminq: -54
EAL: Error - exiting with code: 1
  Cause: Requested device 0000:81:00.0 cannot be used

Software Versions:
DPDK - 2.1.0
pktgen - 2.9.5
NIC - XL =710

NIC Setup:
Network devices using DPDK-compatible driver
============================================
0000:81:00.0 'Ethernet Controller XL710 for 40GbE QSFP+' drv=igb_uio unused=i40e
0000:81:00.1 'Ethernet Controller XL710 for 40GbE QSFP+' drv=igb_uio unused=i40e

Network devices using kernel driver
===================================
0000:01:00.0 'I350 Gigabit Network Connection' if=eth0 drv=igb unused=igb_uio *Active*
0000:01:00.1 'I350 Gigabit Network Connection' if=eth1 drv=igb unused=igb_uio

Other network devices
=====================
<none>

**Comment by pktgen** [comment]
Hi Rajitha,

Not sure I can help here as it appears the PMD failed to init the NIC and does not appear to be something Pktgen is doing. It seems like you have done everything correctly. All I can suggest is you as this question on dev@dpdk.org or look at the maintainers list for DPDK and ask that person directly. I do not have one of these NICs as well.

**Comment by rajitharlt1** [comment]
Dear Keith,

Thank you very much for the promt reply.
I changed the testbed to 10Gbps NICs and now I can send the pcaps.

This may be a novice question as I am so new to the pktgen.
Could you please tell me how to get the throughput (Gbps) of the dpfk-pktgen.
Can I get or calculate it from the status interface?

Please give me some advice at your free time.

Thank you very much and kind regards.

**Comment by pktgen** [comment]
The Gbps per second is reported on the screen, if you want the values in a program you can use Lua and it stats functions.

Not sure I understand your question.

**Comment by rajitharlt1** [comment]
Dear Keith,

Thank you very much for your kind reply. I have gone through your documentations regarding the pktgen and has figured out the commands and its operation.

I am clear on the point you gave me and I am studying the Lua scripts.
Thank you for all the help and guidance.

Thank you very much and kind regards.

Cheers for the good work.

Rajitha L. TENNEKOON
