### ISSUE TITLE
Run Packet gen using scripts

### ISSUE THREAD

**Issue by haris00** [pktgen/Pktgen-DPDK#47]
Is there a way to run packet gen with particular specification via a script?
For instance, can we define source ip, destination ip, run time, rate etc., in a script and just call the script and it would run for that time and exit?
If this is possible, please let me know.
Thanks

**Comment by pktgen** [comment]
Have a look at the Lua scripts rfc2444.lua in the scripts or test directory. The Lua scripts allows you to control Pktgen via a script not sure it will do everything you want as Pktgen is more of a console interactive tool.

**Comment by haris00** [comment]
Thank you for the reply. Can you provide me instructions on how to run the script?

**Comment by pktgen** [comment]
You need to install Lua from Lua.org Lua-5.3 version. Then you can use the command line option to run the script or use the load command on the pktgen command line interface. Have a look at the help and readme file they explain how the Lua scripts can be used.

**Comment by haris00** [comment]
Thank you for the reply. Sorry to bother you again but i have just one more question.
Is there a way in packet gen that while i am sending traffic to a System Under Test, i would be able to send every 1 second the stats reported in packet gen (Tx,Rx, Rx Mbs, Tx Mbs, etc) to some other system?

**Comment by pktgen** [comment]
Pktgen can not do what you want directly, but you can use the –G option on the command line, which is the GUI interface. The GUI interface is what some use to interact with Pktgen from a remote application. The GUI interface is just a TCP socket and allows the developer to send and receive commands/data from Pktgen remotely. The TCP socket is explained a bit in the README and it allows you to send Lua code to the Pktgen controlling it remotely. The –G option stops screens updates and gives you a Pktgen command line prompt, so you have to start Pktgen first via a command line command of some other way. Then you can open the TCP socket and send/receive data.

**Comment by haris00** [comment]
ThankYou for the reply.
One final question :)
I am not able to resolve arp in packetgen. When I start packet gen i do following:
mac_from_arp on
send arp req 0

But packet gen is not able to resolve arp. However if I insert the mac using "set mac 0 aa:...", packet gen works fine?
Can you comment on what am i doing wrong?
Thank You :+1:

**Comment by pktgen** [comment]
The process for using mac_from_arp on is you must add the static ARP entry the DUT, then do a ping to the IP address that matches the Pktgen interface.

If port 0 on Pktgen is IP 10.10.0.1/24 then ‘arp –s 10.10.0.1 00:00:11:22:33:44’ then 'ping 10.10.0.1’ should set the MAC destination address for port 0.

**Comment by haris00** [comment]
If we have to manually ping then what is the "send arp req 0" command for?

**Comment by pktgen** [comment]
To send an ARP request :-) No one knows your IP address and can not respond to you ARP request.

**Comment by haris00** [comment]
my DUT is also a dpdk based application and it does not use Kernel IP stack. Therefore, I may not be able to add arp entry. What do I do then?
We have made our own UDP Send application and it does resolve arp successfully. Than means that DUT(a UDP_ECHO application based on dpdk) has ability to resolve arp but I am not able to resolve it through Packet Gen

**Comment by haris00** [comment]
incidentally, i have discovered that when "send arp req <portlist>" is set, it only sends arp request when pktgen is exited (using 'quit' command') and not while its running :)
Strange!

**Comment by haris00** [comment]
Incidentally, i have discovered that when "send arp req <portlist>" is set, it only sends arp request when pktgen is exited (using 'quit' command') and not while its running :)
Strange!

**Comment by pktgen** [comment]
You need to use the set Mac 0 address in pktgen.

**Comment by haris00** [comment]
Please do check this bug. I have confirmed this on pktgen console.
It would only send arp request (when command 'send arp req 0' is used) only when we close the console and not while it is in the console.

**Comment by haris00** [comment]
I am also not able to set 'A' or 'G' flag on any port
