### ISSUE TITLE
PktGen Arp and ping Packets sent only when PktGen quits

### ISSUE THREAD

**Issue by haris00** [pktgen/Pktgen-DPDK#48]

**Comment by haris00** [comment]
Issue was solved by decreasing the burst size :)

**Comment by pktgen** [comment]
I tried the send arp req 0 on my system and the packets are sent when I execute the command. I need to understand what makes your machine different. Can  you explain your system. Mine is just a Xeon two sockets and a total of 72 lcores and 82599 nics.

**Comment by pktgen** [comment]
Hmm I did not decrease the burst size as these types of packets are sent without waiting for the burst size.

**Comment by haris00** [comment]
Follwoing is my NIC. (I am inside a guest virtual machine, with a passthrough sriov virtual function)
>00:05.0 Ethernet controller [0200]: Intel Corporation 82599 Ethernet Controller Virtual Function [8086:10ed] 
And the CPU of my host node is:
>Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz

My issue is resolved by decreasing the burst size to 1 for sending arp. It won't send arp unless i decrease the burst size or i send 32 arps (having default burst size of 32)
