### ISSUE TITLE
Illegal instruction (core dumped) - Program received signal SIGILL, Illegal instruction. 0x000000000043333c in numa_nodeX_cpus ()

### ISSUE THREAD

**Issue by yockgen** [pktgen/Pktgen-DPDK#49]
Hi,

I'm using two VMs (UBUNTU 16 and 18) to test run with the same steps, but received the same error:

Program received signal SIGILL, Illegal instruction.
0x000000000043333c in numa_nodeX_cpus ()
(gdb) 

DPDK version: 20.11.0 and 20.08
Pktgen-dpdk version: 20.12.0

Please help, have run out of idea what to do next.

Full steps of reproduce the error as below:
=================================================================================
root@osboxes:~# cd /home/osboxes/pktgen-dpdk/
root@osboxes:/home/osboxes/pktgen-dpdk# mkdir -p /dev/hugepages
root@osboxes:/home/osboxes/pktgen-dpdk# mountpoint -q /dev/hugepages || mount -t hugetlbfs nodev /dev/hugepages
root@osboxes:/home/osboxes/pktgen-dpdk# echo 64 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
root@osboxes:/home/osboxes/pktgen-dpdk# ifconfig enp0s8 down
root@osboxes:/home/osboxes/pktgen-dpdk# ifconfig enp0s9 down
root@osboxes:/home/osboxes/pktgen-dpdk# modprobe vfio-pci
root@osboxes:/home/osboxes/pktgen-dpdk# echo 1 > /sys/module/vfio/parameters/enable_unsafe_noiommu_mode

root@osboxes:/home/osboxes/pktgen-dpdk# ./tools/run.py -s default 
>>> sdk 'None', target 'None'
<module 'cfg' from 'cfg/default.cfg'>
Setup DPDK to run 'pktgen' application from cfg/default.cfg file

root@osboxes:/home/osboxes/pktgen-dpdk# python3 /home/osboxes/dpdk/usertools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:00:08.0 '82540EM Gigabit Ethernet Controller 100e' drv=vfio-pci unused=e1000
0000:00:09.0 '82540EM Gigabit Ethernet Controller 100e' drv=vfio-pci unused=e1000

Network devices using kernel driver
===================================
0000:00:03.0 '82540EM Gigabit Ethernet Controller 100e' if=enp0s3 drv=e1000 unused=vfio-pci *Active*

root@osboxes:/home/osboxes/pktgen-dpdk# ./tools/run.py default 
>>> sdk 'None', target 'None'
<module 'cfg' from 'cfg/default.cfg'>
   Trying ./usr/local/bin/pktgen
sudo -E ./usr/local/bin/pktgen -l 2,3-4,5-6,16-17,18-19 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 05:00.0 -a 84:00.0 -a 03:00.0 -a 81:00.0 -- -v -T -P -j -m [3:4].0 -m [5:6].1 -m [16:17].2 -m [18:19].3 -f themes/black-yellow.theme 

Copyright (c) <2010-2020>, Intel Corporation. All rights reserved. Powered by DPDK

root@osboxes:/home/osboxes/pktgen-dpdk# ./Builddir/app/pktgen -l 0-4 -n 4 --proc-type auto --log-level 7 --socket-mem 8192,8192 --file-prefix pg -w 0000:81:00.0 -- t -T -N -m [1:2].0 -l pktGen.log -s 0:/tmp/check.pcap -G

Copyright (c) <2010-2020>, Intel Corporation. All rights reserved. Powered by DPDK
Illegal instruction (core dumped)

root@osboxes:/home/osboxes/pktgen-dpdk# gdb ./Builddir/app/pktgen
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Builddir/app/pktgen...(no debugging symbols found)...done.
(gdb)  r -l 0-4 -n 4 --proc-type auto --log-level 7 --socket-mem 8192,8192 --file-prefix pg -w 0000:81:00.0 -- -T -N -m [1:2].0 -l pktGen.log -s 0:/tmp/check.pcap
Starting program: /home/osboxes/pktgen-dpdk/Builddir/app/pktgen -l 0-4 -n 4 --proc-type auto --log-level 7 --socket-mem 8192,8192 --file-prefix pg -w 0000:81:00.0 -- -T -N -m [1:2].0 -l pktGen.log -s 0:/tmp/check.pcap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Copyright (c) <2010-2020>, Intel Corporation. All rights reserved. Powered by DPDK

Program received signal SIGILL, Illegal instruction.
0x000000000043333c in numa_nodeX_cpus ()
(gdb)

**Comment by pktgen** [comment]
What are the versions of DPDK and Pktgen you are using. If not on the latest DPDK or Pktgen, then it will be hard for me to debug.

You are using -l 0-4 and you are only using lcores 0, 1, 2 so could be -l 0-2. This is not the problem just something to point out.

I normally run on Ubuntu 20.04 or 20.10, but I do not believe that is the problem as well.

Are you running pktgen as root via sudo, if not that is the problem, but I assume you are.

The error is inside a system level API and not in Pktgen as pktgen does not have a function called numa_nodeX_cpu(). It could be in DPDK, but I do not think so.

Normally these types of problems are related to the CPU, meaning the compiler created code that can not run on your system or something is corrupting the code to create a invalid instruction.

Does testpmd work?

**Comment by yockgen** [comment]
Hi,

I've managed to make the pktgen run without the "illegal instruction" issue after tried on VM with UBUNTU 20.04, detail software package as below:

DPDK version: 20.11.0 
Pktgen-dpdk version: 20.12.0
VM: VirtualBox
OS: UBUNTU 20.04

However, the same pieces of software and installation steps NOT WORKING (illegal instruction) on following OS running via VM (VirtualBox)
1. Ubuntu 16.04 (I've tried to update the Linux kernel to 5.4.0)
2. Ubuntu 18.04


Anything I've missed? Any compilation option I could fine tuned?

Thanks!

**Comment by pktgen** [comment]
Without being able to debug the problem it’s going to be hard to figure out what is causing the problem.

16.04 and 18.04 are pretty old, do you need to use these older versions of Ubuntu?

Did you try testpmd and did it work on these older versions. Plus I assume you recompiled pktgen and dpdk for each OS version.

**Comment by yockgen** [comment]
I've further troubleshooting by running the VMs (UBUNTU18 and UBUNTU20) again in different host machines, and able to make the previously not working UBUNTU 18 run pktgen, the only different on both machines so far spotted is:

-The working machine's CPU with AVX support (using "grep avx /proc/cpuinfo" to find out)
-The NOT working machine's CPU with NO AVX support (using "grep avx /proc/cpuinfo" to find out) 

Take note, all experiments are based on: 
===========================
-DPDK 20.11 
-pktgen-dpdk 20.12.0
-VirtualBox 6.1
-Recompiled both DPDK and Pktgen
-testpmd and dpdk helloworld, skeleton and l2fwd examples able to run properly all experimental machine
  
Is CPU avx instruction the root cause of the issue? Any flag in Pktgen compilation could control this?

Thanks!

**Comment by pktgen** [comment]
Pktgen does not control AVX usage this is a DPDK build and configuration problem. Some VMs do not allow access to the cpu flags or they create fake flags. 

I would look into how dpdk is built to help solve this problem as it is not a pktgen problem as I stated before. DPDK should detect the cpu flags and build the correct image for that machine. You can not run one dpdk built on one machine on another machine as the two machines may have different cpu features without building dpdk to the lowest possible common feature set. Dpdk does have ways to do that build but you need to consult dpdk build configuration to fix the problem.

**Comment by yockgen** [comment]
I've found the solution finally:

For host CPU not support avx2, set "enable-avx2" to false (default is true) in meson_options.txt:

**option('enable-avx2',** type: 'boolean', value: false, description: 'compile with AVX2 support')

And, just issue "make" to recompile again pktgen-dpdk.

Thanks everyone!
