### ISSUE TITLE
Compilation failing with latest DPDK version.

### ISSUE THREAD

**Issue by artosan** [pktgen/Pktgen-DPDK#50]
I'm having problems compiling pktgen using latest DPDK. 

pktgen-stats.c is using ibadcrc and ibadlen which are deprecated and cause the compilation to fail.

For instance, here is one of the errors i get when i run make:

"app/pktgen-stats.c:308:9: error: ‘ibadcrc’ is deprecated..."

Is there a fix available to this or do i have to use older version of dpdk?

**Comment by pktgen** [comment]
Yes, I have a fix. I will post that one. I was tying to figure out why the performance dropped in Pktgen, but have not found it yet :-( It looks like DPDK 2.2 may have a performance problem with Pktgen.

**Comment by pktgen** [comment]
You should be able to do a pull of the new released version. Let me know if you have any problems.

**Comment by artosan** [comment]
Hi,

Thanks for the quick response. 

I will try this out asap.

**Comment by artosan** [comment]
Yes, this worked, i got it compiled and running. Thank you.
