### ISSUE TITLE
Port Assignment Issue

### ISSUE THREAD

**Issue by nishant-v** [pktgen/Pktgen-DPDK#51]
i am having Xeon d 1540. with 2 10G and 2 1Gb ethernet support.
I have installed dpdk-2.1.0 and latest pktgen.

Problem is when assigned just 1 10Gb to DPDK and start pktgen with that port, everything looks good. Link status shown as UP.
As soon as, i just assigned another 10Gb NIC to DPDK(just to dpdk not to pktgen, just assignment) pktgen links goes down.

Just to make sure port condition and dpdk instalIation, i have checked with testpmd app, fire command "port start all", i found no issue in that.

Any clue why it is happening, will be highly appreciated

**Comment by pktgen** [comment]
Is this two instances for DPDK or just one? If you are doing two instances then you can look at the pktgen-slave.sh and pktgen-master.sh scripts.

DPDK requires you to assign two differ file prefixes to each DPDK instance then you have to make sure you have enough memory for instances assigned to the system then divided between the two. The next thing is to make you black list the second port for the first instances and then black list the first port for the second instance. You did not give me much information, so I just assumed you were trying to run two instances of DPDK.

**Comment by nishant-v** [comment]
Thanks for the reply.

No, their is just one instance of DPDK.
Just for clarity purpose, i will provide exact thing, i am doing.

Setup Info: I have two 10Gb Port that i have connected through cross cable. My intention is to assign one port to pktgen and other one to l2fwd and check throughput. Surely i will use file-prefix and shared-mem, if i run two dpdk instance.
But right now problem come in port assignment, much before that step.

1.  Out of two 10Gb Port, just one is assigned to DPDK by using bind script, other is still with linux. After that, i tried to run pktgen. It work fine. Link status shown as "10000 UP". Now i just tried to execute bind script again to Bind other 10Gb port to DPDK.
3. But just by assigning the port to DPDK through script, till now i haven't try to initiate other dpdk app, my pkt-gen shows my "LINK DOWN".

I have checked my cross cable by executing pktgen and l2fwd on different machine(some different configuration), its working fine. I am able to get throughput.

Thanks for reading.

**Comment by pktgen** [comment]
What I do is bind both ports to igb_uio from the start and then use -b option to black list one from each of the applications. Binding ports to DPDK after startup I have not play with at all.

**Comment by nishant-v** [comment]
Thanks a lot. It works.
