### ISSUE TITLE
how to build the pktgen with dpdk static library(pktgen 21.01)?

### ISSUE THREAD

**Issue by wliu2007** [pktgen/Pktgen-DPDK#54]
pktgen 21.01 only support meson/ninja build method,    the meson.build set the 'default_library=static',  why the built pktgen is shared library?

if i want to use dpdk static library,  how can i do?

dpdk shared library:
```console
root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ldd app/pktgen
        linux-vdso.so.1 =>  (0x00007ffd863f4000)
        librte_timer.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_timer.so.21 (0x00007f5de6d13000)
        librte_ethdev.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_ethdev.so.21 (0x00007f5de6a6f000)
        librte_net.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_net.so.21 (0x00007f5de6868000)
        librte_mbuf.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_mbuf.so.21 (0x00007f5de665c000)
        librte_mempool.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_mempool.so.21 (0x00007f5de6452000)
        librte_eal.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_eal.so.21 (0x00007f5de6163000)
        libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f5de5f22000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5de5d1e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5de5a15000)
        librte_net_bond.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_net_bond.so.21 (0x00007f5de57f7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5de55da000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5de5210000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5de6f18000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f5de5005000)
        librte_kvargs.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_kvargs.so.21 (0x00007f5de4e02000)
        librte_telemetry.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_telemetry.so.21 (0x00007f5de4bf9000)
        librte_ring.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_ring.so.21 (0x00007f5de49f5000)
        librte_meter.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_meter.so.21 (0x00007f5de47f2000)
        librte_bus_pci.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_bus_pci.so.21 (0x00007f5de45e6000)
        librte_pci.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_pci.so.21 (0x00007f5de43e3000)
        librte_bus_vdev.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_bus_vdev.so.21 (0x00007f5de41de000)
        librte_sched.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_sched.so.21 (0x00007f5de3fd1000)
        librte_ip_frag.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_ip_frag.so.21 (0x00007f5de3dc7000)
        librte_hash.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_hash.so.21 (0x00007f5de3baa000)
        librte_rcu.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_rcu.so.21 (0x00007f5de39a5000)
root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ls -lh app/pktgen
-rwxrwxr-x 1 root admin 453K Jan 27 14:54 app/pktgen
root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# 
```

#dpdk static library
```console
root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# 
root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ldd /home/admin/pktgen 
        linux-vdso.so.1 =>  (0x00007fffe67cc000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f91fb5e6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f91fb2dd000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f91fb0d2000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f91faece000)
        libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f91fac8d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f91faa70000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f91fa6a6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f91fb7ee000)
root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ls -lh /home/admin/pktgen 
-rwxr-xr-x 1 root admin 14M Jan 21 19:47 /home/admin/pktgen
root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# 
```

**Comment by pktgen** [comment]
In the meson.build at the top level directories both DPDK and Pktgen have static set, I will have to look into it when I get time this weekend. Sorry work is very busy right now.

**Comment by pktgen** [comment]
Can not reproduce this problem, open it again if you find something different.

**Comment by subrnath** [comment]
I am facing the same issue. pkg-config --cflags --libs libdpdk.pc returns the shared library for linking.

versions -
pktgen-21.02.0 
dpdk-20.11

**Comment by nishant-v** [comment]
> pktgen 21.01 only support meson/ninja build method, the meson.build set the 'default_library=static', why the built pktgen is shared library?
> 
> if i want to use dpdk static library, how can i do?
> 
> dpdk shared library:
> 
> ```
> root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ldd app/pktgen
>         linux-vdso.so.1 =>  (0x00007ffd863f4000)
>         librte_timer.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_timer.so.21 (0x00007f5de6d13000)
>         librte_ethdev.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_ethdev.so.21 (0x00007f5de6a6f000)
>         librte_net.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_net.so.21 (0x00007f5de6868000)
>         librte_mbuf.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_mbuf.so.21 (0x00007f5de665c000)
>         librte_mempool.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_mempool.so.21 (0x00007f5de6452000)
>         librte_eal.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_eal.so.21 (0x00007f5de6163000)
>         libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f5de5f22000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5de5d1e000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5de5a15000)
>         librte_net_bond.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_net_bond.so.21 (0x00007f5de57f7000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5de55da000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5de5210000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f5de6f18000)
>         libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f5de5005000)
>         librte_kvargs.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_kvargs.so.21 (0x00007f5de4e02000)
>         librte_telemetry.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_telemetry.so.21 (0x00007f5de4bf9000)
>         librte_ring.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_ring.so.21 (0x00007f5de49f5000)
>         librte_meter.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_meter.so.21 (0x00007f5de47f2000)
>         librte_bus_pci.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_bus_pci.so.21 (0x00007f5de45e6000)
>         librte_pci.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_pci.so.21 (0x00007f5de43e3000)
>         librte_bus_vdev.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_bus_vdev.so.21 (0x00007f5de41de000)
>         librte_sched.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_sched.so.21 (0x00007f5de3fd1000)
>         librte_ip_frag.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_ip_frag.so.21 (0x00007f5de3dc7000)
>         librte_hash.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_hash.so.21 (0x00007f5de3baa000)
>         librte_rcu.so.21 => /usr/local/lib/x86_64-linux-gnu/librte_rcu.so.21 (0x00007f5de39a5000)
> root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ls -lh app/pktgen
> -rwxrwxr-x 1 root admin 453K Jan 27 14:54 app/pktgen
> root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# 
> ```
> 
> #dpdk static library
> 
> ```
> root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# 
> root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ldd /home/admin/pktgen 
>         linux-vdso.so.1 =>  (0x00007fffe67cc000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f91fb5e6000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f91fb2dd000)
>         libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f91fb0d2000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f91faece000)
>         libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f91fac8d000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f91faa70000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f91fa6a6000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f91fb7ee000)
> root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# ls -lh /home/admin/pktgen 
> -rwxr-xr-x 1 root admin 14M Jan 21 19:47 /home/admin/pktgen
> root@CyOS:/data/work/Pktgen-DPDK-pktgen-21.01.2/build# 
> ```
Do you remember how you fixed that issue???

**Comment by nishant-v** [comment]
> I am facing the same issue. pkg-config --cflags --libs libdpdk.pc returns the shared library for linking.
> 
> versions - pktgen-21.02.0 dpdk-20.11

@subrnath any idea how you resolved that issue???

**Comment by WENPIN1** [comment]
in top level directory add follwing option for try.
Don't know why it might work.
'prefer_static=true'

e.g.

default_options: [
                'buildtype=release',
                'default_library=static',
                'prefer_static=true',
                'warning_level=3',
                'werror=true'
        ],
