### ISSUE TITLE
Latency measurements with pktgen-dpdk?

### ISSUE THREAD

**Issue by TapioT** [pktgen/Pktgen-DPDK#54]
There was some (non-working?) code to implement latency measurements with pktgen-dpdk, any updates on this?

**Comment by pktgen** [comment]
I have not had a chance to work on that code, sorry.

**Comment by chengweiw** [comment]
I have a branch of Pktgen-DPDK with latency, jitter measurements. It is working and I have been using this version for my experiments. 

Please let me know any questions if you would like to give it a try

https://github.com/chengweiw/Pktgen-DPDK

Chengwei

**Comment by pktgen** [comment]
Thanks Chengweiw. I will have a look am hoping you based your changes on the current 2.2.0 DPDK

**Comment by chengweiw** [comment]
this branch is not based on latest, but I have an updated version workable with current DPDK. I will update the github on that, and also the readme file. 

Thanks
Chengwei

**Comment by joshic** [comment]
Hi Chengwei,
I was trying to use the packet generator for latency measurement but it seems to be incompatible with dpdk2.2.0.
Am I missing something ?

**Comment by chengweiw** [comment]
I am fixing issues with supporting dpdk 2.1.0 or higher, will update soon. Currently the pktgen-dpdk-latency-jitter works with DPDK 1.7.0. You can use the 1.7.0 subdir to install and run pktgen. --Chengwei
________________________________________

**Comment by ZhihuiWu** [comment]
Hi, @pktgen do you have a plan to support Latency measurements in pktgen-dpdk?

**Comment by pktgen** [comment]
Please look at the 'dev' branch at dpdk.org I have a start at latency testing in that version.

**Comment by ZhihuiWu** [comment]
That is great. Thanks for your reply.
