### ISSUE TITLE
seqCnt Configuration.... pktgen crashed

### ISSUE THREAD

**Issue by nishant-v** [pktgen/Pktgen-DPDK#55]
Just to check how pktgen seqCnt works. I executed pktgen binary, with 2 cores and 1 port.
I like to check how it will send packets to destination with different destination address.

I just executed this command on pktgen prompt
" seq 0 all 0000:4455:6677 0000:1234:5678 10.11.0.1 10.10.0.1/16 5 6 ipv4 udp 1 128 "
after that
" set 0 seqCnt 1"

after that, i executed "start all"
and pktgen crashed. It might possible i had missed some configuration. 
I will appreciate if anyone please let me know, whats wrong in this process?

Thanks

**Comment by pktgen** [comment]
Which version of Pktgen-DPDK are you using?

Also look at the ‘page seq’ command and see if the packet is configured correctly before the start all.

Thanks

**Comment by pktgen** [comment]
BTW, the IP addresses appear to be missing the dots. Is that an email problem or did not include the dots?

**Comment by nishant-v** [comment]
IP address dot are not showing up, although you can check my initial post, it was their.

By just issuing seq command with parameters as shown in initial mail, parameters are not getting changed on pktgen side. 

I will share the detailed view in couple of hours but till that time can any one from this community please let me know the correct use of seq command at pktgen

thanks.

**Comment by pktgen** [comment]
Are you loking on the sequence page via 'page seq' ?

**Comment by pktgen** [comment]
The command looks fine. You did not tell me which DPDK version or pktgen version. 

Also please send the command line too.

**Comment by nishant-v** [comment]
My DPDKversion is 2.1.0
Pktgen is 2.7.7

./pktgen  -c 0xff -n 4 -- p 0x01 -P -m "[4-5].0

seq 0 all 0000:4455:6677 0000:1234 :5678 10.11.0.1 10.10.0.1/16 5 6 ipv4 udp 1 128
set all seqCnt 1

**Comment by nishant-v** [comment]
Here is the detailed pic of pktgen. 
![office lens 20160111-175023](https://cloud.githubusercontent.com/assets/7613402/12249248/88f225b0-b88c-11e5-95ea-bac9c12ac965.jpg)

When i executed pktgen command, sequence flag got enabled.
After that i give command start, that leads to crash.
Here is the crash output.
![office lens 20160111-175235](https://cloud.githubusercontent.com/assets/7613402/12249283/c0349116-b88c-11e5-9ba5-134d5ecd9b64.jpg)

**Comment by pktgen** [comment]
I would suggest if you can move to the latest version of pktgen and DPDK.  You will find both at DPDK.org in the download tab. I do not support that old of version.

**Comment by pktgen** [comment]
Weird I could have sworn you were using an older version, but when I look at the emails on GitHub you are using a good version. DPDK 2.1 and 2.9.6 are OK.

This problem looks to be related to the packet fill code.

BTW the -p 0x01 option is not required any more.

The only problem is I am out of town at all day meetings, so I will have to look at the problem next weekend.

**Comment by nishant-v** [comment]
Moved to latest pktgen version 2.9.7
DPDK version is 2.1.0

Run command same command on pktgen as stated in my previous pic. But this time crashed is somewhat different. PFA crash snapshort.
![office_lens_20160118-181704 1](https://cloud.githubusercontent.com/assets/7613402/12405247/35c7b254-be10-11e5-9a8a-a851368e69b9.jpg)
-------
Apart from this crash, some basic question about seq and seqCnt
1. what is significance of seq# in seq command?
2. what set seqCnt do internally? 
3. Suppose i need to send only 20 packet in sequence? how can i state this in command?
I haven't found anything specific on this topic, Doc are also not too descriptive.

Please explain. Any link or article will be appreciated.
thanks.

**Comment by pktgen** [comment]
OK, I think I found the bug, please pull Pktgen-DPDK 2.9.8 thanks for the help.

**Comment by nishant-v** [comment]
thanks keith.
Yes this time their is no crash.

But still my problem is not fully solved.
1. When i issue seq command, the destination mac is not updated on display screen. although pkt size got changed as desired.
2. I set count as 1000. after that when i captured the packet, i have checked that even i issued seqcnt command, but still packet flow is just between 1 set of IP and port. All 1000 packets are between same IP's. 

My assumption was, that after issuing seq command, Let sat, my first packet is from 192.168.1.1 then my next would be from 192.168.1.2 ..... and so on.

Please correct me if i am wrong.

![office_lens_20160119-101102 1](https://cloud.githubusercontent.com/assets/7613402/12422486/35811008-be95-11e5-80a0-735cf3a7490e.jpg)

**Comment by pktgen** [comment]
The sequence packets try to keep the packets in order.
