### ISSUE TITLE
Does Pktgen-DPDK have a TCP stack ?

### ISSUE THREAD

**Issue by chengweiw** [pktgen/Pktgen-DPDK#56]
Hi, 

It is actually not an issue but a question about Pktgen-DPDK. I think that pktgen-dpdk does not have a TCP stack as I did not find related code in the source, but I am not sure....

Thanks for clarification. 
Chengwei

**Comment by pktgen** [comment]
Correct pktgen does not have. TCP stack only able to construct a TCP packet with very basic support.

**Comment by chengweiw** [comment]
thanks
