### ISSUE TITLE
Turning on range mode for a port prevents the sending of packets

### ISSUE THREAD

**Issue by DoctorSher** [pktgen/Pktgen-DPDK#57]
### Setup:
I am running a simple experiment where I have a pktgen sender connected to a software router, and the receiver of the pktgen traffic connected to a different port on the same router.

First, to ensure my setup is working, I configure pktgen with the destination IP address, a /32 source IP address (192.168.1.2), and the destination mac address. This transfer works perfectly, and I see ~300 Kpps at the router.

### Problem:
Then I want to send a range of source IP addresses to achieve multiple flows. 
I enter the commands:
```
src.ip min 0 192.168.1.2
src.ip start 0 192.168.1.2
src.ip max 0 192.168.1.254
src.ip inc 0 0.0.0.1
range 0 on
```
And start the transfer. The pktgen sender thinks it is sending at line rate, but the router's ingress port does not receive any traffic. If I turn range mode off and start a new transfer, it starts receiving traffic again.

### Leads I have pursued:
* I have done `range 0 enable`, `range 0 on`, and both of them together.
* I have tried different spots to turn on range mode (before the src.ip commands, after the commands, and both at the same time).
* I have tried collapsing my sending range such that the only source IP address is the one I used in the previous non-range transfer. This too fails to send. Just to be specific, this would change max and inc from the previous list of commands to `src.ip max 0 192.168.1.2` and `src.ip inc 0 0.0.0.0`.
* I have configured the NIC on the ingress port of the router in promiscuous mode; it still does not receive any pktgen packets.
* I have tried other permutations of pktgen versions and dpdk versions, which I can specify if requested.

### Specs:
**pktgen**: version 2.9.8 
**DPDK**: version 2.2.0
**pktgen invocation**: `sudo ./pktgen -c 0xf -n 3 -- -P -m "[1:3].0"`
**NIC**: Intel Corporation Ethernet Controller 10-Gigabit X540-AT2
**CPU**: 2 sockets, 6 physical cores each
**Operating System details**: Ubuntu 14.04, Linux 3.19.0-30-generic, x86_64

**Comment by pktgen** [comment]
Did you set the MAC address for the router in the range as the single packet and range have its own MAC address. 

Do 'page range' to see the range configuration and use 'port x' to select the port.

**Comment by DoctorSher** [comment]
Ah, I was NOT setting the MAC address for the router in the range. I mistakenly thought the single packet settings would carry over if I didn't overwrite them. It works perfectly now. Thank you very much.

**Comment by DoctorSher** [comment]
Ah, I was NOT setting the MAC address for the router in the range. I mistakenly thought the single packet settings would carry over if I didn't overwrite them. It works perfectly now. Thank you very much.
