### ISSUE TITLE
pktgen send with pcap error.

### ISSUE THREAD

**Issue by I0-0I-gqj** [pktgen/Pktgen-DPDK#57]
Hi:
  I use core(hugepage) not in socket 0 to send one pacp error ' create mubfs error. '. Then i find in app/pktgen-pcap.c : 358 rte_mempool_create(..., rte_lcore_to_socket_id(0) ; why is must be socket 0?
  I modified it by correct socket, then it's run ok.

**Comment by pktgen** [comment]
Thanks

**Comment by pktgen** [comment]
fixed in latest version 21.02.0
