### ISSUE TITLE
Cannot transmit with latest 2.2.0 pktgen-dpdk release and ixgbe

### ISSUE THREAD

**Issue by wkevils** [pktgen/Pktgen-DPDK#58]
Hello,

I have two Linux machines; each has an IXGBE card.
These two machines are connected by a direct cable. 
On machine A, I had run
ip address add 12.0.0.2/24 dev eth2

On machine B, I had run
ip address add dev eth6 12.0.0.1/24

I can ping between A and B
Also, on B, ethtool -i eth6 | grep bus shows:
bus-info: 0000:04:00.1

I had install dpdk-2.2.0 and pktgen-dpdk on machine B.

Now, I run the following on B:
ifconfig eth6 down
modprobe uio_pci_generic
/work/src/dpdk-2.2.0/tools/dpdk_nic_bind.py -b uio_pci_generic 0000:04:00.1

./app/app/build/pktgen -c 0x1f -n 3 --proc-type auto -- -p 0x0 -P -m "1.0"

I see a message that port 0 is up:
Port  0: Link Up - speed 10000 Mbps -..

And I do reach the Pktgen> prompt on B.

Now I try to send traffic from B dpdk-pktgen command line to A thus:

Pktgen> set 0 rate 1
Pktgen> set 0 count 10
Pktgen>set ip dst 0 12.0.0.2
Pktgen>set ip src 0 12.0.0.1/24
and then 
Pktgen>start  0

I don't see that Tx counters are incremented.
Shouldn't this work ? 
On side A I had started a sniffer with ethteool -i eth2 but I don't see any packets
I also added print messages in the pkt-gen dpdk code, in pktgen_start_transmitting(),and I 
_do_ reach them when I ran "start 0". 

Any idea what went wrong? why I am not seeing the traffic on A with the sniffer ? what should be added on B so that it will work ? 

Regards,
Kevin

**Comment by wkevils** [comment]
I have dpdk-pktgen from git latest tree,

I added now (according to what I understand, this is the way to set dest MAC address):
Pktgen> set mac 0 macAddr
Where macAddr is the mac address of eth2 and B.
I also removed  -p 0x0  from the command line invocation of pktgen


Still I cannot see any trafffic with tshark -i eth2, and still I do see message in pktgen_start_transmitting()

Any ideas how to debug this ? 


Kevin

**Comment by wkevils** [comment]
First, I run tshark as needed, not on the machine which runs dpdk-pktgen, but on the other side.
Second, as said, I am setting the correct MAC address of the destination, by Pktgen> set mac 0 macAddr

> If you see the TX packet count increasing on Pktgen, then the packet is being sent. 

What is the correct way to get this information ? I do see that the pktgen_start_transmitting()
is called, but I don't think that the tx counter is incremented. How do I check it ? 

Kevin

**Comment by pktgen** [comment]
Did you resolve this issue?

**Comment by AlecZadikian9001** [comment]
Similar problem here with latest version. I don't have anything on the receiving end (yet). Just trying to make it send packets first. I start it similarly to how he does it, enter "start 0", then look at the screen. Says 0 Max/Tx and doesn't show anything for "Total Tx Pkts"... but I do see it using 100% CPU.

**Comment by pktgen** [comment]
> On Jan 19, 2017, at 4:21 PM, AlecZ <notifications@github.com> wrote:
> 
> Similar problem here with latest version. I don't have anything on the receiving end (yet). Just trying to make it send packets first. I start it similarly to how he does it, enter "start 0", then look at the screen. Says 0 Max/Tx and doesn't show anything for "Total Tx Pkts"... but I do see it using 100% CPU.

For Pktgen and DPDK the CPU will always be at 100% as it is polling the interfaces and does not stop.

Normally the ports must be UP to send traffic and if you have the configuration wrong that too can cause it to not send packets.

Can you send me the command line you used and maybe a screen shot would help too.

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by AlecZadikian9001** [comment]
I run it with this command in the pktgen directory: `sudo -E ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x01 --socket-mem 1024,1024 -w 06:00.0 -w 06:00.1 -- -T -P` I tried different core masks like 0x03 and 0x07, same result.

It prints this as it starts:

Copyright (c) <2010-2016>, Intel Corporation. All rights reserved. Powered by Intel® DPDK
EAL: Detected 16 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:06:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe

Then this is what my interactive session looks like. It doesn't seem to do anything when I type the commands:

![screen shot 2017-01-19 at 10 49 06 pm](https://cloud.githubusercontent.com/assets/5402886/22139219/ad5417c2-de99-11e6-932f-0c483549fc28.png)

**Comment by pktgen** [comment]
> On Jan 20, 2017, at 12:51 AM, AlecZ <notifications@github.com> wrote:
> 
> I run it with this command in the pktgen directory: sudo -E ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x01 --socket-mem 1024,1024 -w 06:00.0 -w 06:00.1 -- -T -P I tried different core masks like 0x03 and 0x07, same result.

You need to use at least two cores one core is consumed by Pktgen to display the console and run timers.

You always need one more cpu then the ones being used with the ports. Next you need to decide how many cores per port to use, which can be to 1 - N cores per ports. Normally the best performance is two cores per port, one for RX and one for TX. You need to add a mapping option to the line using the -m “…” command.

I would use something like -c 0x07 or you can use the newer option -l 1-3, which I find easier to use then a bitmap for the lcores. Then create a -m “[2:3].0” for the ports. If you have more ports then one add more lcores and -m “[2:3].0, [4:5].1, …"

> 
> It prints this as it starts:
> 
> Copyright (c) <2010-2016>, Intel Corporation. All rights reserved. Powered by Intel® DPDK
> EAL: Detected 16 lcore(s)
> EAL: Probing VFIO support...
> EAL: PCI device 0000:06:00.0 on NUMA socket 0
> EAL: probe driver: 8086:10fb net_ixgbe
> EAL: PCI device 0000:06:00.1 on NUMA socket 0
> EAL: probe driver: 8086:10fb net_ixgbe
> 
> Then this is what my interactive session looks like. It doesn't seem to do anything when I type the commands:
> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by AlecZadikian9001** [comment]
The "-m" option, assigning at least one core to each port, made it successfully send packets. I had been assuming it would automatically assign cores to ports without it. Thanks! For anyone viewing this, this is exactly what I ran, and it worked:
`sudo -E ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x0f --socket-mem 1024,1024 -w 06:00.0 -w 06:00.1 -- -T -m "[2:3].0, [4:5].1"`
