### ISSUE TITLE
RSS Rx with Intel XL710

### ISSUE THREAD

**Issue by marcofaltelli** [pktgen/Pktgen-DPDK#59]
Hi,
I'm trying to send&receive 64B line-rate traffic (approx. 38Mpps) with an Intel XL710 card. One link is sending and the other one is receiving.
With a single core in Rx I get almost line rate performance. When I switch to 2+ cores and do `enable 0 range`, performances significantly decrease (around 17Mpps received). Do you have any experience/best practices for XL710 NICs or multiqueue scaling?
I'm using Pktgen 21.02, DPDK 19.11 ans Linux 4.15 (also tried to switch to kernel 5.4, nothing changed). CPU is Intel Xeon 4110 @2.1GHz.
I'm also using the xl710 cfg file with the appropriate changes in terms of PCI addresses and cores allocated.
Another strange thing: even if a single core is allocated for Rx, i still see 3 Rx queues receiving traffic when doing `page stats`

**Comment by pktgen** [comment]
The range mode the code must touch each packet to adjust the packet to send the range of packets. The performance will drop because of needing to touch and modify every packet sent ☹

When range mode is enabled you have to add more cores for RX/TX of packets. I do not know how you have Pktgen configured, but I have multiple cores send/receive  to/from different port/queues to get the performance back up to the level it was before.

Without knowing your configuration, it is hard to say why you see three RX queues stats. It maybe you allocated three RX core instead of on when you want 1 Rx and three TX cores.

**Comment by marcofaltelli** [comment]
Yes I knew performance would decrease a bit when I do `enable 0 range`, but that's ok for me. :)
Instead, my problem is on the receive side, since once RSS starts, performance significantly decrease.
Here is my configuration:
[xl710.txt](https://github.com/pktgen/Pktgen-DPDK/files/6015102/xl710.txt) (GitHub does not accept .cfg files)
As you can see, the cores configuration is:
`'map': (
		'[6:16/18/20].0',
		'[8/10/12:4].1',
		),`
So port 0 has 3 TX cores and port 1 has 3 RX cores.
Starting pktgen in this way, I get almost 37Mpps in RX and they are all received on a single RX queue since the `range` feature is disabled by default (I am sure of this since I see it from the `page stats` command).
Once I run the same application but with the `enable 0 range` command, performances significantly decrease even if the traffic is now split among 3 different RX queues (around 17Mpps in RX).
That is the problem I'm having. Am I missing something?

PS. the `stats` issue is now solved, please do not further consider it

**Comment by pktgen** [comment]
What does the core layout look like? You can use the DPDK tool cpu-layout.py tool.

The map looks ok for your configuration. What is the full .cfg file look like?

If you just have [6:16].0, [8:4].1 what is the performance with the range enabled and disabled?

Is this machine a two socket/processor machine or one?

**Comment by marcofaltelli** [comment]
Output from cpu_layout.py
![immagine](https://user-images.githubusercontent.com/50075466/108608971-e48d8500-73ca-11eb-8790-48833dad7532.png)
As you can see, it's a dual-socket server. Intel XL710 NICs are associated to Socket 0, so I'm using even cores.
The full cfg file is the one linked in my previous comment (I simply changed its extension from .cfg to .txt because GitHub was not accepting the .cfg extension).
If i give just one core RX and one TX for both links, the throughput is around 20Mpps and it does not change whether the `range` feature is enabled or not. Throughput is entirely received (no loss) in both cases.
Previously, I had also tried to increase the RX queue size in the `app/pktgen-constants.h` file, but with minimal improvements.
Further insight, I'm using the `vfio-pci` driver together with the Intel iommu feature.

**Comment by pktgen** [comment]
Sorry, I missed the .cfg file.

Here is a cfg file that may fix the problem, I added some comments in the file to explain the issue.

[xl710-kw.txt](https://github.com/pktgen/Pktgen-DPDK/files/6016853/xl710-kw.txt)

The issue with the .cfg file was you were using two lcores on the same physical core 4 and 20.

Hope that fixes the problem.

**Comment by marcofaltelli** [comment]
I tried your configuration, but with no improvements...
I made only one small change to your .cfg, since command line tells me core 0 should not be used for RX/TX functionalities, I changed it to
```
'[2:4/6].0',
'[8/10/12:14].1',
```
Which shouldn't be a big issue (TX throughput is now around 37 Mpps).
As I told you, the issue remains the same. As long as one core is receiving, line-rate throughput can almost be sustained. Once the load is split across multiple cores in RX, throughput dramatically goes down (17 Mpps total).
The thing is, I need more cores in RX since I'd like to perform more complex stuff than just receiving, for example a L3 forwarder.

**Comment by pktgen** [comment]
OK, must be a bug in the RX side or something else for multiple RX queues on a port.

One thing about multiple RX queues is the NIC must divide it's internal memory into N number of queues, which can reduce the RX performance. This normally starts to happen at around 6 queues, maybe it happens are 4 here. Have you tried 2 queues and 3 queues? Does the performance driver at 2, sorry if you stated this before.

**Comment by marcofaltelli** [comment]
I ran some tests and it seems to be a little difference when varying between 2,3 or 4 RX queues: with 3 queues it goes a little bit better (19Mpps vs. 17-18Mpps for 2,4 RX queues).
One thing that comes to my mind is that my CPUs don't have Intel DDIO, could this be an important limitation? In my mind a XL710 NIC has an ingress throughput of 42 Mpps, so once it splits traffic on 3 RX queues, every queue has around 14 Mpps of RX throughput, just like a single RX queue on a 10Gbps NIC, which works fine on my server.
I tried receiving packets with MoonGen and I managed to get around 36 Mpps of RX throughput with 4 queues, so I'm thinking that the NIC RSS configuration may somehow be different.

**Comment by pktgen** [comment]
If the traffic is balanced across the queues then we should see similar performance to moongen I would think.

**Comment by marcofaltelli** [comment]
That was my take too... still, the traffic seems balanced in PktGen
![immagine](https://user-images.githubusercontent.com/50075466/108778046-120e3600-7565-11eb-91f2-af61502c7ed1.png)
Did you ever tested PktGen with Intel XL710? And if so, can you remember some specifications for those tests (DPDK driver, NIC firmware, CPU type, kernel version...)?

**Comment by pktgen** [comment]
I have the XL710, but not tested in you specific setup and I do not have the time yet to set it up.

Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 02)

Ubuntu 20.10
Linux purley 5.8.0-43-generic #49-Ubuntu SMP Fri Feb 5 03:01:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ sudo ethtool -i enp94s0f0
driver: i40e
version: 2.8.20-k
firmware-version: 6.01 0x800035da 1.1747.0
expansion-rom-version:
bus-info: 0000:5e:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

I remember testing this state sometime back and did not see a problem, but I was not looking at your specific issue.

**Comment by marcofaltelli** [comment]
So, I have one server with your same driver version and a newer firmware, so I guess that is not the problem.
In the next days I'm going to move the XL710 to a server equipped with DDIO and see if the performances change.
Please let me know if you find anything useful.
In the meantime, thank you for your quick replies, you've been very helpful! :smile:

**Comment by pktgen** [comment]
Thank you, hope you get it working.
