### ISSUE TITLE
Combination of latency and range mode

### ISSUE THREAD

**Issue by gpanouts** [pktgen/Pktgen-DPDK#61]
Hello,
I’m trying to send traffic with a range of IPs, ports and, in the same time, to retrieve latency statistics. Is this possible with pktgen (version 21.02)?

I’m using the following lua file to send the traffic:

```
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"

require "Pktgen"

print("**** Execute Range test ********");

pktgen.range.dst_mac("0", "start", "1a:97:f6:1a:d7:cf");

pktgen.range.dst_ip("0", "start", "16.0.153.153");
pktgen.range.dst_ip("0", "inc", "0.0.0.1");
pktgen.range.dst_ip("0", "min", "16.0.153.153");
pktgen.range.dst_ip("0", "max", "16.0.153.154");

pktgen.range.src_ip("0", "start", "48.0.153.153");
pktgen.range.src_ip("0", "inc", "0.0.0.1");
pktgen.range.src_ip("0", "min", "48.0.153.153");
pktgen.range.src_ip("0", "max", "48.0.153.154");

pktgen.range.dst_port("0", "start", 0);
pktgen.range.dst_port("0", "inc", 1);
pktgen.range.dst_port("0", "min", 0);
pktgen.range.dst_port("0", "max", 1000);

pktgen.range.src_port("0", "start", 0);
pktgen.range.src_port("0", "inc", 1);
pktgen.range.src_port("0", "min", 0);
pktgen.range.src_port("0", "max", 1000);

pktgen.set("0", "size", 64);

pktgen.set("all", "rate", 45)
pktgen.set_proto("all", "udp");

pktgen.set_range("0", "on");
pktgen.start(0)
```

However, when I enable the latency mode (enable 0 latency), pktgen stops sending the previous traffic. Then, I have to set specific IPs and ports to send traffic while latency mode is enabled. But this is not the case for me, I want to have multiple IPs, ports in the packets.

I came across with the recent addition of latency sampler but it is not clear to me if and how I can use it.

Thank you in advance,
Georgia

**Comment by pktgen** [comment]
Sorry, you cannot do range and latency at the same time. Latency requires the min packet size to be around 82 bytes (I think that is right) as well.

From: Georgia Panoutsakopoulou ***@***.***>
Date: Wednesday, March 24, 2021 at 10:25 AM
To: pktgen/Pktgen-DPDK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pktgen/Pktgen-DPDK] Combination of latency and range mode (#61)

Hello,
I’m trying to send traffic with a range of IPs, ports and, in the same time, to retrieve latency statistics. Is this possible with pktgen (version 21.02)?

I’m using the following lua file to send the traffic:

package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"







require "Pktgen"







print("**** Execute Range test ********");







pktgen.range.dst_mac("0", "start", "1a:97:f6:1a:d7:cf");







pktgen.range.dst_ip("0", "start", "16.0.153.153");



pktgen.range.dst_ip("0", "inc", "0.0.0.1");



pktgen.range.dst_ip("0", "min", "16.0.153.153");



pktgen.range.dst_ip("0", "max", "16.0.153.154");







pktgen.range.src_ip("0", "start", "48.0.153.153");



pktgen.range.src_ip("0", "inc", "0.0.0.1");



pktgen.range.src_ip("0", "min", "48.0.153.153");



pktgen.range.src_ip("0", "max", "48.0.153.154");







pktgen.range.dst_port("0", "start", 0);



pktgen.range.dst_port("0", "inc", 1);



pktgen.range.dst_port("0", "min", 0);



pktgen.range.dst_port("0", "max", 1000);







pktgen.range.src_port("0", "start", 0);



pktgen.range.src_port("0", "inc", 1);



pktgen.range.src_port("0", "min", 0);



pktgen.range.src_port("0", "max", 1000);







pktgen.set("0", "size", 64);







pktgen.set("all", "rate", 45)



pktgen.set_proto("all", "udp");







pktgen.set_range("0", "on");



pktgen.start(0)



However, when I enable the latency mode (enable 0 latency), pktgen stops sending the previous traffic. Then, I have to set specific IPs and ports to send traffic while latency mode is enabled. But this is not the case for me, I want to have multiple IPs, ports in the packets.

I came across with the recent addition of latency sampler but it is not clear to me if and how I can use it.

Thank you in advance,
Georgia

**Comment by gpanouts** [comment]
@pktgen Thanks for the feedback!
