### ISSUE TITLE
pktgen-pcap.c: compile problem at CentOS 7

### ISSUE THREAD

**Issue by FeldmanFM** [pktgen/Pktgen-DPDK#61]
Good day! 
New to linux and especially compiling things form sources. 
While "make" of pktgen-dpdk Im having this errors:

`/home/user/pktgen-dpdk/app/pktgen-pcap.c: In function ‘pktgen_pcap_mbuf_ctor’:`
`/home/user/pktgen-dpdk/app/pktgen-pcap.c:268:2: error: implicit declaration of function ‘RTE_MBUF_ASSERT’ [-Werror=implicit-function-declaration]`
  `RTE_MBUF_ASSERT(mp->elt_size >= sizeof(struct rte_mbuf));
  ^`
`/home/dark/pktgen-dpdk/app/pktgen-pcap.c:268:2: error: nested extern declaration of ‘RTE_MBUF_ASSERT’ [-Werror=nested-externs]`
`cc1: all warnings being treated as errors`
`make[2]: *** [pktgen-pcap.o] Error 1`
`make[1]: *** [all] Error 2
`
Im using CentOS 7 
`[root@ pktgen-dpdk]# cat /etc/centos-release`
`CentOS Linux release 7.2.1511 (Core) `
`[root@ pktgen-dpdk]# uname -a`
`Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux``

Hope you will give me advice.

**Comment by pktgen** [comment]
You must have update to the latest release of DPDK as they have updated some code from the 16.04 release lately. Just edit that file and replace the RTE_MBUF_ASSERT with RTE_ASSERT and you should be good to go.

**Comment by FeldmanFM** [comment]
Thank you for a fast reply!
I've downloaded pktgen with 
`git clone http://dpdk.org/git/apps/pktgen-dpdk` 
at 02.05

Editing file have solved my problem and pktgen compiled. Thak you!
