### ISSUE TITLE
libcommon.so ABI version compilation error on Centos7

### ISSUE THREAD

**Issue by RoryCharlton** [pktgen/Pktgen-DPDK#62]
I'm trying to compile pktgen on a centos7 container (with dpdk 2.2.0 installed) and I receive the following error when I try to make:

Must Specify a libcommon.so. ABI version
make[1]: *** [libcommon.so.] Error 1
make: *** [all] Error 2

Any advice would be greatly appreciated.

**Comment by pktgen** [comment]
Are you trying to compile pktgen to use shared libs, which is something I have never done. Pktgen does not support ABI revisions only static builds.
