### ISSUE TITLE
Some questions about performance testing

### ISSUE THREAD

**Issue by weijinkang** [pktgen/Pktgen-DPDK#62]
I encountered some confusion when I used Pktgen-DPDK for some performance tests.

My experimental environment: Hardware: CPU: Intel i7-9700K, NIC: Intel X540-T2 (10 Gigabit dual network port); Software: CentOS7+ DPDK18.05.1+pktgen-dpdk-3.5.1

1. Unable to reach line-rate
The NIC is negotiated to gigabit, the packet sending rate set to 100%. The actual maximum packet sending rate is:
64B: 1487460 Pkts/s (line-rate: 1488095 Pkts/s)
128B: 844384 Pkts/s (line-rate: 844594 Pkts/s)
256B: 452846 Pkts/s (line-rate: 452898 Pkts/s)
512B: 234945 Pkts/s (line-rate: 234962 Pkts/s)
1024B: 119730 Pkts/s (line-rate: 119731 Pkts/s)
1280B: 97152 Pkts/s (line-rate: 96153 Pkts/s)
1518B: 81273 Pkts/s (line-rate: 81274 Pkts/s)
It can be seen that when the frame length is less than 512B,  the packet sending rate  is lower than the line-rate. What method can I use to increase the rate of sending packets and stabilize it at the line-rate?

2. The data is not accurate enough
I connected the NIC to the TestCenter, the package was sent by pktgen-DPDK, and the package was received by TestCenter.The packet sending rate displayed by pktgen-DPDK is 1488540 Pkts/s, and the packet rate received by TestCenter is 1487460 Pkts/s. The value displayed by pktgen-DPDK is already greater than the line-rate (1488095 Pkts/s), which is obviously unreasonable.

3. Latency test results are not accurate
I use pktgen-DPDK and TestCenter to test the same device, set the same frame length and packet sending rate, the results are quite different(The result of TestCenter is 6.509us, and the result of pktgen-DPDK is 176us).

**Comment by pktgen** [comment]
From: Jinkang_Wei ***@***.***>
Date: Wednesday, April 7, 2021 at 11:57 AM
To: pktgen/Pktgen-DPDK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pktgen/Pktgen-DPDK] Some questions about performance testing (#62)

I encountered some confusion when I used Pktgen-DPDK for some performance tests.

My experimental environment: Hardware: CPU: Intel i7-9700K, NIC: Intel X540-T2 (10 Gigabit dual network port); Software: CentOS7+ DPDK18.05.1+pktgen-dpdk-3.5.1

1.       Unable to reach line-rate
The NIC is negotiated to gigabit, the packet sending rate set to 100%. The actual maximum packet sending rate is:
64B: 1487460 Pkts/s (line-rate: 1488095 Pkts/s)
128B: 844384 Pkts/s (line-rate: 844594 Pkts/s)
256B: 452846 Pkts/s (line-rate: 452898 Pkts/s)
512B: 234945 Pkts/s (line-rate: 234962 Pkts/s)
1024B: 119730 Pkts/s (line-rate: 119731 Pkts/s)
1280B: 97152 Pkts/s (line-rate: 96153 Pkts/s)
1518B: 81273 Pkts/s (line-rate: 81274 Pkts/s)
It can be seen that when the frame length is less than 512B, the packet sending rate is lower than the line-rate. What method can I use to increase the rate of sending packets and stabilize it at the line-rate?

The rates are being handle by software reading the NIC counters the TestCenter will always be more accurate then Pktgen ☹

2.       The data is not accurate enough
I connected the NIC to the TestCenter, the package was sent by pktgen-DPDK, and the package was received by TestCenter.The packet sending rate displayed by pktgen-DPDK is 1488540 Pkts/s, and the packet rate received by TestCenter is 1487460 Pkts/s. The value displayed by pktgen-DPDK is already greater than the line-rate (1488095 Pkts/s), which is obviously unreasonable.

Same answer as above, but it could Pktgen is doing something wrong. The TestCenter I assume is hardware based counters and I cannot compete with the hardware. Remember Pktgen is for development if you need performance numbers that are accurate then the TestCenter should be used.

3.       Latency test results are not accurate
I use pktgen-DPDK and TestCenter to test the same device, set the same frame length and packet sending rate, the results are quite different(The result of TestCenter is 6.509us, and the result of pktgen-DPDK is 176us).

Pktgen is using the TimeStamp Counter in the CPU. The packet being sent must be received by the same lcore or CPU core to be reasonable. If you are receiving the packet on a different the lcore the timestamp in the packet is not correct as it came from a different CPU/lcore.

**Comment by weijinkang** [comment]
Thank you for your reply.

On the first question, I did not make myself clear. The test data of the first question is collected by TestCenter, the data is accurate.These data indicate that when the frame length is less than 512B, the packet is not sent at line-rate. 

Can pktgen-dpdk send packages at a stable line-rate? If so, what kind of hardware is needed.

**Comment by pktgen** [comment]
As I stated pktgen sends packets using timers from dpdk and the time stamp counter. The rate being sent should be easy to maintain. 

I am not suggesting the testcenter is not accurate. 

What is the pktgen command line being used. Plus can you move to the latest dpdk and pktgen versions. I can not debug or test older versions I do not have the time. 

Thanks

**Comment by syeedhaiderali** [comment]
I am using 2 servers, one is used to send traffic and another is used to receive traffic via pktgen. I have Mellanox ConnectX6 100G cards on both servers. 

Sender:
Server Model name:          Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
Card: Mellanox Technologies MT28908 Family [ConnectX-6]

$ sudo ./Builddir/app/pktgen -l 1,3,5,7,9,11,13,15,17,19,21,23,25,27 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 85:00.0,txq_inline_mpw=128 --socket-mem 0,8192 -- -T -P -m [3:5/7/9/11/13/15/17/19/21/23/25/27].0 -f themes/black-yellow.theme

Receiver:
Server Model name:   Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
Card: Mellanox Technologies MT28908 Family [ConnectX-6]

$ sudo ./Builddir/app/pktgen -l 1,3,5,7,9,11,13,15,17,19,21,23,25,27 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 85:00.0,mprq_en=1,rxqs_min_mprq=1  --socket-mem 0,8192 -- -T -P -m [3/5/7/9/11/13/15/17/19/21/23/25:27].0 -f themes/black-yellow.theme

I have performed performance testing but I am not able to send more than ~99MPPS and receive ~12MPPS packet rate. 
![image](https://user-images.githubusercontent.com/20606725/121858398-057a3d00-cd10-11eb-8397-91142dd7c3ba.png)

**Comment by pktgen** [comment]
For the RX side to receive with more than one core you need to make sure the RSS is working. The RSS needs to have multiple flows being received to distribute the RX traffic among the different core on the RX side. If you do not have the flow evenly distributed among the RSS queues you become limited by the performance of a single core or only a few cores.

Pktgen have a page which shows all of the queues to help you see the distribution. 'page xstats'

**Comment by syeedhaiderali** [comment]
Yeah, I have checked that page and it seems packets are evenly distributing but RX performance is very bad. I have check with 8, 12, and 16 RX queues but rate of RX packets is not increasing from 26 MPPS
![image](https://user-images.githubusercontent.com/20606725/121995782-f606fc80-cdc0-11eb-996d-10e560f92695.png)

**Comment by pktgen** [comment]
hmmm, not sure why this is happening. If one machine can RX 99Mpps and the other can only do 26Mpps then it must be something in the systems. I am understanding the problem?

Make sure the NICs are in the same PCIe slots and the slots are the same width for the NIC. On my mother boards sometimes the PCIe slots are not the same wide ie 8x, 16x, ...
