### ISSUE TITLE
RSS Issue

### ISSUE THREAD

**Issue by nishant-v** [pktgen/Pktgen-DPDK#63]
I am using DPDK 16.04 and pktgen 3.0.00
On my DPDK machine, i have configured RSS rule just for Destination IP (172.10.10.2).
![rss](https://cloud.githubusercontent.com/assets/7613402/15160737/2aa17d4e-16c9-11e6-9161-4178056176ca.png)

From Pktgen when i changed **destination IP** as **172.10.10.2**, **proto **as **ICMP**, and after that i tried command **ping4 0**
Packet reaches to correct queue in DPDK application.

But if i changed the source IP at packet gen (any IP other then 192.168.0.1), I am not getting packet at correct core on DPDK machine.
Here is my pktgen IP looks like.
![pktgen](https://cloud.githubusercontent.com/assets/7613402/15160993/4f8920b6-16ca-11e6-9811-dbe8ac3f34f7.png)

If i revert my my source IP change, it again reached to correct core.

My port configuration is
"
![rss_conf](https://cloud.githubusercontent.com/assets/7613402/15160996/557bdb80-16ca-11e6-9df4-52a7e504d4f7.png)

"

**Comment by pktgen** [comment]
You have the promiscuous mode enabled which allows any packet to be received.
