### ISSUE TITLE
Rate control not supported for Mellanox MCX4560(100G) cards 

### ISSUE THREAD

**Issue by morphyno** [pktgen/Pktgen-DPDK#64]
I have been running pkt-gen version 2.9.12 with Mellanox's 100G card using their package of DPDK (version 2.2_1.6) [http://www.mellanox.com/page/products_dyn?product_family=209&mtag=pmd_for_dpdk](url)

In screenshots below, pkt-gen would run 87 Gpbs regardless whether the rate is set at 1% or 100%.

![87gbps_at_1pct](https://cloud.githubusercontent.com/assets/3343500/15326659/b5245ab0-1c03-11e6-8409-d038d5901b1d.png)
![87gbps_at_100pct](https://cloud.githubusercontent.com/assets/3343500/15326658/b5232172-1c03-11e6-903d-f4d35c5b9206.png)

I have also tried a newer version of pkt-gen and shows the same issue. Is this just a hardware support issue?

**Comment by pktgen** [comment]
Have you tried the test-pmd app to see if it gets the same issue?

For pktgen it sends traffic based on rdtsc values.

**Comment by adolia** [comment]
Hi,
Can I replay the pcap at the rate specified in the pcap file using Pktgen?

**Comment by jlynch1** [comment]
Hi,

I see the same issue with the Intel X710 2x10g card. I am using dpdk-16.04 and pktgen-dpdk-pktgen-v3.0.05. Is it a known issue the rate control does not work?

Regards
Jonathan

**Comment by pktgen** [comment]
> On Jul 12, 2016, at 9:12 AM, jlynch1 <notifications@github.com> wrote:
> 
> Hi,
> 
> I see the same issue with the Intel X710 2x10g card. I am using dpdk-16.04 and pktgen-dpdk-pktgen-v3.0.05. Is it a known issue the rate control does not work?

I only have access to my laptop using --vdev=eth0 and the rate changes as I change the rate value from 100% to 1%, not a perfect rate, but close the right values. I modified the eth_ring PMD to be a 100G interface on on my laptop in a Ubuntu VirtualBox VM it seems to work.

**Comment by jlynch1** [comment]
Hi Keith,

Do you have the igb driver on your laptop? igb driver has a function called igb_set_vf_rate_limit() for handling that in ./lib/librte_eal/linuxapp/kni/ethtool/igb/igb_main.c 

Did you see my comments about only the ixgbe driver having a rate limiter for tx'ing on a physical port. ie set_queue_rate_limit function is implemented.

Regards
Jonathan

**Comment by pktgen** [comment]
I am currently running on a Mac machine and access to the physical port is not setup yet.

**Comment by pktgen** [comment]
Did you resolve this issue?

**Comment by jlynch1** [comment]
To rate limit the tx for a particular device, it appears the set_queue_rate_limit() function needs to be implemented in the device specific code in DPDK. The framework to rate limit was implmented in dpdk in the following patch:  http://dpdk.org/ml/archives/dev/2014-May/002751.html

There are some discussions on the confusion of how it was implemented across virtual fuctions and physical functions in the thread http://dev.dpdk.narkive.com/ZRcewgfM/dpdk-dev-patch-v2-1-3-ether-add-api-to-support-setting-tx-rate-for-queue-and-vf#post4

As stated above I can only see it implemented for ixgbe (physical and virtual) and a virtual function of the igb driver through the kni via net_device_ops. Also the full blown i40e device driver (not dpdk) has some rate limiting functionality in the driver code, but none of this is added in the i40e dpdk driver.
