### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by AqsaKashaf** [pktgen/Pktgen-DPDK#65]
Hi,

I am using dpdk 20.11. When I use the latest pktgen and try to make it i  get a lot of errors of the type:
```
PG_ETHER_TYPE_IPv4’ undeclared (first use in this function); did you mean ‘RTE_ETHER_TYPE_IPV4’?
  case PG_ETHER_TYPE_IPv4:
       ^~~~~~~~~~~~~~~~~~
       RTE_ETHER_TYPE_IPV4
```
and many other similar errors. I checked that these are defined in lib/common/pg_compat.h, but I am always getting this error. Not sure why?

**Comment by pktgen** [comment]
Please checkout the 'dev' branch and see if that fixes the problem.

**Comment by AqsaKashaf** [comment]
It worked with the dev branch
