### ISSUE TITLE
Can I run Pktgen-dpdk on a virtual machine

### ISSUE THREAD

**Issue by abhimanyubhatter** [pktgen/Pktgen-DPDK#65]
Hi All,

Can I run Pktgen-dpdk on a virtual machine. As just running pktgen gives very less amount of packets generated per second around 2 million packets. How can I increase the packets generated per second.

Current version of pktgen is: 2.74

**Comment by pktgen** [comment]
Yes, you can run pktgen in a VM, but the performance is going to vary 
based on the interface type you are using. Are you using virtual 
interfaces or access directly to the hardware devices. Pktgen running in 
a VM accessing the hardware directly should run reasonable well, but if 
depends on the VM configuration and the type of VM be used.

**Comment by abhimanyubhatter** [comment]
Hi ,
I am using virto based interface generated by Openstack( IAAS) system , but the main issue is I am getting lot of packet drop( measured by packet received and packet sent).
How can I use DPDK pktgen , please let me know , is it worth to use it or not.

**Comment by pktgen** [comment]
The limitation here is the virtio interface and would not be Pktgen as 
it can do 10Gb 64 byte packets at wire rate on direct access to the 
hardware.

DPDK, does support accessing virtual devices, but it means you need to 
build and setup DPDK to use these virtual devices. Please read the DPDK 
docs http://dpdk.readthedocs.io/en/v16.04/ for details on how to setup 
virtual devices using --vdev option.

**Comment by abhimanyubhatter** [comment]
How can I use pktgen receiver part as I want to measure the packets received at the other end , to calculate packet loss.

**Comment by pktgen** [comment]
I do not really understand what you are asking sorry.

**Comment by abhimanyubhatter** [comment]
Hi,

Actually I want to measure the packet loss , is it possible I can do with pktgen module.

Thanks
Abhimanyu

**Comment by pktgen** [comment]
Let's say you send a 10000 packets and these packets should be sent back to pktgen then you can measure you get 10000 packets back. Any other way is not possible.
