### ISSUE TITLE
measuring of the DPDK utilization

### ISSUE THREAD

**Issue by adolia** [pktgen/Pktgen-DPDK#66]
Hi all, 
How can I add measuring of the DPDK utilization related to the while loop (such as ratio of the total while loop time and the dpdk time)?
Thanks in advance!

**Comment by pktgen** [comment]
I do not have any idea exactly how that could be done without doing some 
work. I would suggest looking at the app/pktgen.c file and look at the 
Rx/Tx routines.

**Comment by adolia** [comment]
Thanks for replay!
But in some cases, what I want to do is a timestamp before and after calling the function(s) that utilize dpdk and get some idea's about the load.  Because DPDK recommends a busy-wait loop, and the CPU load is always 100% for a typical application.

**Comment by pktgen** [comment]
If you read the docs for DPDK we do have an example of code to help 
understand idle/busy load on CPUs. It does not timestamp function calls, 
but it does seem to look at loading of the CPUs. I have not looked at 
the code is some time, but you can look and see if this will help you 
add your needed support.

Have a look at that code, but that is about as far as I can help, sorry.

**Comment by adolia** [comment]
Thanks a lot!
