### ISSUE TITLE
ERROR: C shared or static library 'rte_process_info' not found

### ISSUE THREAD

**Issue by daldr-ntml** [pktgen/Pktgen-DPDK#66]
Hi, I'm trying to build pktgen 19.12.0 against DPDK 19.11.8. Is that a valid combination?

(I want to use DPDK 19.11.8 because I am using shared libraries and I know that works with the non-meson build system).

I followed the instructions in the pktgen readme but I see error:

```
[pktgen-dpdk-pktgen-19.12.0]$ meson build
The Meson build system
Version: 0.55.1
Source dir: /data/daldrich/pktgen_dpdk_19.11/pktgen-dpdk-pktgen-19.12.0
Build dir: /data/daldrich/pktgen_dpdk_19.11/pktgen-dpdk-pktgen-19.12.0/build
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/lib64/pkgconfig/libdpdk.pc'
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/lib64/pkgconfig/libdpdk.pc'
Project name: pktgen
Project version: 19.05.0-rc0
C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)")
C linker for the host machine: cc ld.bfd 2.27-34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Message: RTE_SDK=/opt/dpdk/dpdk-stable-19.11.8/
Message: RTE_TARGET=x86_64-native-linux-gcc
meson.build:46: WARNING: Consider using the built-in optimization level instead of using "-O3".
meson.build:46: WARNING: Consider using the built-in debug option instead of using "-g".
Message: Using dpdk_libdir = /opt/dpdk/dpdk-stable-19.11.8//x86_64-native-linux-gcc/lib
Compiler for C supports arguments -Wno-format-truncation -Wformat-truncation: NO
Message: Process common
Library rte_eal found: YES
Library rte_kvargs found: YES
Library rte_cmdline found: YES

lib/common/meson.build:36:1: ERROR: C shared or static library 'rte_process_info' not found
```

Could you help me fix this build error please?

**Comment by pktgen** [comment]
I normally suggest latest Pktgen and then use the latest DPDK. As pktgen is a standalone DPDK application you can build pktgen to the latest DPDK and then build you application to whatever DPDK version you would like to use.

It is possible the latest pktgen will build with an older version for DPDK, but I do not support building pktgen to older version except for some bare minimum support.

**Comment by daldr-ntml** [comment]
Thanks. Do you know which version of dpdk, pktgen 19.12.0 was tested against?

**Comment by pktgen** [comment]
Possible just to the previous release of DPDK 19.08 or 19.11.

Why do you want to use Pktgen 19.12 and not the latest version?

**Comment by daldr-ntml** [comment]
I just assumed that the latest may not be compatible with DPDK 19.11, which I do want to use.

**Comment by pktgen** [comment]
Try the next version of pktgen, but it appears the rte_process_info() is not in DPDK 19.11.8

I can not find the DPDK version 19.11.8 only the version 19.11 and it is not using rte_process_info() which is a metrics library in DPDK. Not sure where you are getting that version, but the big problem is I can not build DPDK 19.11 on my Ubuntu 20.10 as I get a number of compiler errors with the latest GCC.

I am not going to be much help with your configuration and versions being used.

**Comment by daldr-ntml** [comment]
Ok, thanks for discussing.
