### ISSUE TITLE
"make buildlua" failed

### ISSUE THREAD

**Issue by madi-nuralin** [pktgen/Pktgen-DPDK#68]
Hi, 
I am using dpdk-v21.02 and Pktgen-DPDK 21.03
When I tried to build pktgen with 'buildlua' option I got the following compilation errors:
```
../lib/lua/lua_config.c: In function ‘lua_create_instance’:
../lib/lua/lua_config.c:182:24: error: ‘RTE_EAL_TAILQ_RWLOCK’ undeclared (first use in this function); did you mean ‘RTE_MAX_TAILQ’?
  rte_rwlock_write_lock(RTE_EAL_TAILQ_RWLOCK);
                        ^~~~~~~~~~~~~~~~~~~~
                        RTE_MAX_TAILQ
```
I am aware of the fact that recently there was a commit about compile time macros to follow DPDK guidelines (changes in pg_compat.h), and project could compile without buildlua option successfully, whereas with buildlua not. Not sure why?

**Comment by pktgen** [comment]
At the following line to lib/lua/lua_config.c at line 29

#include <pg_compat.h>

**Comment by madi-nuralin** [comment]
Ok, thanks!
