### ISSUE TITLE
Pcap replay garbage

### ISSUE THREAD

**Issue by adolia** [pktgen/Pktgen-DPDK#68]
Hi,
So, there is a problem with transmitted packets from pcap.
When I check, which packets I've received, it looks like that : 

16:26:32.070230 00:f0:be:c4:00:f0 (oui Unknown) > be:05:00:f0:be:c4 (oui Unknown), ethertype Unknown (0xbec4), length 75: 
	0x0000:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0010:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0020:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0030:  00f0 bec4 00f0 bec4 00f0 bec4 00         .............
16:26:32.070232 00:f0:be:c4:00:f0 (oui Unknown) > be:05:00:f0:be:c4 (oui Unknown), ethertype Unknown (0xbec4), length 135: 
	0x0000:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0010:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0020:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0030:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0040:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0050:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0060:  00f0 bec4 00f0 bec4 00f0 bec4 00f0 bec4  ................
	0x0070:  00f0 bec4 00f0 bec4 00                   .........

But in pcap that I've sent packets looks like that :
Port: 0, PCAP Count: 0 of 50
  Seq            Dst MAC           Src MAC            Dst IP              Src IP    Port S/D  Protocol:VLAN Size-FCS
    0:    00:60:97:de:54:36   00:10:7b:38:46:32      204.71.200.129        172.16.112.100     1074/80  IPv4/UDP:        
1:    00:10:7b:38:46:32   00:60:97:de:54:36      172.16.112.100        204.71.200.129     80/1071  IPv4/UDP:        
2:    00:10:7b:38:46:32   00:60:97:de:54:36      172.16.112.100        204.71.200.129     80/1072  IPv4/UDP:       
 3:    00:10:7b:38:46:32   00:60:97:de:54:36      172.16.112.100        204.71.200.129     80/1073  IPv4/UDP:        
4:    00:10:7b:38:46:32   00:60:97:de:54:36      172.16.112.100        204.71.200.129     80/1074  IPv4/UDP:       
 5:    00:10:7b:38:46:32   00:60:97:de:54:36      172.16.112.100        204.71.200.129     80/1074  IPv4/UDP:

So, what the problem, why I've received a garbage but not a pcap traffic?
Have you any suggestion?
Thanks in advance!

**Comment by pktgen** [comment]
I assume you enabled sending the PCAP traffic on the port via the 
command interface, also did you use the command line option to attach 
the pcap file the port you wanted to send the traffic on?

**Comment by adolia** [comment]
So, I've start pktgen using this options:
./pktgen -c 0x0F -n 3 --proc-type auto -- -m "[1:2].0,[3].1" -s 0:pcap/big.pcap  -s 1:pcap/large.pcap
When it started, in flags state the pcap sending enabled : 
Flags:Port    :   ----p----------:0   ----p----------:1

**Comment by pktgen** [comment]
Well it looks like you have it setup correctly, but I will not be able 
to debug the problem for a few day till possible the weekend. The code 
in pktgen just loads the PCAP file into a set of mbufs and send the 
mbufs, which is pretty simple.

**Comment by adolia** [comment]
Yes, I know! So, can I dump some mbufs and to see that they kept?

**Comment by pktgen** [comment]
You can capture packet with ptkgen if you loop the cable back to another port and then you can look at the pcap file it creates. Look at the help information in pktgen. Also I have a dump like command in pktgen to see the pcap packets on the screen look at the help again for details. I think it is 'page pcap'.

**Comment by adolia** [comment]
So, I currently try this solution and got a results that I've provided in issue...
I mean that I want to dump packets at the transmitter side before it push packet to the queue!

**Comment by adolia** [comment]
So, if you have any suggestion or some debug results, please, reply me!

**Comment by adolia** [comment]
I'm debugging pktgen too long, but not found such a bug. But after that , I've built pktgen with dpdk-16.04 and it is working normally. So, the problem was in dpdk-16.07. 
But now, I can't preload pcap file that as big as earlier.

**Comment by moshohayeb** [comment]
Can confirm this is an issue with 16.07. I the garbage pattern is different than the posted one but consistent with the structure 

Compiling against 2.2 fixed the issue.

**Comment by pktgen** [comment]
I have a patch for pktgen to fix the pcap problem for dpdk 16.07 release

**Comment by adolia** [comment]
Hi! It's good! Where I can get it?

**Comment by pktgen** [comment]
Here you go hope this works.

**Comment by adolia** [comment]
ok! Thanks a lot!

**Comment by adolia** [comment]
I think we can close this issue!

**Comment by pktgen** [comment]
Thanks

**Comment by pktgen** [comment]
Patch applied
