### ISSUE TITLE
Setting packet size issue

### ISSUE THREAD

**Issue by pervazeakhtar** [pktgen/Pktgen-DPDK#69]
I'm using pktgen 3.0.00. On the older versions, I was able to issue set packet size using LUA, 

pktgen.set("all", "size", 64);
then later
pktgen.set("all", "size", "256");

It appears now, to generate both 64 byte and 256 byte packets. Previously it would switch (solely) to the packet size requested. It works no better using the pktgen commands via the GUI.

**Comment by pktgen** [comment]
Yes, in the previous version I reset the port to reclaim the packets sitting on the tx done queue, but too many people complained about the link drop and other problems with that method. 

I need to figure out a different method.

**Comment by pktgen** [comment]
In the latest version 16.07 and Pktgen this problem should be resolved.
