### ISSUE TITLE
port parsing - array size 0 in the data structure

### ISSUE THREAD

**Issue by hemantagr** [pktgen/Pktgen-DPDK#70]
Following data structure needs to be updated when RTE_MAX_LCORE and RTE_MAX_ETHPORTS are less than 8. 
File: lib/common/wr_l2p.c

typedef struct ls_s {
	uint8_t ls[RTE_MAX_LCORE / 8];
} ls_t;
typedef struct ps_s {
	uint8_t ps[RTE_MAX_ETHPORTS / 8];
} ps_t;

suggested change:
typedef struct ls_s {
	uint8_t ls[(RTE_MAX_LCORE+7) / 8];
} ls_t;

typedef struct ps_s {
	uint8_t ps[(RTE_MAX_ETHPORTS+7) / 8];
} ps_t;

**Comment by pktgen** [comment]
Thanks
