### ISSUE TITLE
Two questions about the latency measurement through LUA API

### ISSUE THREAD

**Issue by ZhihuiWu** [pktgen/Pktgen-DPDK#72]
Hi, @pktgen 
I am a beginner of pktgen-dpdk.
I am working on a test case using pktgen-dpdk v3.0.06 to measure latency. 

I met two questions about the latency measurement through LUA API.
1. enable latency with LUA API. 
when I use pktgen.latency("all", "enable"), it throw an error "latency is not working yet". And I read lpktgenlib.c. I guess it is not support it. Is it right?
1. How to get latency's value through LUA API?
   From the screen, I can see

```
Latency usec      :                   0               68100
```

I understand latency's value is 68100. Is it right?
I guess I can use "pktgen.portStats("all", "latency")" to get latency's value. What i got is:

```
[1] = {
    ["obytes"] = 140724198977952,
    ["ierrors"] = 0,
    ["ibytes"] = 17217038032,
    ["rx_nombuf"] = 140508047464280,
    ["opackets"] = 0,
    ["oerrors"] = 37168832,
    ["ipackets"] = 0,
},
[0] = {
    ["obytes"] = 140724198977952,
    ["ierrors"] = 0,
    ["ibytes"] = 17217038032,
    ["rx_nombuf"] = 140508047464280,
    ["opackets"] = 0,
    ["oerrors"] = 37168832,
    ["ipackets"] = 0,
},
["n"] = 2,
```

I confused and blocked here. Could you please help me to make it clear? Thanks in advance.

**Comment by pktgen** [comment]
At this point the Lua side of using the Latency is not completed only the command line.

**Comment by ZhihuiWu** [comment]
Thanks for your reply. Do you have a plan about it? If yes, can you please tell me when it might be completed? 
Thanks in advance.

**Comment by pktgen** [comment]
I have planned to do the work, but do not have a time frame. I do accept patches if you would like to do the work.

**Comment by ZhihuiWu** [comment]
Thank you very much. I use linux expect to solve my issue temporarily.

**Comment by pktgen** [comment]
Please have a look at the current release, I did add some code for Lua support for Latency.

> On Jul 22, 2016, at 7:50 AM, ZhihuiWu <notifications@github.com> wrote:
> 
> Thank you very much. I use linux expect to solve my issue temporarily.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Keith Wiles
keith.wiles@icloud.com

**Comment by ZhihuiWu** [comment]
That's great! It is really helpful. I will use it today.
Thanks for your great work!

**Comment by ZhihuiWu** [comment]
Hi, I used pktgen-3.0.0.08. I print the lua table of port's stats, here is the return:

[1] = {
    ["max_latency"] = 780681,
    ["dropped_pkts"] = 0,
    ["vlan_pkts"] = 0,
    ["min_latency"] = 780681,
    ["echo_pkts"] = 0,
    ["ipv6_pkts"] = 0,
    ["jitter_count"] = 2304780,
    ["arp_pkts"] = 0,
    ["avg_latency"] = 60815202279,
    ["ip_pkts"] = 2305280,
    ["tx_failed"] = 0,
    ["unknown_pkts"] = 0,

The avg_latency is bigger than mix_latency and max_latency.
what is the mean of avg_latency? Hope for your reply.

**Comment by pktgen** [comment]
The avg_latency is the average latency, not sure why the value is so big. Did you find any solution here or still waiting for me?

**Comment by mandar-deshpande07** [comment]
Hi,

I am trying to get latency through pktgen-dpdk (v3.0.13). To start I am using following command : 

sudo ./app/app/{RTE_SDK}/app/pktgen -c 0x1f -n 4 --proc-type auto  --file-prefix pg -- -T -P -f cmd -p 0x3 -m "[1:2].0,[3:4].1" 

Once pktgen starts I execute following commands : 

Pktgen> page latency
Pktgen> latency 0,1 on   ...... (0,1 for 2 ports)
Pktgen> set all size 96
Pktgen> start all

Now pktgen starts and packets can be seen transmitted and received. But how do I get latency vales?

I tried passing a file to store log information(using -l option), still couldn't find latency being displayed.

Any comments on this would be helpful.

Thanks

**Comment by pktgen** [comment]
The values should be on the page latency screen, but I am not at my machine to look. They should also be in the stats values in the Lua code.

Keith Wiles
keith.wiles@icloud.com

**Comment by mandar-deshpande07** [comment]
Thanks @pktgen for the reply, I could see latency parameter on latency screen : 
Latency usec      :                   0                   0

As it shows latency as 0 usec, I doubt if I am missing out something. To get more info about the same, I would like to print latency details from lua table.

As you mention :"They should also be in the stats values in the Lua code." could you help me in finding stats values... do we need to write a script in lua to get stats or should we pass an existing script to get details alongwith log file to get values?

Thanks in Advance.

**Comment by pktgen** [comment]
In the script I have they are pulling the stats, but grep around in the scripts. The normal rate stats should be pulling the latency values as well if that port has latency supported. The stats should only new present while the port is sending traffic.

The latency screen should be showing the stats when the port is sending. The only reason it would not work is the packets are not returning to Pktgen. Please loopback the cables and try one port, this should show some latency values. I used this method to test the code, maybe not the best way.

Keith Wiles
keith.wiles@icloud.com

**Comment by ZhihuiWu** [comment]
@pktgen , I didn't find the solution since I am not familiar with C. Sorry. I have to use a linux expect script to get latency value from screen. At least, it works.

**Comment by raiesmh08** [comment]
@pktgen 
I am using pktgen version 3.0.11 and dpdk version as  DPDK 16.11.0-rc0

When I went on latency page and started transmission of packets, i could see the latency value is too high.
In my case I see it as - "73816426453270"
But i observe that packet is reaching very early.
any idea, why it is taking too much time ?

**Comment by a1boyband** [comment]
how can i get lua table for latency?

**Comment by pktgen** [comment]
> On Oct 4, 2016, at 6:04 AM, raiesmh08 <notifications@github.com> wrote:
> 
> @pktgen 
> I am using pktgen version 3.0.11 and dpdk version as DPDK 16.11.0-rc0
> 
> When I went on latency page and started transmission of packets, i could see the latency value is too high.
> In my case I see it as - "73816426453270"
> But i observe that packet is reaching very early.
> any idea, why it is taking too much time ?

The latency packet needs to return to the same core to be calculated correctly. Different cores have a different timestamp value. I really should turn the value into time, but I have not done that yet.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by a1boyband** [comment]
@pktgen ,Excuse me, where can I find a way to get the latency value，at the lua script

**Comment by a1boyband** [comment]
@ZhihuiWu ，can you tell me you qq or webcart for talk about the pktgen latency testing？

**Comment by pktgen** [comment]
> On Dec 6, 2016, at 8:01 AM, a1boyband <notifications@github.com> wrote:
> 
> @pktgen ,Excuse me, where can I find a way to get the latency value，at the lua script

The pktStats call will grab the latency stats. 

prints(“pktStats”, pktgen.pktStats("all”))


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by pktgen** [comment]
The values are only listed in the output when latency is enabled on that port.

> On Dec 6, 2016, at 8:10 AM, Roger Keith Wiles <keith.wiles@icloud.com> wrote:
> 
> 
>> On Dec 6, 2016, at 8:01 AM, a1boyband <notifications@github.com> wrote:
>> 
>> @pktgen ,Excuse me, where can I find a way to get the latency value，at the lua script
> 
> The pktStats call will grab the latency stats. 
> 
> prints(“pktStats”, pktgen.pktStats("all”))
> 
> 
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> Keith Wiles
> keith.wiles@icloud.com
> 
> 
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by a1boyband** [comment]
@pktgen 
in the top line of lua scrpit，i already enable latency value on all port
example：
pktgen.latency("all", "enable")
and after send the packets，i written this line “prints(“pktStats”, pktgen.pktStats("all”))” for count the latency

now，is working ，thanks  a lot

But I still have a problem.
I want to get direct access to such:avg latency or max latency,Is there a way to achieve it.for example:json、xml or other ways？

**Comment by pktgen** [comment]
> On Dec 6, 2016, at 8:25 AM, a1boyband <notifications@github.com> wrote:
> 
> @pktgen
> in the top line of lua scrpit，i already enable latency value on all port
> example：
> pktgen.latency("all", "enable")
> and after send the packets，i written this line “prints(“pktStats”, pktgen.pktStats("all”))” for count the latency
> 
> now，is working ，thanks a lot
> 
> But I still have a problem.
> I want to get direct access to such:avg latency or max latency,Is there a way to achieve it.for example:json、xml or other ways？

Sorry, only lua scripts can access the values or getting them from the screen somehow.

> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by a1boyband** [comment]
@pktgen  i don‘t konw,if i written the lua scrpit is "prints(“pktStats”, pktgen.pktStats("avg_latency”))” , it can be obtained the avg_latency ?

**Comment by pktgen** [comment]
> On Dec 6, 2016, at 8:30 AM, a1boyband <notifications@github.com> wrote:
> 
> @pktgen i don‘t konw,if i written the lua scrpit is "prints(“pktStats”, pktgen.pktStats("avg_latency”))” , it can be obtained the avg_latency ?

You are going to need to know Lua to get the values, the data returned from pktgen.pktStats("avg_latency”) is a table. Please learn more about Lua from lua.org.

lat = pktgen.pktStats("avg_latency”);

print(lat[0].arp_pkts);

Zero being the port number.

or in Pktgen use: !lua print(pktgen.pktStats(“all”)[0].ip_pkts)


> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by a1boyband** [comment]
@pktgen ,yes,the result look like a list or dict,thank you so much 👍

**Comment by anthonyaje** [comment]
@pktgen @a1boyband Hi, I tried to measure latency using Pktgen Ver: 3.2.5 (DPDK 16.11.0). I did the above mention techniques in my lua script to test my modified l2fwd-like system at another machine. But, I am seeing the latency value equals 0. Any idea why I am getting this result?

**Comment by pktgen** [comment]
Make sure you use the same core for both rx/tx of the packets plus use the same port for both rx/tx. I am using the rd_tsc which only works on the same core. 

I am out of town right and can not look at the in more detail

**Comment by anthonyaje** [comment]
@pktgen Yes, that's exactly what I wanted to do, tx/rx by one core and using one port. 

Am I running the pktgen correctly by executing: sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0xff -n 2 -- -m "[2:2].0"  ?

**Comment by pktgen** [comment]
> On Apr 18, 2017, at 7:01 PM, ANTHONY <notifications@github.com> wrote:
> 
> @pktgen Yes, that's exactly what I wanted to do, tx/rx by one core and using one port.
> 
> Am I running the pktgen correctly by executing: sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0xff -n 2 -- -m "[2:2].0” ?

Try just -m 2.0 instead, it should be the same thing. Also would use -l 1-2 instead for -c 0xff you have allocated way to many cores then needed.

Make sure you have the MAC addresses correct or just use the -P option after the two dashes.


> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by anthonyaje** [comment]
I tried your suggestion for the execution command, yet still couldn't get it works. 

I setup two machines connected directly to each other (no switch in between). In one machine, I run pktgen v3.2.6 compiled with mellanox dpdk v16.11 with enable 0  latency and promiscuous mode. In the other machine, I have my dpdk application that read packets from NIC and push it back again (previously we tried to swap the MAC addr before pushing back to NIC). 

I wonder under what scenario/setup could I see pktgen latency feature works? 

Thank you very much, Keith!

**Comment by srcvirus** [comment]
@pktgen  Hi, I'm working with @anthonyaje on the same thing. So I added some debug output in pktgen source code to trace the path of latency measurement. It seems like in pkgen.c, the function pktgen_latency_apply is being called and timestamp/magic number is being populated. On the dpdk app end, our dpdk app is not modifying anything in the packet and just echoing it back to the directly connected sending machine. In the pktgen side, inside pktgen_recv_latency funtion, the if (latency->magic == LATENCY_MAGIC) is never becoming true. I am not sure as to why this is happening since the packets are not being modified by the dpdk app at all. Then I did a packet capture instead of running the dpdk app and looking into the packet reveals that there is only 6 bytes of payload in each TCP segment. But the latency_t struct has 16bytes to data inside it (8byte timestamp, 8byte magic). Any explanation as to why this might be happening? The packet size is currently set to 64B.

**Comment by pktgen** [comment]
That setup should work. I assumed you enabled the latency test? 

I can not verify the setup as I am out of town and I could have broken it too. 

The latency if I remember only sends out one packet at a time, I could be wrong memory needs and upgrade.

**Comment by pktgen** [comment]
Try increasing the size of the packet to allow for the latency information or you could look at udp packets if that will work.

**Comment by srcvirus** [comment]
@pktgen Keith, thank you very much. Increasing packet size beyond 64 bytes did the trick. Surprisingly now pktgen is also showing non-zero latency with 64byte packets, but the numbers are very very big !!

**Comment by pktgen** [comment]
The value is the number of cycles based on the CPU speed. Remember pktgen is using the Time stamp register in the CPU. 

Need to convert the number form cycles to time. Each cycles is some number of nano seconds.

**Comment by srcvirus** [comment]
I see. Just to be clear, in the latency page where it reports "Latency usec" it is not actually latency in microseconds, it is latency in terms of number of cpu cycles. Another thing is, during latency test pktgen does not saturate the NIC (I am currently testing with 96byte packets and throughput is ~4.8Gbps on a 10Gbps NIC). Is this an expected behavior?

**Comment by pktgen** [comment]
The latency page is reporting the value in usec but the value in the packet is cycles sorry for the confusion. 

Remember dpdk is batching up a lot of packets and the latency is going to be high. Dpdk is designed for throughput. 

The reason for the Lowe speed is I have to modify each packet on the send side and examine each packet on the receive side. 

Try sending only one packet and see if the number more reasonable. Also make sure you clear the stats too. 

The latency in pktgen needs some work 😞

**Comment by srcvirus** [comment]
Ah I see. Thanks a lot for you help @pktgen Keith.

**Comment by mbulatova** [comment]
Hi, I have the same problem with pktgen-v3.1.0:  latency is displayed as 0.
I do according to recommendations in this discussion, but that does not help.
What I do:
run pktgen with tx/rx on one core.
pktgen -l 0-1 -n 2 -- -P -m 1.0 -T
latency 0 on
set 0 size 96 (also tried to send udp packets, with no effect)
In the other machine, dpdk application read packets from NIC and send it back again to same port.
I wonder did I miss something to make that work?

**Comment by pktgen** [comment]
> On May 15, 2017, at 10:26 AM, Maria Bulatova <notifications@github.com> wrote:
> 
> Hi, I have the same problem with pktgen-v3.1.0: latency is displayed as 0.
> I do according to recommendations in this discussion, but that does not help.
> What I do:
> run pktgen with tx/rx on one core.
> pktgen -l 0-1 -n 2 -- -P -m 1.0 -T
> latency 0 on
> set 0 size 96 (also tried to send udp packets, with no effect)

I assume you did a ‘start 0’ command?

> In the other machine, dpdk application read packets from NIC and send it back again to same port.
> I wonder did I miss something to make that work?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by mbulatova** [comment]
Yes, I did. I see packets are received back, but latency is 0.

**Comment by pktgen** [comment]
> On May 15, 2017, at 1:15 PM, Maria Bulatova <notifications@github.com> wrote:
> 
> Yes, I did. I see packets are received back, but latency is 0.

I cannot look at the code right now or test it, but it should be working. I will have to look at the problem next weekend as I am busy this week and out of town.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by yt2017** [comment]
I am using pktgen 3.2.11 and DPDK 17.05. But i cannot see the "latency on" command. I am using two ports with two lcores. Any setting for that?

**Comment by yt2017** [comment]
Pktgen:/> set 0 count 100
Pktgen:/> start 0
Pktgen:/> start 0
Pktgen:/> latency 0 on
** command not found (latency)
Pktgen:/> start 0
Pktgen:/> 
Latency usec      :                   0                   0
Jitter Threshold  :                  50                  50
Jitter count      :                   0                   0
Total Rx pkts     :                   0                 400

<<< as shown above latency always 0

**Comment by pktgen** [comment]
The command in the current Pktgen code is ‘[enable | disable] <portlist> latency’ so it should be 'enable 0 latency’.

This command should be in the help command. if missing please let me know.

I normally do not support previous versions of Pktgen only to answer questions. Please checkout the latest version.

> On Nov 9, 2017, at 7:47 PM, yt2017 <notifications@github.com> wrote:
> 
> Pktgen:/> set 0 count 100
> Pktgen:/> start 0
> Pktgen:/> start 0
> Pktgen:/> latency 0 on
> ** command not found (latency)
> Pktgen:/> start 0
> Pktgen:/>
> Latency usec : 0 0
> Jitter Threshold : 50 50
> Jitter count : 0 0
> Total Rx pkts : 0 400
> 
> <<< as shown above latency always 0
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by yt2017** [comment]
Thanks for the response! 
Some how my terminal size was not right and i missed the next page of help.
Now the latency value shows up! with size of 96 and two ports on one core, I can get "4 usec" on loopback ( port 0 directly connected to port 1 with cable), with packet count as 1~10.  If i set packets count as  100 or more, i get 10 usec. I understand from above discussion that the "usec" is really CPU cycles.  But is that "4 ~ 10 cycles" too fast to be true. One core sending / receiving on two ports. That must be more than 10 cycles to send and get back a packet

**Comment by pktgen** [comment]
> On Nov 13, 2017, at 11:11 AM, yt2017 <notifications@github.com> wrote:
> 
> Thanks for the response!
> Some how my terminal size was not right and i missed the next page of help.
> Now the latency value shows up! with size of 96 and two ports on one core, I can get "4 usec" on loopback ( port 0 directly connected to port 1 with cable), with packet count as 1~10. If i set packets count as 100 or more, i get 10 usec. I understand from above discussion that the "usec" is really CPU cycles. But is that "4 ~ 10 cycles" too fast to be true. One core sending / receiving on two ports. That must be more than 10 cycles to send and get back a packet

You will have to look at the code, but I think 4usec is the right answer here cycles are too fast. I am out of town and can not look at this time.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Regards,
Keith

**Comment by ChengjunJia** [comment]
I don't know whether the newest version which has solved the problem.
But I use the **pktgen-3.4.2** and find the difference in calculation of the **avg_latency** in _lua_ and the **latency usec** in the _page latency_ . Maybe it can help.
In _lua_, it is the sum of CPU cycles in fact -- shown in **app/pktgen-latency.c**;
In _page latency_, it is the average latency in us -- shown in **app/pktgen-latency.c** 

In **app/pktgen.c"
`info->avg_latency += lat;`

In **app/pktgen-latency.c** 
`ticks = rte_get_timer_hz() / 1000000;`
`avg_lat = 0;`
`if (info->latency_nb_pkts) {`
`avg_lat = (info->avg_latency / info->latency_nb_pkts) / ticks;`
`...`

**Comment by pktgen** [comment]
In a later version someone did submit a patch to update the latency calculations. 

Can you look at the latest code and see if you agee with the change.

**Comment by ChengjunJia** [comment]
OK. Can you give the diff link?
