### ISSUE TITLE
PktGen : No Packets are  transmitted  

### ISSUE THREAD

**Issue by prasshri** [pktgen/Pktgen-DPDK#74]
Hi,

I am new to pktgen and dpdk. I am facing an issue as mentioned below : 
I am using pktgen on a virtual machine (open suse) on windows 
VM has 2 cores and I am using 2 of the Ethernet ports (eth2 and eth3) on vm for DPDK + pktgen 

DPDK version : 16.07.0-rc3
Pktgen Ver: 3.0.06

I am using 2 ports (0 and 1) and the pktgen start command is 
**./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x1 -n 3 -- -P -m "1.0,2.1" -T -f traffic.lua -l temp.log**

traffic.lua file has all the configuration .. The issue I am facing is that I am not able to see any packets getting transmitted on wire, stats are not getting incremented and I have checked on wireshark too 
The console logs are : 

 Copyright (c) <2010-2016>, Intel Corporation. All rights reserved.
   Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<

Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio
>>> Packet Burst 32, RX Desc 512, TX Desc 512, mbufs/port 4096, mbuf cache 512

=== port to lcore mapping table (# lcores 1) ===
   lcore:     0 
port   0:  D: T =  1: 1
port   1:  D: T =  1: 1
Total   :  0: 0
    Display and Timer on lcore 0, rx:tx counts per port/lcore

Configuring 2 ports, MBUF Size 1920, MBUF Cache Size 512
Lcore:
    1, RX-TX  
                RX( 1): ( 0: 0) 
                TX( 1): ( 0: 0) 
    2, RX-TX  
                RX( 1): ( 1: 0) 
                TX( 1): ( 1: 0) 

Port :
    0, nb_lcores  1, private 0x8c0470, lcores:  1 
    1, nb_lcores  1, private 0x8c27b8, lcores:  2 

** Dev Info (rte_em_pmd:0) **
   max_vfs        :   0 min_rx_bufsize    : 256 max_rx_pktlen : 16128 max_rx_queues         :   1 max_tx_queues:   1
   max_mac_addrs  :  15 max_hash_mac_addrs:   0 max_vmdq_pools:     0
   rx_offload_capa:   0 tx_offload_capa   :   0 reta_size     :     0 flow_type_rss_offloads:0000000000000000
   vmdq_queue_base:   0 vmdq_queue_num    :   0 vmdq_pool_base:     0
** RX Conf **
   pthreash       :   0 hthresh          :   0 wthresh        :     0
   Free Thresh    :   0 Drop Enable      :   0 Deferred Start :     0
** TX Conf **
   pthreash       :   0 hthresh          :   0 wthresh        :     0
   Free Thresh    :   0 RS Thresh        :   0 Deferred Start :     0 TXQ Flags:00000000

Initialize Port 0 -- TxQ 1, RxQ 1,  Src MAC 08:00:27:32:6e:d5
    Create: Default RX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176

    Create: Default TX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Range TX    0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Sequence TX 0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176

                                                                       Port memory used =  32897 KB

** Dev Info (rte_em_pmd:0) **
   max_vfs        :   0 min_rx_bufsize    : 256 max_rx_pktlen : 16128 max_rx_queues         :   1 max_tx_queues:   1
   max_mac_addrs  :  15 max_hash_mac_addrs:   0 max_vmdq_pools:     0
   rx_offload_capa:   0 tx_offload_capa   :   0 reta_size     :     0 flow_type_rss_offloads:0000000000000000
   vmdq_queue_base:   0 vmdq_queue_num    :   0 vmdq_pool_base:     0
** RX Conf **
   pthreash       :   0 hthresh          :   0 wthresh        :     0
   Free Thresh    :   0 Drop Enable      :   0 Deferred Start :     0
** TX Conf **
   pthreash       :   0 hthresh          :   0 wthresh        :     0
   Free Thresh    :   0 RS Thresh        :   0 Deferred Start :     0 TXQ Flags:00000000

Initialize Port 1 -- TxQ 1, RxQ 1,  Src MAC 08:00:27:b2:64:a5
    Create: Default RX  1:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176

    Create: Default TX  1:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Range TX    1:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Sequence TX 1:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Special TX  1:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176

                                                                       Port memory used =  32897 KB
                                                                      Total memory used =  65794 KB
Port  0: Link Up - speed 1000 Mbps - full-duplex <Enable promiscuous mode>
Port  1: Link Up - speed 1000 Mbps - full-duplex <Enable promiscuous mode>

=== Display processing on lcore 0

Link State        :        <UP-1000-FD>        <UP-1000-FD>     ----TotalRate----
Pkts/s Max/Rx     :                 0/0                 0/0                   0/0
       Max/Tx     :                 0/0                 0/0                   0/0
MBits/s Rx/Tx     :                 0/0                 0/0                   0/0
Broadcast         :                   0                   0
Multicast         :                   0                   0
  64 Bytes        :                   0                   0
  65-127          :                   0                   0
  128-255         :                   0                   0
  256-511         :                   0                   0
  512-1023        :                   0                   0
  1024-1518       :                   0                   0
Runts/Jumbos      :                 0/0                 0/0
Errors Rx/Tx      :                 0/0                 0/0
Total Rx Pkts     :                   0                   0
      Tx Pkts     :                   0                   0
      Rx MBs      :                   0                   0
      Tx MBs      :                   0                   0
ARP/ICMP Pkts     :                 0/0                 0/0
                  :
Pattern Type      :             abcd...             abcd...
Tx Count/% Rate   :      Forever / 100%      Forever / 100%
PktSize/Tx Burst  :           64 /    1           64 /    1
Src/Dest Port     :         2152 / 2152         2152 / 2152
Pkt Type:VLAN ID  :     IPv4 / UDP:0001     IPv4 / UDP:0001
Dst  IP Address   :         10.11.10.41         10.11.10.41
Src  IP Address   :      10.11.10.31/24      10.11.10.32/24
Dst MAC Address   :   98:90:96:c9:d5:8e   98:90:96:c9:d5:8e
Src MAC Address   :   08:00:27:32:6e:d5   08:00:27:b2:64:a5
VendID/PCI Addr   :   8086:100e/00:09.0   8086:100e/00:10.0

I am also attaching the lua script that I am using with pktgen. 
Please help me out on this 

Thanks and Regards
Prashant

**Comment by prasshri** [comment]
[traffic.txt](https://github.com/pktgen/Pktgen-DPDK/files/383571/traffic.txt)

**Comment by prasshri** [comment]
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;../?.lua"

require "Pktgen";

local seq_table = {
    ["eth_dst_addr"] = "0011:4455:6677",
    ["eth_src_addr"] = "0011:1234:5678",
    ["ip_dst_addr"] = "10.12.0.1",
    ["ip_src_addr"] = "10.12.0.1/16",
    ["sport"] = 2152,
    ["dport"] = 2152,
    ["ethType"] = "ipv4",
    ["ipProto"] = "udp",
    ["vlanid"] = 1,
    ["pktSize"] = 128
};

--pktgen.seqTable(0, "all", seq_table );

local sendport = "0";
local rcvport = "1";

local srcip_sendport = "10.11.10.31";
local dstip_sendport = "10.11.10.41";

local srcip_rcvport = "10.11.10.32";
local dstip_rcvport = "10.11.10.41";

local dstip_max = "10.11.10.41";
local netmask = "/24";
local src_mac = "08:00:27:32:6e:d5";
local dst_mac = "98:90:96:c9:d5:8e";
local rate = 100;
local send_for_secs = 30; --5mins
local log_file = "/root/pktgen_5mins."..os.time()..".log";
local gtputeid_min = "5000";
local gtputeid_max = "7000";
local gtputeid_start = "5000";
local sport = 2152
local dport = 2152


pktgen.set_ipaddr(sendport, "dst", dstip_sendport);
pktgen.set_ipaddr(sendport, "src", srcip_sendport..netmask);
pktgen.set_ipaddr(rcvport, "dst", dstip_rcvport);
pktgen.set_ipaddr(rcvport, "src", srcip_rcvport..netmask);


pktgen.set_mac(sendport, dst_mac);
pktgen.set_mac(sendport, dst_mac);
pktgen.set_mac(rcvport, src_mac);
pktgen.set_mac(rcvport, dst_mac);

pktgen.set(sendport, "rate", rate);

pktgen.range(sendport, "off");
pktgen.set_proto(sendport..","..rcvport, "udp")
pktgen.set_proto("all", "udp");
--pktgen.page("range");

--pktgen.set_mac("0-1", "0800:2732:6ed5");

pktgen.dst_mac("all", dst_mac);
pktgen.src_mac("all", src_mac);

pktgen.set("all", "burst", 1);

pktgen.dst_ip("all", "start", dstip_sendport);
pktgen.dst_ip("all", "inc", "0.0.0.1");
pktgen.dst_ip("all", "min", dstip_sendport);
pktgen.dst_ip("all", "max", dstip_max);

pktgen.src_ip("all", "start", srcip_sendport);
pktgen.src_ip("all", "inc", "0.0.0.0");
pktgen.src_ip("all", "min", srcip_sendport);
pktgen.src_ip("all", "max", srcip_sendport);
	
pktgen.set(sendport, "sport", sport);
pktgen.set(sendport, "dport", dport);

pktgen.set(rcvport, "sport", sport);
pktgen.set(rcvport, "dport", dport);

pktgen.icmp_echo("all", "on");
pktgen.send_arp("all", "g");

pktgen.gtpu_teid(sendport,"min",gtputeid_min);
pktgen.gtpu_teid(sendport,"max",gtputeid_max);
pktgen.gtpu_teid(sendport,"start",gtputeid_start);
pktgen.gtpu_teid(rcvport,"min",gtputeid_min);
pktgen.gtpu_teid(rcvport,"max",gtputeid_max);
pktgen.gtpu_teid(rcvport,"start",gtputeid_start);

local pktSize = tonumber(pktgen.input("Size of packets to send (64-1518B): "));
if pktSize == nil then
    pktSize = 64;
end
pktgen.set(sendport, "size", pktSize);

printf("\n*** Sending %dB packets for %d seconds ***\n", pktSize, send_for_secs);
pktgen.start(sendport);
local start_time = os.time();

-- I don't use just sleep(send_for_secs) because it blocks Pktgen's output
-- refreshing. Instead let's check the time on start and poll it until
-- the difference time_now - start_time reaches sends_for_secs.
while os.difftime(os.time(), start_time) < send_for_secs do
    sleep(1);
end
pktgen.stop(sendport);

-- Displaying results immediately shows 0 pkts, so let's wait a bit
sleep(5);
local stats = pktgen.portStats(sendport..","..rcvport, "port");
local sentpkts = stats[tonumber(sendport)].opackets;
--local rcvdpkts = stats[tonumber(rcvport)].ipackets;

printf("\n*** RESULT:\tFinished in\t\t%d seconds\n", send_for_secs);
printf("\t\tsent %d pkts\t%.4f Mpkts/sec\n", sentpkts,
                                            (sentpkts/1000000)/send_for_secs);
--printf("\t\trcvd %d pkts\t%.4f Mpkts/sec\n", rcvdpkts,
--                                            (rcvdpkts/1000000)/send_for_secs);
--printf("\t\tdeltapkts(TX - RX):\t%d pkts\n***\n", sentpkts-rcvdpkts);

printf("\nWriting to file %s\n", log_file);
write_stats_to_file(log_file, sendport, rcvport, send_for_secs);

**Comment by pktgen** [comment]
Not sure why you reopened the ticket, but the original problem is you need to have at least 3 cores in the VM -c 0x01 needs to be -c 0x07 to give Pktgen a display core and one core for each port you are using.

**Comment by prasshri** [comment]
Actually while creating the Issue I accidently closed it .. That's I reopened it 
Sorry for that 
I will increase the number of CPU's and try with -c 0x07 option .. Thanks for the reply

**Comment by prasshri** [comment]
Hi, 

I have added 3 cores and started pktgen with above mentioned changes and yes its working fine.
Thanks a lot Sir for your help. just wanted one more favour. I wanted to generate GTPU traffic using pktgen and I have added below mentioned configuration in the lua script 

local gtputeid_min = "5000";
local gtputeid_max = "7000";
local gtputeid_start = "5000";
pktgen.gtpu_teid ("all", "min", gtputeid_min);
pktgen.gtpu_teid ("all", "max", gtputeid_max);
pktgen.gtpu_teid ("all", "start", gtputeid_start);

I have set the port to 2152 and protocol to UDP, I can see GTP packets on wire, but they are all having teid value as 0. I have already configured the ranges for teid but its not getting in effect 

Can you please let me know what is it that I am missing 

Thanks in Advance

**Comment by pktgen** [comment]
Did you resolve this issue?

**Comment by prasshri** [comment]
Hi Kieth,

Sorry for the delay in reply.
I have finally configured the TEID ranges in a correct manner and now I can see TEID's getting incremented for the outgoing GTP packets 

I am closing the Issue 
Thanks Again 

Best Regards
Prashant

**Comment by pktgen** [comment]
Thank you.
