### ISSUE TITLE
How to compile ?

### ISSUE THREAD

**Issue by h2cw2l** [pktgen/Pktgen-DPDK#75]
root@ubuntu:~/Pktgen-DPDK# make
>>> Use 'make help' for more commands

./tools/pktgen-build.sh build
>>> lua_enabled      : '-Denable_lua=false'
>>> gui_enabled      : '-Denable_gui=false'
>>> SDK Directory    : '/root/Pktgen-DPDK'
>>> Build Directory  : '/root/Pktgen-DPDK/Builddir'
>>> Target Directory : '/root/Pktgen-DPDK/usr'

>>> Ninja build in '/root/Pktgen-DPDK/Builddir' buildtype='release'
meson -Dbuildtype=release -Denable_lua=false -Denable_gui=false Builddir
./tools/pktgen-build.sh: line 43: meson: command not found
log: ninja version 0.1.3 initializing
log: magic group: gid=0 (root)
log: entering main loop
log: generating initial pid array..
log: now monitoring process activity
die: got signal SIGSEGV -- segmentation fault
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 1
root@ubuntu:~/Pktgen-DPDK#

root@ubuntu:~/Pktgen-DPDK# meson -Dbuildtype=release -Denable_lua=false -Denable_gui=false Builddir
The Meson build system
Version: 0.29.0
Source dir: /root/Pktgen-DPDK
Build dir: /root/Pktgen-DPDK/Builddir
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file meson.build, line 1, column 0:
Expected 1 arguments, got 2.
root@ubuntu:~/Pktgen-DPDK#

**Comment by pktgen** [comment]
do 'make rebuild' if you are using the latest Pktgen and DPDK. It does all of the meson / ninja work and the output binaries in pktgen/usr/...
