### ISSUE TITLE
Multiple Instances of Pktgen 

### ISSUE THREAD

**Issue by churchillyik** [pktgen/Pktgen-DPDK#76]
The enviorment:
cpu lcores:
Socket   :    0  
  Core   0 : [ 0, 4]  
  Core   1 : [ 1, 5]  
  Core   2 : [ 2, 6]  
  Core   3 : [ 3, 7] 

ports:
`dpdk-2.2.0-rc1/tools/dpdk_nic_bind.py --status`
# Network devices using DPDK-compatible driver

0000:01:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=
0000:01:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=

I use 'test/my.lua' to setup a sequence of packets(each of them is 64k) to send, and start 2 instances of Pktgen as follows:
`./app/app/x86_64-native-linuxapp-gcc/pktgen -c f -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg1 -b 01:00.1 -- -T -P -m "[1-2:3].0" -f test/my.lua -l my2.log themes/black-yellow.theme`
`./app/app/x86_64-native-linuxapp-gcc/pktgen -c f0 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg2 -b 01:00.0 -- -T -P -m "[5-6:7].0" -f test/my.lua -l my.log themes/black-yellow.theme`

And these 2 Pktgens send packets to each other. But the RX of both sides can only get to about 10.5m rather then 14.88m. 
![ins1](http://img1.ph.126.net/peOKTXrE23sVMbl3XjGe8w==/6631610924444079649.png)
![ins2](http://img2.ph.126.net/P6CfCi-a0686HObWlc3D-g==/6631706581955697899.png)

However, if I abandon the RX of one instance like this:
`./app/app/x86_64-native-linuxapp-gcc/pktgen -c f0 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg2 -b 01:00.0 -- -T -P -m "[8:7].0" -f test/my.lua -l my.log themes/black-yellow.theme`
then I got the RX 14.88m for one side:
![ins3](http://img2.ph.126.net/nC08iAogJkv5ps1EV8VmWw==/6631770353630104430.png)
![ins4](http://img1.ph.126.net/TV8t4BduQmiuwbEK-w43bA==/6631604327374310497.png)

So my question is how to get both RX to be 14.88m.

**Comment by pktgen** [comment]
> On Aug 1, 2016, at 4:19 AM, churchillyik <notifications@github.com> wrote:
> 
> The enviorment:
> cpu lcores:
> Socket : 0
> 
> Core 0 : [ 0, 4]
> 
> Core 1 : [ 1, 5]
> 
> Core 2 : [ 2, 6]
> 
> Core 3 : [ 3, 7]
> 
> ports:
> lspci | grep Ether
> 00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I217-V (rev 05)
> 01:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
> 01:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
> 
> I use 'test/my.lua' to setup a sequence of packets(each of them is 64k) to send, and start 2 instances of Pktgen as follows:
> ./app/app/x86_64-native-linuxapp-gcc/pktgen -c f -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg1 -b 01:00.1 -- -T -P -m "[1-2:3].0" -f test/my.lua -l my2.log themes/black-yellow.theme
> ./app/app/x86_64-native-linuxapp-gcc/pktgen -c f0 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg2 -b 01:00.0 -- -T -P -m "[5-6:7].0" -f test/my.lua -l my.log themes/black-yellow.theme

The problem you are running into is you have 8 lcores, but only have 4 physical cores. When you set Pktgen to run on all lcores you are really sharing the physical cores, which is not going to work well.

You need to setup up each pktgen to own its own physical cores to get the best performance.


> 
> And these 2 Pktgens send packets to each other. But the RX of both sides can only get to about 10.5m rather then 14.88m. 
> 
> 
> 
> However, if I abandon the RX of one instance like this:
> ./app/app/x86_64-native-linuxapp-gcc/pktgen -c f0 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg2 -b 01:00.0 -- -T -P -m "[8:7].0" -f test/my.lua -l my.log themes/black-yellow.theme
> then I got the RX 14.88m for one side:
> 
> 
> 
> So my question is how to get both RX to be 14.88m.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by churchillyik** [comment]
Thanks for Keith Wiles' answer. 
The fact is that even if I set 2 entire physical cores for the rx of one instance like this:
`./app/app/x86_64-native-linuxapp-gcc/pktgen -c 77 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg1 -b 01:00.1 -- -T -P -m "[1-2/5-6:4].0" -f test/my.lua -l my2.log themes/black-yellow.theme`
and the other one is set to be:
`./app/app/x86_64-native-linuxapp-gcc/pktgen -c 89 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg2 -b 01:00.0 -- -T -P -m "[3:7].0" -f test/my.lua -l my.log themes/black-yellow.theme`
The result just changes a little:
![31](http://img2.ph.126.net/h8kUurS7F9fZd4WSL0l_Jg==/6631557048374343953.png)
![32](http://img1.ph.126.net/tc_je90m_cTOjYVNMQPQzw==/6631461390862734805.png)
Is there anything else I didn't consider?

**Comment by pktgen** [comment]
> On Aug 2, 2016, at 2:36 AM, churchillyik <notifications@github.com> wrote:
> 
> Thanks for Keith Wiles' answer. 
> The fact is that even if I set 2 entire physical cores for the rx of one instance like this:
> ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 77 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg1 -b 01:00.1 -- -T -P -m "[1-2/5-6:4].0" -f test/my.lua -l my2.log themes/black-yellow.theme
> and the other one is set to be:
> ./app/app/x86_64-native-linuxapp-gcc/pktgen -c 89 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg2 -b 01:00.0 -- -T -P -m "[3:7].0" -f test/my.lua -l my.log themes/black-yellow.theme
> The result just changes a little:

The problem is you are still using the second hyper-thread on the physical cores. Only having 4 cores is a problem with trying to run two Pktgens at this rate.

The only configuration I can see to work is maybe this:

./app/app/x86_64-native-linuxapp-gcc/pktgen -l 0-1 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg1 -b 01:00.1 -- -T -P -m “1.0" -f test/my.lua -l my2.log themes/black-yellow.theme


./app/app/x86_64-native-linuxapp-gcc/pktgen -l 2-3 -n 2 --proc-type auto --log-level 0 --socket-mem 512 --file-prefix pg2 -b 01:00.0 -- -T -P -m "3.0" -f test/my.lua -l my.log themes/black-yellow.theme

DPDK has an option —master-lcore which allows you to select the master lcore and maybe using 0 and 4 on the first core gives you an extra core to use, but I have not tested that configuration with pktgen. I hope that option would help.

**Comment by churchillyik** [comment]
I have try the --master-lcore option, but it does not improve much with 4 cores only. So how many physical cores at least for 2 pktgens to be best performance? (1 core for RX + 1 core for TX) * 2 + 1 for master core = 5 cores?

**Comment by pktgen** [comment]
Normally 2 cores per port [1:2].0 like this and the master cores on each pktgen are on core 0 lcore 0 and 4 I think that was it

**Comment by pktgen** [comment]
Were you able to resolve this issue?

**Comment by churchillyik** [comment]
Not yet. I have another problem. Only one rx queue can receive packets even if I use the RSS

**Comment by churchillyik** [comment]
I have setup a sequeue of packets with random src/dst IPs and ports and multi lcores for the rx of the port.

**Comment by pktgen** [comment]
That is odd, can you verify that only a single flow or subset of flows are present on the one queue. Could be all of the flows appear on that single queue, which would mean to me the it could be just bad luck they are hash to the same queue, but I would not think so.

**Comment by churchillyik** [comment]
I found that I just make a mistake. The RSS cfg indeed take effect because the "m->hash.rss" value in the rte_mbuf struct is non-zero. However, pktgen does not split the rx stats for each queue if you do not adding code like:
in "for (q = 0; q < rt.rx; q++)" loop of "pktgen_config_ports" function 
`int lid = wr_get_port_lid(pktgen.l2p, pid, q);`
`pktgen_log_info(">>>> set rx queue stats mapping pid = %d | q = %d | lid = %d", pid, q, lid);`
`rte_eth_dev_set_rx_queue_stats_mapping(pid, q, lid);`
then the rx stats will split to several pieces via lcore id.

**Comment by pktgen** [comment]
Thanks I will look in to that issue.

**Comment by pktgen** [comment]
I think I pushed your suggestion into pktgen 3.0.12, please have a look and see if this will work.

> On Aug 14, 2016, at 10:06 PM, churchillyik <notifications@github.com> wrote:
> 
> I found that I just make a mistake. The RSS cfg indeed take effect because the "m->hash.rss" value in the rte_mbuf struct is non-zero. However, pktgen does not split the rx stats for each queue if you do not adding code like:
> in "for (q = 0; q < rt.rx; q++)" loop of "pktgen_config_ports" function 
> int lid = wr_get_port_lid(pktgen.l2p, pid, q);
> pktgen_log_info(">>>> set rx queue stats mapping pid = %d | q = %d | lid = %d", pid, q, lid);
> rte_eth_dev_set_rx_queue_stats_mapping(pid, q, lid);
> then the rx stats will split to several pieces via lcore id.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Keith Wiles
keith.wiles@intel.com
