### ISSUE TITLE
Segmentation fault when blacklisting PCI device

### ISSUE THREAD

**Issue by cjdoucette** [pktgen/Pktgen-DPDK#77]
I'm trying to generate and receive packets using pktgen on two DPDK-enabled interfaces, but I'm not sure that I have the correct memory and PCI device blacklisting setup. Thanks for any time and help you can give.

My setup is two 10Gb NICs, both with two ports. DPDK recognizes card A to have ports 0 and 2, and card B to have ports 1 and 3. I've connected ports 0 and 1 as well as ports 2 and 3 via cables.

I am using pktgen to send packets from port 0 and receive them on port 1 using the following commands:

    $ sudo ./pktgen -c 7 --socket-mem 256 --file-prefix pg1 -b 85:00.0 -- -T -P -m "[1:2].0"

    $ sudo ./pktgen -c 70 --socket-mem 256 --file-prefix pg2 -b 83:00.0 -- -T -P -m "[5:6].1"

This works fine. But when I try to do this with ports 2 and 3, I get a segmentation fault when trying to run pktgen on port 3:

    $ # works:
    $ sudo ./pktgen -c 7 --socket-mem 256 --file-prefix pg1 -b 85:00.1 -- -T -P -m "[1:2].2"

    $ # doesn't work:
    $ sudo ./pktgen -c 70 --socket-mem 256 --file-prefix pg2 -b 83:00.1 -- -T -P -m "[5:6].3"

This is the error message I get when trying to run that command on port 3:

    === port to lcore mapping table (# lcores 3) ===
       lcore:     4     5     6 
    port   3:  D: T  1: 0  0: 1 =  1: 1
    Total   :  0: 0  1: 0  0: 1
        Display and Timer on lcore 4, rx:tx counts per port/lcore

    Configuring 3 ports, MBUF Size 1920, MBUF Cache Size 512
    Lcore:
        5, RX-Only
                    RX( 1): ( 3: 0) 
        6, TX-Only
                    TX( 1): ( 3: 0) 
    
    Port :
        3, nb_lcores  2, private (nil), lcores:  5  6 
    
    
                                                                          Total memory used =      0 KB
    
    
    === Display processing on lcore 4
      RX processing lcore:   5 rx:  1 tx:  0
    Segmentation fault (core dumped)`
    
This happens if I blacklist any of the other PCI devices (83:00.0, 83:00.1, or 85:00.0), but if I don't blacklist any, then the segmentation fault doesn't happen. Any ideas what I'm doing incorrectly here?

Here's some information about the devices:

    $ lspci | grep Ethernet
    <omitted>
    83:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
    83:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
    85:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
    85:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)

**Comment by pktgen** [comment]
The port numbers used in the -m option always start with zero. When you black the first three port in a 4 port system the -m would  start with zero like [2:3].0 even thou it is the third port of the four. Always start counting your ports from zero.

**Comment by cjdoucette** [comment]
That makes more sense, and works perfectly. Thanks very much for the quick reply.

This can be closed, since it's not a pktgen problem. Just user error. :)
