### ISSUE TITLE
not tx packets with one virtio_user0 port

### ISSUE THREAD

**Issue by LilyaBu** [pktgen/Pktgen-DPDK#77]
Hello. 
I build Pktgen 21.03.0 (DPDK 21.05.0)  and run container with two vhostuserdpdk ports connected to ovs-dpdk switch (ovs-vsctl (Open vSwitch) 2.15.90 ).

When i run in container  pktgen application with single virtio_user port:

> ./pktgen -l 3-7 -n 3 --socket-mem 1024,1024     --vdev=virtio_user0,path=$sock1 -- -P -N -m "5:6.0"

configure port and start tx:

> set 0 src mac 00:11:22:33:44:11
> set 0 dst mac 00:11:22:33:44:21 
> start 0

port 0 stats shows tx 0 packets:

> Link State          :   <UP-4294967295-HD>     ---Total Rate--- 
> Pkts/s Rx           :                    0                    0                        
>           Tx            :                    0                     0

Is this issue or i have mistakes in configuration?

When i run in container pktgen with 2 ports - port stats shows tx, rx counters are increasing,
ovs--ofctl dump-ports shows tx, rx counters are increasing.

> pktgen -l 3-7 -n 3 --socket-mem 1024,1024 \
>    --vdev=virtio_user0,mac=00:11:22:33:44:11,path=$sock1 \
>    --vdev=virtio_user1,mac=00:11:22:33:44:12,path=$sock2 \
> -- -P -N -m "5.0,6.1"

> set 0 src mac 00:11:22:33:44:11
> set 0 dst mac 00:11:22:33:44:21

> set 1 src mac 00:11:22:33:44:12
> set 1 dst mac 00:11:22:33:44:22

> start 0
> start 1

both ports has tx & tx traffic:
> Link State          :   <UP-4294967295-HD>   <UP-4294967295-HD>     ---Total Rate--- 
> Pkts/s Rx           :              1811648              1811616              3623264    
>           Tx           :              1811648              1827168              3638816

Thank you.

**Comment by KeithWiles** [comment]
If you do not have link state of UP, then pktgen will not send any traffic to the port. In the text above you did not show the link state values.

In the first setup you have two cores sending to a single port, try just one core "5.0" instead of 5:6.0

**Comment by LilyaBu** [comment]
Thank you! 
With one core traffic is transmitted.

Link state is UP
> Link State          :   <UP-4294967295-HD>     ---Total Rate---
