### ISSUE TITLE
pktgen-dpdk on Openstack VM

### ISSUE THREAD

**Issue by hemz2711** [pktgen/Pktgen-DPDK#78]
Hello,

For our dataplane testing. I have created two VM's on the openstack environment and I have installed pktgen and dpdk packages following the procedure from http://www.dpdk.org/. when I run the setup.sh script I see the following status.

root@ubuntu:~# ./pktgen-dpdk/setup.sh
Using directory: /root/dpdk//x86_64-native-linuxapp-gcc
Setup 1 socket(s) with 256 pages.
AnonHugePages: 4096 kB
HugePages_Total: 256
HugePages_Free: 256
HugePages_Rsvd: 0
HugePages_Surp: 0
Hugepagesize: 2048 kB
trying to remove old igb_uio module and may get an error message, ignore it
trying to remove old rte_kni module and may get an error message, ignore it
# Network devices using DPDK-compatible driver

<none>
# Network devices using kernel driver

0000:00:03.0 'Virtio network device' if= drv=virtio-pci unused=igb_uio
# Other network devices

<none>

So I have used the following command to bind the nic  ./dpdk_nic_bind.py -b uio_pci_generic 00:03.0. I have attached the pics after I have executed the command. I am unable to find the  interface and run sample tests. 
![1](https://cloud.githubusercontent.com/assets/21065130/17710194/d65cf0c0-63b1-11e6-8e8d-9719078cfa8c.png)
![2](https://cloud.githubusercontent.com/assets/21065130/17710193/d65c74b0-63b1-11e6-9adf-57767a2adf85.png)

**Comment by pktgen** [comment]
Keith Wiles
keith.wiles@icloud.com



> On Aug 16, 2016, at 1:03 PM, hemz2711 <notifications@github.com> wrote:
> 
> Hello,
> 
> For our dataplane testing. I have created two VM's on the openstack environment and I have installed pktgen and dpdk packages following the procedure from http://www.dpdk.org/. when I run the setup.sh script I see the following status.
> 
> root@ubuntu:~# ./pktgen-dpdk/setup.sh
> Using directory: /root/dpdk//x86_64-native-linuxapp-gcc
> Setup 1 socket(s) with 256 pages.
> AnonHugePages: 4096 kB
> HugePages_Total: 256
> HugePages_Free: 256
> HugePages_Rsvd: 0
> HugePages_Surp: 0
> Hugepagesize: 2048 kB
> trying to remove old igb_uio module and may get an error message, ignore it
> trying to remove old rte_kni module and may get an error message, ignore it
> 
> Network devices using DPDK-compatible driver
> 
> 
> Network devices using kernel driver
> 
> 0000:00:03.0 'Virtio network device' if= drv=virtio-pci unused=igb_uio
> 
> Other network devices
> 
> 
> So I have used the following command to bind the nic ./dpdk_nic_bind.py -b uio_pci_generic 00:03.0. I have attached the pics after I have executed the command. I am unable to find the interface and run sample tests. 

Normally when you do a dpdk_nic_bind command it will remove the NIC from the kernel and this means the device is no longer managed by the kernel thus the interface disappears from the ifconfig command.

**Comment by hemz2711** [comment]
How should I proceed from here? I need to test the dpdk

**Comment by hemz2711** [comment]
How should I enable the nic so that it becomes capable of accepting traffic

**Comment by pktgen** [comment]
Keith Wiles
keith.wiles@icloud.com



> On Aug 16, 2016, at 5:08 PM, hemz2711 <notifications@github.com> wrote:
> 
> How should I enable the nic so that it becomes capable of accepting traffic

The DPDK docs talk about a —vdev option that allows you to attach to virtio or virtual devices.

In the README.md file for pktgen I should the option vdev and in the DPDK docs they talk about how to use that option.

Also look in the doit.sh script as I have some options in that file using —vdev with the eth_ring PMD, but you can use virtio devices in this style too.

**Comment by kaminek** [comment]
you should bind your interface with igb_uio driver rather than this one.
