### ISSUE TITLE
maximum simultaneous flows 

### ISSUE THREAD

**Issue by ibrahimmenem** [pktgen/Pktgen-DPDK#79]
Hi,

On Pktgen Ver: 3.0.09 (DPDK 16.11.0-rc0) I found that independently of the ranges I configure I always get 8k flows (a subset of the range I defined), how can I increase this limit?

Thanks

**Comment by pktgen** [comment]
One the total number of flows is dependent on the number of packet buffer allocated to the range. The number of packets or memory is define in the pktgen-constants.h file. You would need to increase MAX_MBUFS_PER_PORT value to allocate more mbufs for the range.

Keith Wiles
keith.wiles@icloud.com

**Comment by ibrahimmenem** [comment]
Thank you very much for the fast response!
