### ISSUE TITLE
OpenStack nova booted VMs are not able to communicate to with pktgen ports

### ISSUE THREAD

**Issue by raiesmh08** [pktgen/Pktgen-DPDK#80]
I have OpenStack setup with contrail backend. I have two compute nodes.
2 VMs are booted (1 on each compute node). These VMs are in same network. 
Each VM has two pci interfaces.
1. Ethernet interface to communicate to each other.
2. DPDK enable interface (port 0 in each case)

When I run start 0 from one VM, these transmitted VMs are supposed to receive on port 0 of 2nd VM on another compute node. But there no packet is received.

What can be the reason ? 

My settings are as below -
########################### port status
root@test-pktgen-1:/home/pktgen-dpdk# ./../dpdk/tools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:00:03.0 'Virtio network device' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:00:04.0 'Virtio network device' if= drv=virtio-pci unused=igb_uio

Other network devices
=====================
<none>
root@test-pktgen-1:/home/pktgen-dpdk#

########################################
root@test-pktgen-1:/home/pktgen-dpdk# grep -i huge /proc/meminfo
AnonHugePages:         0 kB
HugePages_Total:     256
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
root@test-pktgen-1:/home/pktgen-dpdk#

These basic setting are on each VMs.

**Comment by pktgen** [comment]
I need to see the command line for Pktgen for each VM, please.

Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x7 -n 1 --  -T -P -m "1.0"

**Comment by raiesmh08** [comment]
One observation : 

in pktgen output I could see IP and mac as -
#VM1 
Pattern Type      :             abcd...
Tx Count/% Rate   :      Forever / 100%
PktSize/Tx Burst  :           64 /   32
Src/Dest Port     :         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / TCP:0001
Dst  IP Address   :         192.168.1.1
Src  IP Address   :      192.168.0.1/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   02:f3:51:f8:52:82
VendID/PCI Addr   :   1af4:1000/00:03.0

#VM2 
Pattern Type      :             abcd...
Tx Count/% Rate   :      Forever / 100%
PktSize/Tx Burst  :           64 /   32
Src/Dest Port     :         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / TCP:0001
Dst  IP Address   :         192.168.1.1
Src  IP Address   :      192.168.0.1/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   02:25:dc:aa:9e:07
VendID/PCI Addr   :   1af4:1000/00:03.0


I updated src/mac address of each other i.e src of 1 is dst of other. Still same problem

**Comment by raiesmh08** [comment]
VM1 port 0 transmitted - 

![image](https://cloud.githubusercontent.com/assets/5044578/19038314/a1a38a30-8998-11e6-95c9-f7ad697269a0.png)

VM2 port 0 received nothing -
![image](https://cloud.githubusercontent.com/assets/5044578/19038354/c3c535e6-8998-11e6-9f70-5126a08ae094.png)

**Comment by pktgen** [comment]
with the -P option the MAC addresses should not matter.

Does Pktgen see the devices as up?

Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
In attached outputs, please have a look.

**Comment by pktgen** [comment]
Are you using OVS or something to connect the two VMs from the Host view?

Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
I am using contrail plugin. It uses vRouter to connect VMs.
With non-dpdk interface (eth1 in my case), I am able to ping VM2 from VM1

**Comment by raiesmh08** [comment]
![image](https://cloud.githubusercontent.com/assets/5044578/19038525/887fbb86-8999-11e6-9ae3-32a506a575d0.png)

**Comment by pktgen** [comment]
I noticed the IP addresses are the same for both pktgen’s can you change MAC dest to point to each others MAC address and change the source/dest IP addresses to be correct. I believe the contrail router is L3 router right?
Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
I did this also (I have put IP address as of non-dpdk interface)- 

VM2#
![image](https://cloud.githubusercontent.com/assets/5044578/19038800/ca30062a-899a-11e6-9320-b1ace83f02b9.png)

VM1#
![image](https://cloud.githubusercontent.com/assets/5044578/19038811/d634f62e-899a-11e6-9680-2e8ac4ffb1ef.png)

**Comment by raiesmh08** [comment]
And yes vRouter is L3. it can act as L2 also.

**Comment by pktgen** [comment]
Does contrail have some way to see if the packets are getting to the router. I do not see any problems with Pktgen to not work, so we need to look at contrail. I have not used contrail and will not be much help with it.
Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
Okay np. I will check it for contrail.
Please confirm only one thing, two VMs on 2 different host (which are able to communicate). pktgen ports can communicate without any problem ? or some extra setting is needed ?

**Comment by pktgen** [comment]
Pktgen is only using the ports like any other DPDK application in a VM. If the two VMs can communicate via as standard ports then then should be able to connect. I have had others get two VMs to work, but I have used these configurations. My guess is you need to look at contrail and make sure the virtio ports are connected to the router. You should also be able to query contrail to see if any packets are being seen on these ports.

Please let me know if you get this working and if you feel Pktgen has a problem here. You can also try test-pmd DPDK application to see if it works.

Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
@pktgen 
Hi, Now ports are able to communicate.
The main problem was vlan setting on each ports.
When I enabled vlan on each of the ports on both the VM, I was able to send and receive traffics.
I used following command : 

"vlan all on" on each pktgen instance

**Comment by raiesmh08** [comment]
Now closing the issue :)

**Comment by pktgen** [comment]
Excellent work :-) that does make sense. So contrail needs VLAN TAG packets.

Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
Thanks.

One more thing, i need to ask, when I am trying to check latency with pktgen version 3.0.11 and dpdk version as DPDK 16.11.0.-rc0

When I send one packet in this case, i can see packet is immediately transferred but the latency is shown too high  - "73816426453270" thus jitter count is 100%.
Do you know what can be the reason ?
