### ISSUE TITLE
Latency value is too high

### ISSUE THREAD

**Issue by raiesmh08** [pktgen/Pktgen-DPDK#81]
# Test1 -

pktgen version 3.0.11, dpdk version - DPDK 16.11.0.-rc0

When I send one ping packet from port 0 on on VM1 (on host A), i can see packet is immediately transferred to VM2(on host 2) but the latency is displayed is too high  - "73816426453270" thus jitter count is 100%. and 100% packet loss.
# Test2 -

I repeated same with latest versions : pktgen version as 3.0.14 and dpdk as 16.07.0
Still I can see same problem.

Any help will be appreciated.

**Comment by raiesmh08** [comment]
@pktgen kindly have a look on this issue.

**Comment by pktgen** [comment]
The problem with latency I am using the CPU cycle counter and the cycle counters are per CPU core. When you send a packet to the other VM it is on a different core. Because different cores have different cycle counters you need to send the packet to VM2 then back to VM1 to get a clear latency value. Is this what you are doing?

Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
What i did is - 
1. set latency on on both the VM ports 
2. Set packet size in VM1 to 96
3. Run "ping4 0" on VM1

#Observation -
On VM2 pktgent instance I can see Latency usec is ~"73816426453270"
and on VM1 "Latency usec" nothing is seen.

**Comment by raiesmh08** [comment]
pktgen commands on each VM - 

VM1#/VM#2 -

./app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x7 -n 1 -- -T -P -m "1.0"

**Comment by raiesmh08** [comment]
VM2# starter message -
![image](https://cloud.githubusercontent.com/assets/5044578/19078076/90038184-8a6c-11e6-8b22-29fbb31db127.png)


VM2# starter message -
 ![image](https://cloud.githubusercontent.com/assets/5044578/19078023/52c0577a-8a6c-11e6-938b-4209754e7118.png)

**Comment by raiesmh08** [comment]
As you said below statement - 
"Because different cores have different cycle counters you need to send the packet to VM2 then back to VM1 to get a clear latency value. Is this what you are doing?"

i.e. send from VM1 to VM2 and VM2 to VM1.

How can I send same packet from VM1 to VM2 and back to VM1 ?

**Comment by pktgen** [comment]
You will need to loop the packet back to VM1 using say L2_fwd or L3_fwd or one you wrote. Look at these two examples to run on VM2 for your tests. The packet need to return VM1 and VM2 needs to loop the packet back to VM1.

Keith Wiles
keith.wiles@icloud.com

**Comment by raiesmh08** [comment]
I didn't much understand it much. Can u please give procedures for this ?

**Comment by raiesmh08** [comment]
I set a new environment.
VM1 with packetgen (Only one port)
VM2 with l2fwd instance (Only one port)

when I send packets from VM1 i cant see them in f2fwd.

What can be the reason ?

**Comment by hemcr** [comment]
Forgive the novice question!
Is it a safe assumption that packet has to be looped back to origin to measure latency while using PktGen?

**Comment by pktgen** [comment]
Keith Wiles
keith.wiles@icloud.com



> On Oct 10, 2016, at 11:21 AM, hemcr <notifications@github.com> wrote:
> 
> Forgive the novice question!
> Is it a safe assumption that packet has to be looped back to origin to measure latency while using PktGen?

Correct, the cycle counter used needs to be the same one.
