### ISSUE TITLE
DPDK with multiple 40G NIC Cards

### ISSUE THREAD

**Issue by chrispappas12** [pktgen/Pktgen-DPDK#82]
I have a machine with 6 dual-port Intel XL710 NICs and want to use 6 ports at 40G, i.e., 1 port per NIC (I think it's possible to use only one port in 40G fully saturated).

When I run pktgen, only one of the 40G NIC transmits packets (and it's the last enabled NIC in the list). I launch pktgen as follows:

sudo ./app/app/x86_64-native-linuxapp-gcc/app/pktgen -c 0xffff -n 3 -- -P -m "[1:3].0,[2:4].1,[3:5].2,[4:6].3,[5:7].4,[6:8].5,[7:9].6,[8:10].7,[9:11].8,[10:12].9,[11:13].10,[12:14].11"

Everything seems to work normally, but typing start all, starts only the last port. The command to start a portid also doesn't work.
Is there something I am doing wrong?

**Comment by pktgen** [comment]
Keith Wiles
keith.wiles@icloud.com



> On Oct 6, 2016, at 10:09 AM, chrispappas12 <notifications@github.com> wrote:
> 
> I have a machine with 6 dual-port Intel XL710 NICs and want to use 6 ports at 40G, i.e., 1 port per NIC (I think it's possible to use only one port in 40G fully saturated).
> 
> When I run pktgen, only one of the 40G NIC transmits packets (and it's the last enabled NIC in the list). I launch pktgen as follows:
> 
> sudo ./app/app/x86_64-native-linuxapp-gcc/app/pktgen -c 0xffff -n 3 -- -P -m "[1:3].0,[2:4].1,[3:5].2,[4:6].3,[5:7].4,[6:8].5,[7:9].6,[8:10].7,[9:11].8,[10:12].9,[11:13].10,[12:14].11”

You are trying to use the same core on multiple ports, is this what you wanted to do?

"[1:3].0,[2:4].1,[5:7].2,[6:8].3,[9:11].4,[10:12].5,[13:15].6,[14:16].7,[17:19].8,[18:20].9,[21:23].10,[22:24].11”

Assuming you have that many physical cores on a single socket, if not then you have to adjust the cores.
