### ISSUE TITLE
run the following command   ./pktgen-l 0-1 -n 3 -- -P -m "[1].0"   ，under "pattern type", did not see what i expected "dst ip address"

### ISSUE THREAD

**Issue by caicaizi1234567** [pktgen/Pktgen-DPDK#82]
![image](https://user-images.githubusercontent.com/88993480/131813836-57c9c9ce-2c2c-4fcb-9c51-a2e826088ccd.png)

**Comment by pktgen** [comment]
Sorry, not able to see the screen information and I can not read some of your comments text.

Please use a bigger xterm or a valid xterm 'hyperterm' is not a valid xterm :-)
