### ISSUE TITLE
WARNING: Wrote 0 sample latencies to file samples

### ISSUE THREAD

**Issue by neel-patel-1** [pktgen/Pktgen-DPDK#83]
Hello,

I am trying to use the latsampler feature of pktgen, but I am getting the warning message that no latencies are written after stopping the sampler.

I run the commands in this order:
set 0 latsampler simple 10 10 samples
start 0 latsampler
stop 0 latsampler

I am transmitting and receiving on the same port
Not sure what I am doing incorrectly

Thanks

**Comment by neel-patel-1** [comment]
This is the command line options:
sudo Builddir/app/pktgen -l0-1  -n10 -w17:00.0 -- -m "[1].0"

**Comment by pktgen** [comment]
Are you seeing packets getting returned (RX counter in pktgen going increasing) and packets being received by the other machine?

You may need to increase the packet size if you are using 64 byte frames.

**Comment by neel-patel-1** [comment]
I am getting packets received,
this is the logs:

![image](https://user-images.githubusercontent.com/36992032/132998558-312e90b7-051c-46cd-935f-299e8fc33cff.png)

**Comment by neel-patel-1** [comment]
what packet size should i set?

**Comment by pktgen** [comment]
I would have to look but I think 76 or 86. The packet needs to be large enough to hold the latency information.

**Comment by neel-patel-1** [comment]
Using packet size of 86 works. I had "enable 0 latency" in my configuration script. After disabling latency packets, the latsampler worked.
Thank you!
