### ISSUE TITLE
Use multiple nics

### ISSUE THREAD

**Issue by lynic** [pktgen/Pktgen-DPDK#83]
I have two 10G nics attached with vfio-pci driver, and I wanna use them both send traffic to another machine.

But I can not send the traffic from both nics.
Here is what I observed:
1. When I use only one nic and blacklist other one, tcpdump can receive packets.
2. When I use both nics, tx numbers show they were both sending packets, but tcpdump only receive packets from one nic(src mac has only one).

Here is the lua file I used:

```
root@host-09:~/gabe/pktgen-tests# cat elynn-xen.lua
-- Lua uses '--' as comment to end of line read the
-- manual for more comment options.
local seq_table = {                     -- entries can be in any order
    ["eth_dst_addr"] = "0c:c4:7a:a3:79:08",
    ["eth_src_addr"] = "0c:c4:7a:66:54:2c",
    ["ip_dst_addr"] = "172.20.1.192",
    ["ip_src_addr"] = "172.20.1.191/24",   -- the 16 is the size of the mask value
    ["sport"] = 9,                      -- Standard port numbers
    ["dport"] = 10,                     -- Standard port numbers
    ["ethType"] = "ipv4",       -- ipv4|ipv6|vlan
    ["ipProto"] = "udp",        -- udp|tcp|icmp
    ["vlanid"] = 1,                     -- 1 - 4095
    ["pktSize"] = 128           -- 64 - 1518
  };

local seq_table2 = {                     -- entries can be in any order
    ["eth_dst_addr"] = "0c:c4:7a:a3:79:08",
    ["eth_src_addr"] = "0c:c4:7a:66:54:2e",
    ["ip_dst_addr"] = "172.20.2.194",
    ["ip_src_addr"] = "172.20.2.193/24",   -- the 16 is the size of the mask value
    ["sport"] = 9,                      -- Standard port numbers
    ["dport"] = 10,                     -- Standard port numbers
    ["ethType"] = "ipv4",       -- ipv4|ipv6|vlan
    ["ipProto"] = "udp",        -- udp|tcp|icmp
    ["vlanid"] = 1,                     -- 1 - 4095
    ["pktSize"] = 128           -- 64 - 1518
  };
-- seqTable( seq#, portlist, table );
pktgen.seqTable(0, "0", seq_table );
pktgen.seqTable(0, "1", seq_table2 );
pktgen.set("0", "seqCnt", 1);
pktgen.set("1", "seqCnt", 1);
```

And I use following command to start pktgen:

```
./pktgen -c 0xf80 -n 4 --proc-type auto --log-level=0 --socket-mem 512 -- -T -P -m “[8:9].0,[10:11].1” -f ../pktgen-tests/elynn-xen.lua  
```

my dpdk version is 2.2.0 and pktgen version is 3.0.06.

**Comment by pktgen** [comment]
I do not see anything wrong with your configuration, so it should work. It is an older DPDK version and Pktgen, so if you can update to the latest of both.


> On Nov 8, 2016, at 6:22 AM, lynic <notifications@github.com> wrote:
> 
> I have two 10G nics attached with vfio-pci driver, and I wanna use them both send traffic to another machine.
> 
> But I can not send the traffic from both nics.
> Here is what I observed:
> 
> 	• When I use only one nic and blacklist other one, tcpdump can receive packets.
> 	• When I use both nics, tx numbers show they were both sending packets, but tcpdump only receive packets from one nic(src mac has only one).
> Here is the lua file I used:
> 
> root@host-09:~/gabe/pktgen-tests# cat elynn-xen.lua
> -- Lua uses '--' as comment to end of line read the
> -- manual for more comment options.
> local seq_table = {                     -- entries can be in any order
>     ["eth_dst_addr"] = "0c:c4:7a:a3:79:08",
>     ["eth_src_addr"] = "0c:c4:7a:66:54:2c",
>     ["ip_dst_addr"] = "172.20.1.192",
>     ["ip_src_addr"] = "172.20.1.191/24",   -- the 16 is the size of the mask value
>     ["sport"] = 9,                      -- Standard port numbers
>     ["dport"] = 10,                     -- Standard port numbers
>     ["ethType"] = "ipv4",       -- ipv4|ipv6|vlan
>     ["ipProto"] = "udp",        -- udp|tcp|icmp
>     ["vlanid"] = 1,                     -- 1 - 4095
>     ["pktSize"] = 128           -- 64 - 1518
>   };
> 
> local seq_table2 = {                     -- entries can be in any order
>     ["eth_dst_addr"] = "0c:c4:7a:a3:79:08",
>     ["eth_src_addr"] = "0c:c4:7a:66:54:2e",
>     ["ip_dst_addr"] = "172.20.2.194",
>     ["ip_src_addr"] = "172.20.2.193/24",   -- the 16 is the size of the mask value
>     ["sport"] = 9,                      -- Standard port numbers
>     ["dport"] = 10,                     -- Standard port numbers
>     ["ethType"] = "ipv4",       -- ipv4|ipv6|vlan
>     ["ipProto"] = "udp",        -- udp|tcp|icmp
>     ["vlanid"] = 1,                     -- 1 - 4095
>     ["pktSize"] = 128           -- 64 - 1518
>   };
> -- seqTable( seq#, portlist, table );
> pktgen.seqTable(0, "0", seq_table );
> pktgen.seqTable(0, "1", seq_table2 );
> pktgen.set("0", "seqCnt", 1);
> pktgen.set("1", "seqCnt", 1);
> 
> And I use following command to start pktgen:
> 
> ./pktgen -c 0xf80 -n 4 --proc-type auto --log-level=0 --socket-mem 512 -- -T -P -m “[8:9].0,[10:11].1” -f ../pktgen-tests/elynn-xen.lua  
> 
> my dpdk version is 2.2.0 and pktgen version is 3.0.06.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by lynic** [comment]
Seems it's related to bonding configuration on switch, I unbound them and now it works fine.
