### ISSUE TITLE
Latency calculation problems

### ISSUE THREAD

**Issue by EvgenyAGRO** [pktgen/Pktgen-DPDK#85]
Hi, I've encountered few bugs/inaccuracies in latency calculations and representation.

1. When retrieving avg_latency via **Lua** it is actually reporting an accumulated latency that was not divided by number of received packets, what I mean is that in function `pkt_stats` the `info->avg_latency` is not being divided by `info->latency_nb_packets` , thus the value is inaccurate.

2. When solely retrieving latency stats via **Lua** without using `page latency` before, max/min latencies are not being calculated, because the only max/min calculation is in `pktgen_page_latency` function which is called only when `page latency` was triggered.

3. Max/min latencies are actually max/min of avg latencies over a window of 2 sec which is the interval for latency page refresh, what I initially thought is that these counters are max/min latencies per packet. So this may be misleading, so maybe it should be described somewhere.

**Comment by ellagxy** [comment]
I also have same concern:
In latency page, we show avg_lat = (info->avg_latency / info->latency_nb_pkts) / ticks; However in lua table we directly get avg latency from info->avg_latency. Is it a bug? 

But the interesting thing is page latency API is the only place I saw we clear info->avg_latency other than clr stats, but whenever I show avg_latency using lua, it gets cleared after the first show, second show will show 0, does this mean page latency code gets executed when show latency using lua?
