### ISSUE TITLE
Is it possible to update pcap parameter via lua script

### ISSUE THREAD

**Issue by morphyno** [pktgen/Pktgen-DPDK#86]
I wish to play a series of pcaps via pkt-gen but they are too big to play at a time. So I broke them up into smaller pcaps. Is it possible to update pcap file from pkt-gen via lua once it is started? I'm running the pcaps in a script and it will be ideal not to script outside of pkt-gen (to avoid the initialization everytime)

**Comment by pktgen** [comment]
> On Jan 19, 2017, at 6:19 PM, Morgan Yang <notifications@github.com> wrote:
> 
> I wish to play a series of pcaps via pkt-gen but they are too big to play at a time. So I broke them up into smaller pcaps. Is it possible to update pcap file from pkt-gen via lua once it is started? I'm running the pcaps in a script and it will be ideal not to script outside of pkt-gen (to avoid the initialization everytime)

At this point the pcap inits is only down at startup time. I never setup the code to allow Lua to setup a PCAP file during runtime.

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by morphyno** [comment]
Can I make this a feature request them :-) ?

**Comment by pktgen** [comment]
> On Jan 19, 2017, at 7:48 PM, Morgan Yang <notifications@github.com> wrote:
> 
> Can I make this a feature request them :-) ?

Sure I even accept patches for this feature :-)

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com
