### ISSUE TITLE
pktgen does not transmit

### ISSUE THREAD

**Issue by vabidi** [pktgen/Pktgen-DPDK#87]
I'm using pktgen 3.1.0  in a AWS ubuntu14.04 VM
It comes up, but does not transmit any packets.

The interface bound to dpdk is an SR-IOV VF on an Intel NIC.

ubuntu@ip-15-0-0-82:~/pktgen-dpdk$ ../dpdk/usertools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:00:04.0 '82599 Ethernet Controller Virtual Function' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:00:03.0 '82599 Ethernet Controller Virtual Function' if=eth0 drv=ixgbevf unused=igb_uio 

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>
ubuntu@ip-15-0-0-82:~/pktgen-dpdk$ lspci | grep Ethernet
00:03.0 Ethernet controller: Intel Corporation 82599 Ethernet Controller Virtual Function (rev 01)
00:04.0 Ethernet controller: Intel Corporation 82599 Ethernet Controller Virtual Function (rev 01)

----------
The cmd line and output are:

ubuntu@ip-15-0-0-82:~/pktgen-dpdk$ sudo -E app/app/x86_64-native-linuxapp-gcc/pktgen  -c 0x1f -n 3 --proc-type auto --socket-mem 256,256 --file-prefix pg --  -P  -m "[2:3-4].0" -s 0:/tmp/decap_10flow.pcap  
sudo: unable to resolve host ip-15-0-0-82

Copyright (c) <2010-2016>, Intel Corporation. All rights reserved. Powered by Intel® DPDK
EAL: Detected 40 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:10ed net_ixgbe_vf
EAL: PCI device 0000:00:04.0 on NUMA socket -1
EAL:   probe driver: 8086:10ed net_ixgbe_vf
[2:3-4].0        lcores: RX( 2 )TX( 3 4 ) ports: RX( 0 )TX( 0 )

PCAP file for port 0: /tmp/decap_10flow.pcap
  magic: a1b2c3d4, Version: 2.4, Zone: 0, snaplen: 32767, sigfigs: 0, network: 1 Endian: Little

 
   Copyright (c) <2010-2016>, Intel Corporation. All rights reserved.
   Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<

Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
>>> Packet Burst 32, RX Desc 512, TX Desc 512, mbufs/port 4096, mbuf cache 512

=== port to lcore mapping table (# lcores 5) ===
   lcore:     0     1     2     3     4 
port   0:  D: T  0: 0  1: 0  0: 1  0: 1 =  1: 2
Total   :  0: 0  0: 0  1: 0  0: 1  0: 1
    Display and Timer on lcore 0, rx:tx counts per port/lcore

Configuring 1 ports, MBUF Size 1920, MBUF Cache Size 512
Lcore:
    2, RX-Only
                RX( 1): ( 0: 0) 
    3, TX-Only
                TX( 1): ( 0: 0) 
    4, TX-Only
                TX( 1): ( 0: 1) 

Port :
    0, nb_lcores  3, private 0x95acf0, lcores:  2  3  4 

** Default Info (0000:00:04.0, if_index:0) **
   max_vfs        :   0, min_rx_bufsize    :1024, max_rx_pktlen : 15872
   max_rx_queues  :   4, max_tx_queues     :   4
   max_mac_addrs  : 128, max_hash_mac_addrs:4096, max_vmdq_pools:    64
   rx_offload_capa:  15, tx_offload_capa   :  63, reta_size     :     0, flow_type_rss_offloads:0000000000000000
   vmdq_queue_base:   0, vmdq_queue_num    :   0, vmdq_pool_base:     0
** RX Conf **
   pthresh        :   8, hthresh          :   8, wthresh        :     0
   Free Thresh    :  32, Drop Enable      :   0, Deferred Start :     0
** TX Conf **
   pthresh        :  32, hthresh          :   0, wthresh        :     0
   Free Thresh    :  32, RS Thresh        :  32, Deferred Start :     0, TXQ Flags:00000f01

PMD: ixgbevf_dev_configure(): VF can't disable HW CRC Strip
Initialize Port 0 -- TxQ 2, RxQ 1,  Src MAC 02:90:63:99:6b:29
    Create: Default RX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
      Set RX queue stats mapping pid 0, q 0, lcore 2

    Create: Default TX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Range TX    0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Sequence TX 0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176
    Create: PCAP TX     0:0  - Number of MBUFs   4096 for    10 packets                 =     19 KB

    Create: Default TX  0:1  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Range TX    0:1  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Sequence TX 0:1  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
    Create: Special TX  0:1  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176
    Create: PCAP TX     0:1  - Number of MBUFs   4096 for    10 packets                 =     19 KB

                                                                       Port memory used =  57640 KB
                                                                      Total memory used =  57640 KB
Port  0: Link Up - speed 10000 Mbps - full-duplex <Enable promiscuous mode>

=== Display processing on lcore 0
WARNING: Nothing to do on lcore 1: exiting
  RX processing lcore:   2 rx:  1 tx:  0
  TX processing lcore:   3 rx:  0 tx:  1
  TX processing lcore:   4 rx:  0 tx:  1

\ Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2016>, Intel Corporation
  Flags:Port      :   P---p----------:0
Link State        :       <UP-10000-FD>     ----TotalRate----
Pkts/s Max/Rx     :                 0/0                   0/0
       Max/Tx     :                 0/0                   0/0
MBits/s Rx/Tx     :                 0/0                   0/0
Broadcast         :                   0
Multicast         :                   0
  64 Bytes        :                   0
  65-127          :                   0
  128-255         :                   0
  256-511         :                   0
  512-1023        :                   0
  1024-1518       :                   0
Runts/Jumbos      :                 0/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :                   0
      Tx Pkts     :                   0
      Rx MBs      :                   0
      Tx MBs      :                   0
ARP/ICMP Pkts     :                 0/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :      Forever / 100%
PktSize/Tx Burst  :           64 /   32
Src/Dest Port     :         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / TCP:0001
Dst  IP Address   :         192.168.1.1
Src  IP Address   :      192.168.0.1/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   02:90:63:99:6b:29
VendID/PCI Addr   :   8086:10ed/00:04.0

-- Pktgen Ver: 3.1.0 (DPDK 17.02.0-rc1)  Powered by Intel® DPDK ---------------

Pktgen > pcap 0 
 enable [Mul-choice STRING]: pcap <portlist> <state>
 disable [Mul-choice STRING]: pcap <portlist> <state>
 on [Mul-choice STRING]: pcap <portlist> <state>
 off [Mul-choice STRING]: pcap <portlist> <state>
Pktgen > pcap 0 enable
Pktgen> start 0
Pktgen> quit

**Comment by pktgen** [comment]
hmmm, everything looks fine except you could use -c 0x1E core mask or -l 1-4 instead of using a core mask which is just a bit easier to read. Also the this frees up core 0 for Linux to use.

I did not see the link state line in the screen display, but I did see it in the startup part of the output.

How many cores do you have assigned to the system?

> On Jan 25, 2017, at 7:59 PM, vabidi <notifications@github.com> wrote:
> 
> I'm using pktgen 3.1.0 in a AWS ubuntu14.04 VM
> It comes up, but does not transmit any packets.
> 
> The interface bound to dpdk is an SR-IOV VF on an Intel NIC.
> 
> ubuntu@ip-15-0-0-82:~/pktgen-dpdk$ ../dpdk/usertools/dpdk-devbind.py --status
> 
> Network devices using DPDK-compatible driver
> 
> 0000:00:04.0 '82599 Ethernet Controller Virtual Function' drv=igb_uio unused=
> 
> Network devices using kernel driver
> 
> 0000:00:03.0 '82599 Ethernet Controller Virtual Function' if=eth0 drv=ixgbevf unused=igb_uio
> 
> Other network devices
> 
> Crypto devices using DPDK-compatible driver
> 
> Crypto devices using kernel driver
> 
> Other crypto devices
> 
> ubuntu@ip-15-0-0-82:~/pktgen-dpdk$ lspci | grep Ethernet 00:03.0 Ethernet controller: Intel Corporation 82599 Ethernet Controller Virtual Function (rev 01) 00:04.0 Ethernet controller: Intel Corporation 82599 Ethernet Controller Virtual Function (rev 01)
> The cmd line and output are:
> 
> ubuntu@ip-15-0-0-82:~/pktgen-dpdk$ sudo -E app/app/x86_64-native-linuxapp-gcc/pktgen -c 0x1f -n 3 --proc-type auto --socket-mem 256,256 --file-prefix pg -- -P -m "[2:3-4].0" -s 0:/tmp/decap_10flow.pcap
> sudo: unable to resolve host ip-15-0-0-82
> 
> Copyright (c) <2010-2016>, Intel Corporation. All rights reserved. Powered by Intel® DPDK
> EAL: Detected 40 lcore(s)
> EAL: Auto-detected process type: PRIMARY
> EAL: Probing VFIO support...
> EAL: PCI device 0000:00:03.0 on NUMA socket -1
> EAL: probe driver: 8086:10ed net_ixgbe_vf
> EAL: PCI device 0000:00:04.0 on NUMA socket -1
> EAL: probe driver: 8086:10ed net_ixgbe_vf
> [2:3-4].0 lcores: RX( 2 )TX( 3 4 ) ports: RX( 0 )TX( 0 )
> 
> PCAP file for port 0: /tmp/decap_10flow.pcap
> magic: a1b2c3d4, Version: 2.4, Zone: 0, snaplen: 32767, sigfigs: 0, network: 1 Endian: Little
> 
> Copyright (c) <2010-2016>, Intel Corporation. All rights reserved.
> Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<
> 
> Lua 5.3.3 Copyright (C) 1994-2016 Lua.org, PUC-Rio
> 
> Packet Burst 32, RX Desc 512, TX Desc 512, mbufs/port 4096, mbuf cache 512
> 
> === port to lcore mapping table (# lcores 5) ===
> lcore: 0 1 2 3 4
> port 0: D: T 0: 0 1: 0 0: 1 0: 1 = 1: 2
> Total : 0: 0 0: 0 1: 0 0: 1 0: 1
> Display and Timer on lcore 0, rx:tx counts per port/lcore
> 
> Configuring 1 ports, MBUF Size 1920, MBUF Cache Size 512
> Lcore:
> 2, RX-Only
> RX( 1): ( 0: 0)
> 3, TX-Only
> TX( 1): ( 0: 0)
> 4, TX-Only
> TX( 1): ( 0: 1)
> 
> Port :
> 0, nb_lcores 3, private 0x95acf0, lcores: 2 3 4
> 
> ** Default Info (0000:00:04.0, if_index:0) **
> max_vfs : 0, min_rx_bufsize :1024, max_rx_pktlen : 15872
> max_rx_queues : 4, max_tx_queues : 4
> max_mac_addrs : 128, max_hash_mac_addrs:4096, max_vmdq_pools: 64
> rx_offload_capa: 15, tx_offload_capa : 63, reta_size : 0, flow_type_rss_offloads:0000000000000000
> vmdq_queue_base: 0, vmdq_queue_num : 0, vmdq_pool_base: 0
> ** RX Conf **
> pthresh : 8, hthresh : 8, wthresh : 0
> Free Thresh : 32, Drop Enable : 0, Deferred Start : 0
> ** TX Conf **
> pthresh : 32, hthresh : 0, wthresh : 0
> Free Thresh : 32, RS Thresh : 32, Deferred Start : 0, TXQ Flags:00000f01
> 
> PMD: ixgbevf_dev_configure(): VF can't disable HW CRC Strip
> Initialize Port 0 -- TxQ 2, RxQ 1, Src MAC 02:90:63:99:6b:29
> Create: Default RX 0:0 - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 = 8193 KB headroom 128 2176
> Set RX queue stats mapping pid 0, q 0, lcore 2
> 
> Create: Default TX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Range TX    0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Sequence TX 0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176
> Create: PCAP TX     0:0  - Number of MBUFs   4096 for    10 packets                 =     19 KB
> 
> Create: Default TX  0:1  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Range TX    0:1  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Sequence TX 0:1  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Special TX  0:1  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176
> Create: PCAP TX     0:1  - Number of MBUFs   4096 for    10 packets                 =     19 KB
> 
>                                                                   Port memory used =  57640 KB
>                                                                  Total memory used =  57640 KB
> 
> Port 0: Link Up - speed 10000 Mbps - full-duplex
> 
> === Display processing on lcore 0
> WARNING: Nothing to do on lcore 1: exiting
> RX processing lcore: 2 rx: 1 tx: 0
> TX processing lcore: 3 rx: 0 tx: 1
> TX processing lcore: 4 rx: 0 tx: 1
> 
> \ Ports 0-0 of 1
> 
> Copyright (c) <2010-2016>, Intel Corporation
> Flags:Port : P---p----------:0
> Link State : ----TotalRate----
> Pkts/s Max/Rx : 0/0 0/0
> Max/Tx : 0/0 0/0
> MBits/s Rx/Tx : 0/0 0/0
> Broadcast : 0
> Multicast : 0
> 64 Bytes : 0
> 65-127 : 0
> 128-255 : 0
> 256-511 : 0
> 512-1023 : 0
> 1024-1518 : 0
> Runts/Jumbos : 0/0
> Errors Rx/Tx : 0/0
> Total Rx Pkts : 0
> Tx Pkts : 0
> Rx MBs : 0
> Tx MBs : 0
> ARP/ICMP Pkts : 0/0
> :
> Pattern Type : abcd...
> Tx Count/% Rate : Forever / 100%
> PktSize/Tx Burst : 64 / 32
> Src/Dest Port : 1234 / 5678
> Pkt Type:VLAN ID : IPv4 / TCP:0001
> Dst IP Address : 192.168.1.1
> Src IP Address : 192.168.0.1/24
> Dst MAC Address : 00:00:00:00:00:00
> Src MAC Address : 02:90:63:99:6b:29
> VendID/PCI Addr : 8086:10ed/00:04.0
> 
> -- Pktgen Ver: 3.1.0 (DPDK 17.02.0-rc1) Powered by Intel® DPDK ---------------
> 
> Pktgen > pcap 0
> enable [Mul-choice STRING]: pcap 
> disable [Mul-choice STRING]: pcap 
> on [Mul-choice STRING]: pcap 
> off [Mul-choice STRING]: pcap 
> Pktgen > pcap 0 enable
> Pktgen> start 0
> Pktgen> quit
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by vabidi** [comment]
The VM has 40 CPUs.

A line in the output says "device on Numa socket -1"
Could that be an issue?

The screen shows link UP
Also, before doing dpdk-devbind, I verified that ifconfig thinks that link is up. 

Could the values used for the packet smac,dmac,sip or dip matter for transmitting? 

Vasmi Abidi

**Comment by pktgen** [comment]
> On Jan 26, 2017, at 9:35 AM, vabidi <notifications@github.com> wrote:
> 
> The VM has 40 CPUs.
> 
> A line in the output says "device on Numa socket -1”

Using cores on socket 0 and sending to socket 1 would only effect performance.

> Could that be an issue?
> 
> The screen shows link UP
> Also, before doing dpdk-devbind, I verified that ifconfig thinks that link is up.

If the link is up then packets should be sent the addresses only effect the RX side unless the port is in promiscuous mode


> 
> Could the values used for the packet smac,dmac,sip or dip matter for transmitting?
> 
> Vasmi Abidi
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by vabidi** [comment]
Hi,
   has anyone tried using pktgen in a AWS linux machine, with SR-IOV NICs?
  just wondering if there are any special gotchas in this case.

 thanks.
Vasmi

**Comment by vabidi** [comment]
Looks like transmit works if I don't pass in the "-s 0:<pcap file>" option.

This cmd-line did not work:
   :~/pktgen-dpdk$ sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -l 1-4 -n 2 --proc-type auto --socket-mem 256,256 --file-prefix pg --  -P  -m "[2:3-4].0" -s 0:big.pcap -l /tmp/f2.log

  This cmd-line worked:
:~/pktgen-dpdk$ sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -l 1-4 -n 2 --proc-type auto --socket-mem 256,256 --file-prefix pg --  -P  -m "[2:3-4].0"  -l /tmp/f2.log

**Comment by pktgen** [comment]
> On Feb 6, 2017, at 8:42 PM, vabidi <notifications@github.com> wrote:
> 
> Looks like transmit works if I don't pass in the "-s 0:" option.
> 
> This cmd-line did not work:
> :~/pktgen-dpdk$ sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -l 1-4 -n 2 --proc-type auto --socket-mem 256,256 --file-prefix pg -- -P -m "[2:3-4].0" -s 0:big.pcap -l /tmp/f2.log

Have ou checked to see if you have enough memory to handle a big.pcap file, try a small one to see.

> 
> This cmd-line worked:
> :~/pktgen-dpdk$ sudo ./app/app/x86_64-native-linuxapp-gcc/pktgen -l 1-4 -n 2 --proc-type auto --socket-mem 256,256 --file-prefix pg -- -P -m "[2:3-4].0" -l /tmp/f2.log
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by vabidi** [comment]
I tried several pcap files, some very small. None worked.
