### ISSUE TITLE
Lua command pktgen.seq has swapped parameters

### ISSUE THREAD

**Issue by devkid** [pktgen/Pktgen-DPDK#91]
Documentation says:
```
pktgen.seq(0, "all", "3cfd:fea2:2d78", "3cfd:fea2:30c8", "2.0.0.10", "2.0.0.10/16", 5, 6, "ipv4", "udp", 1, 64);
```

But with this, pktgen-dpdk sends ICMP packets.

Instead, the following sends UDP packets:
```
pktgen.seq(0, "all", "3cfd:fea2:2d78", "3cfd:fea2:30c8", "2.0.0.10", "2.0.0.10/16", 5, 6, "udp", "ipv4", 1, 64);
```
(`"udp"` and `"ipv4"` swapped)

**Comment by pktgen** [comment]
Thank you for the note, what version of Pktgen are you using?

> On Apr 25, 2017, at 8:54 AM, Alfred Krohmer <notifications@github.com> wrote:
> 
> Documentation says:
> 
> pktgen.seq(0, "all", "3cfd:fea2:2d78", "3cfd:fea2:30c8", "2.0.0.10", "2.0.0.10/16", 5, 6, "ipv4", "udp", 1, 64);
> 
> But with this, pktgen-dpdk sends ICMP packets.
> 
> Instead, the following sends UDP packets:
> 
> pktgen.seq(0, "all", "3cfd:fea2:2d78", "3cfd:fea2:30c8", "2.0.0.10", "2.0.0.10/16", 5, 6, "udp", "ipv4", 1, 64);
> 
> ("udp" and "ipv4" swapped)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by pktgen** [comment]
The command should be “ipv4”, “udp” and I fixed the code and will be in the next release.

> On Apr 25, 2017, at 8:56 AM, Roger Keith Wiles <keith.wiles@icloud.com> wrote:
> 
> Thank you for the note, what version of Pktgen are you using?
> 
>> On Apr 25, 2017, at 8:54 AM, Alfred Krohmer <notifications@github.com> wrote:
>> 
>> Documentation says:
>> 
>> pktgen.seq(0, "all", "3cfd:fea2:2d78", "3cfd:fea2:30c8", "2.0.0.10", "2.0.0.10/16", 5, 6, "ipv4", "udp", 1, 64);
>> 
>> But with this, pktgen-dpdk sends ICMP packets.
>> 
>> Instead, the following sends UDP packets:
>> 
>> pktgen.seq(0, "all", "3cfd:fea2:2d78", "3cfd:fea2:30c8", "2.0.0.10", "2.0.0.10/16", 5, 6, "udp", "ipv4", 1, 64);
>> 
>> ("udp" and "ipv4" swapped)
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> Keith Wiles
> keith.wiles@icloud.com

Keith Wiles
keith.wiles@icloud.com
