### ISSUE TITLE
Measurement of throughput and latency

### ISSUE THREAD

**Issue by imehrdad2012** [pktgen/Pktgen-DPDK#92]
Hello,

In my setup, I have two VMs that both run Pktgen (one acting as a generator and the other as a receiver). I can see that the basic packet generation functionality is working. I was wondering how I can measure the received data rate and latency information at the latency side? 

I did the homework and read the documentation but I could not find any clue in regard to the rate/latency measurement.
https://media.readthedocs.org/pdf/pktgen/latest/pktgen.pdf

Thanks

**Comment by pktgen** [comment]
> On Apr 26, 2017, at 5:11 PM, Mehrdad Moradi <notifications@github.com> wrote:
> 
> Hello,
> 
> In my setup, I have two VMs that both run Pktgen (one acting as a generator and the other as a receiver). I can see that the basic packet generation functionality is working. I was wondering how I can measure the received data rate and latency information at the latency side?

The same core must send and receive the latency packet or the results are off. Also you can not send a huge number of packet or at a high rate as DPDK is optimized for throughput not latency.

Also make sure you enable latency for the ports you want to enable, then use ‘page latency’ to see the results.

> 
> I did the homework and read the documentation but I could not find any clue in regard to the rate/latency measurement.
> https://media.readthedocs.org/pdf/pktgen/latest/pktgen.pdf
> 
> Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com
