### ISSUE TITLE
pktgen portStats all 0

### ISSUE THREAD

**Issue by djoreilly** [pktgen/Pktgen-DPDK#95]
Hi,

I'm using 3.2.8 on DPDK 16.07.0 and trying to get this script to work. The stats show on the screen as non-zero after the run completes, but the counters in portStats are zero when they are read. I tried rfc2544_tput_test.lua and it seems to have the same problem. Any ideas?

Thanks!

```
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
require "Pktgen";

local pkt_size          = 64;
local duration          = 10000;
local pauseTime         = 1000;

local sendport          = "0";
local recvport          = "1";
local num_tx, num_rx, num_dropped;


-- 'set' commands for a number of per port values
pktgen.set("all", "rate", 100);
pktgen.set("all", "size", pkt_size);
-- send continuous stream of traffic
pktgen.set("all", "count", 0);
-- pktgen.set("all", "burst", 128);
pktgen.set("all", "sport", 0x5678);
pktgen.set("all", "dport", 0x9988);
-- pktgen.set("all", "prime", 3);

pktgen.set_ipaddr("0", "dst", "172.17.25.150");
pktgen.set_ipaddr("0", "src", "172.17.25.15/24");
pktgen.set_ipaddr("1", "dst", "172.17.25.15");
pktgen.set_ipaddr("1", "src", "172.17.25.150/24");
pktgen.set_proto("all", "udp");
-- pktgen.set_type("all", "ipv4");


--pktgen.clr();
pktgen.start("all");
pktgen.delay(duration);
pktgen.stop("all");
pktgen.delay(pauseTime);


statTx = pktgen.portStats(sendport, "port")[tonumber(sendport)];
statRx = pktgen.portStats(recvport, "port")[tonumber(recvport)];
num_tx = statTx.opackets;
num_rx = statRx.ipackets;
num_dropped = num_tx - num_rx;
print("Tx: " .. num_tx .. ". Rx: " .. num_rx .. ". Dropped: " .. num_dropped);

prints("DEBUG portStats", pktgen.portStats("all", "port"));
```

sudo -E app/app/build/pktgen -c 0xe  --   -P -m "2.0, 3.1" -f tx-rx-loopback2.lua

```
   Copyright (c) <2010-2017>, Intel Corporation. All rights reserved.
   Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<

>>> Packet Burst 32, RX Desc 512, TX Desc 1024, mbufs/port 8192, mbuf cache 1024

=== port to lcore mapping table (# lcores 3) ===
   lcore:    1       2       3      Total
port   0: ( D: T) ( 1: 1) ( 0: 0) = ( 1: 1)
port   1: ( D: T) ( 0: 0) ( 1: 1) = ( 1: 1)
Total   : ( 0: 0) ( 1: 1) ( 1: 1)
  Display and Timer on lcore 1, rx:tx counts per port/lcore

Configuring 2 ports, MBUF Size 1920, MBUF Cache Size 1024
Lcore:
    2, RX-TX  
                RX_cnt( 1): (pid= 0:qid= 0) 
                TX_cnt( 1): (pid= 0:qid= 0) 
    3, RX-TX  
                RX_cnt( 1): (pid= 1:qid= 0) 
                TX_cnt( 1): (pid= 1:qid= 0) 

Port :
    0, nb_lcores  1, private 0x8c2e80, lcores:  2 
    1, nb_lcores  1, private 0x8c51d8, lcores:  3 



** Default Info (0:3.0, if_index:0) **
   max_vfs        :   0, min_rx_bufsize    :  64, max_rx_pktlen :  9728
   max_rx_queues  :   1, max_tx_queues     :   1
   max_mac_addrs  :  64, max_hash_mac_addrs:   0, max_vmdq_pools:     0
   rx_offload_capa:   0, tx_offload_capa   :   0, reta_size     :     0, flow_type_rss_offloads:0000000000000000
   vmdq_queue_base:   0, vmdq_queue_num    :   0, vmdq_pool_base:     0
** RX Conf **
   pthresh        :   0, hthresh          :   0, wthresh        :     0
   Free Thresh    :   0, Drop Enable      :   0, Deferred Start :     0
** TX Conf **
   pthresh        :   0, hthresh          :   0, wthresh        :     0
   Free Thresh    :   0, RS Thresh        :   0, Deferred Start :     0, TXQ Flags:00000f00

    Create: Default RX  0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
      Set RX queue stats mapping pid 0, q 0, lcore 2


    Create: Default TX  0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
    Create: Range TX    0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
    Create: Sequence TX 0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
    Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176

Initialize Port 0 -- TxQ 1, RxQ 1,  Src MAC fa:16:3e:71:e0:00

** Default Info (0:4.0, if_index:0) **
   max_vfs        :   0, min_rx_bufsize    :  64, max_rx_pktlen :  9728
   max_rx_queues  :   1, max_tx_queues     :   1
   max_mac_addrs  :  64, max_hash_mac_addrs:   0, max_vmdq_pools:     0
   rx_offload_capa:   0, tx_offload_capa   :   0, reta_size     :     0, flow_type_rss_offloads:0000000000000000
   vmdq_queue_base:   0, vmdq_queue_num    :   0, vmdq_pool_base:     0
** RX Conf **
   pthresh        :   0, hthresh          :   0, wthresh        :     0
   Free Thresh    :   0, Drop Enable      :   0, Deferred Start :     0
** TX Conf **
   pthresh        :   0, hthresh          :   0, wthresh        :     0
   Free Thresh    :   0, RS Thresh        :   0, Deferred Start :     0, TXQ Flags:00000f00

    Create: Default RX  1:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
      Set RX queue stats mapping pid 1, q 0, lcore 3


    Create: Default TX  1:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
    Create: Range TX    1:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
    Create: Sequence TX 1:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176
    Create: Special TX  1:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176

                                                                       Port memory used =  65665 KB
Initialize Port 1 -- TxQ 1, RxQ 1,  Src MAC fa:16:3e:d5:5f:db
                                                                      Total memory used = 131330 KB
Port  0: Link Up - speed 10000 Mbps - full-duplex <Enable promiscuous mode>
Port  1: Link Up - speed 10000 Mbps - full-duplex <Enable promiscuous mode>


=== Display processing on lcore 1
  RX/TX processing lcore:   2 rx:  1 tx:  1
For RX found 1 port(s) for lcore 2
For TX found 1 port(s) for lcore 2
  RX/TX processing lcore:   3 rx:  1 tx:  1
For RX found 1 port(s) for lcore 3
For TX found 1 port(s) for lcore 3

/ Ports 0-1 of 2   <Main Page>  Copyright (c) <2010-2016>, Intel Corporation                                                                                                                                                  [0/1814]
  Flags:Port      :   P--------------:0   P--------------:1
Link State        :       <UP-10000-FD>       <UP-10000-FD>     ----TotalRate----
Pkts/s Max/Rx     :          20331776/0          20331864/0                   4/0
       Max/Tx     :          20331872/0          20331776/0                   0/0
MBits/s Rx/Tx     :                 0/0                 0/0                   0/0
Broadcast         :                   0                   0
Multicast         :                  12                  12
  64 Bytes        :            20331778            20331866
  65-127          :                   0                   0
  128-255         :                   0                   0
  256-511         :                  12                  12
  512-1023        :                   0                   0
  1024-1518       :                   0                   0
Runts/Jumbos      :                 0/0                 0/0
Errors Rx/Tx      :                 0/0                 0/0
Total Rx Pkts     :            20331790            20331878
      Tx Pkts     :            20331872            20331776
      Rx MBs      :               13662               13663
      Tx MBs      :               13663               13662
ARP/ICMP Pkts     :                 0/0                 0/0
                  :
Pattern Type      :             abcd...             abcd...
Tx Count/% Rate   :       Forever /100%       Forever /100%
PktSize/Tx Burst  :           64 /   32           64 /   32
Src/Dest Port     :        22136 /39304        22136 /39304
Pkt Type:VLAN ID  :     IPv4 / UDP:0001     IPv4 / UDP:0001
Dst  IP Address   :       172.17.25.150        172.17.25.15
Src  IP Address   :     172.17.25.15/24    172.17.25.150/24
Dst MAC Address   :   fa:16:3e:d5:5f:db   fa:16:3e:71:e0:00
Src MAC Address   :   fa:16:3e:71:e0:00   fa:16:3e:d5:5f:db
VendID/PCI Addr   :   1af4:1000/00:03.0   1af4:1000/00:04.0

-- Pktgen Ver: 3.2.8 (DPDK 16.07.0)  Powered by Intel® DPDK ------------------


** Version: DPDK 16.07.0, Command Line Interface with timers
Pktgen:/> Tx: 0. Rx: 0. Dropped: 0
DEBUG portStats = {
  [1] = {
    ["ibytes"] = 0,
    ["rx_nombuf"] = 0,
    ["ipackets"] = 0,
    ["obytes"] = 0,
    ["opackets"] = 0,
    ["ierrors"] = 0,
    ["oerrors"] = 0,
  },
  [0] = {
    ["ibytes"] = 0,
    ["rx_nombuf"] = 0,
    ["ipackets"] = 0,
    ["obytes"] = 0,
    ["opackets"] = 0,
    ["ierrors"] = 0,
    ["oerrors"] = 0,
  },
  ["n"] = 2,
}

```

**Comment by djoreilly** [comment]
The script works on 3.1.2 (with DPDK 16.07.0). The counters on the screen refresh during the run too.

**Comment by pktgen** [comment]
Thanks, that will help figure out the problem.

> On May 9, 2017, at 9:03 AM, djoreilly <notifications@github.com> wrote:
> 
> The script works on 3.1.2 (with DPDK 16.07.0). The counters on the screen refresh during the run too.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by pktgen** [comment]
I found the problem with the port stats I removed a rte_timer_manage() call my mistake. Your script seems to work now, but make sure you can before asking for the stats as the timers need to fire and update the software counters.

You will find pktgen-3.2.9 already pushed to the repo.

Thanks for the bug report.
> On May 9, 2017, at 9:08 AM, Roger Keith Wiles <keith.wiles@icloud.com> wrote:
> 
> Thanks, that will help figure out the problem.
> 
>> On May 9, 2017, at 9:03 AM, djoreilly <notifications@github.com> wrote:
>> 
>> The script works on 3.1.2 (with DPDK 16.07.0). The counters on the screen refresh during the run too.
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> Keith Wiles
> keith.wiles@icloud.com
> 
> 
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by djoreilly** [comment]
that fixed it - thanks!

**Comment by mting806** [comment]
in 3.4.9 , the problem looks back:(

**Comment by pktgen** [comment]
I looked at the code and the code has not changed, so this maybe a different problem. Can you explain what version of DPDK and how you are getting this problem. I need more details to reproduce the problem.

> On Mar 8, 2018, at 4:30 AM, mting806 <notifications@github.com> wrote:
> 
> in 3.4.9 , the problem looks back:(
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by mting806** [comment]
Pktgen Ver: 3.4.9 (DPDK 18.05.0-rc0) 

here is my lua file

prints("portstats", pktgen.portStats("all", "port"));  showed everything are 0

sudo ./app/x86_64-native-linuxapp-gcc/pktgen -c 0x0f -n 4  -- -P -m "2.0" -f /home/ubuntu/pktgen_tput.lua


ubuntu@ediandu-server1:/pktgen-dpdk$ cat /home/ubuntu/pktgen_tput.lua
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"

 -- require "Pktgen";
function pktgen_config()

  pktgen.screen("on");

  pktgen.set_ipaddr("0", "src", "192.168.89.101/24");
  pktgen.set_ipaddr("0", "dst", "192.168.89.102");
  pktgen.set_mac("0", "FA:16:3E:26:E9:E6");
  pktgen.set("all", "sport", 1000);
  pktgen.set("all", "dport", 1000);
  pktgen.set("all", "size", 64);
  pktgen.set("all", "rate", 100);
  pktgen.set_type("all", "ipv4");
  pktgen.set_proto("all", "udp");

  pktgen.src_ip("0", "start", "192.168.89.101");
  pktgen.src_ip("0", "inc", "0.0.0.0");
  pktgen.src_ip("0", "min", "192.168.89.101");
  pktgen.src_ip("0", "max", "192.168.89.101");
  pktgen.dst_ip("0", "start", "192.168.89.102");
  pktgen.dst_ip("0", "inc", "0.0.0.0");
  pktgen.dst_ip("0", "min", "192.168.89.102");
  pktgen.dst_ip("0", "max", "192.168.89.102");

  pktgen.dst_mac("0", "start", "FA:16:3E:26:E9:E6");

  pktgen.src_port("all", "start", 1000);
  pktgen.src_port("all", "inc", 1);
  pktgen.src_port("all", "min", 1000);
  pktgen.src_port("all", "max", 1009);
  pktgen.dst_port("all", "start", 1000);
  pktgen.dst_port("all", "inc", 1);
  pktgen.dst_port("all", "min", 1000);
  pktgen.dst_port("all", "max", 1010);

  pktgen.pkt_size("all", "start", 64);
  pktgen.pkt_size("all", "inc",0);
  pktgen.pkt_size("all", "min", 64);
  pktgen.pkt_size("all", "max", 64);
  pktgen.ip_proto("all", "udp");
  pktgen.set_range("all", "on");

  pktgen.start("all");
  pktgen.sleep(10)
  pktgen.stop("all");
  pktgen.sleep(1)

  prints("portstats", pktgen.portStats("all", "port"));

  end

pktgen_config()

**Comment by pktgen** [comment]
Change the last sleep to a larger value and try it again. I am not near my machine.

**Comment by pktgen** [comment]
BTW, the lua script given on the command is run very early in startup and it is possible the ports are not completely setup. Can you also try loading the script from the pktgen command line. I really only meant command line scripts to be used for initialization and not running complexed commands.

Let me know if you need startup scripts that are more then just setup and configuration.

> On Mar 8, 2018, at 10:32 AM, mting806 <notifications@github.com> wrote:
> 
> Pktgen Ver: 3.4.9 (DPDK 18.05.0-rc0)
> 
> here is my lua file
> 
> prints("portstats", pktgen.portStats("all", "port")); showed everything are 0
> 
> sudo ./app/x86_64-native-linuxapp-gcc/pktgen -c 0x0f -n 4 -- -P -m "2.0" -f /home/ubuntu/pktgen_tput.lua
> 
> ubuntu@ediandu-server1:/pktgen-dpdk$ cat /home/ubuntu/pktgen_tput.lua
> package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
> 
> -- require "Pktgen";
> function pktgen_config()
> 
> pktgen.screen("on");
> 
> pktgen.set_ipaddr("0", "src", "192.168.89.101/24");
> pktgen.set_ipaddr("0", "dst", "192.168.89.102");
> pktgen.set_mac("0", "FA:16:3E:26:E9:E6");
> pktgen.set("all", "sport", 1000);
> pktgen.set("all", "dport", 1000);
> pktgen.set("all", "size", 64);
> pktgen.set("all", "rate", 100);
> pktgen.set_type("all", "ipv4");
> pktgen.set_proto("all", "udp");
> 
> pktgen.src_ip("0", "start", "192.168.89.101");
> pktgen.src_ip("0", "inc", "0.0.0.0");
> pktgen.src_ip("0", "min", "192.168.89.101");
> pktgen.src_ip("0", "max", "192.168.89.101");
> pktgen.dst_ip("0", "start", "192.168.89.102");
> pktgen.dst_ip("0", "inc", "0.0.0.0");
> pktgen.dst_ip("0", "min", "192.168.89.102");
> pktgen.dst_ip("0", "max", "192.168.89.102");
> 
> pktgen.dst_mac("0", "start", "FA:16:3E:26:E9:E6");
> 
> pktgen.src_port("all", "start", 1000);
> pktgen.src_port("all", "inc", 1);
> pktgen.src_port("all", "min", 1000);
> pktgen.src_port("all", "max", 1009);
> pktgen.dst_port("all", "start", 1000);
> pktgen.dst_port("all", "inc", 1);
> pktgen.dst_port("all", "min", 1000);
> pktgen.dst_port("all", "max", 1010);
> 
> pktgen.pkt_size("all", "start", 64);
> pktgen.pkt_size("all", "inc",0);
> pktgen.pkt_size("all", "min", 64);
> pktgen.pkt_size("all", "max", 64);
> pktgen.ip_proto("all", "udp");
> pktgen.set_range("all", "on");
> 
> pktgen.start("all");
> pktgen.sleep(10)
> pktgen.stop("all");
> pktgen.sleep(1)
> 
> prints("portstats", pktgen.portStats("all", "port"));
> 
> end
> 
> pktgen_config()
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Regards,
Keith

**Comment by mting806** [comment]
hello Keith
i have tried to start pktgen first , then load the script , but the result is same, 
What I want is that executing pktgen within my auto testing script, and output the sentout packet number.
beside this lua script, is there any other smart way?
thank you very much

ubuntu@ediandu-server1:/pktgen-dpdk$ cat ~/pktgen_tput.lua
package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"

 -- require "Pktgen";
function pktgen_config()

  pktgen.screen("on");

  pktgen.set_ipaddr("0", "src", "192.168.89.101/24");
  pktgen.set_ipaddr("0", "dst", "192.168.89.102");
  pktgen.set_mac("0", "FA:16:3E:26:E9:E6");
  pktgen.set("all", "sport", 1000);
  pktgen.set("all", "dport", 1000);
  pktgen.set("all", "size", 64);
  pktgen.set("all", "rate", 100);
  pktgen.set_type("all", "ipv4");
  pktgen.set_proto("all", "udp");

  pktgen.src_ip("0", "start", "192.168.89.101");
  pktgen.src_ip("0", "inc", "0.0.0.0");
  pktgen.src_ip("0", "min", "192.168.89.101");
  pktgen.src_ip("0", "max", "192.168.89.101");
  pktgen.dst_ip("0", "start", "192.168.89.102");
  pktgen.dst_ip("0", "inc", "0.0.0.0");
  pktgen.dst_ip("0", "min", "192.168.89.102");
  pktgen.dst_ip("0", "max", "192.168.89.102");

  pktgen.dst_mac("0", "start", "FA:16:3E:26:E9:E6");

  pktgen.src_port("all", "start", 1000);
  pktgen.src_port("all", "inc", 1);
  pktgen.src_port("all", "min", 1000);
  pktgen.src_port("all", "max", 1099);
  pktgen.dst_port("all", "start", 1000);
  pktgen.dst_port("all", "inc", 1);
  pktgen.dst_port("all", "min", 1000);
  pktgen.dst_port("all", "max", 1100);

  pktgen.pkt_size("all", "start", 64);
  pktgen.pkt_size("all", "inc",0);
  pktgen.pkt_size("all", "min", 64);
  pktgen.pkt_size("all", "max", 64);
  pktgen.ip_proto("all", "udp");
  pktgen.set_range("all", "on");

  pktgen.start("all");
  pktgen.sleep(20)
  pktgen.stop("all");
  pktgen.sleep(20)

  prints("opackets", pktgen.portStats("all", "port")[0].opackets);
  prints("oerrors", pktgen.portStats("all", "port")[0].oerrors);

  end

pktgen_config()

----------------------------------------------------------------------------------------------

| Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2017>, Intel Corporation
  Flags:Port      :   P-----R--------:0
Link State        :       <UP-10000-FD>     ----TotalRate----
Pkts/s Max/Rx     :                 0/0                   0/0
       Max/Tx     :           9482080/0                   0/0
MBits/s Rx/Tx     :                 0/0                   0/0
Broadcast         :                   0
Multicast         :                   0
  64 Bytes        :                   0
  65-127          :                   0
  128-255         :                   0
  256-511         :                   0
  512-1023        :                   0
  1024-1518       :                   0
Runts/Jumbos      :                 0/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :                   0
      Tx Pkts     :             9482080
      Rx MBs      :                   0
      Tx MBs      :                6371
ARP/ICMP Pkts     :                 0/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :       Forever /100%
PktSize/Tx Burst  :           64 /   64
Src/Dest Port     :         1000 / 1000
Pkt Type:VLAN ID  :     IPv4 / UDP:0001
802.1p CoS        :                   0
ToS Value:        :                   0
  - DSCP value    :                   0
  - IPP  value    :                   0
Dst  IP Address   :      192.168.89.102
Src  IP Address   :   192.168.89.101/24
Dst MAC Address   :   fa:16:3e:26:e9:e6
Src MAC Address   :   fa:16:3e:1b:6f:09
VendID/PCI Addr   :   1af4:1000/00:04.0

-- Pktgen Ver: 3.4.9 (DPDK 18.05.0-rc0)  Powered by DPDK ----------------------
[opackets"] = 0,
["oerrors"] = 0,
