### ISSUE TITLE
Is there a chance to send line-rate on a single XL710 40GE NIC?

### ISSUE THREAD

**Issue by labingIt** [pktgen/Pktgen-DPDK#95]
I've tried several tuning techniques, such as using hyper-thread on different physical cores and etc.
I've got a XL710 and Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz, working with Ubuntu 20.04.
Here is my cfg file and cpu-layout. And adding more core to send packets doesn't improve it at this very point.
Is there any chance I can tune it to line-rate?
```
# Setup configuration
setup = {
    'exec': (
        'sudo', '-E'
        ),

    'devices': (
            '18:00.0'
            ),
    # UIO module type, igb_uio, vfio-pci or uio_pci_generic
    'uio': 'igb_uio'
    }

# Run command and options
run = {
    'exec': ('sudo', '-E'),

    # Application name and use app_path to help locate the app
    'app_name': 'pktgen',

    # using (sdk) or (target) for specific variables
    # add (app_name) of the application
    # Each path is tested for the application
    'app_path': (
                './usr/local/bin/%(app_name)s',
                '/usr/local/bin/%(app_name)s'
        ),

        'cores': '0,1,2,3,4,5',
        'nrank': '4',
        'proc': 'auto',
        'log': '7',
        'prefix': 'pg',

        'blocklist': (
                #'03:00.0', '05:00.0',
                #'81:00.0', '84:00.0'
                ),
        'allowlist': (
                '18:00.0'
                ),

        'opts': (
                '-v',
                '-T',
                '-P',
                #'-j',
                '-N',
                ),
        'map': (
                '[1:2-5].0'
                ),

        'theme': 'themes/black-yellow.theme'
        }

```

```
WARNING: Python 2 is deprecated for use in DPDK, and will not work in future releases.
Please use Python 3 instead
======================================================================
Core and Socket Information (as reported by '/sys/devices/system/cpu')
======================================================================

cores =  [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 25, 26, 27, 28, 29]
sockets =  [0, 1]

        Socket 0        Socket 1
        --------        --------
Core 0  [0, 48]         [24, 72]
Core 1  [1, 49]         [25, 73]
Core 2  [2, 50]         [26, 74]
Core 3  [3, 51]         [27, 75]
Core 4  [4, 52]         [28, 76]
Core 5  [5, 53]         [29, 77]
Core 6  [6, 54]         [30, 78]
Core 8  [7, 55]         [31, 79]
Core 9  [8, 56]         [32, 80]
Core 10 [9, 57]         [33, 81]
Core 11 [10, 58]        [34, 82]
Core 12 [11, 59]        [35, 83]
Core 13 [12, 60]        [36, 84]
Core 16 [13, 61]        [37, 85]
Core 17 [14, 62]        [38, 86]
Core 18 [15, 63]        [39, 87]
Core 19 [16, 64]        [40, 88]
Core 20 [17, 65]        [41, 89]
Core 21 [18, 66]        [42, 90]
Core 25 [19, 67]        [43, 91]
Core 26 [20, 68]        [44, 92]
Core 27 [21, 69]        [45, 93]
Core 28 [22, 70]        [46, 94]
Core 29 [23, 71]        [47, 95]

```

**Comment by KeithWiles** [comment]
I use two cores (for TX) (Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz) to get about 42.5Mpps 64 byte frames on XL710 40Gbe. Adding more cores does not seem to improve the performance much.

You did not say what speed you were getting and what version of Pktgen.

The only thing I can think of is to make sure your NIC is plugged into a PCIe slot of the correct bit width and performance to match the NIC.

**Comment by labingIt** [comment]
> I use two cores (for TX) (Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz) to get about 42.5Mpps 64 byte frames on XL710 40Gbe. Adding more cores does not seem to improve the performance much.
> 
> You did not say what speed you were getting and what version of Pktgen.
> 
> The only thing I can think of is to make sure your NIC is plugged into a PCIe slot of the correct bit width and performance to match the NIC.

Thank you so much for replying ^^

I'm using Pktgen-20.11.3 with dpdk-21.11-LTS and getting about 42-43Mpps at top with the cfg above. I can't change the hardware layout at this very point, so I'm searching for other software solutions.

**Comment by KeithWiles** [comment]
Maybe the best you are going to get as I do not see any other things to try. Good Luck, if you find the solution please let me know.

**Comment by labingIt** [comment]
> Maybe the best you are going to get as I do not see any other things to try. Good Luck, if you find the solution please let me know.

OK. I'll reopen this issue again if I find a way.
