### ISSUE TITLE
pktgen-port 0 cannot  Link Up

### ISSUE THREAD

**Issue by YanAnzouyijun** [pktgen/Pktgen-DPDK#96]
Hi,My platform is Centos 7 desktop, 64-bit running on VirtualBox. The VM has 4GB of RAM, 4 cores and a two network adaptors（disable promiscuous mode）, both Virtio. One network adaptor is set to use the igb_uio module, the other is using the virtio driver.And hugepage =512*2M

but unluckily,when i execute the command:

```shell
./app/app/x86_64-native-linuxapp-gcc/app/pktgen -c 0xe -n 4 --file-prefix pg -b 00:03.0 --proc-type auto -- -T -m "[2:3].0" -f themes/black-yellow.theme
```

the result is that:

```shell
Create: Default TX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
Create: Range TX    0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
Create: Sequence TX 0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176


Port memory used =  32897 KB
Total memory used =  32897 KB
```

and the app die here,i cannot see the the result

```c
Port  0: Link Up - speed 10000 Mbps - full-duplex
```

then i read the source code combining with the log,i found that the app fell into the dead cycle in the function

```c
static int virtio_send_command(struct virtnet_ctl *cvq, struct virtio_pmd_ctrl *ctrl,
    int *dlen, int pkt_num)
{
    uint32_t head, i;
    int k, sum = 0;
    virtio_net_ctrl_ack status = ~0;
    struct virtio_pmd_ctrl result;
    struct virtqueue *vq;

    ctrl->status = status;

    if (!cvq || !cvq->vq) {
        PMD_INIT_LOG(ERR, "Control queue is not supported.");
        return -1;
    }
    vq = cvq->vq;
    head = vq->vq_desc_head_idx;

    PMD_INIT_LOG(DEBUG, "vq->vq_desc_head_idx = %d, status = %d, "
        "vq->hw->cvq = %p vq = %p",
        vq->vq_desc_head_idx, status, vq->hw->cvq, vq);

    if ((vq->vq_free_cnt < ((uint32_t)pkt_num + 2)) || (pkt_num < 1))
        return -1;

    memcpy(cvq->virtio_net_hdr_mz->addr, ctrl,
        sizeof(struct virtio_pmd_ctrl));

    /*
     * Format is enforced in qemu code:
     * One TX packet for header;
     * At least one TX packet per argument;
     * One RX packet for ACK.
     */
    vq->vq_ring.desc[head].flags = VRING_DESC_F_NEXT;
    vq->vq_ring.desc[head].addr = cvq->virtio_net_hdr_mem;
    vq->vq_ring.desc[head].len = sizeof(struct virtio_net_ctrl_hdr);
    vq->vq_free_cnt--;
    i = vq->vq_ring.desc[head].next;

    for (k = 0; k < pkt_num; k++) {
        vq->vq_ring.desc[i].flags = VRING_DESC_F_NEXT;
        vq->vq_ring.desc[i].addr = cvq->virtio_net_hdr_mem
            + sizeof(struct virtio_net_ctrl_hdr)
            + sizeof(ctrl->status) + sizeof(uint8_t)*sum;
        vq->vq_ring.desc[i].len = dlen[k];
        sum += dlen[k];
        vq->vq_free_cnt--;
        i = vq->vq_ring.desc[i].next;
    }

    vq->vq_ring.desc[i].flags = VRING_DESC_F_WRITE;
    vq->vq_ring.desc[i].addr = cvq->virtio_net_hdr_mem
            + sizeof(struct virtio_net_ctrl_hdr);
    vq->vq_ring.desc[i].len = sizeof(ctrl->status);
    vq->vq_free_cnt--;

    vq->vq_desc_head_idx = vq->vq_ring.desc[i].next;

    vq_update_avail_ring(vq, head);
    vq_update_avail_idx(vq);

    PMD_INIT_LOG(DEBUG, "vq->vq_queue_index = %d", vq->vq_queue_index);

    virtqueue_notify(vq);
```

```c
    /*the code fell into the dead cycle，added by me*/
     rte_rmb();
      while (VIRTQUEUE_NUSED(vq) == 0) {
               rte_rmb();
               usleep(100);
          }
      
```
     

```c
    while (VIRTQUEUE_NUSED(vq)) {
        uint32_t idx, desc_idx, used_idx;
        struct vring_used_elem *uep;

        used_idx = (uint32_t)(vq->vq_used_cons_idx
                & (vq->vq_nentries - 1));
        uep = &vq->vq_ring.used->ring[used_idx];
        idx = (uint32_t) uep->id;
        desc_idx = idx;

        while (vq->vq_ring.desc[desc_idx].flags & VRING_DESC_F_NEXT) {
            desc_idx = vq->vq_ring.desc[desc_idx].next;
            vq->vq_free_cnt++;
        }

        vq->vq_ring.desc[desc_idx].next = vq->vq_desc_head_idx;
        vq->vq_desc_head_idx = idx;

        vq->vq_used_cons_idx++;
        vq->vq_free_cnt++;
    }

    PMD_INIT_LOG(DEBUG, "vq->vq_free_cnt=%d\nvq->vq_desc_head_idx=%d",
            vq->vq_free_cnt, vq->vq_desc_head_idx);

    memcpy(&result, cvq->virtio_net_hdr_mz->addr,
            sizeof(struct virtio_pmd_ctrl));

    return result.status;
}
```
then ,i donot know the reason.can anyone tell me why the app fell into the dead cycle ?

**Comment by pktgen** [comment]
> On May 10, 2017, at 2:06 AM, YanAnzouyijun <notifications@github.com> wrote:
> 
> Hi,My platform is Centos 7 desktop, 64-bit running on VirtualBox. The VM has 4GB of RAM, 4 cores and a two network adaptors（disable promiscuous mode）, both Virtio. One network adaptor is set to use the igb_uio module, the other is using the virtio driver.And hugepage =512*2M
> 
> but unluckily,when i execute the command:
> 
> ./app/app/x86_64-native-linuxapp-gcc/app/pktgen -c 0xe -n 4 --file-prefix pg -b 00:03.0 --proc-type auto -- -T -m "[2:3].0" -f themes/black-yellow.theme
> the result is that:
> 
> Create: Default TX  0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Range TX    0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Sequence TX 0:0  - Memory used (MBUFs 4096 x (size 1920 + Hdr 128)) + 192 =   8193 KB headroom 128 2176
> Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176

Looks like the dead code is not really dead code, it is code to stop polling until a packet arrives then it grabs the packets and returns. Maybe an attempt to reduce the CPU into some type of idle state. So to me then means no packets have arrived to be consumed.

> 
> 
> Port memory used =  32897 KB
> Total memory used =  32897 KB
> 
> and the app die here,i cannot see the the result
> 
> Port  0: Link Up - speed 10000 Mbps - full-duplex
> then i read the source code combining with the log,i found that the app fell into the dead cycle in the function
> 
> static int virtio_send_command(struct virtnet_ctl *cvq, struct
>  virtio_pmd_ctrl *ctrl,
>     
> int *dlen, int
>  pkt_num)
> {
>     
> uint32_t
>  head, i;
>     
> int k, sum = 0
> ;
>     virtio_net_ctrl_ack status = ~
> 0
> ;
>     
> struct
>  virtio_pmd_ctrl result;
>     
> struct
>  virtqueue *vq;
> 
>     ctrl->status = status;
> 
>     
> if
>  (!cvq || !cvq->vq) {
>         
> PMD_INIT_LOG(ERR, "Control queue is not supported."
> );
>         
> return -1
> ;
>     }
>     vq = cvq->vq;
>     head = vq->vq_desc_head_idx;
> 
>     
> PMD_INIT_LOG(DEBUG, "vq->vq_desc_head_idx = %d, status = %d, "
> 
>         
> "vq->hw->cvq = %p vq = %p"
> ,
>         vq->vq_desc_head_idx, status, vq->hw->cvq, vq);
> 
>     
> if ((vq->vq_free_cnt < ((uint32_t)pkt_num + 2)) || (pkt_num < 1
> ))
>         
> return -1
> ;
> 
>     
> memcpy
> (cvq->virtio_net_hdr_mz->addr, ctrl,
>         
> sizeof(struct
>  virtio_pmd_ctrl));
> 
>     
> /*
>      * Format is enforced in qemu code:
>      * One TX packet for header;
>      * At least one TX packet per argument;
>      * One RX packet for ACK.
>      */
> 
>     vq->vq_ring.
> desc[head].flags
>  = VRING_DESC_F_NEXT;
>     vq->vq_ring.
> desc[head].addr
>  = cvq->virtio_net_hdr_mem;
>     vq->vq_ring.
> desc[head].len = sizeof(struct
>  virtio_net_ctrl_hdr);
>     vq->vq_free_cnt--;
>     i = vq->vq_ring.
> desc[head].next
> ;
> 
>     
> for (k = 0
> ; k < pkt_num; k++) {
>         vq->vq_ring.
> desc[i].flags
>  = VRING_DESC_F_NEXT;
>         vq->vq_ring.
> desc[i].addr
>  = cvq->virtio_net_hdr_mem
>             + 
> sizeof(struct
>  virtio_net_ctrl_hdr)
>             + 
> sizeof(ctrl->status) + sizeof(uint8_t
> )*sum;
>         vq->vq_ring.
> desc[i].len
>  = dlen[k];
>         sum += dlen[k];
>         vq->vq_free_cnt--;
>         i = vq->vq_ring.
> desc[i].next
> ;
>     }
> 
>     vq->vq_ring.
> desc[i].flags
>  = VRING_DESC_F_WRITE;
>     vq->vq_ring.
> desc[i].addr
>  = cvq->virtio_net_hdr_mem
>             + 
> sizeof(struct
>  virtio_net_ctrl_hdr);
>     vq->vq_ring.
> desc[i].len = sizeof
> (ctrl->status);
>     vq->vq_free_cnt--;
> 
>     vq->vq_desc_head_idx = vq->vq_ring.
> desc[i].next
> ;
> 
>     
> vq_update_avail_ring
> (vq, head);
>     
> vq_update_avail_idx
> (vq);
> 
>     
> PMD_INIT_LOG(DEBUG, "vq->vq_queue_index = %d"
> , vq->vq_queue_index);
> 
>     
> virtqueue_notify(vq);
>      /* the code fell into the dead cycle*/
> 
>      
> rte_rmb
> ();
>       
> while (VIRTQUEUE_NUSED(vq) == 0
> ) {
>                
> rte_rmb
> ();
>                
> usleep(100
> );
>           }
>       
> 
>     while
>  (VIRTQUEUE_NUSED(vq)) {
>         
> uint32_t
>  idx, desc_idx, used_idx;
>         
> struct
>  vring_used_elem *uep;
> 
>         used_idx = (
> uint32_t
> )(vq->vq_used_cons_idx
>                 & (vq->vq_nentries - 
> 1
> ));
>         uep = &vq->vq_ring.
> used
> ->ring[used_idx];
>         idx = (
> uint32_t
> ) uep->id;
>         desc_idx = idx;
> 
>         
> while (vq->vq_ring.desc[desc_idx].flags
>  & VRING_DESC_F_NEXT) {
>             desc_idx = vq->vq_ring.
> desc[desc_idx].next
> ;
>             vq->vq_free_cnt++;
>         }
> 
>         vq->vq_ring.
> desc[desc_idx].next
>  = vq->vq_desc_head_idx;
>         vq->vq_desc_head_idx = idx;
> 
>         vq->vq_used_cons_idx++;
>         vq->vq_free_cnt++;
>     }
> 
>     
> PMD_INIT_LOG(DEBUG, "vq->vq_free_cnt=%d\nvq->vq_desc_head_idx=%d"
> ,
>             vq->vq_free_cnt, vq->vq_desc_head_idx);
> 
>     
> memcpy
> (&result, cvq->virtio_net_hdr_mz->addr,
>             
> sizeof(struct
>  virtio_pmd_ctrl));
> 
>     
> return
>  result.status;
> }
> 
> then ,i donot know the reason.can anyone tell me why the app fell into the dead cycle ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by YanAnzouyijun** [comment]
thank u very much!!!

your reply give me a lot of hints.

first,"it is code to stop polling until a packet arrives then it grabs the packets and returns."
i know it grabs the packet from qemu,then i upgrade the qemu to 2.8.94.
but unluckily,it cannot return the expected outcome。

secondly,"Maybe an attempt to reduce the CPU into some type of idle state"
i abandon the cmd about:
```shell
    -m "[2:3].0"
```
then，it came the result as this:

```c
\ Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2016>, Intel Corporation
  Flags:Port      : 
Link State        :     ----TotalRate----
Pkts/s Max/Rx     :                   0/0
       Max/Tx     :                   0/0
MBits/s Rx/Tx     :                   0/0
Broadcast         : 
Multicast         : 
  64 Bytes        : 
  65-127          : 
  128-255         : 
  256-511         : 
  512-1023        : 
  1024-1518       : 
Runts/Jumbos      : 
Errors Rx/Tx      : 
Total Rx Pkts     : 
      Tx Pkts     : 
      Rx MBs      : 
      Tx MBs      : 
ARP/ICMP Pkts     : 
                  :
Pattern Type      : 
Tx Count/% Rate   : 
PktSize/Tx Burst  : 
Src/Dest Port     : 
Pkt Type:VLAN ID  : 
Dst  IP Address   : 
Src  IP Address   : 
Dst MAC Address   : 
Src MAC Address   : 
VendID/PCI Addr   : 

-- Pktgen Ver: 3.0.06 (DPDK 16.07.0)  Powered by Intel? DPDK ------------------
```
but the result is not normally. 


because the result that i use the pktgen using the kvm is like this:
```c
/ Ports 0-0 of 1   <Main Page>  Copyright (c) <2010-2016>, Intel Corporation
  Flags:Port      :   ---------------:0
Link State        :       <UP-10000-FD>     ----TotalRate----
Pkts/s Max/Rx     :              282/20                282/20
       Max/Tx     :                 0/0                   0/0
MBits/s Rx/Tx     :                 0/0                   0/0
Broadcast         :                   0
Multicast         :                7967
  64 Bytes        :                7320
  65-127          :                2457
  128-255         :                4101
  256-511         :                  24
  512-1023        :                   0
  1024-1518       :                   0
Runts/Jumbos      :                22/0
Errors Rx/Tx      :                 0/0
Total Rx Pkts     :               13914
      Tx Pkts     :                   0
      Rx MBs      :                  13
      Tx MBs      :                   0
ARP/ICMP Pkts     :              7008/0
                  :
Pattern Type      :             abcd...
Tx Count/% Rate   :      Forever / 100%
PktSize/Tx Burst  :           64 /   32
Src/Dest Port     :         1234 / 5678
Pkt Type:VLAN ID  :     IPv4 / TCP:0001
Dst  IP Address   :         192.168.1.1
Src  IP Address   :      192.168.0.1/24
Dst MAC Address   :   00:00:00:00:00:00
Src MAC Address   :   fa:16:3e:2e:a6:c8
VendID/PCI Addr   :   1af4:1000/00:04.0

-- Pktgen Ver: 3.0.06 (DPDK 16.07.0)  Powered by Intel® DPDK ------------------
```

because i am not familiar with the kernel and the cpu,i donot know how to continue...

**Comment by pktgen** [comment]
> On May 11, 2017, at 8:49 PM, YanAnzouyijun <notifications@github.com> wrote:
> 
> thank u very much!!!
> 
> your reply give me a lot of hints.
> 
> first,"it is code to stop polling until a packet arrives then it grabs the packets and returns."
> i know it grabs the packet from qemu,then i upgrade the qemu to 2.8.94.
> but unluckily,it cannot return the expected outcome。
> 
> secondly,"Maybe an attempt to reduce the CPU into some type of idle state"
> i abandon the cmd about:
> 
>     -m "[2:3].0"
> then，it came the result as this:

Normally when you get something like below it means the port does not exit or the command line wrong. In this case it seems it is qemu problem I guess.

You are using a pretty old version of pktgen the latest is 3.2.10, if you could try the latest version as I do not really work in older versions per say.

> 
> \ Ports 0-0 of 1   <Main Page>  Copyright
>  (c) <2010-2016>, Intel Corporation
>   Flags:Port      : 
> Link State        :     ----TotalRate----
> Pkts/s Max/Rx     :                   0/0
>        Max/Tx     :                   0/0
> MBits/s Rx/Tx     :                   0/0
> Broadcast         : 
> Multicast         : 
>   64 Bytes        : 
>   65-127          : 
>   128-255         : 
>   256-511         : 
>   512-1023        : 
>   1024-1518       : 
> Runts/Jumbos      : 
> Errors Rx/Tx      : 
> Total Rx Pkts     : 
>       Tx Pkts     : 
>       Rx MBs      : 
>       Tx MBs      : 
> ARP/ICMP Pkts     : 
>                   :
> Pattern Type      : 
> Tx Count/% Rate   : 
> PktSize/Tx Burst  : 
> Src/Dest Port     : 
> Pkt Type:VLAN ID  : 
> Dst  IP Address   : 
> Src  IP Address   : 
> Dst MAC Address   : 
> Src MAC Address   : 
> VendID/PCI Addr   : 
> 
> -- Pktgen Ver: 3.0.06 (DPDK 
> 16.07.0)  Powered by Intel? DPDK ------------------
> but the result is not normally.
> 
> because the result that i use the pktgen using the kvm is like this:
> 
> / Ports 0-0 of 1   <Main Page>  Copyright
>  (c) <2010-2016>, Intel Corporation
>   Flags:Port      :   ---------------:0
> Link State        :       <UP-10000-FD>     ----TotalRate----
> Pkts/s Max/Rx     :              282/20                282/20
>        Max/Tx     :                 0/0                   0/0
> MBits/s Rx/Tx     :                 0/0                   0/0
> Broadcast         :                   0
> Multicast         :                7967
>   64 Bytes        :                7320
>   65-127          :                2457
>   128-255         :                4101
>   256-511         :                  24
>   512-1023        :                   0
>   1024-1518       :                   0
> Runts/Jumbos      :                22/0
> Errors Rx/Tx      :                 0/0
> Total Rx Pkts     :               13914
>       Tx Pkts     :                   0
>       Rx MBs      :                  13
>       Tx MBs      :                   0
> ARP/ICMP Pkts     :              7008/0
>                   :
> Pattern Type      :             abcd...
> Tx Count/% Rate   :      Forever / 100%
> PktSize/Tx Burst  :           64 /   32
> Src/Dest Port     :         1234 / 5678
> Pkt Type:VLAN ID  :     IPv4 / TCP:0001
> Dst  IP Address   :         192.168.1.1
> Src  IP Address   :      192.168.0.1/24
> Dst MAC Address   :   00:00:00:00:00:00
> Src MAC Address   :   fa:16:3e:2e:a6:c8
> VendID/PCI Addr   :   1af4:1000/00:04.0
> 
> -- Pktgen Ver: 3.0.06 (DPDK 
> 16.07.0)  Powered by Intel® DPDK ------------------
> because i am not familiar with the kernel and the cpu,i donot know how to continue...
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by YanAnzouyijun** [comment]
unluckily,when i upgrade the pktgen to the newest version(3.2.10,dpdk(17.05)),the result is that:

    Copyright (c) <2010-2017>, Intel Corporation. All rights reserved. Powered by Intel® DPDK 
    EAL: Detected 4 lcore(s) 
    EAL: Auto-detected process type: PRIMARY 
    EAL: Probing VFIO support... 
    EAL: PCI device 0000:00:03.0 on NUMA socket -1 
    EAL:   Device is blacklisted, not initializing 
    EAL: PCI device 0000:00:08.0 on NUMA socket -1 
    EAL:   probe driver: 1af4:1000 net_virtio 
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
    Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio 
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
       Copyright (c) <2010-2017>, Intel Corporation. All rights reserved. 
       Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<< 
     
    >>> Packet Burst 32, RX Desc 512, TX Desc 1024, mbufs/port 8192, mbuf cache 1024 
     
    === port to lcore mapping table (# lcores 3) === 
       lcore:    1       2       3      Total 
    port   0: ( D: T) ( 1: 0) ( 0: 1) = ( 1: 1) 
    Total   : ( 0: 0) ( 1: 0) ( 0: 1) 
      Display and Timer on lcore 1, rx:tx counts per port/lcore 
     
    Configuring 1 ports, MBUF Size 1920, MBUF Cache Size 1024 
    Lcore: 
        2, RX-Only 
                    RX_cnt( 1): (pid= 0:qid= 0)  
        3, TX-Only 
                    TX_cnt( 1): (pid= 0:qid= 0)  
     
    Port : 
        0, nb_lcores  2, private 0xa3b3c0, lcores:  2  3  
     
     
     
    ** Default Info (0000:00:08.0, if_index:0) ** 
       max_vfs        :   0, min_rx_bufsize    :  64, max_rx_pktlen :  9728 
       max_rx_queues  :   1, max_tx_queues     :   1 
       max_mac_addrs  :  64, max_hash_mac_addrs:   0, max_vmdq_pools:     0 
       rx_offload_capa:  28, tx_offload_capa   :  44, reta_size     :     0, flow_type_rss_offloads:0000000000000000 
       vmdq_queue_base:   0, vmdq_queue_num    :   0, vmdq_pool_base:     0 
    ** RX Conf ** 
       pthresh        :   0, hthresh          :   0, wthresh        :     0 
       Free Thresh    :   0, Drop Enable      :   0, Deferred Start :     0 
    ** TX Conf ** 
       pthresh        :   0, hthresh          :   0, wthresh        :     0 
       Free Thresh    :   0, RS Thresh        :   0, Deferred Start :     0, TXQ Flags:00000f00 
     
        Create: Default RX  0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
          Set RX queue stats mapping pid 0, q 0, lcore 2 
     
     
        Create: Default TX  0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
        Create: Range TX    0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
        Create: Sequence TX 0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
        Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176 
     
                                                                           Port memory used =  65665 KB 
    Initialize Port 0 -- TxQ 1, RxQ 1,  Src MAC 08:00:27:04:e1:68 
                                                                          Total memory used =  65665 KB

then i use the cmdline,

    gdb attach pid

the result is that

(gdb) bt
#0  0x00007f8d7b4f08ad in nanosleep () from /lib64/libc.so.6
#1  0x00007f8d7b521284 in usleep () from /lib64/libc.so.6
#2  0x0000000000691405 in virtio_send_command.constprop.29 ()
#3  0x00000000006916ad in virtio_dev_promiscuous_disable ()
#4  0x00000000004a0f6e in rte_eth_dev_start ()
#5  0x00000000004766db in pktgen_config_ports () at /root/pktgen-3.2.10/app/pktgen-port-cfg.c:433
#6  0x0000000000447d9c in main (argc=6, argv=<optimized out>) at /root/pktgen-3.2.10/app/pktgen-main.c:384

the reason is the same as before,i hava no better methods to solve it;
then i think maybe the virtualbox version is too old? 
the version of virtualbox is :

    VirtualBox-5.0-5.0.6_103037_el7-1.x86_64

**Comment by pktgen** [comment]
Most use KVM/QEMU instead of virtualbox. I do not see any reason why pktgen is not working in this environment.

Sorry, I do not know virtio very well. I assumed you verified virtio was working before running pktgen or any dpdk application? Sorry If I have asked this question before too many emails.

> On May 12, 2017, at 1:48 AM, YanAnzouyijun <notifications@github.com> wrote:
> 
> unluckily,when i upgrade the pktgen to the newest version(3.2.10,dpdk(17.05)),the result is that:
> 
> Copyright (c) <2010-2017>, Intel Corporation. All rights reserved. Powered by Intel® DPDK 
> EAL: Detected 4 lcore(s) 
> EAL: Auto-detected process type: PRIMARY 
> EAL: Probing VFIO support... 
> EAL: PCI device 0000:00:03.0 on NUMA socket -1 
> EAL:   Device is blacklisted, not initializing 
> EAL: PCI device 0000:00:08.0 on NUMA socket -1 
> EAL:   probe driver: 1af4:1000 net_virtio 
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
> Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio 
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>    Copyright (c) <2010-2017>, Intel Corporation. All rights reserved. 
>    Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<< 
>  
> >>> Packet Burst 32, RX Desc 512, TX Desc 1024, mbufs/port 8192, mbuf cache 1024 
>  
> === port to lcore mapping table (# lcores 3) === 
>    lcore:    1       2       3      Total 
> port   0: ( D: T) ( 1: 0) ( 0: 1) = ( 1: 1) 
> Total   : ( 0: 0) ( 1: 0) ( 0: 1) 
>   Display and Timer on lcore 1, rx:tx counts per port/lcore 
>  
> Configuring 1 ports, MBUF Size 1920, MBUF Cache Size 1024 
> Lcore: 
>     2, RX-Only 
>                 RX_cnt( 1): (pid= 0:qid= 0)  
>     3, TX-Only 
>                 TX_cnt( 1): (pid= 0:qid= 0)  
>  
> Port : 
>     0, nb_lcores  2, private 0xa3b3c0, lcores:  2  3  
>  
>  
>  
> ** Default Info (0000:00:08.0, if_index:0) ** 
>    max_vfs        :   0, min_rx_bufsize    :  64, max_rx_pktlen :  9728 
>    max_rx_queues  :   1, max_tx_queues     :   1 
>    max_mac_addrs  :  64, max_hash_mac_addrs:   0, max_vmdq_pools:     0 
>    rx_offload_capa:  28, tx_offload_capa   :  44, reta_size     :     0, flow_type_rss_offloads:0000000000000000 
>    vmdq_queue_base:   0, vmdq_queue_num    :   0, vmdq_pool_base:     0 
> ** RX Conf ** 
>    pthresh        :   0, hthresh          :   0, wthresh        :     0 
>    Free Thresh    :   0, Drop Enable      :   0, Deferred Start :     0 
> ** TX Conf ** 
>    pthresh        :   0, hthresh          :   0, wthresh        :     0 
>    Free Thresh    :   0, RS Thresh        :   0, Deferred Start :     0, TXQ Flags:00000f00 
>  
>     Create: Default RX  0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
>       Set RX queue stats mapping pid 0, q 0, lcore 2 
>  
>  
>     Create: Default TX  0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
>     Create: Range TX    0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
>     Create: Sequence TX 0:0  - Memory used (MBUFs 8192 x (size 1920 + Hdr 128)) + 192 =  16385 KB headroom 128 2176 
>     Create: Special TX  0:0  - Memory used (MBUFs   64 x (size 1920 + Hdr 128)) + 192 =    129 KB headroom 128 2176 
>  
>                                                                        Port memory used =  65665 KB 
> Initialize Port 0 -- TxQ 1, RxQ 1,  Src MAC 08:00:27:04:e1:68 
>                                                                       Total memory used =  65665 KB
> 
> then i use the cmdline,
> 
> gdb attach pid
> 
> the result is that
> 
> (gdb) bt
> #0 0x00007f8d7b4f08ad in nanosleep () from /lib64/libc.so.6
> #1 0x00007f8d7b521284 in usleep () from /lib64/libc.so.6
> #2 0x0000000000691405 in virtio_send_command.constprop.29 ()
> #3 0x00000000006916ad in virtio_dev_promiscuous_disable ()
> #4 0x00000000004a0f6e in rte_eth_dev_start ()
> #5 0x00000000004766db in pktgen_config_ports () at /root/pktgen-3.2.10/app/pktgen-port-cfg.c:433
> #6 0x0000000000447d9c in main (argc=6, argv=) at /root/pktgen-3.2.10/app/pktgen-main.c:384
> 
> the reason is the same as before,i hava no better methods to solve it;
> then i think maybe the virtualbox version is too old?
> the version of virtualbox is :
> 
> VirtualBox-5.0-5.0.6_103037_el7-1.x86_64
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com
