### ISSUE TITLE
Memory allocation fails during pktgen initialization

### ISSUE THREAD

**Issue by davidfernandes1212** [pktgen/Pktgen-DPDK#97]
Hi !

I am trying to run paket-gen but it seems there is some problems concerning memory allocation 

**My system**
CPU : Intel Core i3-6100 (3.70 GHz, 2 cores, 2 threads/core)
HyperThreading : enabled
NIC : X540-AT2 with 2x10Gbe ports
OS : Linux Ubuntu Server 16.04 (kernel 4.4)
DPDK version : 16.11.1
Pktgen version : 3.2.10

I enter the next command : 

**./pktgen -c 0x07 -n 1 -m "1.0, 2.1"**

And I get the following output : 

```
Copyright (c) <2010-2017>, Intel Corporation. All rights reserved. Powered by Intel® DPDK

EAL: Detected 4 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   probe driver: 8086:1528 net_ixgbe
HASH: memory allocation failed
PMD: ixgbe_fdir_filter_init(): Failed to create fdir hash table!
EAL: PCI device 0000:01:00.1 on NUMA socket -1
EAL:   probe driver: 8086:1528 net_ixgbe
HASH: memory allocation failed
PMD: ixgbe_fdir_filter_init(): Failed to create fdir hash table!

Lua 5.3.4  Cop   Copyright (c) <2010-2017>, Intel Corporation. All rights reserved.
   Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<

>>> Packet Burst 32, RX Desc 512, TX Desc 1024, mbufs/port 8192, mbuf cache 1024

=== port to lcore mapping table (# lcores 3) ===
   lcore:    0       1       2      Total
Total   : ( 0: 0) ( 0: 0) ( 0: 0)
  Display and Timer on lcore 0, rx:tx counts per port/lcore

Configuring 2 ports, MBUF Size 1920, MBUF Cache Size 1024
Lcore:

Port :


                                               Total memory used =      0 KB


=== Display processing on lcore 0
WARNING: Nothing to do on lcore 1: exiting
WARNING: Nothing to do on lcore 2: exiting
```

```
- Ports 0-1 of 2   <Main Page>  Copyright (c) <2010-2016>, Intel Corporation
  Flags:Port      : 
Link State        :     ----TotalRate----
Pkts/s Max/Rx     :                   0/0
       Max/Tx     :                   0/0
MBits/s Rx/Tx     :                   0/0
Broadcast         : 
Multicast         : 
  64 Bytes        : 
  65-127          : 
  128-255         : 
  256-511         : 
  512-1023        : 
  1024-1518       : 
Runts/Jumbos      : 
Errors Rx/Tx      : 
Total Rx Pkts     : 
      Tx Pkts     : 
      Rx MBs      : 
      Tx MBs      : 
ARP/ICMP Pkts     : 
                  :
Pattern Type      : 
Tx Count/% Rate   : 
PktSize/Tx Burst  : 
Src/Dest Port     : 
Pkt Type:VLAN ID  : 
Dst  IP Address   : 
Src  IP Address   : 
Dst MAC Address   : 
Src MAC Address   : 
VendID/PCI Addr   : 

-- Pktgen Ver: 3.2.10 (DPDK 17.05.0)  Powered by Intel® DPDK ------------------

Pktgen:/>

```
As you can see, ports don't appear on the CLI page. 

It seems like hugepages are not allocated by DPDK :

> HardwareCorrupted:     0 kB
> AnonHugePages:      2048 kB
> CmaTotal:              0 kB
> CmaFree:               0 kB
> HugePages_Total:    1024
> HugePages_Free:     1023
> HugePages_Rsvd:        0
> HugePages_Surp:        0
> Hugepagesize:       2048 kB
> DirectMap4k:       66544 kB
> DirectMap2M:     2973696 kB
> DirectMap1G:     2097152 kB
> 

I tested modifing the HugePages size from 2MB to 1GB and it stills not working.

I tried testpmd application and it seems to work.

Do you have any suggestion ?

Thanks in advance !

David

**Comment by pktgen** [comment]
> On May 16, 2017, at 6:53 AM, davidfernandes1212 <notifications@github.com> wrote:
> 
> Hi !
> 
> I am trying to run paket-gen but it seems there is some problems concerning memory allocation
> 
> My system
> CPU : Intel Core i3-6100 (3.70 GHz, 2 cores, 2 threads/core)
> HyperThreading : enabled
> NIC : X540-AT2 with 2x10Gbe ports
> OS : Linux Ubuntu Server 16.04 (kernel 4.4)
> DPDK version : 16.11.1
> Pktgen version : 3.2.10
> 
> I enter the next command :
> 
> ./pktgen -c 0x07 -n 1 -m "1.0, 2.1"
> 
> And I get the following output :
> 
> Copyright (c) <2010-2017>, Intel Corporation. All rights reserved. Powered by Intel® DPDK
> 
> EAL: Detected 4 lcore(s)
> EAL: No free hugepages reported in hugepages-1048576kB
> EAL: Probing VFIO support...
> EAL: PCI device 0000:01:00.0 on NUMA socket -1
> EAL:   probe driver: 8086:1528 net_ixgbe
> HASH: memory allocation failed
> PMD: ixgbe_fdir_filter_init(): Failed to create fdir hash table!
> EAL: PCI device 0000:01:00.1 on NUMA socket -1
> EAL:   probe driver: 8086:1528 net_ixgbe
> HASH: memory allocation failed
> PMD: ixgbe_fdir_filter_init(): Failed to create fdir hash table!
> 
> Lua 5.3.4  Cop   Copyright (c) <2010-2017>, Intel Corporation. All rights reserved.
>    Pktgen created by: Keith Wiles -- >>> Powered by Intel® DPDK <<<
> 
> >>> Packet Burst 32, RX Desc 512, TX Desc 1024, mbufs/port 8192, mbuf cache 1024
> 
> === port to lcore mapping table (# lcores 3) ===
>    lcore:    0       1       2      Total
> Total   : ( 0: 0) ( 0: 0) ( 0: 0)
>   Display and Timer on lcore 0, rx:tx counts per port/lcore
> 
> Configuring 2 ports, MBUF Size 1920, MBUF Cache Size 1024
> Lcore:
> 
> Port :
> 
> 
>                                                Total memory used =      0 KB

It looks like no ports were found or it is not able to configure the ixgbe devices. It seems like the ixgbe fdir filter init is not working. This has nothing to do with pktgen. I would double check the hardware or to make sure DPDK supports the NIC version. Pktgen would be able to allocate some memory if the ports were found.

If seems like the PMD in DPDK is not able to allocate memory for the ports. Ahh I spotted the problem :-)

The command ‘./pktgen -c 0x07 -n1 -m “1.0,, 2.0”’ needs to be ‘./pktgen -c 0x07 -n 1 -- -m "1.0, 2.1”’ the “dash dash” is missing.


> 
> 
> === Display processing on lcore 0
> WARNING: Nothing to do on lcore 1: exiting
> WARNING: Nothing to do on lcore 2: exiting
> 
> - Ports 0-1 of 2   <Main Page>  Copyright (c) <2010-2016>, Intel Corporation
>   Flags:Port      : 
> Link State        :     ----TotalRate----
> Pkts/s Max/Rx     :                   0/0
>        Max/Tx     :                   0/0
> MBits/s Rx/Tx     :                   0/0
> Broadcast         : 
> Multicast         : 
>   64 Bytes        : 
>   65-127          : 
>   128-255         : 
>   256-511         : 
>   512-1023        : 
>   1024-1518       : 
> Runts/Jumbos      : 
> Errors Rx/Tx      : 
> Total Rx Pkts     : 
>       Tx Pkts     : 
>       Rx MBs      : 
>       Tx MBs      : 
> ARP/ICMP Pkts     : 
>                   :
> Pattern Type      : 
> Tx Count/% Rate   : 
> PktSize/Tx Burst  : 
> Src/Dest Port     : 
> Pkt Type:VLAN ID  : 
> Dst  IP Address   : 
> Src  IP Address   : 
> Dst MAC Address   : 
> Src MAC Address   : 
> VendID/PCI Addr   : 
> 
> -- Pktgen Ver: 3.2.10 (DPDK 17.05.0)  Powered by Intel® DPDK ------------------
> 
> Pktgen:/>
> 
> 
> As you can see, ports don't appear on the CLI page.
> 
> It seems like hugepages are not allocated by DPDK :
> 
> HardwareCorrupted: 0 kB
> AnonHugePages: 2048 kB
> CmaTotal: 0 kB
> CmaFree: 0 kB
> HugePages_Total: 1024
> HugePages_Free: 1023
> HugePages_Rsvd: 0
> HugePages_Surp: 0
> Hugepagesize: 2048 kB
> DirectMap4k: 66544 kB
> DirectMap2M: 2973696 kB
> DirectMap1G: 2097152 kB
> 
> I tested modifing the HugePages size from 2MB to 1GB and it stills not working.
> 
> I tried testpmd application and it seems to work.
> 
> Do you have any suggestion ?
> 
> Thanks in advance !
> 
> David
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Keith Wiles
keith.wiles@icloud.com

**Comment by davidfernandes1212** [comment]
It works ! That was the problem ! 

Thank you very much for your help and your quick response !
