### ISSUE TITLE
Unable to load and replay a large pcap file

### ISSUE THREAD

**Issue by labingIt** [pktgen/Pktgen-DPDK#98]
I want to replay a 100MB-level pcap file, but I can't load it into Pktgen. I'm using a XL710 NIC, and Pktgen-Pktgen-20.11.3 with dpdk-21.11. My cmdline and output logs as below: 
`sudo -E ./usr/local/bin/pktgen -l 0,1,2,3,4,5 -n 4 --file-prefix pg -w 18:00.0 --socket-mem=6000,6000 -- -v -T -P -N -m [1:2/3/5].0 -s 0:/home/xxx/pcap/single0_0.pcap
`
```
!PANIC!: Cannot init port 0 for 1543165 PCAP packets
PANIC in pktgen_pcap_parse():
Cannot init port 0 for 1543165 PCAP packets
7: [./usr/local/bin/pktgen(+0xa80e) [0x558ea414580e]]
6: [/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7facbe9030b3]]
5: [./usr/local/bin/pktgen(+0xa384) [0x558ea4145384]]
4: [./usr/local/bin/pktgen(+0x2dd30) [0x558ea4168d30]]
3: [./usr/local/bin/pktgen(+0x25e5e) [0x558ea4160e5e]]
2: [/usr/local/lib/x86_64-linux-gnu/librte_eal.so.21(__rte_panic+0xcd) [0x7facbeb71d8f]]
1: [/usr/local/lib/x86_64-linux-gnu/librte_eal.so.21(rte_dump_stack+0x32) [0x7facbeb96bb2]]
Aborted
```

**Comment by KeithWiles** [comment]
Please update to the latest pktgen or try the dev branch. I believe some works was done this year on loading PCAP file. It will require the latest DPDK as well.

**Comment by KeithWiles** [comment]
Please look at issues #106
